### PR TITLE
Use rewrite for placeholders and improve cache control

### LINKED ISSUE #4707: Placeholder redirects and CORS don't mix
## The problem

We want to have the service worker cache brand images for performance and offline use (https://github.com/home-assistant/frontend/pull/17840).  In order to do this, all  responses must contain the `Access-Control-Allow-Origin` header.  These were added in #4652, but they do not apply to the 302 redirects to the placeholder images.  So when the frontend goes to fetch them, a CORS error is thrown.

AFAIK, there is no way to actually modify the headers of a redirect for security reasons (e.g. [`Response.redirect()` creates a response with immutable headers](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Basic_concepts#guard)).  There is also a [relevant discussion in the Netlify support forum](https://answers.netlify.com/t/netlify-does-not-send-custom-headers-in-a-redirect-file-using-https-in-the-to/25773/15).

A potentially easy fix is to just rewrite the URL instead of redirecting it, which [can be done in `netlify.toml`](https://docs.netlify.com/routing/redirects/rewrites-proxies/).  However, Netlify applies the `[[headers]]` for the request URL, not the rewritten one, so it won't be cached as desired.

Similarly, `[[headers]]` in the config file are applied regardless of the response status, which means requests without a placeholder fallback that return a 404 are currently being cached for the longer time.

The only way I see to achieve the desired responses is to use  an edge function.

## Proposed Solution
1. Use an edge function to handle all the image responses.  It sets the cache and CORS headers as desired.
2. Use a query parameter to request a placeholder fallback instead of the `/_/` directory.  This cuts the domain storage in half, and makes it much simpler and safer to test for in the edge function.  It would also make it easier for the frontend service worker to manipulate how images are cached if needed.

### LINKED ISSUE #4718: Browser cache life is too short and restricted
## The problem

The term "critical asset" here would mean that the page would either break or not make sense if a stale copy were served, which I don't think is the case for any uses of these brand images.  With that in mind:

1. A browser cache life of 15 minutes for non-critical and largely static images is much too short.  This forces a lot of unnecessary revalidations over the net which reduces performance.  Since they are heavily used in the frontend, it also means that HA cannot survive even a small internet outage.  This should be more like a week or even a month.
2. It does not make sense to have `s-maxage > max-age`.  Right now, the server is saying Cloudflare can consider a copy fresh for a week, but the browser should stop treating it as fresh after only the first 15 minutes of that, forcing a revalidation nearly every load.  This scenario only makes sense as a technique for reducing origin server load on critical assets that rarely change (because the proxy can be purged when needed).  Instead, here it makes sense that `s-maxage <= max-age`, so Cloudflare picks up changes faster without browsers losing their cache benefits (essentially getting changes to users faster).
3. The `must-revalidate` directive is also too strict here as again the images are not critical.  At the end of `max-age`, browsers should be free to serve stale copies as they see fit in case of an outage.  The `stale-while-revalidate` strategy can also be used here instead for browsers that support it.

## Additional information
Equivalent frontend issue is https://github.com/home-assistant/frontend/issues/17560.  However, that can only be addressed via the service worker, which does not apply to legacy browsers or access without `https`.

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

This makes changes to the Netlify config to fix the referenced issues:

- Condenses the `redirects` table into just 2 entries for brevity, and removes the `headers` keys which are not applicable (explained more in #4685)
- Uses rewrites instead of redirects for placeholder fallback, i.e. return 200 instead of 302
  - Skips the extra network requests resulting in a performance bump
  - Unblocks issues with CORS requests in frontend service work as discussed in #4707
  - Minor disadvantage is that placeholders cannot have separate headers applied for cache control; however, this seems like an acceptable compromise given that it really only helps for domain additions and not other changes.  This is addressed further in the next point.
- Apply a single set of cache control directives for all assets, with adjusted ages and revalidation policy as discussed in #4718
  - Cache in browsers for 7 days for good browser performance and internet outage protection
  - Cache on Cloudflare for 24 hours to pick up any change relatively quickly, not just full domain additions (users reloading then guaranteed < 1 day old data)
  - Apply `stale-while-revalidate` strategy for another 7 days for browsers that support it (Firefox and Chrome at the moment); others will use their internal heuristics

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #4707 and fixes #4718 
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This change seems incomplete.

- The PR description mentions rewrites instead of redirects, but these are not in this PR?
- Removed redirect have no replacement. For example, all the fallback logic is done using redirects, but those have been completely removed and not replaced. For example `dark_logo` falls back to `logo` using a redirect; but has been removed without replacement.
- Redirects are throwing a status 200 now, which is not correct in the HTTP specification.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
> The fallback behavior is exactly the same. 

It isn't.

From the old rules:

```
[[redirects]]
  from = "/brands/_/*/dark_logo.png"
  to = "/brands/_/_placeholder/logo.png
```

Nothing is replacing any of that logic.

../Frenck

**Comment by steverep** [comment]
That's replaced by:

```toml
[[redirects]]
  from = "/brands/_/*/:image"
  to = "/brands/_/_placeholder/:image"
  force = false
  status = 200
```

It rewrites to `.../_placeholder/dark_logo.png`, but that's the same image (and allows putting in dark placeholder variants w/o changing config if desired).

These links return the same placeholder image:
- https://brands.home-assistant.io/brands/_/steverep/dark_logo.png
- https://deploy-preview-4722--home-assistant-brands.netlify.app//brands/_/steverep/dark_logo.png

**Comment by frenck** [comment]
> That's replaced by:

That is not a replacement. Again:

```
[[redirects]]
  from = "/brands/_/*/dark_logo.png"
  to = "/brands/_/_placeholder/logo.png
```

Is breaking/missing in this PR.

../Frenck

**Comment by steverep** [comment]
To try to be ultra-clear on the rule you claim is broken:

| Branch | From | Action | To | Result |
|:---:|:---:|:---:|:---:|:---:|
| Current | `/brands/_/*/dark_logo.png` | Redirect | `/brands/_/_placeholder/logo.png` | Copy of `core_integrations/_placeholder/logo.png` |
| PR | `/brands/_/*/dark_logo.png` | Rewrite | `/brands/_/_placeholder/dark_logo.png` | Copy of `core_integrations/_placeholder/logo.png` (since there's no dark placeholders) |

In other words, the current rule for dark variants is redundant with the build script: [`# Create fallback for dark variants`](https://github.com/home-assistant/brands/blob/420a36d975530808646fbaa4f1481a05d826fed8/scripts/build.sh#L113)is .  This PR is just removing that redundancy.  Here's the deploy preview link working just fine for Epson (which does not have dark variants in the repo):

https://deploy-preview-4722--home-assistant-brands.netlify.app//brands/_/epson/dark_logo.png

**Comment by steverep** [comment]
@frenck I know you're probably busy with the stream today, but could we please resolve this when you get a chance?  I think if you actually test the Netlify preview, you'll see the placeholder fallbacks are working correctly.

**Comment by frenck** [comment]
> Nearly a month and 90 subsequent PRs have followed this one, the majority of which were promptly merged or approved without much wait.

You are right, this is not a PR I review I would review from my tablet, the other I would (and do). So, yeah.

**Comment by frenck** [comment]
> To try to be ultra-clear on the rule you claim is broken:

That is really helpful! The part that didn't exist in my mind was:

https://github.com/home-assistant/brands/blob/ce098e0aeee978f93424298f4e010886f74613d5/scripts/build.sh#L113-L121

**Pull request merged**
