### PR TITLE
Add Firmata integration image

### PR DESCRIPTION
**Pull request by DaAwesomeP**
## Proposed change

Adds icon for new Firmata integration. **This is the only official image I could find; I could not find anything bigger.**

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/35591
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/13508
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
@frenck that is the biggest image that I could find. Is the preferred solution to add bordering white space?

**Comment by DaAwesomeP** [comment]
I have added white space around the icon—please let me know if that works.

**Comment by frenck** [comment]
Not, we don't generally do that. If there are no images available, we can't add the icons or logos. Alternatively, one could contact the vendor.

**Comment by DaAwesomeP** [comment]
OK, I will contact them and ask if they have a newer icon or larger version. I guess I should close this in the meantime. Thanks!

**Comment by DaAwesomeP** [comment]
Just for documentation: I have an issue to update the logo to a new vector I created https://github.com/firmata/protocol/issues/118

**Pull request closed without merging**
