### PR TITLE
Add iDiamant by Netatmo custom integration images

### PR DESCRIPTION
**Pull request by clementprevot**
## Proposed change

Add the needed brand images for the iDiamant by Netatmo custom integration I'm currently working on. The integration is not ready yet, so this PR is not urgent.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Repository (WIP): https://github.com/clementprevot/home-assistant-idiamant

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @clementprevot, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3211).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
This PR contains product images, however, the goal of this repository is to provide brand images.

I would have expected the Netatmo branding here?

**Comment by clementprevot** [comment]
> This PR contains product images, however, the goal of this repository is to provide brand images.
> 
> I would have expected the Netatmo branding here?

Thank you for your comment.
In fact, this is specifically dedicated to the iDiamant product which is a bit apart from Netatmo.

Do you still want me to use netatmo branding instead?

**Comment by frenck** [comment]
Yes, we do not store product images in this repository (hence its called `brands` 😉 )

**Review by frenck — APPROVED** [review]
Thanks, @clementprevot 👍

**Pull request merged**
