### PR TITLE
added icons for new azure data explorer component

### PR DESCRIPTION
**Pull request by kaareseras**
## Type of change

- [x ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/68992
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/21643
- Link to integration documentation on our website: 

## Checklist

- [ x] The added/replaced image(s) are **PNG**
- [x ] Icon image size is 256x256px (`icon.png`)
- [ x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by kaareseras** [comment]
Anyone able to move this PR ahead?

**Comment by frenck** [comment]
@kaareseras There is nothing to move ahead for this PR at this point in time?

**Comment by frenck** [comment]
> Sorry, Im new to the process here, so the merge will be unblocked when I push the actual integration?

If there is no integration, there is no reason to merge this PR?

**Comment by kaareseras** [comment]
> > Sorry, Im new to the process here, so the merge will be unblocked when I push the actual integration?
> 
> If there is no integration, there is no reason to merge this PR?

I have just made a PR on the Integration:
https://github.com/home-assistant/core/pull/66519

**Comment by frenck** [comment]
Closing the PR as the parent PR has been closed.

**Comment by kaareseras** [comment]
The Parent has been moved to a new PR:
https://github.com/home-assistant/core/pull/68992
Its waiting for review. This needs to be reopend, and have it parent updated

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
