### PR TITLE
Add icons and logo for lennoxS30 custom integration

### PR DESCRIPTION
**Pull request by PeteRager**
Logos and icons for lennoxs30 custom integration
https://github.com/PeteRager/lennoxs30

## Proposed change
Adding icons and logos for the lennoxs30 custom integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logos look upscaled and thus are blurry a bit:

CleanShot 2022-11-20 at 17 51 33@2x

Additionally, the icons look like product or application icons and not branding used by Lennox.

Could you take a look?

../Frenck

**Comment by PeteRager** [comment]
Thanks for the review.  I updated the logos to give better resolution.

The icons are correct - that's the branding lennox uses for this device - anyone with an S30 will recognize it.  It's also what they use for their mobile apps on ios and android.

Here are some images of what the device looks like.

image

Of course the HA integration far exceeds the capabilities of any of these other integrations they have :-).

image

**Comment by frenck** [comment]
Right, but their app icon, is not their branding as it seems. Checking out their social media profiles, they don't seem to use that app icon for their branding:

image

image

image

So, to me, it seems the currently provided icons are not correct.

../Frenck

**Comment by PeteRager** [comment]
Lennox is a big company they make alot of products

A) If we want the branding to be company branding then I can make a square icon with a Lennox Logo.  

B) If we want the branding of the specific device we are communicating with the app icon would be best. 

You are recommending approach (a)

something like this:
  
  
B6DD98EC-D702-439D-995B-D8F4342E3C22

**Comment by Jc2k** [comment]
https://spaces.hightail.com/space/uc4kz3aAGp/files/fi-62b34e36-a26e-4aca-889b-3553c4bb004a/fv-fd8b6f6e-5e8a-40d2-b1bf-64e9143127e4/Lennox%20Brand%20Guidelines%20May%202021_20-LNX-0037.pdf#pageThumbnail-10

The Dave character should not be used according to the brand guidelines. "Internal employees" and "Agency partners" can, but with strict guidelines on what's acceptable.

**Comment by PeteRager** [comment]
I've updated the icons to the standard red lennox in a 256x256 and 512x512 for the icons.

**Review by frenck — APPROVED** [review]
Thanks, @PeteRager 👍

**Pull request merged**
