### PR TITLE
Add branding for llama_conversation

### PR DESCRIPTION
**Pull request by acon96**
## Proposed change

Add branding for the Llama Conversation custom component

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/acon96/ha-brands
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/acon96/home-llm

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon provided is a custom created icon/branding. This is not something we can accept as this might misrepresent it and in many cases violated branding guidelines from the providers.

Please create a new PR containing official upstream branding from the manufacturer/provider.

../Frenck

**Comment by acon96** [comment]
> The icon provided is a custom created icon/branding. This is not something we can accept as this might misrepresent it and in many cases violated branding guidelines from the providers.
> 
> Please create a new PR containing official upstream branding from the manufacturer/provider.
> 
> ../Frenck

I'm the maintainer of the component and I made the icon myself. Do I not have authority to decide on the branding for my own integration?

**Comment by frenck** [comment]
> Do I not have authority to decide on the branding for my own integration?

Sure, but we decide if we want to accept it in these repositories. The fact is, this integration represents/integrates with a service that is not yours, misrepresenting it can cause issues of its own. That is not a route we want to take. Therefore, this PR isn't accepted into our repositories.

../Frenck

**Comment by acon96** [comment]
> > Do I not have authority to decide on the branding for my own integration?
> 
> Sure, but we decide if we want to accept it in these repositories. The fact is, this integration represents/integrates with a service that is not yours, misrepresenting it can cause issues of its own. That is not a route we want to take. Therefore, this PR isn't accepted into our repositories.
> 
> ../Frenck

Makes sense. The reasoning in your first comment was just confusing.

**Comment by tannisroot** [comment]
> > Do I not have authority to decide on the branding for my own integration?
> 
> Sure, but we decide if we want to accept it in these repositories. The fact is, this integration represents/integrates with a service that is not yours, misrepresenting it can cause issues of its own. That is not a route we want to take. Therefore, this PR isn't accepted into our repositories.
> 
> ../Frenck

What if the project was called `LLM Conversation` and did not reference `llama` (is `llama` even trademarked?)? This integration works with many local ai backends, like llama.ccp, ollama, so it can't use logos of a single project it integrates with because it wouldn't be representative.
Having an icon is a requirement for being published for HACS, so it's sad to see it being denied being published there over legal stuff.

**Pull request closed without merging**
