### PR TITLE
Added Electra Smart logos to custom integration

### PR DESCRIPTION
**Pull request by jafar-atili**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I cannot find the public repository providing this integration, could you point me to it?

Thanks! 👍 

../Frenck

**Comment by jafar-atili** [comment]
> I cannot find the public repository providing this integration, could you point me to it?
> 
> Thanks! 👍
> 
> ../Frenck

You are so fast my friend, I am uploading it :)

**Comment by frenck** [comment]
> You are so fast my friend, I am uploading it :)

Lol sorry 😓

**Comment by jafar-atili** [comment]
> I cannot find the public repository providing this integration, could you point me to it?
> 
> Thanks! 👍
> 
> ../Frenck

Here's the repo: https://github.com/jafar-atili/home-assistant-electrasmart
Here's the wheel PR: https://github.com/home-assistant/wheels-custom-integrations/pull/613

**Comment by jafar-atili** [comment]
I hopped to be able to add those integration officially, but the PR review process unfortunately takes time, will it be possible migrate this integration to core post PR review?

**Comment by frenck** [comment]
> will it be possible migrate this integration to core post PR review?

Sure, I would recommend to take that into account for the integration domain.
For example, name the custom integration domain `electrasmart_beta` or something, so when adding it to core later on it won't conflict on domains.

**Comment by jafar-atili** [comment]
I can just change the core integration to electra_smart (wasn't sure if underscore are valid as domain names)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by frenck — APPROVED** [review]
Thanks, @jafar-atili 👍

**Pull request merged**
