### PR TITLE
Update logo for trem custom integrations

### PR DESCRIPTION
**Pull request by J1A-T13N**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [x] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/J1A-T13N/ha-trem

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR has a merge conflict @J1A-T13N. Could you take a look?

Thanks! 👍 

../Frenck

**Comment by frenck** [comment]
Moved this PR back to draft, as the merge conflict hasn't been resolved.

Please resolve the review comments above before you mark this PR ready for review.

Thanks 👍 

../Frenck

**Review by J1A-T13N — COMMENTED** [review]
Update logo

**Comment by frenck** [comment]
> Update logo

Cool, but as per last two comments, there is a merge conflict.

CleanShot 2024-06-08 at 09 41 07@2x

Please resolve it and mark the PR ready for review after that.

../Frenck

**Review by J1A-T13N — COMMENTED** [review]
Review merge conflict

**Comment by frenck** [comment]
ok, @J1A-T13N You need to resolve the merge conflict:

CleanShot 2024-06-08 at 10 02 59@2x

This is the last attempt I'm going to ask you to resolve this.

../Frenck

**Comment by J1A-T13N** [comment]
I'm still new to merge PR.

**Comment by frenck** [comment]
> I'm still new to merge PR.

Sure, but you have to resolve the merge conflict in this PR.

**Pull request closed without merging**
