### PR TITLE
add aqua_temp

### PR DESCRIPTION
**Pull request by elad-bar**
## Proposed change
Add new integration to HACS - Aqua Temp

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
  https://github.com/radical-squared/aquatemp
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I could not find the public repository providing this custom integration. Can you please point me to it?

Thanks! 👍 

../Frenck

**Comment by elad-bar** [comment]
@frenck repo is available at https://github.com/radical-squared/aquatemp

**Comment by elad-bar** [comment]
not sure if something is still missing from my side for that item to be reviewed, can you please let me know?

thanks

**Review by frenck — APPROVED** [review]
Thanks, @elad-bar 👍 

../Frenck

**Comment by elad-bar** [comment]
Thanks!

**Pull request merged**
