### PR TITLE
Create test

### PR DESCRIPTION
**Pull request by Jarnsen**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by Jarnsen** [comment]
add icon and logo

**Comment by klaasnicolaas** [comment]
You add assets for a custom integration (you have checked this), but put them in the core_integration folder. Missing a link to the integration repository and the hDPI images look quite blurry.

./Klaas

**Comment by Jarnsen** [comment]
> You add assets for a custom integration (you have checked this), but put them in the core_integration folder. Missing a link to the integration repository and the hDPI images look quite blurry.
> 
> ./Klaas

its for custom integration, i haven't better pictures. the custom comtonent ist not realy ready, but for testing the integration i need the icons and logos

**Comment by klaasnicolaas** [comment]
That's not how it works... once your custom integration is ready to use you can add the brand assets here. I also see that someone else is the codeowner (@theosnel) of the integration, who is working on getting it into core 🤔 

./Klaas

**Comment by Jarnsen** [comment]
> That's not how it works... once your custom integration is ready to use you can add the brand assets here. I also see that someone else is the codeowner (@theosnel) of the integration, who is working on getting it into core 🤔
> 
> And you created already an PR: #5400
> 
> ./Klaas

ok, thank you. later i will talk with @theosnel, i know he would like to create a core integration some days before, but at this time its easier to create a custom component. he is the codeowner of both. I would like to help him with the icons and logos. at this time i have a very first copy of the custom component.

https://github.com/Jarnsen/ha-xsense-component_test thats the for of a test of the first version.

**Comment by Jarnsen** [comment]
https://github.com/Jarnsen/ha-xsense-component_test

is it now corect?

**Comment by klaasnicolaas** [comment]
You still have to place the logos in the correct folder since it is a custom integration.

./Klaas

**Comment by Jarnsen** [comment]
How Can i do that, close this request and Open a new with the right Folder.

**Comment by klaasnicolaas** [comment]
By putting the files in the correct folder and committing it to the branch you also used for this PR.

./Klaas

**Comment by Jarnsen** [comment]
ok, thank you

**Pull request closed without merging**
