### PR TITLE
Add logos for new aruba_instant component.

### PR DESCRIPTION
**Pull request by apaperclip**
## Proposed change

A new aruba device_tracker component is being created that will use the device API and will offer more capabilities. It will eventually replace the existing aruba component. This PR is to get the logos in place for the eventual code PR for the new component.  These images are simply a copy of the existing aruba component logos.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:  https://github.com/home-assistant/core/pull/42442
- Link to documentation pull request:  https://github.com/home-assistant/home-assistant.io/pull/15429
- Link to integration documentation on our website:  tbd

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
So these are copies from the logos in the `aruba` folder, right?
If so, this folder should be symlinked (and not a copy).

**Comment by apaperclip** [comment]
Correct, just copies. The long term plan is to sunset the legacy aruba integration so I duplicated them .  To do a symlink do you mean an os filesystem symbolic link of the new directory to the old or some other method?

**Comment by frenck** [comment]
if the plan is to sunset the original integration, IMHO, that should be already merged into the existing integration (or slowly build upon the existing integration instead).

**Comment by frenck** [comment]
closing PR as the parent PR has been closed.

**Pull request closed without merging**
