### PR TITLE
add icon for yr

### LINKED ISSUE #804: Yr is missing brand images
## The problem

The Yr integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/yr/icon.png`
- `src/yr/logo.png`
- `src/yr/icon@2x.png`
- `src/yr/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: yr.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/yr.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @danielhiversen! Mind taking a look at this issue as it is with an integration (yr) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/yr/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

### PR DESCRIPTION
**Pull request by flowolf**
## Proposed change

add icon for yr (aka yr.no)

## Type of change

- [ ] Add a new logo or icon for a new integration
- [x] Add a missing icon or logo for an existing integration
- [ ] Replace an exiting icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #804
- Link to code base pull request: 
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/12612
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
Should we add the logo's too?

met-logo (1) (2)
met-logo (1) (1)

**Comment by flowolf** [comment]
I've never seen this logo before. Would not recognize it - and I'm using their app.

**Comment by frenck** [comment]
YR is a service provided by met.no. It is a bit weird, I agree. 
Same for the met.no integration and services, that use the met.no logo, but on all apps, websites and social media, they use the YR icon on met.no services...

🤷‍♂

**Comment by flowolf** [comment]
then the question would be where does HA use the logo and where the icons? IMO the YR brand seems to be the more popular one. As the service is also named 'yr', I'd tend to just use that.

**Comment by frenck** [comment]
Ok makes sense, alternative just a `logo.png`? (Could not find a big enough image for the 2x size).

Yr-logo

**Comment by flowolf** [comment]
that seems to be the OLD logo. I had that in the folder, and read up on it - did not commit it because it's old.

**Comment by frenck** [comment]
Yeah, you're right, looked around, but this square icon is now their logo as well indeed. So let's stick with that 👍

**Comment by palengh** [comment]
Could be I'm late to the "party", guys. 
Yr is the joint online weather service from the Norwegian Meteorological Institute (met.no) and the Norwegian Broadcasting Corporation (NRK). 
These two public institutions have worked together since 1923 transmitting weather forecasts to Norway and abroad.

Yr is unique in Europe because of their very detailed weather forecasts and the free data policy. [Information about the free weather data service](http://om.yr.no/verdata/free-weather-data/%20%E2%80%8E).

Yr was released in September 2007 and quickly became a popular site in Norway. A survey in June 2008, showed that 87 percent of the Norwegian population knew about Yr, and today up to 9 million use it every week.

Source: [help.yr.no](url)
You may also be interested in: [About Yr, the API and our privacy policy](https://hjelp.yr.no/hc/en-us/categories/200450271-About-Yr-the-API-and-our-privacy-policy)

**Comment by flowolf** [comment]
@palengh thanks for clearing that up. I think we used the correct graphics then 😄

**Comment by palengh** [comment]
> @palengh thanks for clearing that up. I think we used the correct graphics then 😄

Not really. You chose the producer’s logo; The Norwegian Meteorological Institute (met.no), not the logo for the service, which is yr.no. I would have chosen the circular blue yr logo, which is their primary logo. 
[see logos, primary first, then  secondary. ](https://info.nrk.no/design/profiler/yr/)

**Comment by flowolf** [comment]
> > @flowolf ; thanks for clearing that up. I think we used the correct graphics then 😄
> Not really. You chose the producer’s logo; The Norwegian Meteorological Institute (met.no), not the logo for the service, which is yr.no. I would have chosen the circular blue yr logo, which is their primary logo.
> ...

we used the round logo, as per commit f666537.

**Comment by frenck** [comment]
This PR has been closed and processed. If there is an issue, please open an issue. Or open a PR to correct things.

Thanks! 👍

**Pull request merged**
