### PR TITLE
Add logos for EyeOnWater

### PR DESCRIPTION
**Pull request by disforw**
## Proposed change

New integration EyeOnWater

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by disforw** [comment]
@frenck sorry, this PR was to merge the files in to the HACS directory. The is currently a PR to core for this integration, but it is still a WIP. Can we merge this to the custom_componants directory for now, and I will open a new PR to brands once we’re getting closer to finalizing the core PR?

**Comment by frenck** [comment]
> Can we merge this to the custom_componants directory for now

That makes no sense? As there is a parent PR open in our code codebase that uses this domain. The custom integration should not use the same domain, it will cause collisions.

../Frenck

**Comment by disforw** [comment]
Being that I thought I was getting ready for a custom_integration, I uploaded the files to custom_integration\eyeonwater. Now that we are pushing forward to a core integration. I moved them to core_integrations\eyeonwater.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
