### PR TITLE
First integration Myfox custom integration logos & icons

### PR DESCRIPTION
**Pull request by eGate2019**
# Proposed change
## Type of change
Add a new logo or icon for a custom integration (custom component) I've not yet opened up a **PR** for my custom integration on the **Home Assistant**
## Additional information
The integration of the custom component is ongoing
## Checklist
 * Icon image size is 256x256px (icon.png)
 * hDPI icon image size is 512x512px for (icon@2x.png)
 * Logo image size has min 128px, but max 256px, on the shortest side (logo.png)
 * hDPI logo image size has min 256px, but max 512px, on the shortest side (logo@2x.png)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @eGate2019, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2256).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by eGate2019** [comment]
Hi,
I have almost completed the integration of Myfox interface based already https://api.myfox.me/. This integration requires the provisioning of the myfox logo and icon.

**Review by frenck — CHANGES_REQUESTED** [review]
I could not find this integration, could you provide me with a link to the repository?

**Comment by frenck** [comment]
@eGate2019 Friendly reminder, could you provide me with a link to the custom integration? Also, at this point, the CI fails, could you take a look at that as well?

Thanks! 👍

**Comment by eGate2019** [comment]
Hello Franck,
My integration of Myfox (HC2) supporting the  https://api.myfox.me/  API is not completed. The logos were missing .
The pull-request was about the logos only. The repository is here. 
https://github.com/eGate2019/brands/tree/master/custom_integrations/myfox
Best regards, Alain

**Comment by frenck** [comment]
> My integration of Myfox (HC2) supporting the api.myfox.me API is not completed. 

I'm confused, so there is no integration? I can't find the integration online, could you provide a link to the repository?

Also, as stated before, the build isn't passing, so I can't merge.

image

You have to fix that and provide a public link to the integration in order for me to be able to merge this PR.

**Comment by frenck** [comment]
PR has been running stale closing it for now. Please feel free to re-open when ready to address the build issue.

Thanks!

../Frenck

**Pull request closed without merging**
