### PR TITLE
Added mercedesmeapi icons

### PR DESCRIPTION
**Pull request by xraver**
## Proposed change

Added Mercedes Me Logos.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The 2x version looks blown up / pixelated.

Maybe consider removing it?

**Comment by xraver** [comment]
Thank you for the feedback.
I've removed the 2x.

**Review by frenck — APPROVED** [review]
Thanks, @xraver 👍 

Happy Holidays 🎄

**Comment by xraver** [comment]
same to you! thanks!

Il giorno lun 21 dic 2020 alle ore 21:38 Franck Nijhof <
notifications@github.com> ha scritto:

**Pull request merged**
