### PR TITLE
Add brand images for Apple WeatherKit

### PR DESCRIPTION
**Pull request by tjhorner**
## Proposed change

This PR adds the brand image for Apple WeatherKit, sourced directly from their attribution info. Apple provides `@2x` and `@3x` images for both the square icon and the logo, but they did not meet the requirements for inclusion here, so I used the highest resolution they had available and made them match the requirements. This means that they needed to be upscaled, as Apple does not provide SVGs for these.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to code base pull request: https://github.com/home-assistant/core/pull/99895
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/28833

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)

### CODE REVIEW

**Comment by bdraco** [comment]
The images aren't so great but out of time to dig for better ones so I left this for now

**Comment by tjhorner** [comment]
I agree, the horizontal logo image especially isn't that good. I can recreate them in a higher resolution and open another PR later if that sounds good @bdraco

**Comment by bdraco** [comment]
No rush on merging this since we have until the end of the month before it goes out anyways

**Comment by tjhorner** [comment]
Ok great, I will go ahead and add the improved images to this PR then

**Comment by tjhorner** [comment]
Re-created the logo as SVG and rendered them out in a higher resolution. Looks much better now. Couldn't find a better version of the icon, but I think it looks fine at the sizes it will be displayed at.

**Review by bdraco — APPROVED** [review]
Thanks @tjhorner

**Pull request merged**
