### PR TITLE
Add iammeter logo

### PR DESCRIPTION
**Pull request by lewei50**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by lewei50** [comment]
I'v uploaded logo file to folder "core_integrations/iammeter/logo.png",hope its the right place this time.
thanks for your patience.

**Review by frenck — CHANGES_REQUESTED** [review]
The image has a lot of whitespace around the edge, please trim the image to remove that.

For specification of the images used in this repository see:

<https://github.com/home-assistant/brands#image-specification>

**Comment by lewei50** [comment]
> The image has a lot of whitespace around the edge, please trim the image to remove that.
> 
> For specification of the images used in this repository see:
> 
> https://github.com/home-assistant/brands#image-specification

I have changed the logo file,removed whitespace.

**Review by frenck — APPROVED** [review]
Thanks, @lewei50 👍

**Comment by lewei50** [comment]
thanks for your review,
I'v seen the logo updated on homepage,
could I close this PR or wait it closed automaticly ?

**Pull request merged**
