### PR TITLE
Add Coway icon and logo

### PR DESCRIPTION
**Pull request by RobertD502**
## Proposed change

Add icon and logo for Coway IOCare as it is currently missing. [Link](https://github.com/sarahhenkens/home-assistant-iocare) to IOCare custom component. 

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
- [ ] I've opened up a PR for my custom integration on the [Home Assistant Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @RobertD502, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2356).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by RobertD502** [comment]
Is there anything else that I need to do to get this pushed through?

**Review by frenck — CHANGES_REQUESTED** [review]
So, there is a bit of a mixup happening here.

IoCare seems to be the name of the app product. However, this repository handles brand images, not product images. So I would only expect coway logos and icons in this PR.

**Comment by RobertD502** [comment]
Sorry about that! I went ahead and removed the iocare directory and added a coway directory with just the coway icon and logo.

**Review by frenck — CHANGES_REQUESTED** [review]
The logo is an icon? Please make sure the logo is just the logo.

**Comment by RobertD502** [comment]
Their logo is just "Coway" as seen in the logo files. For their brand icon, they use the company name as well- I pulled the icon from their official channels. They do have unique icons for specific products such as "IoCare" and "Coway Tower", but since this PR is for the brand itself, I added the plain brand icon.

**Comment by frenck** [comment]
The logo is in an icon format. Its needs to have all empty space around the actual logo removed.

**Comment by RobertD502** [comment]
Sorry about that frenck. I misread the instructions and though the logos were restricted to 256x256 and 512x512- that's besides me forgetting to remove as much background as possible. New logo files should be correct.

**Review by frenck — APPROVED** [review]
Nice! Thanks @RobertD502! 👍  🎉

**Pull request merged**
