### PR TITLE
To adapt HACS domain requirement

### PR DESCRIPTION
**Pull request by blindlight86**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I only see an icon being added? What is supposed to be happing with the old icon?

**Comment by blindlight86** [comment]
add a logo and change the domain for HACS

**Comment by frenck** [comment]
I get what you are trying to do, but the old one isn't cleaned up? 

See: https://github.com/home-assistant/brands/pull/1957/files

It only adds files. Where is your previous PR cleaned up in this case?

**Comment by blindlight86** [comment]
> I get what you are trying to do, but the old one isn't cleaned up?
> 
> See: https://github.com/home-assistant/brands/pull/1957/files
> 
> It only adds files. Where is your previous PR cleaned up in this case?

The old folder "usr_iot" is already gone.  I just change the folder name as I memember.
https://github.com/blindlight86/brands/commit/b5eab624a6ccd645f763b65b587bd07a71d7cd5b#diff-39fb5269fe2fcbfc0469268af93b2aab2f3e18b51c4f7b7b4055b7f7fcef5215
I'm new to "git" system. Is there supposed to be a "delete folder" commit if I do this?

**Comment by frenck** [comment]
Your fork is out of sync with the reality here. Please git rebase your branch (as a matter of fact, please use feature branches)

**Pull request closed without merging**
