### PR TITLE
Add pid_controller

### PR DESCRIPTION
**Pull request by soloam**
## Proposed change
Add new custom_integrations pid_controller

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @soloam, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3078).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
- I can't find the public repository for this custom integration, could you please point me to it?

- The logo looks like the HA house, we generally don't accept that (unless the icon is from a registered brand), to prevent people from thinking it is an officially supported integration.

**Comment by soloam** [comment]
The repo is https://github.com/soloam/ha-pid-controller. I'm going to push it to HACS when it's available in brands.

If it's a problem I can remove the house from the logo! Is this a issue?

Tks

**Comment by soloam** [comment]
Done, icon updated to remove the HA house

**Review by frenck — APPROVED** [review]
Thanks, @soloam 👍

**Pull request merged**
