### PR TITLE
Add logos for growatt_server_hacs (direct copy of growatt_server from…

### PR DESCRIPTION
**Pull request by muppet3000**
… core_integrations)

## Proposed change

Adds logos for Growatt Server HACS custom component: https://github.com/muppet3000/growatt_server_hacs

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The PR looks good, but I do know that HACS will reject integration domains with `hacs` in the domain.

../Frenck

**Comment by muppet3000** [comment]
@frenck Thanks for the heads-up. I'll do a re-brand in that case and change the directory once I think of a better name! (I want to keep the name and the domain the same where possible).

**Comment by frenck** [comment]
> Does the name of the folder in this repository have to match the name of the domain in the custom component?

Yes.

**Comment by muppet3000** [comment]
Pushed changes to rename to `growatt_server_api`, I've just renamed it all in the custom component repo as well which should now align.

**Comment by frenck** [comment]
CleanShot 2023-01-06 at 14 13 57

**Comment by muppet3000** [comment]
> CleanShot 2023-01-06 at 14 13 57

When I asked earlier you said it was just the domain that needed to match. 
I agree that I missed the folder rename, but does the whole repository have to be named to match?

**Comment by frenck** [comment]
> When I asked earlier you said it was just the domain that needed to match.

You asked: "Does the name of the folder in this repository have to match the name of the domain in the custom component?"

To which I answered affirmatively.

However, there seem to be other mismatches too.

**Comment by muppet3000** [comment]
> > When I asked earlier you said it was just the domain that needed to match.
> 
> You asked: "Does the name of the folder in this repository have to match the name of the domain in the custom component?"
> 
> To which I answered affirmatively.
> 
> However, there seem to be other mismatches too.

I think I've confused things, I was referring to this brand repo.

I have now changed everything in my repo with the exception of the name of the repo itself. Can you confirm if it's now in an acceptable state?

**Review by frenck — APPROVED** [review]
Thanks, @muppet3000 👍 

../Frenck

**Pull request merged**
