### PR TITLE
add kumo cloud icons for custom component

### PR DESCRIPTION
**Pull request by omriasta**
## Proposed change
Add logo for kumo cloud custom component

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X ] The added/replaced image(s) are **PNG**
- [ X] Icon image size is 256x256px (`icon.png`)
- [ X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by omriasta** [comment]
Hey @frenck do you know if anyone can help us get kumo up and running with config flow so it can be integrated with homeassistant? I saw that @bdraco got this done for rachio and was wondering if he could help out? @dlarrick has everything all setup as a custom component in HACS here https://github.com/dlarrick/hass-kumo 
I'll be more than happy to test out...just don't know my way around python....

**Comment by bdraco** [comment]
@omriasta,
 
If @dlarrick is interested they can get the process started by submitting a PR after doing something like this:

Create a branch, merge in the kumo code, get started on the config flow with `python3 -m script.scaffold config_flow`, and send a PR when its ready for review.

**Comment by omriasta** [comment]
@bdraco I tried to do the PR myself...already warned you that I don't know my way around python or github so apologize in advance if I did it wrong.... Let me know if I can do anything else.

**Comment by bdraco** [comment]
> @bdraco I tried to do the PR myself...already warned you that I don't know my way around python or github so apologize in advance if I did it wrong.... Let me know if I can do anything else.

The PR needs to come from @dlarrick as its their code and we need to verify they are ok with merging it though the `cla` process.

**Pull request merged**
