### PR TITLE
Add Binance logo

### PR DESCRIPTION
**Pull request by DevSecNinja**
## Proposed change

Add the Binance logo (new integration)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/46662
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/16773
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/binance/

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logo's for binance are available as SVG: 

<https://commons.wikimedia.org/wiki/File:Binance_logo.svg>

Please add those as well 👍

**Comment by DevSecNinja** [comment]
> The logo's for binance are available as SVG:
> 
> https://commons.wikimedia.org/wiki/File:Binance_logo.svg
> 
> Please add those as well 👍

Sure! I don't see any other SVG files in the repository, so I assume you want me to convert it to PNG and upload it as logo.png. Working on it. (Y)

**Comment by frenck** [comment]
This PR adds brand images to the `custom_integrations` folder, however, there is a parent PR linked to add it as a core integration. Therefore, the images should go into the `core_integrations` folder.

**Comment by DevSecNinja** [comment]
> This PR adds brand images to the `custom_integrations` folder, however, there is a parent PR linked to add it as a core integration. Therefore, the images should go into the `core_integrations` folder.

Thanks, I moved the images.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
