### PR TITLE
Adding CleverSpa Icons and Logos

### PR DESCRIPTION
**Pull request by Wh1terat**
## Proposed change

Add logos for CleverSpa (hot tubs) for new custom component in development.
High res (extracted SVG from PDF Manual), correctly sized and including variants for light/dark themes.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
Please add a public link to the repository of this custom integration to the descript ion this PR

**Comment by Wh1terat** [comment]
> Please add a public link to the repository of this custom integration to the description this PR

As stated "new custom component **in development**." 
Currently hosted at https://github.com/Wh1terat/cleverspa-component

**Comment by ludeeus** [comment]
> Edit:
Perhaps worth adding that as a requirement to the pull request template if it is required. (Although other accepted pulls do not seem to have asked for the url to an in-progress component..)

For most custom integration that is not needed since they also open a PR against the wheels repo (which includes a link in that PR)
Looking at your manifest, you also need to add a PR against that repo.

**Comment by Wh1terat** [comment]
> For most custom integration that is not needed since they also open a PR against the wheels repo (which includes a link in that PR)
> Looking at your manifest, you also need to add a PR against that repo.

Thanks @ludeeus - I was unaware of that process (my bad!)
PR now raised home-assistant/wheels-custom-integrations#497

**Review by Wh1terat — COMMENTED** [review]
.

**Review by ludeeus — APPROVED** [review]
Thanks :+1:

**Pull request merged**
