### PR TITLE
Add beolink assets

### PR DESCRIPTION
**Pull request by djerik**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This seems like assets from an icon form the app? We collect manufacturer branding in this repository, which would mean the B&O branding should have been used.

../Frenck

**Comment by djerik** [comment]
This BeoLink custom component is essentially a bridge between HA and the BeoLink app, giving BeoLink users control of their HA entities in the Bang & Olufsen look and feel app. This is to me similar to the HomeKit Bridge component, that uses the HomeKit app icon and not the Apple icon.

**Comment by frenck** [comment]
Sorry, you are comparing internals, which follow in some cases a different ruleset.

In the end, this custom integration is to integrate B&O devices and thus should carry their branding.

../Frenck

**Comment by djerik** [comment]
The component publish HA entities to the BeoLink iOS app without having to own any Bang & Olufsen devices. It does not provide an integration to any types of Bang & Olufsen devices.

Maybe check out screenshots in repository or App Store for reference?

https://apps.apple.com/dk/app/beoliving/id1417970502?l=da

**Review by frenck — APPROVED** [review]
Thanks for that clarification @djerik 👍 

../Frenck

**Pull request merged**
