### PR TITLE
New icons and logos for apple_airplayer

### PR DESCRIPTION
**Pull request by filmgarage**
## Proposed change

These icons and logos are for the specific AirPlay feature of Apple.
I think they represent this integration better than the generic Apple logo.
The artwork has an alpha channel and a dark_mode version to make it suit all possible backgrounds.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [X] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
AirPlay isn't a brand, but an product image/logo.

We collect brand images in this repository, so the Apple logo is expected.

**Comment by filmgarage** [comment]
I tried following the logic as it is applied in the home-assistant brands collection already. For HomeKit I noticed the HomeKit Icon. For Google Cast likewise, it uses the Google Cast Icon, not the generic Google Icon. This integration supports the specific AirPlay service which is available on a lot of platforms and devices by a lot of vendors nowadays. On top of that Airplay is indeed a brand 'owned' by Apple. it shows up in their extensive list of Trademarks.

Schermafbeelding 2022-01-21 om 09 47 50

**Comment by frenck** [comment]
As I stated in my previous comment, we generally do not add product branding to this repository. Thus I requested changes on this PR, as it contains product branding.

**Comment by filmgarage** [comment]
May I ask why you decided otherwise for the logos of Google Cast and HomeKit? From my point of view a HomePod or an AppleTV is the product, AirPlay is the service. BTW: I don't want to be pushy! I'll just pull this request again. Just curious to know.

**Pull request closed without merging**
