### PR TITLE
Added `sonnen_batterie`

### PR DESCRIPTION
**Pull request by yxkrage**
## Proposed change

Added logos and icons for _Sonnen Batterie_ home battery as `sonnen_batterie`. A custom integration named `sonnenbatterie` is already present but it should have an underscore in the name since _Sonnen_Gmbh_ provides other hardware that might require other logos e.g. `sonnen_inverter`.

Since, in this case, case the images are the same `sonnen_batterie` have been added as a symbolic link, pointing to `sonnenbatterie` which should be possible according to the `README.md`.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by klaasnicolaas — CHANGES_REQUESTED** [review]
> Symlinks are currently not allowed in the custom integrations folder.

./Klaas

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @yxkrage 👋 

I could not find the public repository providing this custom integration. Can you please point me to it?

Thanks 👍 

../Frenck

**Comment by Poshy163** [comment]
Have a feeling its referring to this integration: https://github.com/weltmeyer/ha_sonnenbatterie

**Comment by yxkrage** [comment]
> Have a feeling its referring to this integration: https://github.com/weltmeyer/ha_sonnenbatterie

No, it actually this one: https://github.com/yxkrage/hass-sonnen

The repo is currently lacking `README.md`, but it will be added soon.

**Review by frenck — APPROVED** [review]
Thanks, @yxkrage 👍 

../Frenck

**Pull request merged**
