### PR TITLE
Add Yandex Weather icons for custom integration

### PR DESCRIPTION
**Pull request by IATkachenko**
## Proposed change

[Yandex weather](https://yandex.ru/pogoda) icons for custom integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I would have expected the Yandex logos and icons, as that is the brand?

**Comment by IATkachenko** [comment]
@frenck hello.

Yandex is using different icons for different services (you may see it in other yandex_* folders).
Umbrella is the icon for weather service.

Unfortunatly, official logo, from branding guidelines, does not meet Home Assiststan size requirements.

**Comment by frenck** [comment]
@IATkachenko Sure, but our goal is not to collect service or product icons, we collect branding assets in this repository. Hence the name 😉

**Comment by IATkachenko** [comment]
@frenck so _(just to be sure that I understand you and key concept right)_: it will be OK if [weather service](https://yandex.com/weather/) will have same icon like [search](https://yandex.ru/) and like any of [50+ different services](https://yandex.ru/all) started with "Yandex" _(theoretically, of course. Now Home Assistant have just few integration with Yandex services, but in brilliant future it will have integration to all services in the World and users will be able to use what they want)_?

I'm suggesting weather service icon for `yandex_weather` domain because it is locally well known icon and user will be confused if weather service will have browser(search/maps/dzen/any of..) icon. Like Youtube with Google Search icon (both this service have "Google" brand)

If Home Assistant should have same icon for all Yandex services (just because it "Yandex" brand), which service logo should we prefer: [general Yandex](https://company-docs.s3.yandex.net/logo21/yandex_logo_en.pdf) with asymmetric Y as icon, browser with symmetric Y or something else?
Alternative idea -- make icon like https://github.com/home-assistant/brands/blob/master/custom_integrations/yandex_smart_home/icon.png: general icon for background and service icon in the conner. From my point of view it worse than native weather logo, but better than same logo for all services branded with Y. Is is acceptable?

**Comment by IATkachenko** [comment]
Have asked Yandex support team for images that meet HA requirements. Let's wait for result... 

Should we close this PR (because current images could not be accepted) and open new iа any suitable images will be received from support? Or keep it open until response and just update images (if any) / close as "could not be merged" after?

**Comment by frenck** [comment]
We already have those, Yandex is already here, just need to copy those same assets into this PR...

**Comment by IATkachenko** [comment]
No one from yandex_ (`core/yandex_transport`, `core/yandextts`, `custom_integrations/yandex_*`) icons in this repository is suitable for Weather. May be some logo may be reused (I should check more carefully).

Yandex have [more than different 50 services](https://yandex.ru/all) and it is not good idea to have same images for all Yandex integrations. Put `_transport` icon to `_weather` is like use Google maps icon for Google search.

**Comment by frenck** [comment]
> Yandex have more than different 50 services and it is not good idea to have same images for all Yandex integrations. 

That is how we decided to run this, as I explained above. We collect brand images, not service images. All Yandex-provided sources should use the same Yandex branding. This PR will not be accepted otherwise.

**Comment by IATkachenko** [comment]
I see. Will use general icons/logo...

Before making this PR I have checked repository for similar situation and have found `broadlink_`,  `cez_`, `damba_`, `dlink_`, `ecodevices*`, `fordpass`, `ge_`, `ha_`, .. `yandex_` itself  _(#1699, #2649, #2489)_ and only `cez` use same icon for all domains. So I thought it should be locally well known icon/logo for `_weather`, rather than general.

**Comment by frenck** [comment]
Let keep it with this review. Things done or accepted in the past don't affect this PR review.

**Comment by IATkachenko** [comment]
Took icons/logo from `core_integrations/yandextts`.

**Review by frenck — APPROVED** [review]
Thanks, @IATkachenko 👍

**Pull request merged**
