### PR TITLE
Add icons for viaris custom integration

### PR DESCRIPTION
**Pull request by HGC72**
## Proposed change

Add icon for [viaris](https://github.com/orbis-developers/home_assistant_viaris) custom integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I cannot find the use of this branding by Orbis

https://orbis-ev.com/

CleanShot 2023-05-21 at 13 54 25@2x

And on their socials:

CleanShot 2023-05-21 at 13 55 10@2x

Please adjust this PR to provide the actual manufacturer branding.

Thanks already! 👍

../Frenck

**Comment by HGC72** [comment]
> I cannot find the use of this branding by Orbis
> 
> https://orbis-ev.com/
> CleanShot 2023-05-21 at 13 54 25@2x
> 
> And on their socials:
> CleanShot 2023-05-21 at 13 55 10@2x
> 
> Please adjust this PR to provide the actual manufacturer branding.
> 
> Thanks already! 👍
> 
> ../Frenck

Hi Frenck,

Thanks for you review. You can find the use of this branding by Orbis in this link https://play.google.com/store/apps/details?id=com.orbis.eviaris&hl=es&gl=US. Please, let me know if it is enough.
Regards,

**Comment by frenck** [comment]
> You can find the use of this branding by Orbis in this link [play.google.com/store/apps/details?id=com.orbis.eviaris&hl=es&gl=US](https://play.google.com/store/apps/details?id=com.orbis.eviaris&hl=es&gl=US). Please, let me know if it is enough.

That is an application graphic/image, not a manufacturer branding. Please use the brand assets instead.

../Frenck

**Comment by HGC72** [comment]
> > You can find the use of this branding by Orbis in this link [play.google.com/store/apps/details?id=com.orbis.eviaris&hl=es&gl=US](https://play.google.com/store/apps/details?id=com.orbis.eviaris&hl=es&gl=US). Please, let me know if it is enough.
> 
> That is an application graphic/image/icon, not a manufacturer branding. Please use the brand assets instead.
> 
> ../Frenck

Ok, thanks.

**Review by frenck — CHANGES_REQUESTED** [review]
Same comment as before, you changed the icon, but didn't resolve the actual request. The previous and currently provided branding doesn't match the branding of the manufacturer.

../Frenck

**Comment by HGC72** [comment]
> Same comment as before, you changed the icon, but didn't resolve the actual request. The previous and currently provided branding doesn't match the branding of the manufacturer.
> 
> ../Frenck

Hi Frenck,
Thanks again. This is the favicon we use on the Orbis website. What is the problem?

**Comment by HGC72** [comment]
Hi, Frenck
We have updated our icon in social media with this one. Please, could you check if this pull request is right?

**Comment by HGC72** [comment]
Please, could you tell me if the provided icon is suitable? I don't get any answer from the last comments.

**Comment by frenck** [comment]
Sorry, @HGC72 I'm not sure if the PR is ready for review? It is marked as draft.

See also the initial response from our bot to learn more about our review process: <https://github.com/home-assistant/brands/pull/4385#issuecomment-1556160358>

**Comment by HGC72** [comment]
Hi! Yes, it is ready for review.

**Comment by HGC72** [comment]
Thanks! @frenck, I installed my custom integration with HACS but I still don´t see the icon.

**Comment by frenck** [comment]
That is possible, we cache heavily on CloudFlare. The cache is flushed on each major release of Home Assistant (first Wednesday of the month). It is possible it becomes available sooner (if the cache expires on certain enpoints).

**Pull request merged**
