### PR TITLE
Added qBittorrent brand images

### LINKED ISSUE #558: qBittorrent is missing brand images
## The problem

The qBittorrent integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/qbittorrent/logo.png`
- `src/qbittorrent/icon@2x.png`
- `src/qbittorrent/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

### PR DESCRIPTION
**Pull request by LanceMcCarthy**
This commit adds 3 images and replaces the old icon.png file.

## Type of change

- [ ] Add a new logo or icon for a new integration
- [x] Add a missing icon or logo for an existing integration
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #558 
- Link to code base pull request: n/a
- Link to documentation pull request: n/a
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/qbittorrent/

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by LanceMcCarthy** [comment]
Note: The @2x icons are not upscaled from 1x. I personally rendered all sizes directly from the source SVG.

**Comment by LanceMcCarthy** [comment]
Indeed, it does. I went through the source https://github.com/qbittorrent/qBittorrent/tree/master/src/icons.

I'll try their CDN instead for brand-specific info and switch to  those

**Comment by LanceMcCarthy** [comment]
I've removed the extra elements form the SVG and re-exported. Bonus: this also allowed me to remove padding thanks to the 1:1 aspect ratio.

**Comment by frenck** [comment]
Nice! Since the logos are now the same as the icons, we can drop the logos (icons will serve as a fallback automatically).

**Comment by LanceMcCarthy** [comment]
Done! :shipit:

**Pull request merged**
