### PR TITLE
pokeys

### PR DESCRIPTION
**Pull request by domen-jersek**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ x ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ x ] The added/replaced image(s) are **PNG**
- [ x ] Icon image size is 256x256px (`icon.png`)
- [ x ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ x ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ x ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Somethings seems wrong with the x2 versions, they look blown up?

CleanShot 2023-09-12 at 11 43 19

Could you take a look?

../Frenck

**Comment by domen-jersek** [comment]
I couldnt find any higher resolution images for 2x versions can i use these?(the icon2x should be 512x512px)

**Comment by frenck** [comment]
> I couldnt find any higher resolution images for 2x versions can i use these?(the icon2x should be 512x512px)

In those cases, just omit the 2x versions.

**Review by frenck — APPROVED** [review]
Thanks, @domen-jersek 👍 

../Frenck

**Pull request merged**
