### PR TITLE
Added brand images for `gs_alarm` custom integration

### PR DESCRIPTION
**Pull request by hostcc**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @hostcc, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3167).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
The 2x images look rather blown up:

CleanShot 2022-02-20 at 11 28 07@2x

Maybe omit them instead?

**Comment by hostcc** [comment]
> The 2x images look rather blown up:
> 
> CleanShot 2022-02-20 at 11 28 07@2x
> 
> Maybe omit them instead?

@frenck, I think that'd be the best way - since I'm not associated with the brand anyhow I had hard time to find even a lowres logs and then scaled them up. Lemme quickly drop those 2x, sir

**Review by frenck — APPROVED** [review]
Thanks, @hostcc 👍

**Comment by hostcc** [comment]
> Thanks, @hostcc 👍

Likewise, @frenck, sir - that was fast as lightning ;)

**Comment by frenck** [comment]
🚀 🤘 
Your welcome sir! 👍

**Pull request merged**
