### PR TITLE
Added icon and logo for custom integration Airstage

### PR DESCRIPTION
**Pull request by danielkaldheim**
## Proposed change

Added Airstage logo and icon for custom integration: https://github.com/danielkaldheim/ha_airstage

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is a Fujitsu product, and thus we except their brand to be used.

The assets provided are product branding, which is not what we collect in general.

../Frenck

**Comment by danielkaldheim** [comment]
Thanks for reviewing.

Would you rather have it like "Fujitsu Airstage" or just "Fujitsu" only?

**Comment by frenck** [comment]
Looking upstream, they mix and match it a lot as well. Some places they seem to fully hide the "Fujitsu". Although we generally just go for the main-brand only (just Fujitsu in this case); I think ""Fujitsu Airstage" is acceptable as well.

../Frenck

**Comment by danielkaldheim** [comment]
Thank you for clarifying that for me. 

I'll update my custom integration to use of "fujitsu_airstage" domain since here are possible other Fujitsu aircondition (not airstage) integration give room for other fujitsu integrations.

**Review by frenck — APPROVED** [review]
Thanks, @danielkaldheim 👍 

../Frenck

**Pull request merged**
