### PR TITLE
Add Lyric Icons from to custom_integration

### PR DESCRIPTION
**Pull request by jasondefuria**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by jasondefuria** [comment]
I think that I fixed it. This is my first PR, so I am hoping that I succeeded.

**Comment by frenck** [comment]
@jasondefuria Nope, sorry. You cannot revert it (as you will now actually revert a PR from someone else). You need to git rebase it.

**Comment by jasondefuria** [comment]
Went through rebase. Still learning, apologize for any problems that I've caused!

**Comment by frenck** [comment]
Don't worry, we all had to learn it at some point 😄 

So the last commit needs to be stripped of, as the revert should not have been done.

`git reset --hard HEAD~1` on your branch, check if it is gone with `git log` and `git push --force` when happy with the result.

**Comment by jasondefuria** [comment]
I believe that is done! Thank you for your help!

**Pull request merged**
