### PR TITLE
Add lacrosseview

### PR DESCRIPTION
**Pull request by regulad**
## Proposed change

Add `lacrosseview` icon, for a custom component I have made as well as made a custom wheel for (https://github.com/home-assistant/wheels-custom-integrations/pull/606)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
They seems to use a different brand image/logo themselves:

image

image

**Comment by regulad** [comment]
I have not seen that logo used on any of their view products. I will update it accordingly.

**Comment by regulad** [comment]
@frenck That logo is of the **company** LaCrosse, this change is only for the LaCrosse View line of products, which are not directly tied to the brand and in fact is licensed out to other companies. I believe leaving it as is will be a better approach.

**Comment by regulad** [comment]
If anything, that logo should be attached to the other lacrosse product: https://www.home-assistant.io/integrations/lacrosse/

**Comment by frenck** [comment]
> That logo is of the company LaCrosse, this change is only for the LaCrosse View line of products

This repository collects brand assets, not product assets.

**Comment by regulad** [comment]
I'll update the file then. My bad.

**Comment by regulad** [comment]
@frenck I added the logo as you requested.

**Review by frenck — APPROVED** [review]
Thanks, @regulad 👍

**Review by frenck — CHANGES_REQUESTED** [review]
Oh I see now the CI failed:

> Cloning into 'mdi'...
Error: Invalid logo size! Size is 380x[106](https://github.com/home-assistant/brands/runs/6323360481?check_suite_focus=true#step:3:106)px, shortest side must be at least 128px: custom_integrations/lacrosseview/logo.png


Could you take a look?

**Comment by regulad** [comment]
> Oh I see now the CI failed:
> 
> > Cloning into 'mdi'...
> Error: Invalid logo size! Size is 380x[106](https://github.com/home-assistant/brands/runs/6323360481?check_suite_focus=true#step:3:106)px, shortest side must be at least 128px: custom_integrations/lacrosseview/logo.png
> 
> 
> Could you take a look?

@frenck this is now done

**Review by frenck — APPROVED** [review]
Thanks, @regulad 👍

**Pull request merged**
