### PR TITLE
Add icons & logos for new custom component: somfy_protexial

### PR DESCRIPTION
**Pull request by the8tre**
## Proposed change

Add icons & logos for new custom component somfy_protexial: https://github.com/the8tre/somfy-protexial

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @the8tre 👋 

Thanks for opening a PR!

I've looked at it, but could not find an occurrence where Somfy is using the provided branding. Could you point me to it?

Thanks already!

../Frenck

**Comment by the8tre** [comment]
Hi Frenck,
Maybe I shouldn't have unleashed my creativity on those icons.
Is the rule to stick to existing brand visuals ?
If so I'll switch to standard Somfy icons.

**Comment by frenck** [comment]
Thanks for getting back to me @the8tre 👍 

The issue is that, in general, all companies have branding guidelines that will prohibit the use of modified versions of their branding. Hence, we don't accept those as such.

Hope you'll understand.

../Frenck

**Comment by the8tre** [comment]
That's clear Frenck.
I'll more careful next time.
In between I switch back to Somfy standard branding icons.
Thanks

**Review by frenck — APPROVED** [review]
> I'll more careful next time.

Well, to be honest, I thought they looked cool though 😉


Thanks for the PR 👍 

../Frenck

**Pull request merged**
