### PR TITLE
Create domains.json

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Add a `domains.json` file that holds all the domain  names  we have in this repository.

https://deploy-preview-2536--home-assistant-brands.netlify.app/domains.json

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by balloob** [comment]
Would it be possible that we create 2 lists. One with built-in and one with custom integrations?

**Comment by frenck** [comment]
Built-in, can be used custom?

**Comment by balloob** [comment]
It's up to the consumer to decide how to use this data. Right now the `domains.json` loses if it's a built-in or custom integration information. We don't know all future use cases :)

**Comment by ludeeus** [comment]
We loose that information anyway, since a custom variant that has a matching core domain, will not be in this repository

**Comment by ludeeus** [comment]
https://github.com/home-assistant/brands/pull/2542

**Pull request merged**
