### PR TITLE
Add icon and logo for custom integration nestup_evn

### PR DESCRIPTION
**Pull request by trvqhuy**
## Proposed change

Add icon and logo for custom integration nestup_evn

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @trvqhuy, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3562).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
I cannot find an upstream use of the brand assets supplied.
I do find these though, which doesn't match the ones provided:

image

Could you point me to a resource that uses the provided branding?

Thanks! 👍 

../Frenck

**Comment by trvqhuy** [comment]
Hi @frenck 

Sorry for my silly misunderstanding, the icons and logos above are my personal designs for my 'nestup_vn' component only.

May I ask if the assets needed to be officially created by the endpoints of my custom component? (In my case, the EVN Company)

Thank you.

**Comment by frenck** [comment]
> Sorry for my silly misunderstanding, the icons and logos above are my personal designs for my 'nestup_vn' component only.

> May I ask if the assets needed to be officially created by the endpoints of my custom component? (In my case, the EVN Company)

Well, we are collecting brand images that integrations integrate with and not trying to create a custom collection of brand assets. So yes, this should have the branding of the service being integrated with.

**Comment by trvqhuy** [comment]
Hi @frenck 

Got it. I've changed the logos and icons to meet your conditions.
Please tell me if there's something wrong.

Thank you for your brilliant support.

**Comment by trvqhuy** [comment]
Hi @frenck 

Got it. I've changed the logos and icons to meet your conditions.
Please tell me if there's something wrong.

Thank you for your brilliant support.

**Comment by trvqhuy** [comment]
Hi @frenck 

Could you please verify whether the asset fulfills the requirements for the merge?

Thank you.

**Review by frenck — APPROVED** [review]
Thanks, @trvqhuy 👍

**Pull request merged**
