### PR TITLE
Add fordpass integration icon

### PR DESCRIPTION
**Pull request by clarkd**
## Proposed change

Adds the logo for a new integration: FordPass.

## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/42089
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/15317
- Link to integration documentation on our website: TBC

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

Last two are N/A as using same icon for icon.png & logo.png.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please add the logos as well. The Ford brand images are available as vector images, so that means we can add them.

**Comment by clarkd** [comment]
> Please add the logos as well. The Ford brand images are available as vector images, so that means we can add them.

Hi @frenck, I was under the impression it would use the same image for both icon.png and logo.png. Or is it best to add a proper aspect ratio image (vs 1:1 for icon) for the logo.png?

**Comment by clarkd** [comment]
@frenck Have now added logo.png & logo@2x.png - thanks.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by clarkd** [comment]
Parent PR closed.

**Pull request closed without merging**
