### PR TITLE
Add logo for numato integration

### PR DESCRIPTION
**Pull request by clssn**
## Type of change

- [x] Add a new logo or icon for a new integration
- [ ] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/33816
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/12749
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by clssn** [comment]
@frenck not sure whether it's mandatory but I contacted the Numato company and got permission to use the logo as it is (unchanged) for the documentation. By the time I asked, I wasn't aware of the brands repo at all, so I missed that. So I might need to get back and ask them for an icon variant to use. Any suggestions?

**Comment by cogneato** [comment]
@clssn After some poking around at their site, I found they have the icon available at many sizes (though the quality is not great)
image

I sized them to our specs and the rest of the logo is recreated using their own font details and colors. These should all be ready to go if you want to use them.
icon
icon@2x
logo
logo@2x

**Comment by clssn** [comment]
@cogneato thanks a lot! But now I'm confused, because the logo images you found (and those on their website) are using a different font, than the one they asked me to use unchanged (look at the M, very different): Numato logo with trademark (R). I'll push the logos you proposed as they are way better quality than the one they gave me, besides they're consistent with their website.

**Comment by clssn** [comment]
Code is merged to dev now. Please merge this PR as well as appropriate. Thanks :-)

**Pull request merged**
