### PR TITLE
Add custom component Haier Evo

### PR DESCRIPTION
**Pull request by and7ey**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/and7ey/haier_evo

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This seems like an app icon or product icon that was added in this PR. However, in this repository we collect the branding of manufacturers or service providers.

In this case, I would have expected the Haier branding to be used.

Can you take a look?

../Frenck

**Comment by and7ey** [comment]
> In this case, I would have expected the Haier branding to be used.

I have added icons only, but haven't added logos (which are optional).

Looking at other integrations (for. ex., localtuya and Tuya local; 3 different yandex integrations) - they all have different icons.

**Comment by frenck** [comment]
> I have added icons only, but haven't added logos (which are optional).

Ok 🤷 my review comment wasn't about that.

> Looking at other integrations (for. ex., localtuya and Tuya local; 3 different yandex integrations) - they all have different icons.

That is quite possible, feel free to open PRs to adjust them if you feel they can be improved.


../Frenck

**Comment by and7ey** [comment]
> Ok 🤷 my review comment wasn't about that.

What should be the approach then?

I can leave icon files as is, but should add Haier logos as logo.png/logo@2x.png? 
Or should I replace my icon files with Haier logos as well?

**Comment by frenck** [comment]
It should only contain Haier branding assets.

../Frenck

**Comment by and7ey** [comment]
Ok, I've updated the icons and added logos.

If you have a question about the color (blue vs. black): Haier branding in Russia is black, see https://haieronline.ru.

**Review by frenck — APPROVED** [review]
Thanks, @and7ey 👍 

../Frenck

**Pull request merged**
