### PR TITLE
Add brand image for tami4 integration

### PR DESCRIPTION
**Pull request by Guy293**
## Proposed change

Add brand image for tami4 integration by symlinking to tami4edge custom integration.

## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Symlinking with custom integrations is not allowed, as per the repository readme. Please adjust.

../Frenck

**Comment by Guy293** [comment]
> Symlinking with custom integrations is not allowed, as per the repository readme. Please adjust.
> 
> ../Frenck

Hi French, @Quentame told me that I can and should symlink to the other Integration here: https://github.com/home-assistant/home-assistant.io/pull/24764#issuecomment-1302100553
Maybe he didn't notice it was a custom integration.
I'll adjust the pull request.

**Comment by Guy293** [comment]
I have copied the logo from the other custom integration, But I thought of using this image of the device instead, is it recommended?
icon2-min

**Comment by frenck** [comment]
We generally don't allow the use of product images, unless there is absolutely nothing else available.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request merged**
