### PR TITLE
Add iNELS core integration icons

### PR DESCRIPTION
**Pull request by jpbaltazar**
## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/89504
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by ZeD4805** [comment]
Changed parent PR

**Review by frenck — CHANGES_REQUESTED** [review]
I'm not sure why this part is in the logos:

image

They don't see doing that on their own branding:

CleanShot 2023-03-10 at 14 39 41

**Comment by ZeD4805** [comment]
> I'm not sure why this part is in the logos:
> 
> image
> 
> They don't see doing that on their own branding:
> 
> ![CleanShot 2023-03-10 at 14 39 41](https://user-images.githubusercontent.com/195327/224330548-6d561247-5d48-475c-bdef-675280a3f74f.

Elko ep is the parent company of iNELS.

**Review by frenck — CHANGES_REQUESTED** [review]
> Elko ep is the parent company of iNELS.

Right, but iNELS itself doesn't use it on its branding either (like their own websites). So it feels out of place to add it here. Please remove it.

../Frenck

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
