### PR TITLE
Add xtend_tuya Branding

### PR DESCRIPTION
**Pull request by azerty9971**
## Proposed change

Add the branding for the xtend_tuya custom integration (for usage in HACS).
https://github.com/azerty9971/xtend_tuya

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/azerty9971/xtend_tuya

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is using a modified Tuya logo, which we cannot accept.

We don't allow customized version of branding, as they often violate upstream branding guidelines.

../Frenck

**Comment by azerty9971** [comment]
Hello,
Would this new version be OK ?

Have a nice day !!

**Review by frenck — CHANGES_REQUESTED** [review]
No, we don't allow adjusted brandings. Please use the original Tuya branding.

Thanks 👍 

../Frenck

**Comment by azerty9971** [comment]
Sorry for the multiple issues.
Is this OK?

Have a nice day !!

**Pull request merged**
