### PR TITLE
Updatet icons to match HomeAssistent Guidelines

### PR DESCRIPTION
**Pull request by flame4ever**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by flame4ever** [comment]
[Updatet icons to match HomeAssistent Guidelines]

**Review by frenck — CHANGES_REQUESTED** [review]
The folder name used, is the domain name of an integration. In this case, the folder name `eeve-willow-mower` was used, which is not a valid integration domain.

Integration domains cannot contain dashes (`-`), they can, however, contain underscores.

Additionally, I was not able to find the public git repository providing this integration. Could you point me to it?

../Frenck

**Comment by flame4ever** [comment]
Folder name changed to eeve_mower_willow and icon's uploaded.

**Comment by frenck** [comment]
I'm confused, you requested a review, but the PR is draft?

**Review by frenck — CHANGES_REQUESTED** [review]
The PR looks good! 

The only thing I could not find: The public repository providing this integration. Could you point me to it?

../Frenck

**Comment by flame4ever** [comment]
Here is the link to the integration repository providing this integration. 
https://github.com/flame4ever/eeve_mower_willow

**Comment by frenck** [comment]
Thanks for the PR @flame4ever, but the upstream repo doesn't look like a functional integration?

../Frenck

**Comment by flame4ever** [comment]
Integration v1 fixed and is working now.

**Review by frenck — APPROVED** [review]
Thanks, @flame4ever 👍 

../Frenck

**Pull request merged**
