### PR TITLE
Adding icons for custom integration: bosch_alarm

### PR DESCRIPTION
**Pull request by sanjay900**
## Proposed change

Adding icons for custom [Bosch Alarm Panel](https://github.com/mag1024/bosch-alarm-homeassistant) integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by sushant-here** [comment]
lets merge this!!!

**Review by frenck — CHANGES_REQUESTED** [review]
The icons look like a custom mashup between some icon and the bosch logo. We don't allow such things in our repository (as it often conflicts with branding guidelines). Please use the official branding from Bosch instead.

../Frenck

**Comment by JayVaraBosch** [comment]
> The icons look like a custom mashup between some icon and the bosch logo. We don't allow such things in our repository (as it often conflicts with branding guidelines). Please use the official branding from Bosch instead.
> 
> ../Frenck

I am the product owner at Bosch Security and provided the icons and logo to @sanjay900 for upload. These match our brand guidelines and from our marketing team in Netherlands.

**Comment by frenck** [comment]
👋 @JayVaraBosch Could you point me to a location where Bosch is using this as their general branding? As I failed to find such a resource.

../Frenck

**Comment by JayVaraBosch** [comment]
> 👋 @JayVaraBosch Could you point me to a location where Bosch is using this as their general branding? As I failed to find such a resource.
> 
> ../Frenck

Please see this link: https://www.boschsecurity.com/xe/en/ Brand logo is at the top. For the  icon this matches Bosch internal brand guide. 
Also as a reference you can see the logo for our mobile application is the same purple color with Bosch branding on the lower white section  https://apps.apple.com/au/app/bosch-remote-security-control/id1279443352 

image

**Comment by frenck** [comment]
@JayVaraBosch Thanks, can you point me to a place these icons are being used? The link provided don't show them.

Let me put it this way, if I open up the socials listed on the page you linked, the icons Bosch is using are different.

CleanShot 2023-06-19 at 17 26 22

CleanShot 2023-06-19 at 17 26 34

CleanShot 2023-06-19 at 17 26 57

CleanShot 2023-06-19 at 17 27 33


However, this PR is using:

image

Which is a completely different branding.

../Frenck

**Comment by sanjay900** [comment]
> The icons look like a custom mashup between some icon and the bosch logo. We don't allow such things in our repository (as it often conflicts with branding guidelines). Please use the official branding from Bosch instead.
> 
> ../Frenck

Funnily enough, the icons came from Bosch, and were provided by their marketing team

**Comment by sushant-here** [comment]
My 2 cents... Maybe replace the I/O icon with the rainbow pallet+logo+text that's used on Facebook and elsewhere? As a consumer, I agree that I would associate the rainbow pallet with Bosch Security.

That said, I suppose we're stuck between a rock and a hard place when you consider that the I/O icon supposedly came from the Bosch marketing team in Netherlands.

**Comment by frenck** [comment]
> I have checked with the marketing team, they will let me know what else they can provide. 

Good. Let us know. Please note, we are looking for the main branding of a manufacturer and do not accept product branding. So, either the same resources as Bosch is using for their main brand publicly are used, or no branding at all.

> They have also stated the following logo's and icons are wrong 

That might be outdated at this point, those have been migrated from the older methods 3 years ago into this repo and have been unchanged at this point. Feel free to open a PR to update those images 👍 

../Frenck

**Comment by frenck** [comment]
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

../Frenck

**Pull request closed without merging**
