### PR TITLE
Add husqvarna_automower

### PR DESCRIPTION
**Pull request by astrandb**
## Proposed change

A couple of variants of custom_componenst/automower exist. They can use same brand images.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please avoid the use of symlinks in custom components.

**Comment by astrandb** [comment]
OK, just so I understand. You would rather see that I submit image files instead?

**Comment by frenck** [comment]
Custom components are managed by different people and projects. These are often more subject to change, therefore we should not interleave them. So yes, please let each custom integration be on its own.

**Review by frenck — APPROVED** [review]
Thanks, @astrandb 👍

**Pull request merged**
