### PR TITLE
Gstreamer

### LINKED ISSUE #309: GStreamer is missing brand images
## The problem

The GStreamer integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/gstreamer/icon.png`
- `src/gstreamer/logo.png`
- `src/gstreamer/icon@2x.png`
- `src/gstreamer/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: gstreamer.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/gstreamer.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

### PR DESCRIPTION
**Pull request by nldroid**
## Type of change

- [ ] Add a new logo or icon for a new integration
- [X] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #309
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

~~**Coulnd't find a hDPI icon**~~ Created  2x icon from SVG

### CODE REVIEW

**Comment by nldroid** [comment]
Easier said than done :)

Will see if i can google some manual for that :)

**Comment by nldroid** [comment]
Reverted the commit. Hope thats enough.

**Comment by frenck** [comment]
The SVG's for gstreamer are generally available. Since we prefer a transparent background on the image, we should do that...

Gstreamer-logo svg (2)
Gstreamer-logo svg (1)

**Comment by frenck** [comment]
Awesome!

Only thing missing right now, is the PR on our documentation repository, as requested in the issue: <https://github.com/home-assistant/brands/issues/309>

**Comment by nldroid** [comment]
> 
> 
> Awesome!
> 
> Only thing missing right now, is the PR on our documentation repository, as requested in the issue: #309

removed the line. Hope this was the idea ;)

**Pull request merged**
