### PR TITLE
add icons for acwd_water_usage

### PR DESCRIPTION
**Pull request by parvez**
## Proposed change

I have created a custom component. The ACWD Water Usage is an integration for Home Assistant that enables users to monitor their water consumption data provided by the Alameda County Water District. This custom component fetches water usage details, billing information, and presents historical usage data in an easily digestible format within the Home Assistant UI.

The repo for the custom component is https://github.com/parvez/acwd_water_usage

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The branding provided in this PR seems to differ from the branding used upstream:

CleanShot 2023-12-19 at 08 49 55@2x


../Frenck

**Comment by parvez** [comment]
> The branding provided in this PR seems to differ from the branding used upstream:
> 
> CleanShot 2023-12-19 at 08 49 55@2x
> 
> ../Frenck

Their official App uses the icon that I have used https://apps.apple.com/us/app/acwd-my-smart-water-connect/id1595935127 and also can be seen here: https://acwd.org/606/Advanced-Metering-Infrastructure-AMI.  They use this icon for their smart metering specifically.

**Comment by frenck** [comment]
Right, but we aren't collecting app icons in this repository, but branding of the manufacturers/companies that provide the integration.

**Comment by parvez** [comment]
> Right, but we aren't collecting app icons in this repository, but branding of the manufacturers/companies that provide the integration.

Oh, Got it. let me update! Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Please add these same assets as logo versions (trimmed the transparent space).

Thanks! 👍 

../Frenck

**Comment by parvez** [comment]
thanks @frenck. I have added the trimmed logo files!

**Review by frenck — APPROVED** [review]
Thanks, @parvez 👍 

../Frenck

**Pull request merged**
