### PR TITLE
Add Nissan Carwings

### PR DESCRIPTION
**Pull request by Hemmeln**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- Link to custom integration repository: https://github.com/remuslazar/homeassistant-carwings

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
When the logos and icons are the same, then the logo versions can be omitted. We automatically fallback onto the icon if the logo is missing.

Please remove the logo versions.

../Frenck

**Comment by Hemmeln** [comment]
Hi Frenck,

The README page states:
_"If the brand uses the same image for the logo and icon (e.g., if the logo has a square aspect ratio), only add the icon images. The icon will be used as a fallback for the logo."_

This logo is not 1:1, that's why i've included both. Please let me know if you still want me to remove the logos.

Hemmeln

**Comment by remuslazar** [comment]
@frenck Hi! I am the owner of https://github.com/remuslazar/homeassistant-carwings and will like to have the logo added sonn, my integration being already available via HACS.

Is there something I could do here, should I open a separate PR here?

**Comment by klaasnicolaas** [comment]
Once the logos are removed we can merge the PR 😉 

./Klaas

**Comment by Hemmeln** [comment]
Hi Klaas,

So the conclusion is that the non square logo's are not a problem? Please let me know so I can fix this for @remuslazar.

**Comment by klaasnicolaas** [comment]
The difference is too small to say that the logos should be added separately, the icon can serve perfectly well as a fallback for the logo.

./Klaas

**Comment by Hemmeln** [comment]
I have removed the logos. Hopefully this is now ready for the merge. Please let me know if you need anything else.

**Review by klaasnicolaas — APPROVED** [review]

**Pull request merged**
