### PR TITLE
Add icon and logo for LG ThinQ integration

### PR DESCRIPTION
**Pull request by LG-ThinQ-Integration**
## Proposed change

Add icon and logo for LG ThinQ integration

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/123860
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/34169
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/lgthinq/
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by LG-ThinQ-Integration** [comment]
'lgthinq' integration will be released soon. 
Icons and logos in this pull request are for the integration.

**Review by LG-ThinQ-Integration — COMMENTED** [review]
Confirmed adding icon and logo for a new core-integration

**Review by YunseonPark-LGE — APPROVED** [review]
Approved.

**Review by frenck — CHANGES_REQUESTED** [review]
Please link this PR to their parent PRs (as requested in the PR description template).

../Frenck

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by joostlek — CHANGES_REQUESTED** [review]
Please move the files to `lg_thinq`

**Comment by LG-ThinQ-Integration** [comment]
> Please move the files to `lg_thinq`

Moved.

**Review by joostlek — APPROVED** [review]

**Pull request merged**
