### PR TITLE
Icons with transparant background

### PR DESCRIPTION
**Pull request by filmgarage**
Shows up better on both dark and light mode

## Transparency 

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
They don't seem to use their icon as such anywhere? Could you point me to a resource that uses the provided icon in an official UptimeRobot resource?

../Frenck

**Comment by filmgarage** [comment]
This is their official logo for the app:
IMG_6231

**Comment by filmgarage** [comment]
On the website they use the green dot on a white background, if in light mode. On the very bottom of the page you can see the dot with the (animated) edge around it: www.uptimerobot.com

**Comment by frenck** [comment]
Right but why replace the normal variant instead of adding a dark variant?

**Comment by filmgarage** [comment]
The normal variant adds a black square around the green circle which is not their default behaviour on a white background as you can see on the company website. So the normal variant is wrong. The new version would show well on a dark as well as a light background, thus removing the need for a dark variant.

**Comment by frenck** [comment]
> So the normal variant is wrong. 

Looking at the several social media of UptimeRobot and the appstores they publish apps in, I'm sorry, but I must disagree with that statement.

**Comment by filmgarage** [comment]
Okidoki, I thought it would be nicer to have an icon with transparency in stead of the full square, but this is also fine with me... :-)

**Comment by frenck** [comment]
@filmgarage Why did you close it? I'm not following it.

You could provide dark icons with the assets in the PR instead of replacing the light variants?

../Frenck

**Comment by filmgarage** [comment]
The icon as it is now will display fine on a dark background. My intention was an icon that would automatically display differently on a dark and a light background. 

Dark background:

Scherm­afbeelding 2023-01-04 om 03 14 58

Light background:

Scherm­afbeelding 2023-01-04 om 03 17 08

On their main page you can see they have plenty green circles on a white background. So I tried to follow that logic. But that's not necessary if we keep the current design. So the icon will display a black square on a white background and it blends into the page if it's on a dark background. No changes needed! :-)

**Pull request closed without merging**
