### PR TITLE
Add motionblinds_ble icon and logo

### PR DESCRIPTION
**Pull request by LennP**
## Proposed change

Add icon and logo for the motionblinds_ble integration. The logo is the same for the motion_blinds (bridge) integration and the motionblinds_ble integration.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/109497
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/31224
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
How can the logo be the same, but the icon different? It is the same brand?

**Comment by LennP** [comment]
> How can the logo be the same, but the icon different? It is the same brand?

Yes indeed, the logo is the same (see https://motionblinds.com) but there are two different icons: one for the normal Motionblinds bridge mobile app and one for the Motionblinds BLE mobile app. Therefore, the icons in Home Assistant for the Motionblinds and Motionblinds BLE app are also different

**Comment by frenck** [comment]
The point being, it shouldn't be app icons to begin with? But use the branding of motionblind itself?

**Comment by LennP** [comment]
Those icons are Motionblinds branding, take a look at the favicon that https://motionblinds.com/ uses. Motionblinds bridge related applications only use the dark version of that icon, and all things Bluetooth related use the light version, they are not only the mobile app icons

**Comment by LennP** [comment]
This can be closed since this was included as part of the Motionblinds brand: https://github.com/home-assistant/brands/pull/5324

**Pull request closed without merging**
