### PR TITLE
Add V-Zug logos

### PR DESCRIPTION
**Pull request by magicmatt007**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @magicmatt007 👋 

I could not find the public repository providing this custom integration, could you point me to it?

Thanks! 👍 

../Frenck

**Comment by frenck** [comment]
Thanks for the screenshot @magicmatt007, not sure what I'm looking at (looks like a commit history of this PR). Could you just provide a link to the repository providing the V-Zug custom integration?

Thanks 👍 

../Frenck

**Comment by magicmatt007** [comment]
Sorry, I'm not a github expert and this is the first pull request of my life.

I think my logos can be seen here: https://github.com/home-assistant/brands/pull/3997/commits/465ad30dc35125a675ef1d45a3d29e07e35c96d0

I haven't published the custom integration itself yet. I understood that before I can do this on HACS, I need to have the icons here on the brands....

**Comment by frenck** [comment]
> I think my logos can be seen here: https://github.com/home-assistant/brands/commit/465ad30dc35125a675ef1d45a3d29e07e35c96d0

I'm not looking for the logos and assets, those are in this PR and I can see.
I'm looking for the integration that uses the logos/assets you are adding to this repository.

If I wanted to install `v_zug` on my personal Home Assistant instance, where would I go?

../Frenck

**Comment by magicmatt007** [comment]
Ah. Well, so far, it is  private repo. I'm preparing it to make it installable via HACS and once ready, will make it public.

I'm following thrse instructions https://hacs.xyz/docs/publish/integration

Hence, I submitted the icons as one of the preparation steps.

If my repo needs to be public at the time of submitting brand icons already , then I need to do some clean up work first.

**Comment by frenck** [comment]
> Ah. Well, so far, it is private repo. 

Ah! That makes it more clear. We can't accept assets for integration that do not exist. Therefore, I'm closing this PR for now. Feel free to re-open when the integration is generally publically available and published.

Thanks 👍 

../Frenck

**Pull request closed without merging**
