### PR TITLE
Added heliotherm heat pump as custom_integration logos in ha_heliotherm domain folder

### PR DESCRIPTION
**Pull request by mbuchber**
## Proposed change
Added heliotherm heat pump as custom_integration logos in ha_heliotherm domain folder

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ x] The added/replaced image(s) are **PNG**
- [ x] Icon image size is 256x256px (`icon.png`)
- [ x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons provided, look like product icons, not brand icons.
Looking at the social media profiles of Heliotherm, it seems like they are using a different icon than what is provided in this PR:

image

image

**Comment by mbuchber** [comment]
That is not the official logo of the brand that you suggested…
please see…
https://www.heliotherm.com/unternehmen/heliotherm-presseportal/

**Comment by frenck** [comment]
Neither is the product image that is being used as an icon.

**Comment by mbuchber** [comment]
...you need to click on the "Logo" section of the press-page I sent you

**Comment by frenck** [comment]
I've looked at it, but the icon provided is a product image, not manufacturer branding. We don't allow the use of product images/branding.

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @mbuchber 👍

**Pull request merged**
