### PR TITLE
Add images for fyta

### PR DESCRIPTION
**Pull request by dontinelli**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/110816
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/31480
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Since you want to add the integration to core, I see no reason to add the assets to the `custom_integrations` folder (see also CI error).

**Comment by dontinelli** [comment]
> Since you want to add the integration to core, I see no reason to add the assets to the `custom_integrations` folder (see also CI error).
> 
> ./Klaas

Thank you. Was not aware that the core images can also be uses for custom components. I removed the duplicate.

**Comment by klaasnicolaas** [comment]
What matters is that an integration domain is unique and that determines which brand assets are displayed. Since you are adding the integration to core, it is most logical to also add the assets only to core.

./Klaas

**Comment by dontinelli** [comment]
> an integration domain is unique and that determines which brand assets are displayed. Since you are adding the integration to core, it is most logical to also add the assets only to core.

@klaasnicolaas: The review of the core commit takes longer than expected and I do not know when it can be merged. Is there a possibility to add images for custom_components until the core PR is processed? It is unfortunate that also the release of the custom_component is held up by the core-review...

**Comment by dontinelli** [comment]
> What matters is that an integration domain is unique and that determines which brand assets are displayed. Since you are adding the integration to core, it is most logical to also add the assets only to core.
> 
> ./Klaas

@klaasnicolaas : as the integration PR now has been merged into dev, may I ask you to review? Thanks!

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @dontinelli :+1:

**Pull request merged**
