### PR TITLE
Added icon for custom integration apsystems_ecur

### PR DESCRIPTION
**Pull request by HAEdwin**
## Type of change

- [X ] Add a new logo or icon for a new core integration
- [X ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @HAEdwin, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2617).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
I'm having trouble finding an occurrence of this icon with the APsystems brand. Could you point me to a resource where APSystem uses this icon in its branding?

**Comment by HAEdwin** [comment]
Hi Frenck, first of all thank you for all your good work. HA brings me a lot of joy using en learning home automation!
The official logo and wordbranding can be found here: https://apsystems.com/
But I doubt that can be used because the HA extension is not a legitimate part of APSystems nor does it represent APSystems. With this icon I hope to combine and link the two products HA and APSystems together without giving the impression that it is an official APSystems product.

**Comment by frenck** [comment]
That is unfortunately not allowed. We collect the actual brand images in this repository and respect the branding from the manufacturer.

**Comment by HAEdwin** [comment]
Ok, I will adapt and post the APSystems logo later.

**Comment by HAEdwin** [comment]
I've added the office APSystems brand logo

**Comment by frenck** [comment]
Unfortunately, the builds are failing, could you take a look?

image

**Review by frenck — APPROVED** [review]
Thanks, @HAEdwin 👍

**Pull request merged**
