### PR TITLE
Add weatherflow_forecast custom integration

### PR DESCRIPTION
**Pull request by briis**
## Proposed change

Adding a new Custom Integration with domain name `weatherflow_forecast` whcih only pulls the forecast data from WeatherFlow

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This seems like a modified version of the WeatherFlow branding. We cannot accept modifications to third-party branding assets, as those are violating branding guidelines most of the time.

../Frenck

**Comment by briis** [comment]
You are right Frenck. I found that there is now a Core application using the old brand image, so I had to invent something new for this similar but different Integration.
Both the Core integration and this integration pulls data from a WeatherFlow weather station, just using different API's. 
Would you suggest I just invent a completely new Icon and Logo, or can we both use the WeatherFlow logo?

**Comment by briis** [comment]
I have now added completely new logos and icons. My own design, so there should not be a conflict with the official Weatherflow branding.

**Comment by briis** [comment]
Check. I have now added the original WeatherFlow icons and logos

**Review by frenck — APPROVED** [review]
Thanks, @briis 👍 

../Frenck

**Pull request merged**
