### PR TITLE
Added brand images for padavan_tracker

### PR DESCRIPTION
**Pull request by PaulAnnekov**
## Proposed change

Added icons for custom integration https://github.com/PaulAnnekov/home-assistant-padavan-tracker/.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR contains product images of an Asus router. I would have expected some kind of logo or icon from Padavan

**Comment by PaulAnnekov** [comment]
@frenck actually, there is no logo from Padavan. Andy Padavan has created a custom firmware for ASUS rt-n56u router which is currently used for several other routers too. This icon is asus rt-n56u photo.

**Comment by frenck** [comment]
If something doesn't have a brand image, we should not add one here.

**Comment by PaulAnnekov** [comment]
HACS guide says its CI checks for brands repo, that's why I created this PR. Will try to make a PR to HACS w/o brands. Thanks.

**Pull request closed without merging**
