### PR TITLE
Adding new eps pool control icon/logos

### PR DESCRIPTION
**Pull request by robsonke**
## Proposed change
Adding icon and logo of EPS Smart Pool Control. A Dutch supplier of pool devices. I've made a custom integration that communicates with their API: https://github.com/robsonke/eps_smart_pool_control
Just let me know if anything is wrong.

## Type of change
- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information
- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/robsonke/eps_smart_pool_control

## Checklist
- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @robsonke 👋 

In case the icon & logos are the same, the logo version can be omitted (we will fallback to the icon in case the logo is missing automatically).

Please remove the logo versions from this PR.

../Frenck

**Comment by robsonke** [comment]
You're fast Frenck, thanks. I've removed them.

**Comment by frenck** [comment]
Don't forget to mark the PR "Ready for review" once you are done 👍 

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @robsonke 👍 

../Frenck

**Pull request merged**
