### PR TITLE
Add Hildebrand Glow Images

### PR DESCRIPTION
**Pull request by holdestmade**
## Proposed change

Add images for Hildebrand Glow Custom Component

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Seems like an product logo/icon was used for this integration, instead of the manufacturer branding. Looking at their website, their branding looks different:

CleanShot 2023-05-23 at 10 00 12@2x

Please use the manufacturer branding in instead.

../Frenck

**Comment by holdestmade** [comment]
I used the glow logos as they are the 'brand' for that particular set of devices:

https://shop.glowmarkt.com/

**Comment by frenck** [comment]
> I used the glow logos as they are the 'brand' for that particular set of devices:

We are not collecting product branding.

../Frenck

**Comment by frenck** [comment]
Why did you opt to close, instead of adding the brand assets?

../Frenck

**Comment by holdestmade** [comment]
Just noticed there is already on done for the hildebrandglow_dcc custom component using the glow images. I have done one for this custom component with the Hildebrand logo

**Comment by frenck** [comment]
To CI errors with the latest changes:

```
Error: Invalid hDPI icon size! Size is 552x552px, must be 512x512px: custom_integrations/hildebrand_glow_ihd/icon@2x.png
Error: Invalid icon size! Size is 276x276px, must be 256x256px: custom_integrations/hildebrand_glow_ihd/icon.png
```

Could you take a look?

Thanks! 👍 

../Frenck

**Pull request merged**
