### PR TITLE
Add Crownstone icons

### PR DESCRIPTION
**Pull request by RicArch97**
## Proposed change

Add icons for Crownstone integration.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/13791
Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/37005

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
Putting PR into progress until the PR description has been updated with the core & docs PR links

**Comment by hillstub** [comment]
Hi guys,
I'm super excited that home assistant is getting support for the Crownstone!! Do you guys have an ETA for when this will be added to the master branch?
Thanks in advance!

**Comment by frenck** [comment]
This is an open-source project, which does not work on a schedule. Furthermore, @hillstub, this PR is just adding a logo and is blocked by parent PRs.

If you have questions like these, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Review by frenck — CHANGES_REQUESTED** [review]
#1829 added these icons as a custom integration icon. This means this PR can no longer add them, but must move them from the custom folder to the core folder.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
