### PR TITLE
Update aqualogic images

### LINKED ISSUE #93: AquaLogic is missing brand images
## The problem

The AquaLogic integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/aqualogic/logo.png`
- `src/aqualogic/icon@2x.png`
- `src/aqualogic/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

### PR DESCRIPTION
**Pull request by bens545**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information
Added missing icons/logos for aqualogic integration:
- `logo.png`
- `logo@2x.png`
- `icon@2x.png`

Updated `icon.png` to a higher quality, less pixelated image.

- This PR fixes or closes issue: fixes #93 
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @bens545, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2548).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
The logo's added do not match the brand images provided on their website:

<https://www.haywardimg.com/hayward---logos.html>

**Comment by bens545** [comment]
Updated the images to match [this logo](https://www.haywardimg.com/uploads/1/1/7/6/117653319/prologic.ai).  Looks like I had a font issue I missed the first time.  If you'd prefer I can also change the ProLogic logo to the Hayward company logo.

**Comment by frenck** [comment]
Yes, it should be the Hayward brand images as that represents the manufacturer. The prologic is product branding.

**Comment by bens545** [comment]
Should be all set now.  Thanks for the quick response!

**Review by frenck — APPROVED** [review]
Thanks, @bens545 👍

**Pull request merged**
