### PR TITLE
Pixometer

### PR DESCRIPTION
**Pull request by myTselection**
## Proposed change

Added Pixometer icon and logo for my custom HACS integration, https://github.com/myTselection/pixometer

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/myTselection/pixometer
- Link to documentation pull request: https://github.com/myTselection/pixometer/readme.md
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The provided icon looks like an app icon. The upstream branding from the manufacturer looks different. For example their Twitter:

image

And Facebook:

CleanShot 2023-01-20 at 13 20 09

Also their logo and naming of their brand is different:

image

Please note, this repository collects branding, not product images or logos.

../Frenck

**Comment by myTselection** [comment]
you are correct (again) frenck :)  I'll fix it towards general branding instead of product specific.

**Comment by myTselection** [comment]
well actually, when thinking about this: I would understand a general company branding is required, if the folder would be called as such too. But since this folder is called 'pixometer', which is a specific product of pixolus, why wouldn't it be allowed to use the product specific branding as well? Is there some re-use of these images for other integrations later on if another product of 'Pixolus' would get integrated?

**Comment by frenck** [comment]
> Google Wifi also has a "product specific" icon, which makes sense to easily differentiate it of the other Google integrations.

That integration is part of a brand collection in Home Assistant, in those cases, it is allowed and helps with differentiating. However, the use of brand collections isn't available for custom integration.

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @myTselection 👍 

../Frenck

**Pull request merged**
