### PR TITLE
Add impc energy

### PR DESCRIPTION
**Pull request by NiaoBlush**
## Proposed change

Add logos for a custom integration called impc_energy, which can get history electricity usage data and current electricity account balance of a family in Inner Mongolia of China.
[repo](https://github.com/NiaoBlush/impc_energy)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @NiaoBlush 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Oh! 

The icon and logo are the same! In those cases, please omit the logo versions. We will automatically fallback.

../Frenck

**Comment by NiaoBlush** [comment]
Logos are removed as instructed. Thanks. @frenck

**Review by frenck — APPROVED** [review]
Thanks, @NiaoBlush 👍 

../Frenck

**Pull request merged**
