### PR TITLE
Icon + Logo for custom integration (4noks_elios4you)

### PR DESCRIPTION
**Pull request by alexdelprete**
## Proposed change

Added icon + logo for my custom integration: https://github.com/alexdelprete/ha-4noks-elios4you

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @alexdelprete 👍 

../Frenck

**Comment by alexdelprete** [comment]
> Thanks, @alexdelprete 👍

Incredible, I was writing here to know if there was something wrong, and you approved it. :)

Thanks a lot Frenck.

**Comment by frenck** [comment]
Hehe I have weekend at times too 😉 

../Frenck

**Comment by alexdelprete** [comment]
@frenck I was testing icon/logo, but it doesn't appear. I emptied caches etc. and I tested it on a brand new VM I just spun up. Looked at the code with the browser dev tool, and it seems it's looking for dark-icon.png instead of icon.png. Does the logic depend on the system setting or HA setting?

Thanks for any hint.

**Pull request merged**
