### PR TITLE
Update parental_controls icons

### PR DESCRIPTION
**Pull request by amitkeret**
## Proposed change

The proposed icon/logo are the official branded icons for the app this integration is intended for.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [x] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/pantherale0/ha-nintendoparentalcontrols

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
Hi there @amitkeret 👋 

Thanks for the PR, but it isn't valid for our purposes / repository. We aim to collect manufacturer branding in this repository. The device/service this integration integrates with is provided by Nintendo, therefore that branding is expected (and not the application assets of one of their apps).

Nevertheless, thanks for being willing to contribute 👍 

../Frenck

**Comment by amitkeret** [comment]
Thanks @frenck.

> We aim to collect manufacturer branding in this repository.

Please see the following examples: [SmartThinq](https://brands.home-assistant.io/_/smartthinq_sensors/icon.png) (by LG), [HomeKit](https://brands.home-assistant.io/_/homekit_controller/icon.png) (by Apple), [B-Hyve](https://brands.home-assistant.io/_/bhyve/icon.png) (by Orbit).
These examples are of manufacturer branding of specific apps/services, which are different to the manufacturer's own brand assets.

Can you please clarify what you mean by "manufacturer branding", so I can find icons that would be compatible with the repo's requirements?
Thank you!

**Comment by frenck** [comment]
Some of the ones you listed are bundled as a brand (brands folder) in the Home Assistant UI. In that particular case one selects a brand (LG) and next one of the product specific integrations. 

This feature isn't available for custom integrations, thus doesn't apply in this case.

That said, if you think existing assets can be improved, we always welcome pull requests.

../Frenck

**Comment by amitkeret** [comment]
Thanks for explaining @frenck 
I've updated the icons to reflect the Nintendo brand; see [here](https://github.com/home-assistant/brands/compare/master...amitkeret:brands:nintendo-parental-controls)
Can the above PR be re-opened, or should I submit a new one?

**Pull request closed without merging**
