### PR TITLE
Add icon and logo for resideo_total_connect

### PR DESCRIPTION
**Pull request by schmittx**
## Proposed change
Add icons and logos for `resideo_total_connect` custom integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: N/A
- Link to code base pull request: N/A
- Link to documentation pull request: N/A
- Link to integration documentation on our website: N/A
- Link to custom integration repository: [link](https://github.com/schmittx/home-assistant-resideo-total-connect)

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logos and icons provides do not seem to match the banding used by Resideo:

CleanShot 2024-05-18 at 13 33 29@2x

Please adjust the branding to match the manufacturer branding.

../Frenck

**Comment by schmittx** [comment]
Thanks for catching the Resideo logo branding, I had just copied over the assets from the core integration and didn't check.

I updated the logos to match Resideo branding, however I kept the icons as is because they're matched with the current Total Connect app icons ([App Store](https://apps.apple.com/us/app/total-connect-2-0/id439763870)) ([Google Play](https://play.google.com/store/apps/details?id=com.alarmnet.tc2&hl=en_US)).

The alternative option is to replace the icons with the Resideo corporate logo "r".

**Review by frenck — CHANGES_REQUESTED** [review]
> I updated the logos to match Resideo branding, however I kept the icons as is because they're matched with the current Total Connect app icons ([App Store](https://apps.apple.com/us/app/total-connect-2-0/id439763870)) ([Google Play](https://play.google.com/store/apps/details?id=com.alarmnet.tc2&hl=en_US)).

Sorry, we don't collect that in this repo, we try to capture the manufacturer branding. Please adjust the icons as well.

../Frenck

**Comment by schmittx** [comment]
Understood, thanks for clarifying! Icons have been updated now.

**Review by frenck — APPROVED** [review]
Thanks, @schmittx 👍 

../Frenck

**Pull request merged**
