### PR TITLE
Add Intellifire Gas Fireplace integration

### PR DESCRIPTION
**Pull request by jeeftor**
## Proposed change

- Adding icons for upcoming intellifire integration
- Icons only 

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:  https://github.com/home-assistant/core/pull/63637
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/21092
- Link to integration documentation on our website: (Does not exist yet ... see PR)

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @jeeftor, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3074).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Please make sure the image validation build passes.

Thanks 👍

**Comment by frenck** [comment]
Nice! Can you also point me to the public repository providing this integration? I could not find a reference.

**Comment by jeeftor** [comment]
@frenck 

I updated the PR with the info but in case you see this 1st:

- Code: https://github.com/home-assistant/core/pull/63637
- Docs: https://github.com/home-assistant/home-assistant.io/pull/21092

**Review by frenck — CHANGES_REQUESTED** [review]
Intellfire is a product of Heatilator. As we collect brands assets in this repository (not product assets), I expected the Heatilator branding here.

**Comment by frenck** [comment]
@jeeftor Should we replace this Hearth 'n Home?

https://www.hearthnhome.com/

**Comment by jeeftor** [comment]
Honestly -> I'm struggling to understand who is the actual parent company who makes all the sub-fireplace brands.

The iOS app lists: "Hearth & Home Technologies" as the developer for the app with the app support page linking to:

https://www.hearthnhome.com/company/ask-a-question

So... to answer your question? Sure? (Where doe we make this change is it in the other codebase? Obviously this is an icon codebase)

**Comment by frenck** [comment]
I've looked around as well, and I agree, it is super confusing...



So, let's stick with this (as an exception), or else it would probably become confusing for the end-user as well.

**Review by frenck — APPROVED** [review]
Thanks, @jeeftor 👍

**Pull request merged**
