### PR TITLE
Add logo and icons for smarwi custom integration

### PR DESCRIPTION
**Pull request by jirutka**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/jirutka/hass-smarwi/

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by jirutka** [comment]
@klaasnicolaas, can you please merge this?

**Comment by klaasnicolaas** [comment]
Asking for it will not speed up the process... could you also add an hDPI version?

./Klaas

**Comment by jirutka** [comment]
> could you also add an hDPI version?

I’d like to, but I couldn’t find a hi-res logo. Even this one I had to upscale using AI and clean up artefacts, and it still doesn’t look good in hDPI.

**Review by frenck — APPROVED** [review]
Thanks, @jirutka 👍 

../Frenck

**Pull request merged**
