### PR TITLE
Add icon for Panasonic Smart App

### PR DESCRIPTION
**Pull request by osk2**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This repository we try to register brand images as much as possible.

In this case, this PR does not add branch assets, but the icon of their app.
Please adjust this PR to contain the brand images of Panasonic (logo & icon)

**Comment by osk2** [comment]
@frenck logo added 👍🏼

**Review by frenck — CHANGES_REQUESTED** [review]
The icon used is still an app icon, not their generic brand image.

**Comment by osk2** [comment]
I don't think use Panasonic logo for [my component](https://github.com/osk2/panasonic_smart_app) is appropriate

1. Unlike `Panasonic Comfort Cloud`, `Panasonic Smart App` is only used in Taiwan. Use generic icon may confuse users
2. `Panasonic Smart App` doesn't have it's own logo except app icon which I uploaded

**Comment by frenck** [comment]
This repository aims for having brand images, not product images. Their app is a product created by Panasonic.

An exception will only be made if there is no alternative available, however, the Panasonic brand images are generally available, thus no reason not to use them.

If you don't want to add those, I'm afraid I cannot merge the PR.

**Comment by osk2** [comment]
Thanks for quick reply

icons have been updated :)

**Review by frenck — APPROVED** [review]
Thanks, @osk2 👍

**Pull request merged**
