### PR TITLE
Add icon for inverter_xpert_king integration

### PR DESCRIPTION
**Pull request by astraliens**
## Proposed change

Add icon for inverter_xpert_king custom integration https://github.com/astraliens/home-assistant-inverter-xpert-king

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @astraliens 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Hmm hold on, this seems to be a generic icon. Looking at the manufacturer, it is using different branding on their website:

image

../Frenck

**Comment by astraliens** [comment]
> Hmm hold on, this seems to be a generic icon. Looking at the manufacturer, it is using different branding on their website:
> 
> image
> 
> ../Frenck

it's not official integration and in most it was written to "clones" of voltronic inverters (not tested on voltronic itself, but it seems that protocols should be the same depending on documentation and it should work on voltronic too)

**Comment by frenck** [comment]
It doesn't matter if it is an official integration or not. Brands collected here are for identification purposes for the end-user.

**Review by frenck — CHANGES_REQUESTED** [review]
Please address the raised review comment.

**Comment by astraliens** [comment]
> It doesn't matter if it is an official integration or not. Brands collected here are for identification purposes for the end-user.

main purpose was to identify this inverters as QDion and FSP, and only after this it could be Voltronic.
What should be the final image in such case - should it be Voltronic logo of FSP or QDion or something else (It was not tested on Voltronic inverters yet, it was tested on QDion / FSP inverters).
Also are there any restrictions for copyrights, coz their logos are registered trademarks and I'm not sure if it is correct to use their logo in third party integrations

**Comment by frenck** [comment]
Feel free to add the best matching branding you think that belongs to the integration.

As said, the branding is used for identification purposes. As for legal, it depends on a lot (FUP, brand policies, and that even differs per country). Ultimately, if a company complains about the use, we will remove it on request.

We will, however, not add random images to represent brands (as that generally does violate branding guidelines of manufacturers).

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @astraliens 👍 

../Frenck

**Pull request merged**
