### PR TITLE
Added images for reolink_cctv custom integration.

### PR DESCRIPTION
**Pull request by JimStar**
## Proposed change

This **reolink_cctv** is a new integration, based on the already existing **reolink_dev** (which is already present here).  
The **reolink_cctv** is a significantly reworked integration in comparison to initial **reolink_dev**, and has full support of Reolink NVRs and multichannel cameras, in addition to just direct camera connections. Plus stability improvements.  
The maintainter of the previous **reolink_dev** project is already inactive for a very long time, but some of Reolink devices' users (including myself, I have an NVR and a couple of cameras on my house) expect it to finally become rewritten/improved. Which I'm preparing for a first release right now, but can't still test it in full because of its logos are not showing up properly in Home Assistant.

## Type of change

Images for a new **reolink_cctv** integration.

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I could not find a public repository providing this custom integration. Could you please point me to it?

../Frenck

**Comment by JimStar** [comment]
Thank you @frenck for looking into this.  
This is a classical chicken-egg problem. As I mentioned - I'm preparing it for a first release right now, but can't still test it in full because of its logos are not showing up properly in Home Assistant. Because of that the repo is not public, before everything is ready for a first release.  
I will make the repo public as soon as all the new integration's logos are tested and showing up properly. I just can't make it available for public to download and install while the integration is not tested with all its logos showing up properly and is looking ugly like this:

Screen Shot 2022-09-27 at 05 18 08

Screen Shot 2022-09-27 at 05 17 30

Everything else is working OK already:

Screen Shot 2022-09-27 at 05 17 49

Could you please accept this pull-request, so I could test it is showing up properly with all its logos, and make the repo public after I made sure all showing up properly and ready for users to start using it...

**Comment by frenck** [comment]
> This is a classical chicken-egg problem.

It isn't. Integration development does not depend on a brand asset. We deal with that multiple times a week in our Core repository. It really isn't needed for development.

> Could you please accept this pull-request, so I could test it is showing up properly with all its logos, and I could make the repo public after I made sure all showing up properly and ready for users to start using it...

I can't.

**Comment by frenck** [comment]
> How is that?

Well, integration cannot influence it. It is all handled by Home Assistant, so there is no reason to test it from an integration standpoint. Your integration cannot do it wrong.

../Frenck

**Comment by JimStar** [comment]
Maybe it would make sense then to just add this folder (`reolink_cctv`) under the `reolink` name instead, because all the logos it has are the standard **Reolink** brand logos? This way **any** integration that implements some Reolink support could add this section to its `manifest.json`, and just use all the **common** Reolink logos, instead of having several folders in this repo that have **the same** logo files in them (at least the `reolink_dev` folder here already has **exactly the same** logo-files in it)... All these files are the Reolink company logos, which are actually nothing to do with neither a `reolink_dev` integration, nor with my `reolink_cctv` integration - these integrations just **support** the devices (NVRs and cameras in my case) produced by the same Reolink company.

In this case it would be proper thing to do - for all integrations that support **Reolink** to have this section in their `manifest.json` file (instead of having a couple of the same copies of the same logo files under several folders in this repo named after each particular integration):

```
{
  "supported_brands": {
    "reolink": "Reolink"
  }
}
```
So you could just rename the `reolink_cctv` folder of this pull request to `reolink` folder, and accept it. Because the "reolink repository" definitely "exists" in the form of Reolink company, you can make sure of it here: [https://reolink.com/](https://reolink.com)

**Comment by frenck** [comment]
> Maybe it would make sense then to just add this folder (reolink_cctv) under the reolink name instead, because all the logos it has are the standard Reolink brand logos?

No, brand icons are per integration domain.

The current PR is correct, it is missing a public integration, as now repeated a couple of times.

Additionally, the suggested supported brands logic isn't available for custom integrations and is thus invalid.

../Frenck

**Comment by frenck** [comment]
Why did you close the PR? Are you not publishing a custom integration?

**Comment by JimStar** [comment]
If I anyway need to publish the integration looking ugly and unprofessional without a proper logo showing up in it - then it makes no sense for me to bother fixing this later... the integration will be already spoiled with this ugly look right from the beginning when users would get it available to install...

And yes, this **IS** a chicken-egg problem. The integration can not look properly and professionally before this folder is available in `brands` repository. But this folder is **rejected** to be added before the integration is already available to any user for installation - so anybody who will install it will anyway see the ugly unprofessional look of this integration with a missing placeholder for a logo.

And **no**, the brand icons are **not** per integration domain. For example the `xiaomi_miio` integration has a Roborock brand in its support, but there is no `roborock` integration. This is from Home Assistant reference:



I just don't want to keep arguing about that, so I've just closed this PR.

I anyway coded this whole integration for my own use (because the existing `reolink_dev` is buggy and does not support NVRs). So I don't care too much for these logos showing up, the main thing for me is that my NVR and all the cameras around my house now are working robustly and properly, in comparison to the previous `reolink_dev` integration.  
I'm of course going to make this repo available for all other users of Home Assistant under MIT license, but if it anyway will be spoiled right from the beginning by this ugly missing-logos look - my reputation as an "attention to details" programmer gets already damaged, so why bother later...

**Comment by frenck** [comment]
> And yes, this IS a chicken-egg problem.

We handle a couple of dozen integrations each month in the same way, this isn't a problem.

>  But this folder is rejected to be added before the integration is already available to any user for installation

That is not what I said. I said a publicly available repository that provides the integration.

> so anybody who will install it will anyway see the ugly unprofessional look of this integration with a missing placeholder for a logo.

Even if I merged this PR, it would not work. As we only publish/flush our caches once a month (during the major release). Even that, isn't (and hasn't been) an issue.

> And no, the brand icons are not per integration domain.

Yes, they are. Each domain in this repository represents (and matches) the domain configured in the `domain` key of the integration manifest. This repository provides branding for integrations.

> For example the xiaomi_miio integration has a Roborock brand in its support, but there is no roborock integration. This is from Home Assistant reference:

Those are `supported_brands`, which is a different concept and not related to integration branding. As said, that feature is not available for custom integrations.

Anyways, it's up to you. I wish you all the best on your journey, and in case you change your mind and want to open up a PR again, feel free to do so. I'm happy to review and merge the PR once it is available.

../Frenck

**Pull request closed without merging**
