### PR TITLE
Add nintendo_parental icons

### PR DESCRIPTION
**Pull request by pantherale0**
## Proposed change
Adds icons for Nintendo Switch Parental Controls custom integration

https://github.com/pantherale0/ha-nintendoparentalcontrols

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This repository collects branding icons/logos. However, this PR seems not provide that. In this case, a Nintendo branding was expected.

../Frenck

**Comment by pantherale0** [comment]
@frenck would the Nintendo Switch icon be appropriate here?

The integration itself is for the Parental Controls service that Nintendo offers - https://www.nintendo.co.uk/Hardware/Nintendo-Switch-Parental-Controls/Nintendo-Switch-Parental-Controls-1183145.html

**Comment by frenck** [comment]
> @frenck would the Nintendo Switch icon be appropriate here?

No, those are product branding, please use the manufacturer branding instead.

../Frenck

**Comment by pantherale0** [comment]
@frenck ok, thanks, will update :)

**Comment by pantherale0** [comment]
I can't find a icon for Nintendo that meets the criteria (although there is an old one from early 70s I believe), but a logo is possible still.

**Review by frenck — APPROVED** [review]
Thanks, @pantherale0 👍 

../Frenck

**Comment by amitkeret** [comment]
@pantherale0
Can this be used?


This is official branding logo by Nintendo, for this specific app.
Can be cropped to create an icon. I'd be happy to help.

**Comment by pantherale0** [comment]
@amitkeret that's what I used in the PR originally so no.

**Comment by amitkeret** [comment]
If I'm not mistaken, you used only the icon in your original commit, before removing it?
I'm suggesting to change the logo to this one, including the text. In this way we add the expected manufacturer's branding for the app, as @frenck requested.
Then the icon can be added, as it is following the same branding design language.

**Comment by pantherale0** [comment]
@amitkeret this was the review on that original commit.
https://github.com/home-assistant/brands/pull/4650#pullrequestreview-1623834177

My understanding from that is this repo collects manufacturer brandings, not product branding (which is what the Nintendo Switch Parental Controls icon is).

Feel free to open another PR for it though. It's not exactly something that is 'breaking'.

**Comment by amitkeret** [comment]
Will do. Thank for your input, I love your integration!

PS. note there are plenty of custom integrations which don't strictly adhere to official branding guidelines, and use this repo to display an icon for the integration... as a random example - [gradual volume](https://brands.home-assistant.io/_/grad_vol/icon.png)

**Comment by pantherale0** [comment]
I think with the example you've given, that one is more of a helper (that could be achieved in this case using automation) rather than an integration with a product, service, application etc. built my a manufacturer. So perhaps that's why that one is ok?

I think what's clear though is perhaps more guidance should be added to the documentation about what sort of things appropriate. I know there are the reqs for the formatting of the image, but I'm not sure if there is much about what that images themselves should actually contain (although happy to be corrected as it's been a while since I last looked at the branding docs).

**Pull request merged**
