### PR TITLE
adding nespresso icon

### PR DESCRIPTION
**Pull request by tikismoke**
## Proposed change
Adding Nespresso logo for custom integration
https://github.com/home-assistant/wheels-custom-integrations/pull/77

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by tikismoke** [comment]
Ho I didn't see this.

Yes we can do this.

Do you me to look at it in the afternoon.

Le 31 mai 2020 11:10:26 GMT+02:00, Franck Nijhof <notifications@github.com> a écrit :
>@frenck requested changes on this pull request.
>
>Nespresso icons and logos are available as SVGs:
>
>- https://commons.wikimedia.org/wiki/File:Nespresso-logo.svg
>- https://worldvectorlogo.com/search/nespresso
>
>Can we add both the icons & logos in the normal & hDPI variants?
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/home-assistant/brands/pull/1671#pullrequestreview-421475659

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

Attention nous avons changer de domaine, utilisez poudot.fr à la place de tikijs.dyndns.org

**Comment by tikismoke** [comment]
@frenck I've update icon and logo from svg.
Is this better and ok for you?

**Comment by frenck** [comment]
How about adding these as the logo?

Nespresso-logo@2x
Nespresso-logo

**Comment by tikismoke** [comment]
> Thanks, @tikismoke +1

Thank's to you and all your job :)

**Pull request merged**
