### PR TITLE
Smappee logo and icon added

### LINKED ISSUE #629: Smappee is missing brand images
## The problem

The Smappee integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/smappee/icon.png`
- `src/smappee/logo.png`
- `src/smappee/icon@2x.png`
- `src/smappee/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: smappee.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/smappee.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

### PR DESCRIPTION
**Pull request by nldroid**
## Type of change

- [ ] Add a new logo or icon for a new integration
- [X] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #629 
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by nldroid** [comment]
> 
> 
> Please trim the images. They all have quite a bit of empty space around them. In case of the icon, it actually became smaller than the specifications because of this.

There's no good large text to be found. I can remove the @2x and use the text from that in the logo.png but we won't have a @2x anymore.

**Comment by cogneato** [comment]
They link to an svg from their site (why can't they all do this?) so it should be easy to make any size.
https://www.smappee.com/skin/frontend/smappee/default/images/logo.svg

**Comment by frenck** [comment]
smappee-logo
smappee-logo2
smappee-icon
smappee-icon2

**Comment by nldroid** [comment]
Good find. I thought i Googled well and did a small check if i fould find them with some extra keywords but still couldn't find them that fast.

**Pull request merged**
