### PR TITLE
Add xmpp logo and icons

### LINKED ISSUE #793: Jabber (XMPP) is missing brand images
## The problem

The Jabber (XMPP) integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/xmpp/icon.png`
- `src/xmpp/icon@2x.png`
- `src/xmpp/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @fabaff, @flowolf! Mind taking a look at this issue as it is with an integration (xmpp) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/xmpp/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

### PR DESCRIPTION
**Pull request by flowolf**
## Proposed change

adding xmpp logo and icons in higher resolution.

## Type of change

- [ ] Add a new logo or icon for a new integration
- [x] Add a missing icon or logo for an existing integration
- [x] Replace an exiting icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #793
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by flowolf** [comment]
ok. will remove the logos.
was wondering about that case - readme didn't specify.

**Comment by Neustradamus** [comment]
@flowolf: Can you use the good XMPP logo?
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by Neustradamus** [comment]
Dear @flowolf, @frenck: Have you seen my comment that I have sent you 3 years ago?
Thanks in advance.

**Comment by flowolf** [comment]
@Neustradamus please open another pull request if you want a change. 

also not sure what you mean by "good logo". thanks

**Comment by Neustradamus** [comment]
@flowolf: Where have you taken the source?

There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg
- https://commons.wikimedia.org/wiki/File:XMPP_logo_(without_text).svg

Old version, there was a problem:
- https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

Linked to:
- https://github.com/home-assistant/brands/pull/870
- https://github.com/home-assistant/brands/issues/793

**Pull request merged**
