### PR TITLE
Add SiHAS branding

### PR DESCRIPTION
**Pull request by cmsong-shina**
## Proposed change

Add SiHAS branding

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The folder name doesn't match the domain of the custom integration:

image

Please make sure the domains match.

Thanks 👍 

../Frenck

**Comment by cmsong-shina** [comment]
> The folder name doesn't match the domain of the custom integration:
> 
> image
> 
> Please make sure the domains match.
> 
> Thanks 👍
> 
> ../Frenck

Thankyou.

I've just fix it.

**Review by frenck — CHANGES_REQUESTED** [review]
The folder name in the custom integration still doesn't match the domain name defined in the manifest.json. 

Please make sure those match.

../Frenck

**Comment by cmsong-shina** [comment]
Oops sorry to bother you.
I think it is done.

**Review by frenck — APPROVED** [review]
Thanks, @cmsong-shina 👍 

../Frenck

**Pull request merged**
