### PR TITLE
Adding MaxSmart (revogi) icon and logo for maxsmart component

### PR DESCRIPTION
**Pull request by Superkikim**
## Proposed change
Adding MaxSmart (revogi) icon and logo for maxsmart component

## Type of change
New icons added

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @Superkikim 👋 

A couple of things I've noticed with this PR:

- The icons & logos are the same. In those cases the logo versions can be omitted; as we automatically use the icon in those cases.
- There is a weird round green edge to the icons provided, I think that needs to be removed.
- It seems like the icons provided are application/app icons? Please use the main manufacturer branding instead.

../Frenck

**Comment by Superkikim** [comment]
>     * The icons & logos are the same. In those cases the logo versions can be omitted; as we automatically use the icon in those cases.
> 
>     * There is a weird round green edge to the icons provided, I think that needs to be removed.
> 
>     * It seems like the icons provided are application/app icons? Please use the main manufacturer branding instead.
> 
> 
> ../Frenck

Hi. 

Unfortunatelly, there's not much I can do regarding the logo. This is the Maxsmart logo (and app icon) from Max Hauri. The Max Hauri logo is just a red square with "MAX HAURI" written. And the maxsmart line is EOL. So unless I start designing a custom logo (which might be fun that said), I believe the proposed images are the best compromise. 

Regarding the corners, these are transparent background corners. So it should be find. I just tried importing the image on PowerPoint to verify and it just looks great with rounded corners :) 

I'll remove the logo versions and send for review.

**Comment by frenck** [comment]
>  This is the Maxsmart logo (and app icon) from Max Hauri.

Right... that was my point in my review comment.

> The Max Hauri logo is just a red square with "MAX HAURI" written. And the maxsmart line is EOL. So unless I start designing a custom logo (which might be fun that said), I believe the proposed images are the best compromise.

Sorry, I'm not following this one. It is expected the manufacturer branding is used. Max Hauri in this case.

**Comment by frenck** [comment]
Marked PR back to draft, as the review comments have not been completely addressed.

**Comment by Superkikim** [comment]
> Sorry, I'm not following this one. It is expected the manufacturer branding is used. Max Hauri in this case.

Max Hauri MaxSmart is the brand for these devices. The logo represents Max Hauri (MH) in a "smart house" hence covers the "Max Hauri MaxSmart" brand. 

I understand your point, but given Max Hauri abandonned the product, and in the end this is a Revogi product rebranded by Max Hauri, I have difficulties to use the Max Hauri Logo. But perhaps you are right. I should use the Max Hauri logo for logo and the MaxSmart icon for icon.

**Comment by frenck** [comment]
Sorry, this wasn't a discussion or a matter of opinion. We collect the branding of manufacturers in this repository.

There is an exception to these rules only if a separate brand is defined. However, this feature is not available for custom integrations. Thus those can only provide branding of manufacturers for their integrations.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Please replace the current icon assets with the logo assets provided.

As per above (now explained multiple times), the icons provided should not be used.

../Frenck

**Review by frenck — COMMENTED** [review]
You keep creating things and ignoring my comments.

At this point, I'm going to friendly decline this PR and close it up.

../Frenck

**Comment by Superkikim** [comment]
> You keep creating things and ignoring my comments.
> 
> At this point, I'm going to friendly decline this PR and close it up.

You keep lecturing me when I don't understand your points.  I didn't create anything except I created the "non-dark background logo" given the manufacturer one has transparent color for the text font. On the last commit, I just followed your command. 

The icon is the official Max hauri logo, visible here: https://www.maxhauri.ch/fr/

The Max Hauri MaxSmart (TM) logo is the official MaxSmart logo, just found here after your last comment:  https://www.maxsmart.ch/files/template/img/maxSMART_logo_web.svg

at that stage, I don't understand what you want from me !

I spent months making the maxsmart python module and the MaxSmart (Revogi) custom component as many others. I've followed all possible recommendations. I disagree with what you say about the icons (given many are using brands and models (i.e. HUE) yet I still do what you ask, using OFFICIAL logos and icons from the manufacturer. 

So I'm doing my best. At that stage, I don't know what to do anymore. 

Note that if there is anything personal you have against me, let me know what so I might make amend ! Otherwise, I really appreciate if you would now approve that PR.

**Comment by frenck** [comment]
> Note that if there is anything personal you have against me,

I have nothing personal against you at all, reviews are never personal.

> You keep lecturing me when I don't understand your points.

Please use the plain manufacturer branding (not product or application branding). As has been mentioned a couple of times now.

../Frenck

**Pull request closed without merging**
