### PR TITLE
Add Luxaflex images

### PR DESCRIPTION
**Pull request by kingy444**
## Proposed change

Hunter Douglas Powerview also goes by brand name Luxaflex - adding logos in support of supported_brands

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/73421
- Link to documentation pull request: 
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/hunterdouglas_powerview/

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon provided in this PR is not the brand icon used by Luxaflex as it seems. For example; from their Twitter profile:

image

**Comment by kingy444** [comment]
The icon in use was the same one being used by the integration requiring the brand icon - hunter Douglas PowerView

the hunter Douglas icon is currently using the PowerView app icon (which you also get if you search luxaflex on the App Store)

If you want this one changed I assume the Hunter Douglas should also be updated from the PowerView app icon to this one ?

**Comment by kingy444** [comment]
B8E04834-9DE7-4A96-A131-4B89A7D70DE1
0D23CB0A-B52C-46A3-BEE7-6016534FD152
681739F9-A972-4BB3-85A1-47720153FDBC

**Comment by kingy444** [comment]
> > If you want this one changed I assume the Hunter Douglas should also be updated from the PowerView app icon to this one ?
> 
> Probably, however, that is not in scope of this review 🤷

I get it might be another PR but given then only reason to add Luxaflex as a brand is to add supported_brands to hunterdouglas_PowerView wouldn’t that make the conversation relevant?

@bdraco as you asked me to look at including this would you like me to update the Hunter Douglas icon as above ?

**Comment by bdraco** [comment]
> @bdraco as you asked me to look at including this would you like me to update the Hunter Douglas icon as above ?

I'm happy with either icon so that works for me

**Review by frenck — APPROVED** [review]
Thanks, @kingy444 👍

**Pull request merged**
