### PR TITLE
Viva

### PR DESCRIPTION
**Pull request by patrickribbing**
## Proposed change

  Icon for a new custom integration that read data from Swedish weather stations (ViVa).

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/patrickribbing/viva-component
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @patrickribbing, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3242).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by patrickribbing** [comment]
Missed to push my branch changes, I'm an idiot...

**Review by frenck — CHANGES_REQUESTED** [review]
I would expect the branding of Sjöfartsverket, not the ViVa product?

**Comment by patrickribbing** [comment]
This is no offical integration to the Sjöfartsverket's service, that's why I don't want to use their logo. The integration only make use of an api they provide.

**Comment by frenck** [comment]
I understand, but this repository is aimed at collecting brand images of their providers, not their products, services, or descendants of that.

As per your answer and description, that means the asset provided does not match the goals of this repository. Therefore this PR cannot be accepted in its current state.

**Pull request closed without merging**
