### PR TITLE
Add images for Philips Hue Play HDMI Sync Box custom integration

### PR DESCRIPTION
**Pull request by mvdwetering**
## Proposed change

Add logo and icon for Philips Hue Play HDMI Sync Box custom integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR symlinks to logos from a core integration. Please avoid symlinking between core and custom integrations.

Furthermore, I'm not sure why the icon is different in this case?

**Comment by mvdwetering** [comment]
From the documentation I got the impression that symlinking was not allowed for the directories that start with an _. Replaced the symlinks with real images.

I thought it might be nice have a distinction for the logos between the normal hue lights integration and the syncbox. However since this repo is about branding that should indeed be just the "Philips Hue" brand. Replaced the logos with the same as the normal hue integration.

**Review by frenck — COMMENTED** [review]
Something is going wrong here:

image

I also have issues checking out this branch locally.

**Comment by mvdwetering** [comment]
Sorry for the mess. It seems like something went wrong when replacing the symlinks with the actual images even though it looked fine in the file browser.
I removed and re-added the logo files, all seems fine now on Github and on a clean clone in a different location.

**Review by frenck — APPROVED** [review]
Thanks, @mvdwetering 👍

**Pull request merged**
