### PR TITLE
Replace Environment Canada logo

### PR DESCRIPTION
**Pull request by gwww**
## Proposed change

This logo has two changes over the existing logo. First the background is not transparent. The existing logo has a transparent background, which does not show up properly in the dark theme. Second the logo included French and English descriptions of the government department (Canada is bilingual).

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

This PR does not fix any existing issues and is independent of any other PRs.

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by gwww** [comment]
FYI - I'm rewriting the Environment Canada integration in conjunction with @michaeldavie. I expect those PRs to start in a couple of days.

**Review by frenck — CHANGES_REQUESTED** [review]
For these purposes, a different, alternative image can be provided.

See: <https://github.com/home-assistant/brands#image-specification>

**Comment by gwww** [comment]
I'll take your lead here, but I was thinking the image in the PR is perfect for both light and dark backgrounds. Is your suggestion that the light background image is transparent background (kind of as is only with French added) and the dark image is as I just submitted?

**Comment by frenck** [comment]
> I'll take your lead here, but I was thinking the image in the PR is perfect for both light and dark backgrounds. Is your suggestion that the light background image is transparent background

I would recommend images that are for either dark or light backgrounds, preferably both transparent.
For example, for the dark variant white letters could be used.

Even with the new image suggested, while it works on a dark background, the white background of the image will pop out. On light background (that are not exactly white) the new image will also not fit in nicely.

**Review by frenck — APPROVED** [review]
Thanks, @gwww 👍

**Pull request merged**
