### PR TITLE
Add icon and logo for new Unmanic integration

### PR DESCRIPTION
**Pull request by JeffResc**
## Proposed change

This adds the icon and logo for a new Unmanic integration.

## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: [homeassistant/core#65352](https://github.com/home-assistant/core/pull/65352)
- Link to documentation pull request: [homeassistant/home-assistant.io#21405](https://github.com/home-assistant/home-assistant.io/pull/21405)
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The 2x version of the icon looks really pixelated/blown-up.

image

Maybe omit that one instead?

**Comment by JeffResc** [comment]
> The 2x version of the icon looks really pixelated/blown-up.

It looks blown up because it is. I didn't realize you could omit the `@2x` version. Just removed it, thank you for the suggestion 👍

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
