### PR TITLE
Add icon and logo for the custom integration spoolman

### PR DESCRIPTION
**Pull request by Disane87**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Hi there @Disane87 👋 

I could not find the public git repository that provides this integration. Could you point me to it?

Thanks! 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Sorry, wrong button. I wanted to request changes. Retry!

**Comment by Disane87** [comment]
Custom integration is currently in development. Will send you the repo tomorrow when it's "publishable".

**Comment by frenck** [comment]
Ok, since we can't process none-existing integration, I'll go ahead and close this PR for now.

../Frenck

**Comment by Disane87** [comment]
I just released a version of the custom component: https://github.com/Disane87/spoolman-homeassistant

**Review by frenck — APPROVED** [review]
Thanks, @Disane87 👍 

../Frenck

**Pull request merged**
