### PR TITLE
Add Opensprinkler OSBee icon

### PR DESCRIPTION
**Pull request by chickenandpork**
## Proposed change

This is required to allow an integration for the OSBee little three-valve controller to be available for easier installs.  My integration is currently at https://github.com/chickenandpork/hass-osbee .. I've only added the basic icon.

Having trouble finding directions or instructions involving home-assistant/wheels-custom-integrations: it seems a near-empty repo, no clear reasoning to guide whether there's a need for a PR there, and how.  The history shows only dependency updates for the last 3 months.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ x ] Add a new logo or icon for a custom integration (custom component)
  - [ x ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/chickenandpork/hass-osbee

## Checklist

- [ x] The added/replaced image(s) are **PNG**
- [ x] Icon image size is 256x256px (`icon.png`)
- [ -] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ -] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ -] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @chickenandpork 👋 

I couldn't find the use of this icon in upstream resources. The open sprinkler project seems to be using different branding. Can you point me to a place where this branding is used?

Thanks already! 👍 

../Frenck

**Comment by chickenandpork** [comment]
> Hi there @chickenandpork 👋
> 
> I couldn't find the use of this icon in upstream resources. The open sprinkler project seems to be using different branding. Can you point me to a place where this branding is used?
> 
> Thanks already! 👍
> 
> ../Frenck

Not used anywhere; the OpenSprinkler developer, “ray”, didn’t respond to my emails before or after I built this integration for osbee and I get it: the money is probably better in bigger OpenSprinkler products.  I wanted to make the integration easier to use and avoid later namespace clash with the Domain, so this PR was needed for that goal.

I didn’t see documentation requiring prior use, and I’m not a GUI guy so much, so I created just any icon.  A designer would probably judge the colours and spacing and whatnot.

**Comment by frenck** [comment]
> Not used anywhere

>  I can’t really use a copywritten icon without a response from ray either.

Understood, but we really cannot accept custom versions. We don't want to misrepresent any upstream branding either, as that often conflicts with brand guidelines as well.

> Registering an integration needs an icon in this repo, so I had to PR an icon in this repo.

That isn't needed. Integration can exist without branding. For that and the above reason, I'll go ahead and close this one up.

../Frenck

**Comment by chickenandpork** [comment]
Understood, @frenck; I’ll post the error output when I retry adding the integration.

thanks for consideration

**Pull request closed without merging**
