### PR TITLE
Add icons for car_wash custom component

### PR DESCRIPTION
**Pull request by Limych**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
https://github.com/Limych/ha-car_wash

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
This uses parts of the home assistant logo, which will make users think that this is supported by home assistant.
There is no reason this icon should have a house in the background, please remove that part.

**Comment by Limych** [comment]
This version of the icons was agreed with @frenck
See https://github.com/home-assistant/brands/pull/2302

**Comment by ludeeus** [comment]
I don't agree with that, but will request a review from frenck (he is on vacation this week)

**Comment by frenck** [comment]
Its not using our template, so I'm fine with that. I agree, it is still a house... but... 🤷

**Pull request closed without merging**
