### PR TITLE
Added omnilogic

### PR DESCRIPTION
**Pull request by chadlyy**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by chadlyy** [comment]
I double-checked and the image file is PNG, square 256x256, and only 55k in size.  Can you advise what it doesn't like about this image?

**Comment by frenck** [comment]
Yes, if you click on the failed CI/build, you can actually see the error:

image

In this case, the filename is not correct.

**Comment by chadlyy** [comment]
So I'm guessing the issue it can't find the manifest file to do a comparison of the name.  We are still in development and haven't published the app yet.  Will try again after we get the initial deployment pushed.

**Comment by frenck** [comment]
No that is not the case, the file name is invalid. That is why I pointed to the readme:


image

**Comment by chadlyy** [comment]
OMG. I saw that and I was like yes, I know it is a png file.  I now get
it.  It has to be specifically called icon.png.  I'm so sorry!  I'll fix.
Thanks for your help!

**Comment by frenck** [comment]
That is incorrect, as written in our manual and in the screenshot I've shown in this review, those files belong in the domain folder.

- `custom_integrations/<integration domain>/icon.png`
- `custom_integrations/<integration domain>/logo.png`

Additionally, please point me to the public repository of this custom integration so I can check the domain after you have adjusted the PR.

**Comment by chadlyy** [comment]
Updated.  The repo isn't public yet as we are still wrapping up dev.  Here is the manfest.json:
`  
{
  "domain": "omnilogic",
  "name": "Hayward Omnilogic",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/omnilogic",
  "requirements": [
    "omnilogic==0.3.4"
  ],
  "ssdp": [],
  "zeroconf": [],
  "homekit": {},
  "dependencies": [],
  "codeowners": [
    "@oliver84"
  ]
}`

**Comment by frenck** [comment]
Please let me know when the repo is public. Thanks! 👍

**Comment by chadlyy** [comment]
So we can't merge this till then?  Should I just cancel this for now?

**Comment by frenck** [comment]
At this point, there is no reason to merge this, as there is nobody that can use it.

**Comment by chadlyy** [comment]
The group working on development can and it will be ready to go when we
release it soon

**Comment by frenck** [comment]
Please let me know when it is publicly available, so we can merge this in at that point.

**Comment by chadlyy** [comment]
will open a new PR as this is being submitted as a new integreation not a custom_component

**Pull request closed without merging**
