### PR TITLE
feat: HACS Sunpower integration

### PR DESCRIPTION
**Pull request by jeeftor**
## Proposed change

Creating a custom icon for: https://github.com/krbaker/hass-sunpower 

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logo has quite a lot of white/transparent space around it, can we trim that down?

**Comment by jeeftor** [comment]
> The logo has quite a lot of white/transparent space around it, can we trim that down?

It just went on a diet! (Extra white has been reduced...)

**Comment by jeeftor** [comment]
Hoping to get this re-reviewd at some point :) (wasn't sure if there was a button I can push)

**Comment by frenck** [comment]
Oh I'm sorry 🙏 
I haven't noticed it was ready.

Nevertheless, the images are still the same size and not trimmed down.

**Comment by jeeftor** [comment]
Maybe I'm confused about what you meant then:

image

Perviously it was a fully white background -> now its a "thin" white border and the rest is transparent. Did you want me to actually cut the images to be smaller? 

image

Also the images appear to be the correct size as far as I can tell..

More guidance please :)

**Comment by jeeftor** [comment]
New Logo Sizes:

```
dark_logo.png PNG 256x128 256x128+0+0 8-bit sRGB 8402B 0.010u 0:00.004
dark_logo@2x.png PNG 512x256 512x256+0+0 8-bit sRGB 16525B 0.000u 0:00.000
logo.png PNG 256x128 256x128+0+0 8-bit sRGB 6341B 0.010u 0:00.000
logo@2x.png PNG 512x256 512x256+0+0 8-bit sRGB 11757B 0.000u 0:00.000
```

**Review by frenck — APPROVED** [review]
Thanks, @jeeftor 👍

**Pull request merged**
