### PR TITLE
Add Wattpilot integration

### PR DESCRIPTION
**Pull request by mk-maddin**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

Custom Integration link: https://github.com/mk-maddin/wattpilot-HA

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks for the PR @mk-maddin 👋 

Nevertheless, it seems like you are adding product icons, however, we collect brand images in this repository.

I would suggest on copying the brand icons from the fronius core integration instead: <https://github.com/home-assistant/brands/tree/master/core_integrations/fronius>

../Frenck

**Comment by mk-maddin** [comment]
Hi @frenck

thanks for your reply.

I am not to deep in the definition differences between vendor VS. product VS. brand ;) 
Just uploaded the icon which is used for the android app (as there are two different apps for Fronius Solar/PV vs Fronius Wattpilot/EV-Charger, exactly as now in HA) , to provide some kind of recognition value.

Never the less I am fine with re-using the icons from core Fronius integration, too.
What do I have to do to use the same icons? just copy/paste into the same repository or is there some kind of symlink or do I reference in my custom component?

**Comment by frenck** [comment]
@mk-maddin don't worry! That is what reviews are for!

Just copy them would do!

**Comment by mk-maddin** [comment]
hi @frenck 

Thanks for your help - copied over the fronius core icons :)

**Pull request merged**
