### PR TITLE
Add icon of 'localtuya_rc' integration

### PR DESCRIPTION
**Pull request by ClusterM**
## Proposed change

Added icon for my LocalTuyaIR Remote Control integration for Home Assistant: https://github.com/ClusterM/localtuya_rc/

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/ClusterM/localtuya_rc/

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @ClusterM 👋 

As this integration integrates an instance with Tuya, I would have expected the Tuya branding to be used.

../Frenck

**Comment by ClusterM** [comment]
> As this integration integrates an instance with Tuya, I would have expected the Tuya branding to be used.

Hi! Not sure that I understand you. What I need to change?

**Comment by frenck** [comment]
This is an integration for Tuya, so the Tuya branding is expected. This PR doesn't contain the Tuya brand.

**Comment by ClusterM** [comment]
> This is an integration for Tuya, so the Tuya branding is expected. This PR doesn't contain the Tuya brand.

Do I need to use the official Tuya logo? Is it legal? Do I just need to create a symlink to core_integrations/tuya? I just saw how it is implemented in other Tuya integrations, such as localtuya, and they use their own logo.

**Comment by frenck** [comment]
> Do I need to use the official Tuya logo?

Yes

> Is it legal?

Well it is what we collect here, at the same time, we also don't want to misrepresent brands, which is just a problematic.

> Do I just need to create a symlink to core_integrations/tuya?

No, see also repo readme.

>  such as localtuya

That is odd, feel free to contribute to fix that occurrence.

../Frenck

**Comment by ClusterM** [comment]
> No, see also repo readme.

Oh, my bad. I understand. Fixed.

I’m sorry for wasting your time because of my lack of attention🙏

**Comment by ClusterM** [comment]
@frenck is it ok now? I just copied images from `core_integrations/tuya`.

**Review by frenck — APPROVED** [review]
Thanks, @ClusterM 👍 

../Frenck

**Pull request merged**
