### PR TITLE
Add images for PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor

### PR DESCRIPTION
**Pull request by PiotrMachowski**
## Proposed change

Add icons for custom integration:
[PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations): [link](https://github.com/home-assistant/wheels-custom-integrations/pull/350)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @PiotrMachowski 👍

**Comment by PiotrMachowski** [comment]
Hi @frenck,

I see that you have closed this PR, not merged - was it on purpose? 😉

**Comment by frenck** [comment]
LOL! Abasolutely not!

**Comment by frenck** [comment]
I cannot re-open it, as the upstream repository has been deleted.

I'm so sorry! It was one of the first PRs this morning. I've must been sleeping :(

**Comment by PiotrMachowski** [comment]
Yeah, I was sleeping as well and I have removed my fork :) I will recreate these changes and open a new PR

**Pull request closed without merging**
