### PR TITLE
Add taipower_bimonthly_cost integration icons

### PR DESCRIPTION
**Pull request by cnstudio**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: https://github.com/cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I would have expected the Taipower branding in this PR.

**Comment by cnstudio** [comment]
This is the integration website: https://github.com/cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant
The major function is calculate Taipower (Taiwan Power Company) bi-monthly (60 days) bill amount from kWh sensor on Home Assistant.

**Comment by frenck** [comment]
Cool. However, it's not the Taipower branding that is submitted in this PR.
Their branding looks different:

CleanShot 2022-04-07 at 14 34 01

**Comment by cnstudio** [comment]
OK, I upload new icons, Now they are Taipower branding. :)

**Review by frenck — APPROVED** [review]
Thanks, @cnstudio 👍

**Pull request merged**
