### PR TITLE
Add Stream Deck brand images

### PR DESCRIPTION
**Pull request by Patrick762**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

Just a copy of the already existing Elgato icons so I can use them in my integration (https://github.com/Patrick762/ha-streamdeck-integration)

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I could not find the repository providing this custom integration, could you point me to it?

Thanks! 👍 

../Frenck

**Comment by frenck** [comment]
Right, at this point, it doesn't look like a publicly usable/available integration as of yet.

Shall we close this until it is?

../Frenck

**Comment by Patrick762** [comment]
Ok. I will close the PR until then

**Comment by Patrick762** [comment]
The integration is now in a useable state: https://github.com/Patrick762/hacs-streamdeck

**Review by frenck — APPROVED** [review]
Thanks, @Patrick762 👍 

../Frenck

**Pull request merged**
