### PR TITLE
Update Various Company Logos + Add Dark Mode Icons

### PR DESCRIPTION
**Pull request by MapGuy11**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [x] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- https://www.home-assistant.io/integrations/discord/
- https://www.home-assistant.io/integrations/dominos/
- https://www.home-assistant.io/integrations/tplink_omada/
- Link to custom integration repository:
- https://github.com/magico13/ha-emporia-vue
- https://github.com/uvjim/hass_hdhomerun

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by MapGuy11** [comment]
There were some issues with some of the logos, so the 2nd pull request removed those changes.

**Review by frenck — CHANGES_REQUESTED** [review]
This PR needs to be split out into a single PR per integration.

../Frenck

**Comment by MapGuy11** [comment]
Okay I'll close this and split it out. Thank you!

**Comment by frenck** [comment]
Nice ❤️ Thank you @MapGuy11 👍

**Pull request closed without merging**
