### PR TITLE
Liquid-Check icon

### PR DESCRIPTION
**Pull request by shivan**
## Proposed change

Logo for a component I'm going to add.
https://github.com/shivan/homeassistant-liquidcheck

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
These are product photos, not manufacturer branding.

Please replace the assets to have the Si Electronik brand assets instead.

../Frenck

**Comment by shivan** [comment]
@frenck changes done.
But folder name can be left the same? Or should I change this also to si elektronik?
But then I would have to change my plug-in name, too?

**Comment by frenck** [comment]
The folder name is the domain name of the integration; those are not bound to those rules (there can even be multiple integrations for the same manufacturer, so in those cases the domains already have to be different).

As for the images provided, something is odd, as the images are mixed transparent / not-transparent.

CleanShot 2023-08-16 at 18 26 28

**Comment by shivan** [comment]
So then would it be better, using the domain name "si_elektronik" and name "liquid-check"?
Then the folder name would have to be "si_elektronik".

But I'm not from si elektronik, I'm just creating that integration, since I need it :-)

--

Currently I only need the integration for the device "liquid-check" -- or would it be ok to leave it as it is now? domain "liquid-check" and name "Liquid-Check"?

**Comment by shivan** [comment]
@frenck any more changes requested?

**Review by frenck — APPROVED** [review]
Thanks, @shivan 👍 

../Frenck

**Pull request merged**
