### PR TITLE
Add logo for Energie VanOns integration

### PR DESCRIPTION
**Pull request by klaasnicolaas**
## Proposed change

Add logo for Energie VanOns (virtual) integration

## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/85704
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/25704
- Link to integration documentation on our website:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Are there no icons?

**Comment by klaasnicolaas** [comment]
From what I have been able to find, the attached logo is the only thing they use as branding

https://energie.vanons.org/

**Comment by MartinHjelmare** [comment]
Do we have fallbacks when there's no icon for an integration but a logo?

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
> Do we have fallbacks when there's no icon for an integration but a logo?

https://deploy-preview-4028--home-assistant-brands.netlify.app/_/_placeholder/icon.png

We don't.



> From what I have been able to find, the attached logo is the only thing they use as branding
> 
> [energie.vanons.org](https://energie.vanons.org/)

You could grab it from Twitter?

https://twitter.com/Energie_VanOns

CleanShot 2023-01-12 at 08 19 50

**Review by MartinHjelmare — APPROVED** [review]

**Pull request merged**
