### PR TITLE
Added icons for custom component somneo

### PR DESCRIPTION
**Pull request by theneweinstein**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @theneweinstein, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2760).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
We collect brands in this repository, so in this case, I would have expected the Philips logos, not the product brand icons.

**Comment by Vato9394** [comment]
This is an integration for philips somneo only, hence the philips smartsleep logo. (same as the app)
this integration is not integrated in other philips custom components because it also uses an other app and API. (different eco system)
both philips hue (https://github.com/home-assistant/brands/blob/master/custom_integrations/huesyncbox/icon.png) and philips ambilight (https://github.com/home-assistant/brands/blob/master/custom_integrations/philips_ambilight%2Bhue/icon.png) have different logo's.
thats why we uploaded this logo.

**Review by Vato9394 — DISMISSED** [review]
This is an integration for philips somneo only, hence the philips smartsleep logo. (same as the app)
this integration is not integrated in other philips custom components because it also uses an other app and API. (different eco system)
both philips hue (https://github.com/home-assistant/brands/blob/master/custom_integrations/huesyncbox/icon.png) and philips ambilight (https://github.com/home-assistant/brands/blob/master/custom_integrations/philips_ambilight%2Bhue/icon.png) have different logo's.
thats why we uploaded this logo.

**Comment by frenck** [comment]
Please adjust the PR to include the brand images as requested. Thanks 👍

**Comment by theneweinstein** [comment]
I've adjusted the icons and logos as you requested.

**Review by frenck — APPROVED** [review]
Thanks, @theneweinstein 👍

**Pull request merged**
