### PR TITLE
Added Mutesync

### PR DESCRIPTION
**Pull request by currentoor**
## Proposed change

Adding mutesync branding to go with the integration I added in the core repo.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: home-assistant/core#49679
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/17593
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @currentoor, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2519).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @currentoor 👋 

- The icon & logo are the same. Please omit the logos in this case (or provide actual logos of course).
- The folder used is `custom_integrations`, however, there is a parent PR in our core codebase associated with this PR. Please use the `core_integrations` folder in that case 👍 

../Frenck 🚂

**Comment by currentoor** [comment]
@frenck done, thanks!

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
