### PR TITLE
Ecowitt

### PR DESCRIPTION
**Pull request by alexdelprete**
## Proposed change

Ecowitt logo+icon for custom component by @garbled1: https://github.com/garbled1/homeassistant_ecowitt

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by garbled1** [comment]
I think there is something odd here, there seem to be some logos for nuki_ng in this commit, did another commit get mixed in here?

**Comment by alexdelprete** [comment]
mmm...those were old PRs of months ago, already merged. The ones with the Verified tag. The only new one has been the ecowitt. I don't know why they come up in the PR. Let's see what Frenck says...

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR, please git rebase it to clean it up.

**Comment by alexdelprete** [comment]
Resubmitted in #3106

**Pull request closed without merging**
