### PR TITLE
Add logos for Frigidaire AC

### PR DESCRIPTION
**Pull request by bm1549**
## Proposed change

Adds logo and icon for a new integration

Also updates the `.gitignore` to ignore files created by the [JetBrains](https://www.jetbrains.com/) family of IDEs

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/17991
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There is a lot of empty space around the logo

image


Please remove that.

**Comment by bm1549** [comment]
@frenck thanks for your review - I've removed the empty space around the logos

**Comment by frenck** [comment]
Unfortunately, the builds didn't pass this time:

```
Error: Invalid logo size! Size is 455x54px, shortest side must be at least 128px: core_integrations/frigidaire/logo.png
Error: Invalid hDPI logo size! Size is 910x107px, shortest side must be at least 256px: core_integrations/frigidaire/logo@2x.png
```

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
