### PR TITLE
Update BMW logo to MyBMW

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

Updates the BMW Connected Drive logo to the current BMW design language. Also changes ConnectedDrive to MyBMW.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Shouldn't the logo also just be the BMW logo?

**Comment by rikroe** [comment]
To be honest, I'm not really sure: 
BMW ConnectedDrive was the name of the backend service and app providing access to BMW vehicles.
MyBMW is the name of the new app (and backend service, if you're logging in via a browser).

We could also just focus on the BMW icon alone and remove the MyBMW logo, would be fine with.

A little bit off-topic: is there some documentation regarding renaming a core integration (i.e. from BMW ConnectedDrive / `bmw_connected_drive` to only BMW/`bmw`)?

**Comment by gerard33** [comment]
I would also prefer to just use the BMW icon and not use the My BMW logo.

**Comment by frenck** [comment]
> A little bit off-topic: is there some documentation regarding renaming a core integration (i.e. from BMW ConnectedDrive / bmw_connected_drive to only BMW/bmw)?

We have no support / logic for renaming domains (hence the Supervisor integration still uses `hassio`).

**Pull request merged**
