### PR TITLE
Add icons for the custom integration komfovent_c5

### PR DESCRIPTION
**Pull request by siku2**
## Proposed change

Hello again, this time I'm here for the custom integration [Komfovent C5](https://github.com/siku2/hass-komfovent-c5), which handles [Komfovent Air Handling Units](https://www.komfovent.com/en/c/products/air-handling-units).

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] ~~I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)~~ _not applicable_
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

The logo is rasterized version of the SVG logo used on the Komfovent website: https://www.komfovent.com/en/
The icon is from the Play Store app listing: https://play.google.com/store/apps/details?id=com.Amalva.komfovent_C5_app

Note that I compressed the icon slightly (should be unnoticeable) to bring its excessive size down.

> [!NOTE]
> There is an arguably prettier icon available for a different Komfovent App seen below. This is for the cloud version though. The one added here is specifically for the local communication to C5 devices.

[logo](https://play.google.com/store/apps/details?id=com.finaly.komfoventcloud)

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon is not a manufacturer branding, but an app branding.

The manufacturer uses a different icon for their branding, for example:

CleanShot 2023-08-22 at 10 11 33


CleanShot 2023-08-22 at 10 12 20

CleanShot 2023-08-22 at 10 12 33

Please adjust this PR to use the branding the manufacturer uses.

../Frenck

**Comment by siku2** [comment]
@frenck, you're right, I was trying to indicate that the integration explicitly deals with the C5 devices, rather than the whole Komfovent suite. Given that this project is focused on brands and the previous icon didn't indicate any kind of relationship with Komfovent, I'm happy to replace it.

Since the icon is the same as the logo, I went ahead and removed the separate logo image from the PR.

**Review by frenck — CHANGES_REQUESTED** [review]
I don't think you should have removed the logo versions. They are not the same (unlike what you wrote). The icons are square, while the logo version is trimmed down.

**Comment by siku2** [comment]
Had a feeling you might say that and that was my first instinct as well. I opted to remove them because I couldn't find any other instances of this situation - where the logo is just a different crop of the icon.

**Review by frenck — APPROVED** [review]
Nice! Thanks, @siku2 👍 

../Frenck

**Comment by siku2** [comment]
Thanks for your patience this time around :)

**Comment by frenck** [comment]
No problem; the honor and pleasure are all mine. Thanks for contribute ❤️

**Pull request merged**
