### PR TITLE
Add logo for smart0183tcp

### PR DESCRIPTION
**Pull request by SmartBoatInnovations**
## Proposed change

Adding a new icon for the smart0183tcp custom integration to be used in the Home Assistant UI.
I write integrations that interface marine instruments to Home Assistant
https://github.com/SmartBoatInnovations/ha-smart0183tcp

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

This is the first submission of the icon for the smart0183tcp integration.

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by SmartBoatInnovations** [comment]
I will once I get better at image editing.Can we just start with the standard resolution icon.png ?
 
 
  On Thu, 7 Mar 2024 at 11:15, Klaas ***@***.***> wrote:   


Could you also add an hDPI version?

./Klaas

**Comment by SmartBoatInnovations** [comment]
> Could you also add an hDPI version? And you marked that you added a logo, but only see an icon.
> 
> ./Klaas

I have now added hDPI version.
Yes it is only an icon that will also be the logo.
I have un selected the checkbox for logo.

**Comment by SmartBoatInnovations** [comment]
> Could you also add an hDPI version? And you marked that you added a logo, but only see an icon.
> 
> ./Klaas

Hello - Are you waiting on anything else from me?

**Review by klaasnicolaas — APPROVED** [review]
Thnx for the PR! 🥇

./Klaas

**Comment by SmartBoatInnovations** [comment]
Hi,

Thanks.
The logo appears it most places in HA not in the Integration popup list
when adding a new integration.
See attached screenshots.

Regards,
Rob

**Pull request merged**
