### PR TITLE
Adding icons for Azure OpenAI

### PR DESCRIPTION
**Pull request by joselcaguilar**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to the custom integration: https://github.com/joselcaguilar/azure-openai-ha

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This logo seems to be self-created? I could not find a reference using this logo? Could you point me to it?

Thanks! 👍 

../Frenck

**Comment by joselcaguilar** [comment]
> This logo seems to be self-created? I could not find a reference using this logo? Could you point me to it?
> 
> Thanks! 👍
> 
> ../Frenck

Hi @frenck It has been self-created based on the official [OpenAI logo](https://commons.wikimedia.org/wiki/File:OpenAI_Logo.svg) and [Azure logo](https://azure.microsoft.com/en-us/blog/a-fluent-new-look-for-the-azure-icon/).

**Review by frenck — CHANGES_REQUESTED** [review]
We can, unfortunately, not accept such creations. This self-created branding is most likely violating the branding of two companies right now.

../Frenck

**Comment by joselcaguilar** [comment]
> We can, unfortunately, not accept such creations. This self-created branding is most likely violating the branding of two companies right now.
> 
> ../Frenck

Hi @frenck what's the best way to proceed here? Using a self-creation without references to official logos? Or use only one official logo without being mixed just like the official OpenAI integration?

Please advice. Thanks in advance!
Jose

**Comment by frenck** [comment]
The logo of the service provider / manufacturer of the hardware, is what we collect in this repository. In this case, Azure.

**Comment by joselcaguilar** [comment]
> The logo of the service provider / manufacturer of the hardware, is what we collect in this repository. In this case, Azure. I think the OpenAI logo could be used alternatively, but might be confused with the API they are offering.

Great, thanks for clarify @frenck it will be fixed by EOD :)

**Comment by joselcaguilar** [comment]
> > The logo of the service provider / manufacturer of the hardware, is what we collect in this repository. In this case, Azure. I think the OpenAI logo could be used alternatively, but might be confused with the API they are offering.
> 
> Great, thanks for clarify @frenck it will be fixed by EOD :)

Done, so sorry for the delay @frenck

**Review by frenck — APPROVED** [review]
Thanks, @joselcaguilar 👍 

../Frenck

**Pull request merged**
