### PR TITLE
Add icon for ntfy

### PR DESCRIPTION
**Pull request by nwithan8**
## Proposed change

Add icon for new ntfy integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/81182
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/24741
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon looks blown up:

image

Can we get a higher resolution version?

The logo is basically the icons, while on their website they use:

image

Should the logo version be replaced with such one?

**Comment by nwithan8** [comment]
> The icon looks blown up:
> 
> image
> 
> Can we get a higher resolution version?
> 
> The logo is basically the icons, while on their website they use:
> 
> image
> 
> Should the logo version be replaced with such one?

The source file for that logo is only 100x80: https://ntfy.sh/static/img/ntfy.png

**Comment by nwithan8** [comment]
Reached out to the ntfy dev, got some high-quality logos.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
