### PR TITLE
Add zhipuai integration

### PR DESCRIPTION
**Pull request by knoop7**
Hello, I have uploaded it as required. In fact, there is a release version. Because I don’t know much about vscode. Every time I distribute the installation package, the content will be messed up. This is public code and does not add any hidden content. I hope you can understand

https://github.com/knoop7/zhipuai

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The integration has an invalid requirement:

https://github.com/knoop7/zhipuai/blob/e7ef0351c8e17e9f4a7a04fe0076421e4f487f57/custom_components/zhipuai/manifest.json#L12

See: <https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-integration-requirements>

../Frenck

**Comment by knoop7** [comment]
Thank you, I have corrected the error according to your request. Thank you for your introduction. I really don't understand it.

**Comment by frenck** [comment]
The issue hasn't been solved.

See: 

https://github.com/knoop7/zhipuai/blob/ed5c8969f883c7402ca62409194b1247afb30eaa/custom_components/zhipuai/manifest.json#L11

Also see my previous comment which links the developer documentation.

../Frenck

**Comment by knoop7** [comment]
https://github.com/knoop7/zhipuai/blob/550949de425d240cba639cf8f512ee08f370e665/custom_components/zhipuai/manifest.json Hello, I have modified the content and deleted unnecessary and wrong content. I'm really sorry for causing you any trouble. All modifications are based on your suggestions. Thank you for your hard work.

**Comment by knoop7** [comment]
Thank you, I have deleted the dependencies, consulted the developer documentation, and learned other people’s integration techniques. I really don’t know much about this, {
  "domain": "zhipuai",
  "name": "\u667a\u8c31\u6e05\u8a00",
  "codeowners": ["@knoop7"],
  "config_flow": true,
  "documentation": "https://github.com/knoop7/zhipuai",
  "integration_type": "hub",
  "iot_class": "cloud_polling",
  "issue_tracker": "https://github.com/knoop7/zhipuai/issues",
  "requirements": [],
  "version": "2024.10.14"
}

**Comment by frenck** [comment]
>  I really don’t know much about this,

Hehe, well don't take this the wrong way... but why are you building a custom integration if you don't know how this all works? :)

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @knoop7 👍 

../Frenck

**Comment by knoop7** [comment]
@frenck 

Thank you for your hard work. When I was studying, I didn’t think much about it.

**Pull request merged**
