### PR TITLE
Rename ai_thermostat to better_thermostat

### PR DESCRIPTION
**Pull request by KartoffelToby**
## Proposed change

The Intigration ai_thermostat has a name change to better_thermostat
https://github.com/KartoffelToby/better_thermostat

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [X] Removing an icon or logo

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by KartoffelToby** [comment]
@frenck you did the PR last time, its just a rename of the project.

**Comment by frenck** [comment]
@KartoffelToby No need to ping people asking to look at PRs. Please don't do that.

**Comment by RubenKelevra** [comment]
@frenck well, but 12 days for a simple rename is quite a long delay. Our CI is failing because of this :/

**Comment by frenck** [comment]
@KartoffelToby Yes, but it is not polite or wished for. As a matter of fact, I don't review when pinged/asked for it out of the blue.

**Comment by KartoffelToby** [comment]
@frenck 

> @KartoffelToby No need to ping people asking to look at PRs. Please don't do that.

Please excuse me, I didn't want to rush you, I wasn't sure about the renaming and therefore wanted to link the one from the old PR. I know how annoying this can be, it won't happen again

**Pull request merged**
