### PR TITLE
Add icons for blitzortung custom integration

### PR DESCRIPTION
**Pull request by mrk-its**
## Proposed change

I'm adding custom component for Blitzortung to default HACS repository and it requires images to be present here.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by mrk-its** [comment]
Do you mean these white round strips (circles)? These are part of the logo, take a look on top bar at http://en.blitzortung.org/cover_your_area.php

**Comment by frenck** [comment]
No there is a fine vertical black striping (multiple).

**Comment by mrk-its** [comment]
Sorry, I don't see any black stripping, attached images were rendered in google chrome:
Screenshot from 2020-07-04 19-08-43
Screenshot from 2020-07-04 19-08-55

**Comment by frenck** [comment]
You are absolutely right! This is my browser going nuts... sorry about that 👍

**Pull request merged**
