### PR TITLE
Add icons and logos for custom integration tuya-hombli

### PR DESCRIPTION
**Pull request by wilbiev**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @wilbiev 👋 

The provided integration domain contains a dash (`-`) which isn't a valid character to use in integration domains. Please move it (suggestion is to use an underscore instead (`_`)).

../Frenck

**Comment by wilbiev** [comment]
Renamed custom integration tuya-hombli to tuyahombli as requested

**Review by frenck — COMMENTED** [review]
Both are still in the PR

**Comment by wilbiev** [comment]
This pull request will be closed and a new one will be created from scratch.

**Pull request closed without merging**
