### PR TITLE
Addmy enedis

### PR DESCRIPTION
**Pull request by saniho**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The domain seems to be `myEnedis`, but domains cannot contain capital letters in Home Assistant, so that cannot be correct?

**Comment by frenck** [comment]
The domain in the custom integration now don't match the images:

<https://github.com/saniho/apiEnedis/blob/main/custom_components/apiEnedis/manifest.json#L2>

**Comment by saniho** [comment]
@frenck , thanks for the feedback, yes, I have this issue, but I don't know, if I can change the domain name easy ... the problem is I have a lot of users( more than 200 ), and if I hange, what is the impact on their configuration ...

**Comment by frenck** [comment]
@saniho That is painful indeed, but the domain is invalid in Home Assistant core as well. It may cause issues in the future if it isn't changed.

**Comment by mdeweerd** [comment]
Somewhat related to this: the hassfest validation does not seem to added to the repository, but I am not sure that it also validates that the naming rules are followed - I was under the impression that it was not complaining about a '-' sign I initially added to the domain name of a componant.

I suggest to add hassfest to the github actions ( https://hacs.xyz/docs/publish/include#before-submitting )

**Pull request closed without merging**
