### PR TITLE
Add CloudWatch custom component icon

### PR DESCRIPTION
**Pull request by Mallonbacka**
## Proposed change

This adds an icon for the [Amazon CloudWatch custom component](https://github.com/Mallonbacka/custom-component-cloudwatch) I wrote to monitor/alert my HA instance. 

It re-uses the AWS icons from the core `aws` integration. 

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
It is expected to be using the upstream branding of the provider, in this case the AWS branding.

The images provided seems to be created / inspired by, which is not something we allow.

../Frenck

**Comment by Mallonbacka** [comment]
> It is expected to be using the upstream branding of the provider, in this case the AWS branding.
> 
> The images provided seems to be created / inspired by, which is not something we allow.
> 
> ../Frenck

Sorry if my comment wasn't clear. This was not "created or inspired by". 

This image is produced by AWS, and downloaded from the page linked above ([Amazon CloudWatch custom component](https://github.com/Mallonbacka/custom-component-cloudwatch)). It's the 'Architecture icon' for the specific service, rather the AWS or Amazon logo, but it's made and provided by them.

[The core Amazon Polly integration](https://www.home-assistant.io/integrations/amazon_polly/) uses the same approach, using the architecture icon to refer to the integration, instead of Amazon or AWS branding. 

I can, of course, swap to a generic AWS logo if you prefer, but, in that case, I guess Polly should too. Personally, I think the service-specific AWS-provided architecture icons are a good choice.

**Comment by frenck** [comment]
> [The core Amazon Polly integration](https://www.home-assistant.io/integrations/amazon_polly/) uses the same approach, using the architecture icon as a logo for the integration, instead of Amazon or AWS branding.

Correct, but those use brand categorization (and thus is used in a second step), which is not available for custom integrations. Thus we should use the main branding instead.

../Frenck

**Comment by Mallonbacka** [comment]
That's a shame, I was hoping not to have multiple generic 'Amazon' icons side-by-side.

But it's updated now, use the same branding as the core `aws` integration. 

Thanks for the clarification.

**Review by frenck — APPROVED** [review]
Thanks, @Mallonbacka 👍 

../Frenck

**Pull request merged**
