### PR TITLE
Add logos and icons for Nikobus custom_integration

### PR DESCRIPTION
**Pull request by fdebrus**
## Proposed change

Add icons and logos for company brand "Niko" product "Nikobus"

Company website https://www.niko.eu/nl-be
Custom integration github https://github.com/fdebrus/Nikobus-HA

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:  
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by fdebrus** [comment]
Hello, Shall I provide more information on this request ? thanks

**Comment by fdebrus** [comment]
It's no longer distributed by Niko and replaced by HomeControl. Nikobus was the predecessor of HomeControl.

Some modules are no longer on sales since 2021 other 2022.
https://www.niko.eu/nl-be/artikel/05-000-02

The solution is robust and being used still today. You can see it was the official logo from Nikobus from this picture of one module. I do not believe I can still find the logo on Niko website, it has been retired.

image

**Comment by fdebrus** [comment]
Good day, am I missing some informations / steps to get this merged ? 

thank you

**Review by frenck — CHANGES_REQUESTED** [review]
The provided icons seem to be application/product-related branding, not manufacturer branding assets.

Looking at the profiles of Niko, they use a different icon:

CleanShot 2024-03-18 at 17 46 47@2x

CleanShot 2024-03-18 at 17 46 59@2x

CleanShot 2024-03-18 at 17 47 10@2x

CleanShot 2024-03-18 at 17 47 25@2x

Please adjust the branding to match.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
So, I was mentioning the provided icon in this PR was not matching upstream. However, in the latest change in this PR, you've replaced the logo... not the icon.

The result: A non standard icon and an logo (that was good) is now replace with an icon?

Please restore the logo and replace the icon.

../Frenck

**Comment by fdebrus** [comment]
Oups, my bad, so the icon shall not be product specific ? 

When I look at the successor of "Nikobus" which is "Niko Home Control" (already existing as a core integration).
The logo is the original one I proposed (will revert) and the icon is product specific "Niko Home Control".

Here my proposal is to have the icon for "Nikobus" product.
You will not find "Nikobus" assets anymore at Niko, it's retired and replaced by "Niko Home Control" but "Nikobus" is still being used widely.

Let me know what you prefer, generic "Niko" icon or product specific for "Nikobus". I'm fine either way.

Again, sorry for the confusion, thanks for your time !

**Comment by frenck** [comment]
> Oups, my bad, so the icon shall not be product specific ?

Correct.

> Here my proposal is to have the icon for "Nikobus" product.

Sorry, we collect brand assets. Please change the icon to match the branding of the manufacturer.

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @fdebrus 👍 

../Frenck

**Pull request merged**
