### PR TITLE
Add icon and logo for custom component rinnaitouch

### PR DESCRIPTION
**Pull request by funtastix**
## Proposed change

Icon and image for custom component [rinnaitouch](https://github.com/funtastix/rinnaitouch). The component integrates the Rinnai Touch Wifi controller that allows control of climate systems by Rinnai. This includes the Brivis brand.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @funtastix, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3272).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
The icons do not seem to match the branding Rinnai uses themselves, some examples:

image

image

**Comment by funtastix** [comment]
> The icons do not seem to match the branding Rinnai uses themselves, some examples:
> 
> image
> 
> image

This branding is specific to the Rinnai Touch application and unit: 
- https://play.google.com/store/apps/details?id=au.com.rinnai.rinnaitouch&hl=en&gl=US
- https://www.rinnai.com.au/online/controllers/heating-and-cooling-controllers/rinnai-touch-wi-fi/

**Comment by frenck** [comment]
> This branding is specific to the Rinnai Touch application and unit:

This repository collects branding of manufacturers/brands; not application images.

**Comment by funtastix** [comment]
> This repository collects branding of manufacturers/brands; not application images.

Changed the icon assets accordingly

**Review by frenck — APPROVED** [review]
Thanks, @funtastix 👍

**Pull request merged**
