### PR TITLE
Add EufyLife logo

### PR DESCRIPTION
**Pull request by bdr99**
## Proposed change
Add logo for the proposed EufyLife integration.

Also add logo and icon for eufy brand.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/85907
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/25757
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons provided seems to be application icons from their apps?
Please use the eufy branding instead.

Please note, the use of more specific product branding is allowed, but that would only be accepted if a brand definition in the Core repository is made under which this integration would be put.

../Frenck

**Comment by bdr99** [comment]
@frenck I was actually planning to create a brand definition in core, since there will be two Eufy integrations. The existing `eufy` integration integrates devices from sold under EufyHome product line, and the new `eufylife_ble` integration will cover the EufyLife product line. But I was going to wait to create the brand definition core PR until after the integration PR is merged. Would it be better if I create it now?

**Comment by frenck** [comment]
> I was actually planning to create a brand definition in core, since there will be two Eufy integrations.

Great, but this PR and the core PR don't reflect that.

> But I was going to wait to create the brand definition core PR until after the integration PR is merged. Would it be better if I create it now?

Can be done in these PRs directly.

../Frenck

**Comment by bdr99** [comment]
@frenck OK, I updated this PR and the core PR to add the eufy brand.

**Review by frenck — CHANGES_REQUESTED** [review]
The `core_integrations/eufy` folder can be symlinked to the brands one

**Comment by bdr99** [comment]
@frenck If I did that, then the `eufy` integration would no longer be able to have its own icon.

**Comment by bdr99** [comment]
To clarify the above statement, the current icon used by the `eufy` integration is actually the logo for the EufyHome product line/app, which makes sense because those are the products that are compatible with that integration. Similarly, the `eufylife_ble` integration will have the icon for the EufyLife product line.

That's the reason why I think the `eufy` integration should have a separate logo from the `eufy` brand.

**Comment by frenck** [comment]
> @frenck If I did that, then the `eufy` integration would no longer be able to have its own icon.

Thanks, that is clear! 👍

**Review by frenck — APPROVED** [review]
Thanks, @bdr99 👍 

../Frenck

**Pull request merged**
