### PR TITLE
Add kdeconnect integration

### PR DESCRIPTION
**Pull request by freundTech**
## Proposed change

This commit adds icons and logos for the new KDE Connect integration I developed.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/67703
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/21914
- Link to integration documentation on our website:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @freundTech, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3233).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
I would have expected this integration to provide just the KDE branding and not the application icons/logos.

**Comment by freundTech** [comment]
Could you explain, why you would expect the KDE logo instead of the KDE Connect logo?
The logo I submitted is the Logo used by KDE Connect on Android, iOS and PC.

KDE Connect, while under the KDE umbrella, is a separate project, that doesn't depend on the KDE desktop environment and can also be used by for example gnome users.

In addition, my integration doesn't only allow pairing to PCs but also to phones running KDE Connect, which would leave desktop linux, and therefore everything KDE other than KDE Connect, out of the equation entirely.

**Comment by rytilahti** [comment]
I agree that it's better to use this KDE Connect logo instead of a generic KDE one, so this should be good to go. Btw, the logo usage seems to be inconsistent: the one used on android has no pinhole nor speaker split.

**Comment by frenck** [comment]
> I agree that it's better to use this KDE Connect logo instead of a generic KDE one, so this should be good to go.

Sorry, that is incorrect.

This brand repo carries branding of manufacturers, not products. We do allow product branding, in case the integration is grouped by a brand, however, that is not the case. 

Thus, in this case, KDE Connect is provided by the KDE project. It even shows as such big on the website and is hosted under the KDE flag and domain.

It is compatible to many other manufacturer who have branding for specific product lines, or services.

**Comment by rytilahti** [comment]
I stand corrected, thanks @frenck! I'd really like to see kdeconnect supported, are you still interested in working on this, @freundTech?

**Comment by frenck** [comment]
@rytilahti There is a parent PR linked in the PR description.

**Comment by freundTech** [comment]
@rytilahti I'm still interested in working on this, but don't have the time for it right now, so don't expect any progress in the near future.
If someone else wants to pick up where I left of that's of course ok too.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
