### PR TITLE
Add icons for integration notify_events

### PR DESCRIPTION
**Pull request by papajojo**
## Proposed change

Addidng logo and brand pictures for new platform for notify component.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: [#36049](https://github.com/home-assistant/core/pull/36049)
- Link to documentation pull request: [#13571](https://github.com/home-assistant/home-assistant.io/pull/13571)
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
I'm confused, is this a custom integration or a core integration?

As you have linked a PR that adds it to the core?

**Comment by papajojo** [comment]
> I'm confused, is this a custom integration or a core integration?
> 
> As you have linked a PR that adds it to the core?

Sorry, it's actually a platform for the notify component

**Comment by frenck** [comment]
For the Home Assistant codebase right? As in, it is going to be part of Home Assistant itself and not a custom component?

**Comment by papajojo** [comment]
> For the Home Assistant codebase right? As in, it is going to be part of Home Assistant itself and not a custom component?

I mean it's an notification integration like those:
https://www.home-assistant.io/integrations/discord/
https://www.home-assistant.io/integrations/flock/

It's not a part of Home Assistant itself

**Comment by papajojo** [comment]
Hello @frenck! Is there anything I can do for this PR?

**Pull request merged**
