### PR TITLE
Add Apex Brand Images

### PR DESCRIPTION
**Pull request by itchannel**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

Brand images for Apex aquarium controller (https://www.neptunesystems.com/) 
 Custom integration github is https://github.com/itchannel/apex-ha

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon is the brand image of Neptune Systems, however, the logos are not.

The logos seem like product naming/images. I would expect the Neptune Systems logo to be provided instead.

**Comment by itchannel** [comment]
> The icon is the brand image of Neptune Systems, however, the logos are not.
> 
> The logos seem like product naming/images. I would expect the Neptune Systems logo to be provided instead.

Agreed. Changed the logo files to the Apex Systems main logo. I've used the black version as per the git rules as the white logo version they have is hard to read.

**Comment by frenck** [comment]
> I've used the black version as per the git rules as the white logo version they have is hard to read.

You could also add the white logo version as the `dark` variant (`dark_logo.png`), they get used when a user is using a dark mode in their instance.

**Comment by itchannel** [comment]
> > I've used the black version as per the git rules as the white logo version they have is hard to read.
> 
> You could also add the white logo version as the `dark` variant (`dark_logo.png`), they get used when a user is using a dark mode in their instance.

Thanks for the suggestion did not know that was possible. I've committed the white version as dark_ as requested.

**Review by frenck — APPROVED** [review]
Thanks, @itchannel 👍

**Pull request merged**
