### PR TITLE
Limych/car wash

### PR DESCRIPTION
**Pull request by Limych**
## Proposed change

This is a reopening of PR #2775

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
https://github.com/Limych/ha-car_wash

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Right... but the review comment from linked PR wasn't resolved.

**Comment by Limych** [comment]
I don't understand what comment you are talking about. Could you please repeat it here?

**Comment by frenck** [comment]
https://github.com/home-assistant/brands/pull/2775#issuecomment-939942491

**Comment by Limych** [comment]
I'm sorry, I don't understand again — change what?

**Comment by frenck** [comment]
@Limych From the upstream PR:

CleanShot 2024-07-07 at 23 24 54@2x

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Pull request closed without merging**
