### PR TITLE
Add Brand Refoss  In core_brands

### PR DESCRIPTION
**Pull request by ashionky**
## Proposed change

Add Brand Refoss  in core_brands

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [x] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @ashionky 👋 

Can you please link up the PR in our core repository that adds this brand?

Thanks! 👍 

../Frenck

**Comment by ashionky** [comment]
> Hi there @ashionky 👋
> 
> Can you please link up the PR in our core repository that adds this brand?
> 
> Thanks! 👍
> 
> ../Frenck

Hi @frenck   
My integration has been launched in the core repository,
I need to create a brand now, and the core repository will use this brand,

In the future, we will add  a  new integration that will use the same Refoss brand, similar to Xiaomi.
I don't know if my introduction is clear.

**Comment by ashionky** [comment]
> > My integration has been launched in the core repository,
> 
> Nice 👍
> 
> > I need to create a brand now, and the core integration will use this brand,
> 
> Ok, so, again, can you point me to the PR that adds the brand to Home Assistant (please note, a brand and integration are not the same things in Home Assistant).
> 
> ../Frenck

like this,
image

image


This is the merged PR:
https://github.com/home-assistant/core/pull/100573

**Review by frenck — CHANGES_REQUESTED** [review]
> This is the merged PR:
> #4525

That is adding the branding assets. Please link the core PR that adds the branding in Home Assistant Core.

Please note (again) an integration != a brand in Home Assistant. A brand is a concept that can bundle multiple integration from a single brand in Core.

../Frenck

**Comment by ashionky** [comment]
> > This is the merged PR:
> > #4525
> 
> That is adding the branding assets. Please link the core PR that adds the branding in Home Assistant Core.
> 
> Please note (again) an integration != a brand in Home Assistant. A brand is a concept that can bundle multiple integration from a single brand in Core.
> 
> ../Frenck

In the core, I found the brand. Does it require two integrations to set up the brand?

**Comment by frenck** [comment]
> In the core, I found the brand.

I have not... hence me asking multiple times now to send me a link to the pull request that adds the brand to the core. Could you please provide me a link to a PR handling this?

> Does it require two integrations to set up the brand?

There is no reason to add a layer to handle multiple integrations for a brand that has a single integration.

../Frenck

**Comment by frenck** [comment]
Alright, as there is still no pointer on where this is being added to core, core currently doesn't have a brand for this either...

I'll go ahead and close this PR.

../Frenck

**Pull request closed without merging**
