### PR TITLE
add new icons for custom_integration melzone_building

### PR DESCRIPTION
**Pull request by comtef**
## Proposed change

Add icon/logo for custom integration melzone_building: https://github.com/comtef/melzone-building

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks, @comtef 👍 

It seems the provided branding for the logos are not a brand image, but a product logo? Could you please swap those out for the general manufacturer branding?

Thanks! 👍 

../Frenck

**Comment by comtef** [comment]
> Thanks, @comtef 👍
> 
> It seems the provided branding for the logos are not a brand image, but a product logo? Could you please swap those out for the general manufacturer branding?
> 
> Thanks! 👍
> 
> ../Frenck

Hi @frenck 
Thanks for the review.
Do you mean changing the two logo.png images for a more general Mitsubishi logo? Something like https://fr.wikipedia.org/wiki/Fichier:Mitsubishi_Electric_logo.png ?

**Comment by frenck** [comment]
@comtef Yes, exactly 👍

**Comment by comtef** [comment]
Ok, I updated the logos.

**Review by comtef — COMMENTED** [review]
Logos updated

**Review by frenck — APPROVED** [review]
Thanks, @comtef 👍 

../Frenck

**Pull request merged**
