### PR TITLE
Images for new name day integration

### PR DESCRIPTION
**Pull request by viktak**
## Proposed change

New images for my new `name day` integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: https://github.com/viktak/abalin_nameday

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. Please git rebase your PR.

**Comment by viktak** [comment]
> 
> 
> There are unrelated commits in this PR. Please git rebase your PR.

Absolutely! I noticed that for some reason some of the old images also made it to this PR, but I couldn't remove them. How do I do that?

**Comment by frenck** [comment]
Here is some basic information:
- <https://developers.home-assistant.io/docs/development_catching_up>
- <https://www.freecodecamp.org/news/an-introduction-to-git-merge-and-rebase-what-they-are-and-how-to-use-them-131b863785f/#git-rebase>

For future PRs, make sure you create a new branch for each thing you do (I see you are still on master in your fork).

**Comment by viktak** [comment]
I went through the steps outlined on this page you suggested: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
All went smoothly, without an error. However, I don't see anything changed on github...
Is there a way to simply remove this PR altogether and start it over?

**Comment by frenck** [comment]
> Is there a way to simply remove this PR altogether and start it over?

uh, yes, close the PR and restart? :)

**Comment by viktak** [comment]
> 
> 
> > Is there a way to simply remove this PR altogether and start it over?
> 
> uh, yes, close the PR and restart? :)

:) :) :) OK, thanks!!!

**Pull request closed without merging**
