### PR TITLE
Added icon and logo for the Philips Pet Series custom integration

### PR DESCRIPTION
**Pull request by AboveColin**
## Proposed change

This will add images for the Philips Pet Series, A smart cat / dog feeder by Philips.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes N/A
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/AboveColin/HA-Philips-Pet-Series/
## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by AboveColin** [comment]
Hey @frenck!, if there is something that needs to be changed before the merge, please let me know and i'll adjust accordingly 😁

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @AboveColin 👋 

It seems like you've used an application or app graphic to represent the Philips brand in the provided icon assets. However, we collect brand images in this repository (hence the name 😄).

Please replace the icons with the Philips branding.

../Frenck

**Comment by AboveColin** [comment]
> Hi there @AboveColin 👋
> 
> It seems like you've used an application or app graphic to represent the Philips brand in the provided icon assets. However, we collect brand images in this repository (hence the name 😄).
> 
> Please replace the icons with the Philips branding.
> 
> ../Frenck

Good morning!

I probably didn't understand you correctly, but these are the icons from the Philips Pet Series app, they are Philips branded then right? Or am I missing something? 😅 
https://play.google.com/store/apps/details?id=com.versuni.nbx.petsseries&hl=nl

**Comment by frenck** [comment]
This repo doesn't collect application icons, but manufacturer branding.

../Frenck

**Comment by AboveColin** [comment]
> This repo doesn't collect application icons, but manufacturer branding.
> 
> ../Frenck

Thanks for the quick reply, are these more in line? 😁

**Review by frenck — APPROVED** [review]
Thanks, @AboveColin 👍 

../Frenck

**Pull request merged**
