### PR TITLE
Add toggl_track

### PR DESCRIPTION
**Pull request by kquinsland**
## Proposed change

This is logo/icon for a custom component i'm working on / wrapping up.
The company provides a [press kit](https://toggl.com/track/media-toolkit/) which includes `svg` which I scaled, converted and then crushed.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by kquinsland** [comment]
Accidentally had `logo.svg`, that's now removed.
Other validation warnings are related to files that are already in the repo :(

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @kquinsland 👋 

I could not find the public repository providing this custom integration. Could you point me to it?

Thanks! 👍 

../Frenck

**Comment by kquinsland** [comment]
> Hi there @kquinsland 👋
> 
> I could not find the public repository providing this custom integration. Could you point me to it?

Sure thing. It's now public, lives here: https://github.com/kquinsland/ha-toggl-track

I was hoping to release yesterday but got hit with pydantic v2 / https://github.com/home-assistant/core/issues/99218.

**Comment by frenck** [comment]
> Sure thing. It's now public, lives here: [kquinsland/ha-toggl-track](https://github.com/kquinsland/ha-toggl-track)

That link doesn't work.

**Comment by kquinsland** [comment]
> > Sure thing. It's now public, lives here: [kquinsland/ha-toggl-track](https://github.com/kquinsland/ha-toggl-track)
> 
> That link doesn't work.

Give it a try now :).  Github now makes you triple confirm you want to make a repo public

**Review by frenck — APPROVED** [review]
Thanks, @kquinsland 👍 

../Frenck

**Comment by kquinsland** [comment]
> Thanks, @kquinsland 👍

Just for my curiosity, can you explain why custom components need to use icons on the  CDN?

I think this pattern is 100% the right move for official/core integrations but  was wondering why custom components cant serve icons out of their root directory.

I [didn't find any explicit rationale](https://github.com/search?q=repo%3Ahome-assistant%2Farchitecture+icon&type=issues) and was just curious if there was a reason beyond "writing two code paths for fetching images is just not something we want to spend time on".

Anyways, thanks and happy new year! (Looking forward to the 24.01 release :D)

**Comment by frenck** [comment]
> Just for my curiosity, can you explain why custom components need to use icons on the CDN?

There are multiple reasons. For example:

- It gives us a small piece of control in upstream branding (and ensures we don't violate any branding).
- We will be able to handle requests from brands that don't want us to use their brand
- We can have a small peek into the custom integration upstream (we often catch dependency issues, domain issues, and other common problems).
- We use this as a list of known/common domains for:
  - Analytics data (opt-in only)
  - Signal domain collisions

There have been multiple ideas on how to handle branding, including shipping them with core (increases distribution size drastically), publishing an add-on that pulls them locally, caching them locally, and... many others.

Up until this time, no concrete plans, architectural proposals, or suggestions of contributions to any of them have been made. 🤷 

../Frenck

**Pull request merged**
