### PR TITLE
Remove Somfy brand

### PR DESCRIPTION
**Pull request by tetienne**
## Proposed change

The Somfy integration will be removed with the next HA release. The associated brand must be removed.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/73527
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/23111
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by MartinHjelmare — COMMENTED** [review]
Are we going to add somfy as a supported brand to overkiz in the core project? If that's the plan we may want to keep the somfy resources here.

**Comment by tetienne** [comment]
@MartinHjelmare That’s indeed the case, Overkiz component supports all the devices supported by the Somfy integrations. So we should keep this brand here?

**Comment by MartinHjelmare** [comment]
I think we should keep somfy here, yes. @frenck can confirm.

**Comment by frenck** [comment]
Is there a PR that adds the supported brand?

**Comment by frenck** [comment]
Can be closed, see: <https://github.com/home-assistant/core/pull/73786>

**Pull request closed without merging**
