### PR TITLE
Add Thermal Vision integration

### PR DESCRIPTION
**Pull request by TheRealWaldo**
## Proposed change

I want to add my custom integration to HACS.  First-time contributor!

Relates to https://github.com/TheRealWaldo/thermal/issues/23

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

Added https://github.com/home-assistant/wheels-custom-integrations/pull/446

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
Shouldn't this get the Panasonic branding?

**Comment by TheRealWaldo** [comment]
@frenck Panasonic manufactures one version of a component that can be used to build a sensor this works with.   It's just one component.  To brand this as Panasonic would be about the same as putting the Intel logo instead of an Apple logo on Mac OS X because the hardware could have an Intel chip inside.  

You cannot buy a device that the integration works with from Panasonic.  Essentially it's a DIY project using what will be open source hardware.  You can use this with other, non Panasonic components as well.  It's just one of the most popular.

I will be adding more details on how to build the actual sensor this works with in a different repo and linking that it the documentation so that it's more clear.

**Comment by frenck** [comment]
Sure, but we slap the Bosch logos on the BME sensors as well 🤷

**Comment by TheRealWaldo** [comment]
@frenck I'm not sure what the standard would be here...

As I understand it, the BME Integration is designed purely to connect to a BME sensor via I2C directly...  This integration wouldn't work in the same manner (although you inspired me to add another option for Raspberry Pi users).

This integration can also use the Omron component, or the Melexis, and others.  It communicates with an HTTP-based API server on DIY-built hardware with custom firmware.

**Comment by TheRealWaldo** [comment]
I guess we need to think about it as a camera integration... It can connect to many different kinds of cameras, of different brands.  It's just that this one is specific to thermal imaging rather than the visible light spectrum.

**Comment by frenck** [comment]
> I guess we need to think about it as a camera integration

I don't think that flies, but ok.

**Comment by TheRealWaldo** [comment]
@frenck could just be a difference in how it is now vs. the direction it is going.  But happy to amend or correct as you see fit!  Is it possible to add multiple brand logos to a single integration?

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
For a core integration, this would not have been accepted.
This repository collected brands (hence the name).

**Comment by TheRealWaldo** [comment]
@frenck I think I might see what you're getting at.  Ideally, HA integrations are specific to a single product?   As in, creating a generic integration (like the generic camera https://www.home-assistant.io/integrations/generic/) is discouraged?

I'm really only adding the logo here as it's a requirement to get into HACS; still learning the ropes so your time is much appreciated!

**Comment by frenck** [comment]
Camera is an internal integration; which is a different class of integration (it is an entity component).

**Comment by TheRealWaldo** [comment]
@frenck perhaps more analogous to My Sensors integration and project then (https://www.home-assistant.io/integrations/mysensors/) where I am building and open-sourcing a DIY sensor platform specifically for thermal imaging.

**Pull request merged**
