### PR TITLE
Add Touchline SL icons

### PR DESCRIPTION
**Pull request by jnsgruk**
## Proposed change

Add icons for Roth Touchline SL integration proposed in Home Assistant Core

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/124557
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/34441
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by jnsgruk** [comment]
Updated to add icons for a new "Roth" brand, which is added in the parent PR.

**Review by joostlek — DISMISSED** [review]
The icons for `touchline` are the same. Please keep the brand images in `core_brands` and then use symlinks to link both `touchline` and `toucline_sl` to the brands. `switchbot` is a good example for this

**Comment by jnsgruk** [comment]
> The icons for `touchline` are the same. Please keep the brand images in `core_brands` and then use symlinks to link both `touchline` and `toucline_sl` to the brands. `switchbot` is a good example for this

Done!

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @jnsgruk :+1:

**Pull request merged**
