### PR TITLE
Alot of Dark Mode Icon Changes & Icon Improvements

### PR DESCRIPTION
**Pull request by MapGuy11**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: There is many sorry :)

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This changeset is too large to handle and, therefore, impossible to review properly. Please split this into multiple smaller PRs.

Thanks 👍 

../Frenck

**Comment by MapGuy11** [comment]
> This changeset is too large to handle and, therefore, impossible to review properly. Please split this into multiple smaller PRs.
> 
> Thanks 👍
> 
> ../Frenck

No Problem will do!

**Comment by MapGuy11** [comment]
The PR is now split: #3991 #3992 #3993 #3994

**Comment by MapGuy11** [comment]
@frenck If there is anything you need done to get this pushed through please let me know. Thank You all again for this amazing project and I hope you all like the new icons!

**Comment by frenck** [comment]
Going to close this PR, as is has been split into multiple smaller ones.

../Frenck

**Pull request closed without merging**
