### PR TITLE
Add icons to AiDot domain

### PR DESCRIPTION
**Pull request by s1eedz**
## Proposed change

Add icons to Aidot domain

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/117337
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/32704
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
Please explain why you did close the previous PR and created this one.

You seem to have the habit of doing that on all our repositories (closing PRs, re-creating them). Please stop doing that. Open a PR and just keep working on that PR instead.

../Frenck

**Comment by s1eedz** [comment]
> Please explain why you did close the previous PR and created this one.
> 
> You seem to have the habit of doing that on all our repositories (closing PRs, re-creating them). Please stop doing that. Open a PR and just keep working on that PR instead.
> 
> ../Frenck

I changed the branch name. I didn't know it would close the PR. This was a mistake. I'm very sorry. I won't make this mistake again.

**Comment by s1eedz** [comment]
I have a bit of obsessive-compulsive disorder, so I changed the branch names of the three warehouse brands and core and io to be consistent. This is why I want to change the branch names. @frenck

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request closed without merging**
