### PR TITLE
Add Sonos brand

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
## Proposed change

Adds Sonos to brands and symlinks the integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/80293
- Link to documentation pull request: 
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/sonos/

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
I haven't really used symlinks before so I'm not sure why it's failing. Any insight into the issue would be appreciated.

**Comment by mvdwetering** [comment]
It looks like you created a textfile in the `sonos` directory with  the content `../core_brands/sonos` instead of a link.

The directory `brands/core_intergrations/sonos` needs to be deleted.
Then you can replace the deleted directory with a symlink.

Executing `ln -s ../core_brands/sonos sonos` while in the `/brands/core_integrations` directory seems to work (at least when running `ls -al` it show the link the same as for others).

**Comment by VIKTORVAV99** [comment]
> It looks like you created a textfile in the `sonos` directory with  the content `../core_brands/sonos` instead of a link.
> 
> The directory `brands/core_intergrations/sonos` needs to be deleted.
> Then you can replace the deleted directory with a symlink to the new brands directory.
> 
> Executing `ln -s ../core_brands/sonos sonos` while in the `/brands/core_integrations` directory seems to work (at least when running `ls -al` it show the link the same as for others).
> 

Thanks! I'll try it later today! 👍🏻

**Comment by frenck** [comment]
Closing this PR as the parent PR has been closed.

**Pull request closed without merging**
