### PR TITLE
Add xbee_humidifier custom integration icon

### PR DESCRIPTION
**Pull request by Shulyaka**
## Proposed change

This is an icon for my own custom integration (https://github.com/Shulyaka/xbee_humidifier) that will unlikely be used by anyone but me. However I haven't found another way to add a logo to it except adding it here. If there is another (local) way, please let me know.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This looks like custom made / modified version of the Home Assistant logo?

We won't be able to accept that. Thanks for understanding.

../Frenck

**Comment by Shulyaka** [comment]
Based on it, yes, but with enough distinction.
Do you have, like, list of rules, what is accepted and what is not?

**Comment by frenck** [comment]
> Do you have, like, list of rules, what is accepted and what is not?

No, not really. We collect brand images in this repository; We can't set requirements on upstream branding. We only set requirements on sizes and file formats.

That said, we don't allow modified brand images to be used. This is simply because that will violate brand guidelines in almost all cases. As for the Home Assistant identity/branding, we don't allow them to be used by custom integrations. This is primarily to prevent people from seeing those as official (while the fact is, we don't support custom integrations).

Lastly, the provided brand images must either match the device or service the integration integrates with or in case it doesn't integrate with a device or service, other creations are allowed.

../Frenck

**Comment by Shulyaka** [comment]
Thank you Frenck, it is much clearer now! I will make changes so that it won't be confused as official.

**Comment by Shulyaka** [comment]
Thank you Frenck, it is much clearer now! I will make changes so that it won't be confused as official.

**Comment by Shulyaka** [comment]
I've made some changes, hope it is good enough now. If not, please let me know, I am ready to make further changes.

**Review by frenck — APPROVED** [review]

**Pull request merged**
