### PR TITLE
Add brand for Wevolor controller for Levolor blinds

### PR DESCRIPTION
**Pull request by timstallmann**
## Proposed change
Add logo and icon for Levolor so that a custom component to control Levolor blinds via the Wevolor arduino controller can be created.

I'm working on adding the code for the custom component to HACS.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to code base pull request: https://github.com/home-assistant/core/pull/63087
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/20950
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @timstallmann, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3036).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
I cannot find the custom integration, can you point me to the public GitHub repository providing it?

**Comment by timstallmann** [comment]
@frenck -- here's the integration PR https://github.com/home-assistant/core/pull/63087

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by timstallmann** [comment]
The core integration PR has been stalled for months, so I'm just going to publish this as a custom integration instead.. modified PR accordingly.

**Review by frenck — APPROVED** [review]

**Pull request merged**
