### PR TITLE
Added powerx brand icon

### PR DESCRIPTION
**Pull request by powerxadmin**
## Proposed change
Want to add icons for a new integration with domain name powerx.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR adds brand images for a new core integration, however, I cannot find a PR in our core repository adding this integration.

Could you please point me to it?

**Comment by powerxadmin** [comment]
Hello @frenck , yes presently it is not in the core branch but we are in the development face of it. So want to test it with the real icon.

**Comment by frenck** [comment]
That won't work, as we won't merge this PR before the code has been accepted to the core repository.

**Comment by frenck** [comment]
19 days later, at this point, this PR is still missing its parent PR.
Closing this PR for now. Feel free to re-open when the parent PR in the core codebase is created.

Thanks! 👍

**Pull request closed without merging**
