### PR TITLE
Added SMA Manager Icons

### PR DESCRIPTION
**Pull request by DEADSEC-SECURITY**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/94618
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/26464
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Review by frenck — CHANGES_REQUESTED** [review]
We already have these assets in our repository, maybe instead it should be symlinked to the existing ones?

**Comment by DEADSEC-SECURITY** [comment]
> We already have these assets in our repository, maybe instead it should be symlinked to the existing ones?

Could you elaborate on how I could achieve this?

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
