### PR TITLE
Add tplink_tapo to core_integrations

### PR DESCRIPTION
**Pull request by rytilahti**
## Proposed change

Copy `custom_integrations/tapo/` to `core_integrations/tplink_tapo` for a virtual integration.

Parent PR for adding the virtual integration:
https://github.com/home-assistant/core/pull/109765

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by bdraco — APPROVED** [review]

**Review by davet2001 — DISMISSED** [review]
Thanks @rytilahti for adding the branding!
These logos look a bit janky, i.e. they look as though they've been some lossy compression, also, the 'tapo' logo provided has square edges, but the newest version on the TP link website has rounded edges and a slightly different color.
image

Are there any better images available?

**Review by bdraco — APPROVED** [review]

**Review by bdraco — APPROVED** [review]

**Review by sdb9696 — APPROVED** [review]
LGTM

**Review by frenck — APPROVED** [review]
Thanks!

**Comment by rytilahti** [comment]
Ah, thanks for taking care of that :+1: Yes, the icons were not the best, I simply copied them over from the custom_components. Maybe we should sync also the new icons there? `tapo` and `tapo_controller` are the integrations that were using the icons I initially uploaded.

**Comment by bdraco** [comment]
> Ah, thanks for taking care of that 👍 Yes, the icons were not the best, I simply copied them over from the custom_components. Maybe we should sync also the new icons there? `tapo` and `tapo_controller` are the integrations that were using the icons I initially uploaded.

I think you could open a PR to symlink to the core integration one now that this is merged

**Comment by bdraco** [comment]
> Symlinks are currently not allowed in the custom integrations folder.


I guess you'll have to copy them for now

**Pull request merged**
