### PR TITLE
Add icons for NEXHome integration

### PR DESCRIPTION
**Pull request by linzh322**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/nexhome-org/nexhome-homeassistant-component

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons and the logos are the same. Please either:

- Drop the logo version (we will automatically fall back to the icon version for the logo)
- Adjust the logo version to just have the logo (remove the transparent space above/below of the actual logo, trim it).

../Frenck

**Review by linzh322 — COMMENTED** [review]
I want to use the same icon, I have removed the logo icon，thank you！

**Review by frenck — CHANGES_REQUESTED** [review]
Looked upstream, the domain used by this integration is invalid:

CleanShot 2024-05-22 at 08 23 01@2x

Ref: <https://github.com/nexhome-org/nexhome-homeassistant-component/blob/ed1e684973a62cd1fa79054f14a025c6b1055b63/custom_components/nexhome/manifest.json#L2>

The domain of an integration cannot contain capital letters.

../Frenck

**Comment by linzh322** [comment]
Yes you are right, I have modified my domain

**Review by frenck — APPROVED** [review]
Thanks, @linzh322 👍 

../Frenck

**Pull request merged**
