### PR TITLE
Add NOIP.com logos and icons

### LINKED ISSUE #483: No-IP.com is missing brand images
## The problem

The No-IP.com integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/no_ip/icon.png`
- `src/no_ip/logo.png`
- `src/no_ip/icon@2x.png`
- `src/no_ip/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: noip.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/no_ip.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @fabaff! Mind taking a look at this issue as it is with an integration (no_ip) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/no_ip/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

### PR DESCRIPTION
**Pull request by BradleyFord**
## Proposed change
Add NOIP.com logos and icons

Logo does not have transparent background...

## Type of change
- [ ] Add a new logo or icon for a new integration
- [x ] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information
- This PR fixes or closes issue: fixes #483
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist
- [x ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by adrianmihalko** [comment]
@BradleyFord the hiDpi version is not just a resized version of 256px (or similar), right? It's pretty blurry and it looks like an upscaled version. Fix me if I am wrong.

The biggest version (409px in height) I've found is:

https://i0.wp.com/www.linuxwebzone.com/wp-content/uploads/2015/03/NoIP.jpg?fit=979%2C409&ssl=1

If we can't find better version of a logo, it's ok to send for logo@2x.png images >=256px, <=512px, in this case the 409px version.

**Comment by BradleyFord** [comment]
Adrian,
Yeah that is the same version that I had for the logo

Not many options available for this one. Let me submit with the 409px, and no transparency.

This exercise going through the logos has really shown how most companies really do not like sharing high def or PNG/SVG versions...

**Comment by adrianmihalko** [comment]
Hi Brad,

let's stick to the max. version available, do not upscale the low-res version in any case. It looks blurry and it doesn't look good, specially on retina displays. If you can't find any better version, you have three choices:

1. Ask the company for a better version. It works 3/5 time in my experience.
2. Try to vectorise the logo. Not all logo can be easily vectorised.
3. Post the max. version what is available. 

🤘

**Comment by BradleyFord** [comment]
Yes, that is obvious. Most of the time I have been taking the vector path; a few times today I needed to grab the EPS and then convert to what I needed.

**Pull request merged**
