### PR TITLE
Add images for Leviosa Motorized Shades

### PR DESCRIPTION
**Pull request by altersis**
## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes # This is a new integration
- Link to code base pull request:  https://github.com/home-assistant/core/pull/48048
- Link to documentation pull request:  Will be entered in a couple of hours
- Link to integration documentation on our website:  https://www.home-assistant.io/integrations/leviosa_shades Not currently working, as the PR to incorporate the docs and logos is pending

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR adds brand images for a core integration I cannot find.
Is there a parent PR that adds this integration to our core codebase?

**Comment by altersis** [comment]
Hi, yes, there will be in a couple of hours. I'm close to creating a PR for the Leviosa Shades integration code and one for the Documentation. Should I create those PRs first, then update this one? I thought the images had to be done first, as the other two need the images to be in place to display properly, right?

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
