### PR TITLE
Adding images for openweathermap_all

### PR DESCRIPTION
**Pull request by viktak**
## Proposed change

I created a new integration and it needs an icon (as far as I understand - this is my first contribution to HA).

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
I'm not sure what these are, sorry. This is the actual component: https://github.com/viktak/ha-cc-openweathermap_all
Let me know if you need anything else.

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)
I have no `logo@2x.png`.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The brand in this case, is openweathermap. The icons provided do not belong to that brand.

**Comment by viktak** [comment]
Just replaced the 2 icons with the official ones.

**Review by frenck — CHANGES_REQUESTED** [review]
The 2x version looks blown up. See:

image


Either provide an icon that has the native resolution or omit it.

**Comment by viktak** [comment]
Sorry about that. Corrected, now using the same images as the core_integrations

**Review by frenck — APPROVED** [review]
Thanks, @viktak 👍

**Pull request merged**
