### PR TITLE
honda_recall_check integration new brand

### PR DESCRIPTION
**Pull request by Danieldiazi**
## Proposed change

Add honda_recall_check integration brand

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request:  https://github.com/Danieldiazi/honda_recall_check
- Link to integration documentation on our website:  https://github.com/Danieldiazi/honda_recall_check
- Link to custom integration repository: https://github.com/Danieldiazi/honda_recall_check

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This integration integrates with Honda, for that reason, I would have expected the branding of Honda to be used.

../Frenck

**Review by Danieldiazi — COMMENTED** [review]
Logos changed

**Comment by Danieldiazi** [comment]
> This integration integrates with Honda, for that reason, I would have expected the branding of Honda to be used.
> 
> ../Frenck

I thought that if I used Honda's official images, there might be copyright issues if I used them for an integration they did not create. 

I've changed the files with the branding of Honda. Sorry!

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks, @Danieldiazi for the update.

However, the logo now contains a modified brand image of the upstream manufacturer, which most often conflicts with branding guidelines. For that reason, we cannot accept those images.

Please replace the logo with the original brand images from the manufacturer.

../Frenck

**Comment by Danieldiazi** [comment]
> Thanks, @Danieldiazi for the update.
> 
> However, the logo now contains a modified brand image of the upstream manufacturer, which most often conflicts with branding guidelines. For that reason, we cannot accept those images.
> 
> Please replace the logo with the original brand images from the manufacturer.
> 
> ../Frenck

Sorry, I've replaced logo files!

**Pull request merged**
