### PR TITLE
Add icons for devolo_home_network

### PR DESCRIPTION
**Pull request by Shutgun**
## Proposed change

Add devolo home network integration assets.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/45866
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/16389
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
These are 2 different icons.
They should be the same, only one bigger than the other.

**Comment by Shutgun** [comment]
@frenck , for me that is the same icon, just differing in resolution. Blue background, devolo at the bottom, wifi waves in the middle. Or am I missing something?

**Comment by frenck** [comment]
One is transparent, the other isn't.

**Comment by Shutgun** [comment]
Nice catch. Could see that in the browser's preview because of white default background.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
