### PR TITLE
Added icon for came_domotic custom integration

### PR DESCRIPTION
**Pull request by fredericks1982**
## Proposed change

Added icon for the new CAME Domotic (`came_domotic`) custom integration. 

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
Hi there @fredericks1982 👋 

This PR is now in draft for two weeks. Do you have plans to move it forward?

../Frenck

**Comment by camedomotic-unofficial** [comment]
Hi, I'm still developing a new custom integration, hoped to close it earlier but I think it'll take at least 2 more weeks... Feel free to clean up if you want: eventually, I'll repost the request when ready.

**Comment by fredericks1982** [comment]
Hi, I'm still developing a new custom integration, hoped to close it earlier but I think it'll take at least 2 more weeks... Feel free to clean up if you want: eventually, I'll repost the request when ready.

**Comment by frenck** [comment]
> Hi, I'm still developing a new custom integration, hoped to close it earlier but I think it'll take at least 2 more weeks

Aah check! Makes sense. I'll go ahead and close this PR for now, as it isn't actionable.
Feel free to re-open when it is ready for review, happy to take a look at that point 👍 

../Frenck

**Pull request closed without merging**
