### PR TITLE
Add Mealie logo

### PR DESCRIPTION
**Pull request by joostlek**
## Proposed change

Add Mealie logo

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/119678
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/33264
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by frenck — APPROVED** [review]
Hmmm @joostlek, missed this one:

```
Error: The integration mealie exists in both core and custom integrations. Core wins.: custom_integrations/mealie
```

Could you take a look?

Thanks! 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
This time the correct button to use...

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by andrew-codechimp** [comment]
@joostlek @frenck 

Hi, I already have a custom integration with a domain called mealie, which has increased functionality (lists, images etc).
https://github.com/andrew-codechimp/HA-Mealie

With this move from custom to core for the brand icons my hacs validation is failing.  Can this brand icon not be duplicated?

**Comment by andrew-codechimp** [comment]
> > With this move from custom to core for the brand icons my hacs validation is failing
> 
> That is an issue you should raise at the HACS project.

So is this issue only with the HACS validation, my custom integration will still pick up the icon OK?

Are there any issued about discoverability when both custom and core have the same domain when users add an integration?

**Comment by frenck** [comment]
> my custom integration will still pick up the icon OK?

Yup.

> Are there any issues about discoverability when both custom and core have the same domain when users add an integration?

Custom integrations win (they are overrides of core).

**Comment by andrew-codechimp** [comment]
Thanks for the info both.
@joostlek I've friend requested you on discord to discuss further.

**Pull request merged**
