### PR TITLE
Remove peco brand images

### PR DESCRIPTION
**Pull request by b-uwe**
## Proposed change

Remove peco brand images because the brand requested the logo to be removed

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [x] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- This PR connects to https://github.com/home-assistant/home-assistant.io/pull/27514

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
Should we add/leave the folder with a text file or something with a note, to prevent it being added again?

**Comment by b-uwe** [comment]
> Should we add/leave the folder with a text file or something with a note, to prevent it being added again?

I explicitly named the reason for removing in the above description and hoped that would be sufficient! But yeah! Adding a small text file makes sense!

**Comment by frenck** [comment]
Yeah I understand, it is just to prevent someone coming along in a couple of month thinking: "Hey those are missing, let me add those..."

**Comment by b-uwe** [comment]
Done!

**Comment by b-uwe** [comment]
Validation fails now 🤦! Can we ignore this or do I need to adjust the filename or smth.?

**Review by frenck — APPROVED** [review]

**Review by IceBotYT — APPROVED** [review]
LGTM!

**Pull request merged**
