### PR TITLE
Adding Unifi Access logos

### PR DESCRIPTION
**Pull request by imhotep**
## Proposed change

Unifi released an Open API for their Access products a while back and I created a custom integration for it [here](https://github.com/imhotep/hass-unifi-access). It would be nice to have a logo for it.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons provided look like an icon from an app or something similar?

However, we collect branding in this repository. Please use the Ubiquiti instead.

Thanks! 👍 

../Frenck

**Comment by imhotep** [comment]
@frenck I saw other integrations created symbolic links. Let me know if this is acceptable.

**Review by frenck — CHANGES_REQUESTED** [review]
As per README instructions in this repository, the use of symlinks for custom integration isn't accepted.

../Frenck

**Comment by imhotep** [comment]
@frenck I removed the symlink and added the [ubiquiti logos](https://github.com/home-assistant/brands/tree/master/core_brands/ubiquiti) and maintained the app's icons. Unless wanted me to use the ubiquiti icons too?

**Review by frenck — CHANGES_REQUESTED** [review]
> and maintained the app's icons.

See my previous response: <https://github.com/home-assistant/brands/pull/4827#pullrequestreview-1704804231>

**Review by frenck — APPROVED** [review]
Thanks, @imhotep 👍 

../Frenck

**Pull request merged**
