### PR TITLE
govee integration

### PR DESCRIPTION
**Pull request by LaggAt**
## Proposed change
adding logo and icons for a new govee integration I currently develop
https://github.com/LaggAt/home-assistant-core/tree/feature/govee-led-strips
https://community.home-assistant.io/t/govee-led-strips-integration/228516

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

I asked for the use of the logo for integration and library i code, api-support@govee.com answered on 15.09.2020:

As for your request, I would like to say that you can use the " Govee " logo for home assistant and/or on the github project page.

However, please kindly note the below terms of the usage of our Govee logo.

Govee and the Govee logo are trademarks or registered trademarks of Shenzhen Intellirock Company Limited, and used by Govee with permission. Neither your use of the Govee Logo grant you any right, title, or interest in, or any license to reproduce or otherwise use, the Govee logo. You shall not at any time, nor shall you assist others to, challenge Govee's right, title, or interest in, or the validity of, the Govee Marks.

We can take back the usage of the Govee logo when we find that there is anything illegal with the usage of the Govee logo.

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/40476
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/14593
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Looking at their apps and social media's, it seems that they are using a different assets for their icon.

For example: <https://apps.apple.com/nl/app/govee-home/id1395696823>

Could you please correct the PR so we respect the brand styling?

**Comment by LaggAt** [comment]
Hi and thank you. I changed the icons.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
