### PR TITLE
Add mobilevikings_pl logo

### PR DESCRIPTION
**Pull request by TheLastGimbus**
## Proposed change

Add logo for mobilevikings_pl integration

## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to code base pull request: https://github.com/home-assistant/core/pull/41146
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/14838

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Looks like their logo is available as SVG:

<https://static.mobilevikings.pl/homepage_dark/assets/logo-big.svg>

So, that would make it possible to have logo files in both 1x and 2x sizes.
Could you add those?

**Comment by TheLastGimbus** [comment]
Yes I can :)

(Btw, I mentioned someone in commit message by accident :laughing: )

**Review by frenck — CHANGES_REQUESTED** [review]
These logos are white with a transparent background, and thus will cause issues on our default layout.

**Comment by TheLastGimbus** [comment]
For now, this integration can't be mereged to core, because it uses web scraping, so I think we can close this

**Pull request closed without merging**
