### PR TITLE
Add 3 custom integrations folders with respective info.md's & icons

### PR DESCRIPTION
**Pull request by mkanet**
## Proposed change

This PR introduces new icons and `info.md` files for two custom integrations: Radarr Upcoming Media and Sonarr Upcoming Media. Additionally, it adds an `info.md` file for the existing Plex Recently Added integration to enhance its documentation.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR adds or updates files for the following custom integrations:
  - **Radarr Upcoming Media**: Added `icon.png`, `icon@2x.png`, and `info.md`.
  - **Sonarr Upcoming Media**: Added `icon.png`, `icon@2x.png`, and `info.md`.
  - **Plex Recently Added**: Only `info.md` was added; the folder and icons already existed.

The addition of these files aims to improve the visibility and documentation of these integrations within the Home Assistant ecosystem.

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by mkanet** [comment]
I've verified the color space of the PNG images using ImageMagick, and they are all in the correct sRGB format. Here are the findings:

- `radarr_upcoming_media/icon.png`: sRGB
- `radarr_upcoming_media/icon@2x.png`: sRGB
- `sonarr_upcoming_media/icon.png`: sRGB
- `sonarr_upcoming_media/icon@2x.png`: sRGB

This confirms that the images meet the project's requirements for color space. Please let me know if there are any other changes needed. Thank you for your time and review.

**Comment by mkanet** [comment]
I've verified the color space of the PNG images using ImageMagick, and they are all in the correct sRGB format. Here are the findings:

- `radarr_upcoming_media/icon.png`: sRGB
- `radarr_upcoming_media/icon@2x.png`: sRGB
- `sonarr_upcoming_media/icon.png`: sRGB
- `sonarr_upcoming_media/icon@2x.png`: sRGB

This confirms that the images meet the project's requirements for color space. Please let me know if there are any other changes needed. Thank you for your time and review.

**Review by frenck — CHANGES_REQUESTED** [review]
There are CI errors, please take a look.

Additionally, each PR should only handle a single integration at the time. So, this PR should be split into at least two new PRs.

../Frenck

**Comment by mkanet** [comment]
Please forgive me.  This is my first PR ever.  Is there any specific actions needed for me to do currently?

**Comment by frenck** [comment]
> Please forgive me. This is my first PR ever. Is there any specific actions needed for me to do currently?

Yes, as I wrote in my previous reply. 

The CI is failing, you need to make sure it passes. Additionally, you need to split this PR into two separate PRs: each integration its own PR.

**Comment by mkanet** [comment]
> > Please forgive me. This is my first PR ever. Is there any specific actions needed for me to do currently?
> 
> Yes, as I wrote in my previous reply.
> 
> The CI is failing, you need to make sure it passes. Additionally, you need to split this PR into two separate PRs: each integration its own PR.

I will definitely split this into 2 separate PR's but I am not sure how to address the CI errors related to info.md being detected as an image file. I am not sure how to modify info.md so it isnt detected as an image.

**Comment by frenck** [comment]
>  I am not sure how to modify info.md so it isnt detected as an image.

They don't belong here. Remove them.

**Comment by mkanet** [comment]
Closing this PR.  I will do it correctly next time with 2 separate PRs and without `info.md`

**Pull request closed without merging**
