### PR TITLE
Added icons and logos for Bosch SHC integration.

### PR DESCRIPTION
**Pull request by tschamm**
## Proposed change

New integration which introduces support for devices managed by the Bosch Smart Home Controller system. PR for home-assistant.io doc and home-assistant core repos are in preparation.

## Type of change

- [x] Add a new logo or icon for a new integration
- [ ] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to code base pull request: https://github.com/home-assistant/core/pull/34063
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/12842

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by cogneato** [comment]
I see where the logo source comes from, but I'm thinking the logo should just be the Bosch medallion and name? Let's get a second opinion from @frenck 

logo

logo@2x

**Comment by frenck** [comment]
Yeah, I agree with you. We are looking for logo's, not product presentation images. 👍

**Comment by cogneato** [comment]
@tschamm Yes, the two files I provided are sized and ready to go if you want to add them

**Comment by adrianmihalko** [comment]
Guys, Bosch logo is already present as high quality transparent logo in bmp280. I suggest to remove this PR and open a new one by symlinking boschshc to bmp280.

Other Bosch devices are symlinked too: bme280/, bme680/  ---> bmp280/

**Comment by frenck** [comment]
Thanks, @adrianmihalko absolutely correct 👍

**Comment by tschamm** [comment]
Thanks, good point!
For the logo I agree, even if Bosch changed their logo 2019 to a flat design. The one used in bmp280 is the old one. I suggest I update the PR with a symlink to bmp280 logo, and add a separate PR for updating to the new Bosch logo.
For the icon of the integration I prefer to use the Bosch Smart Home icon I added in this PR.

**Comment by adrianmihalko** [comment]
> Thanks, good point!
> For the logo I agree, even if Bosch changed their logo 2019 to a flat design. The one used in bmp280 is the old one. I suggest I update the PR with a symlink to bmp280 logo, and add a separate PR for updating to the new Bosch logo.
> For the icon of the integration I prefer to use the Bosch Smart Home icon I added in this PR.

One more thing, logo is not high quality + has white space around it.

Please use this one, if you want flat logo:

https://worldvectorlogo.com/logo/bosch-logo-simple

Or classic:

https://worldvectorlogo.com/logo/bosch

**Review by frenck — DISMISSED** [review]
Thanks! 👍

**Comment by tschamm** [comment]
The upstream HACS default PR fails without this being merged. 
Link to HACS default PR: https://github.com/hacs/default/pull/792

**Comment by frenck** [comment]
@tschamm This one cannot be merged against a custom integration, as this PR add graphics for a core intrgation.

**Comment by tschamm** [comment]
You're totally right of course, I'm sorry. I'll add another PR for the custom integration.
I would like to leave this PR open, until the core integration is merged. It's still in review.

**Review by frenck — APPROVED** [review]

**Pull request merged**
