### PR TITLE
Add HomeWhiz logo

### PR DESCRIPTION
**Pull request by velijv**
## Proposed change

Add logo and icon for [HomeWhiz](https://github.com/rowysock/home-assistant-HomeWhiz)
Source: https://www.homewhiz.com/

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The domain doesn't match the domain in the custom integration.

https://github.com/rowysock/home-assistant-HomeWhiz/blob/f0e84164b14c0728f7d18f5566f09b8aad852a00/custom_components/HomeWhiz/manifest.json#L2

In this case, the custom integration is incorrect, as domains must be lower case.


../Frenck

**Comment by frenck** [comment]
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

**Comment by TechHummel** [comment]
Could this PR be reopened? I forked the project and [adjusted the domain](https://github.com/TechHummel/home-assistant-HomeWhiz/blob/main/custom_components/homewhiz/manifest.json). Thanks!

**Comment by velijv** [comment]
> Since there was no response at all, I'm declaring this PR stale and closing it. Feel free to re-open this PR when you feel like that is the appropriate thing to do.

I am assigned, but don't have rights to _reopen pull request_. Synced and now the branch is **Successfully fetched and merged from upstream home-assistant:master.**

**Review by frenck — APPROVED** [review]
Thanks, @velijv 👍

**Pull request merged**
