### PR TITLE
add icon of custom integration degree days

### PR DESCRIPTION
**Pull request by nelbs**
## Proposed change
add icon of custom integration [degree days](https://github.com/Ernst79/degree-days) to implement component in HACS 

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This custom integration is using HA brandin. <odified HA branding even and colors, which violates our branding guidelines on our logo usage.

We cannot accept this for that reason.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks, @nelbs 👍 

One final thing, it seems that the icons & logos are the same assets. In that case, the logo version can be omitted (we will automatically fall back onto the icon in that case). So, could you remove the logo version?

Thanks! 👍 

../Frenck

**Comment by nelbs** [comment]
Thanks @frenck  
I removed the logo version as requested.

**Review by frenck — APPROVED** [review]
Thanks, @nelbs 👍 

../Frenck

**Pull request merged**
