### PR TITLE
Add ManageMyHealth icons

### PR DESCRIPTION
**Pull request by codyc1515**
## Type of change
- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information
- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist
- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by gickowtf — APPROVED** [review]
Great!
Would love to get a review from you thanks

**Review by frenck — CHANGES_REQUESTED** [review]
There seems to be empty transparent space in the logo, should the login be trimmed down from the top & bottom?

../Frenck

**Comment by codyc1515** [comment]
I thought it had to be a square? If not, I can easily upload a smaller higher quality logo with no white space.

**Comment by frenck** [comment]
Icons, yes. Logos only have a short-side requirement, which is specified in the README of this repository.

../Frenck

**Review by codyc1515 — COMMENTED** [review]
Fixed. Sorry, I didn't see this first time.

**Review by frenck — APPROVED** [review]
Thanks, @codyc1515 👍 

../Frenck

**Pull request merged**
