### PR TITLE
Add epa_uvindex icon

### PR DESCRIPTION
**Pull request by davidn**
## Proposed change

Add a logo for the [epa_uvindex custom component](https://github.com/davidn/epa_uvindex).

This logo is created by me, based on [WHO INTERSUN programme graphics](https://www.who.int/publications/m/item/the-uv-index-sun-protection-table) that "can be downloaded and used free of charge".

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by davidn** [comment]
Switched to EPA logo. The "logo" uses the full EPA logo, the "icon" is just the graphic part, to allow it to be square.

**Comment by frenck** [comment]
@davidn This PR is currently still marked as draft. What is the state of it?

../Frenck

**Comment by davidn** [comment]
I switched logos as you requested, and it is ready for another round of review. Apologies for leaving status as draft, I'm but very familiar with GitHub pr tooling.

**Review by frenck — APPROVED** [review]
Thanks, @davidn 👍 

../Frenck

**Pull request merged**
