### PR TITLE
Add Overkiz brand for new core integration

### PR DESCRIPTION
**Pull request by iMicknl**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/62640
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/20841
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This replaced the old integration, right? Which needs to be cleaned up in that case as well?

**Comment by iMicknl** [comment]
> This replaced the old integration, right? Which needs to be cleaned up in that case as well?

You are right. I was thinking about moving `tahoma` to custom_integrations, since there is still `ha-tahoma` that is utilising the TaHoma domain. Would that make sense? Or should I remove it in this PR.

**Comment by frenck** [comment]
Adding a custom integration is a separate PR and not related to core changes.

**Comment by iMicknl** [comment]
> Adding a custom integration is a separate PR and not related to core changes.

Ok. I will remove `tahoma` in this PR, since that will be replaced by `overkiz`.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by iMicknl** [comment]
> ✅ Approved. Can be merged as soon as the parent PR gets merged.

Parent has been merged (#62640)

**Comment by frenck** [comment]
@iMicknl Not need to mention/ping that stuff. Thanks 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
