### PR TITLE
Add icons for Elasticsearch

### PR DESCRIPTION
**Pull request by legrego**
## Proposed change

Adds an icon for the Elasticsearch custom component hosted at https://github.com/legrego/homeassistant-elasticsearch.

I'm only providing the `icon` since both the logo and icon are square by design (as instructed in this repo's README)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations) (https://github.com/home-assistant/wheels-custom-integrations/pull/224)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logo is also available as SVG, can we add the logo format as well? That would make everything look even slicker in the UI 👍

**Comment by legrego** [comment]
> The logo is also available as SVG, can we add the logo format as well? That would make everything look even slicker in the UI

@frenck I'd be happy to! I didn't know that SVG was a format that this repo supported. Would you like me to update the README as well to indicate this?

**Comment by frenck** [comment]
It doesn't support SVG. It does however provide links to tools you could use.
That said, SVG's can be scaled and exported to an image at any size you need.

**Comment by legrego** [comment]
Sorry I misunderstood what you were asking at first. I'll add a dedicated logo in addition to the icon, using the SVG to export a properly scaled PNG 👍

**Review by frenck — CHANGES_REQUESTED** [review]
Did you add more icons? Please add logo versions, the icons were already covered 👍

**Comment by legrego** [comment]
@frenck sorry for the confusion - the SVG asset for Elasticsearch is square, so the icon and logo in this PR are effectively the same, so as to comply with the image requirements outlined in this repo's readme.

Am I misinterpreting the requirements? If the SVG is already square, and I'm supposed to honor the source aspect ratio, then I think I've added everything correctly.

I'm happy to make any necessary adjustments, but I'm struggling to understand the requirements. Thanks for your patience with this PR, I appreciate your feedback.

**Comment by frenck** [comment]
We have icons and logos. Icons are square, usually used on social media and such. Logos are full-blown.

The icon is fine, this is the logo of elastic search:

<https://commons.wikimedia.org/wiki/File:Elasticsearch_logo.svg>

My suggest was to add that.

**Comment by legrego** [comment]
Ah - the branding guide I had [originally pulled from](https://brand.elastic.co/302f66895/p/41ff52-solution-logos/b/14d954) did not offer such assets. I was able to find another one (still from Elastic) which does offer one, so I'll use that to create the logo.

**Comment by legrego** [comment]
@frenck thanks for the feedback. I added real logos in [`66601e7` (#2132)](https://github.com/home-assistant/brands/pull/2132/commits/66601e7b8a36c0e934e55c65599c5507e11784ac)

**Review by frenck — APPROVED** [review]
Thanks, @legrego 👍

**Pull request merged**
