### PR TITLE
Rename kingspan_connect to kingspan_watchman_sensit

### PR DESCRIPTION
**Pull request by masaccio**
## Proposed change

I have renamed my custom integration as part of the development and am not ready to deploy with the new name. The previous icons were never used by an integration that was included in HACS so should simply be deleted as per this PR.

The new name is in line with the branding used by the manufacturer of the device.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR suggests a rename, but instead, adds new icons.
Should the old folder be removed?

**Comment by masaccio** [comment]
PR adds new icons in one folder and deletes the old folder.

**Comment by masaccio** [comment]
Looks like I might have created the PR and then removed the files afterwards. My git knowledge is failing me now - my fork has these removed but I don't know, but I don't know how to update the PR with the changes I've made.

**Review by frenck — APPROVED** [review]
It now is correct @masaccio. Thanks 👍 

../Frenck

**Pull request merged**
