### PR TITLE
Updated Microsoft Teams logo & icon

### PR DESCRIPTION
**Pull request by loryanstrant**
## Proposed change

An update of the existing Microsoft Teams logo & icon used on the HA website.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logo version has logs of empty transparent padding above and below the actual image contents. Can we trim that?

CleanShot 2022-11-23 at 10 07 59

../Frenck

**Comment by loryanstrant** [comment]
Technically, there is no actual Microsoft Teams logo that has the name "Microsoft Teams" in it.
Microsoft official use of logos these days is (when they follow their own rules) just the icon.
So in theory for this PR, we should actually just remove the logo files and only have the icon file - I just wasn't sure what to do there.

**Comment by frenck** [comment]
Right but that doesn't address the review comment? 🤷

**Comment by loryanstrant** [comment]
Have trimmed the empty space out

**Review by frenck — APPROVED** [review]
Thanks, @loryanstrant 👍

**Pull request merged**
