### PR TITLE
Add Huawei Solar Energy Management icons

### PR DESCRIPTION
**Pull request by woopstar**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes https://github.com/woopstar/hsem/issues/1
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/woopstar/hsem

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is a custom branding, while this integration integrates with device of Huawai. We therefore expect this to carry the Huawai branding as we don't want to misrepresent a brand.

../Frenck

**Comment by woopstar** [comment]
Also for a custom integration ?

This is not official from Huawei. But just a energy management system that integrates with Huawei Solar provided by another custom integration.

**Comment by frenck** [comment]
> Also for a custom integration ?

Yes.

**Review by frenck — APPROVED** [review]
Thanks, @woopstar 👍 

../Frenck

**Pull request merged**
