### PR TITLE
my custom module

### PR DESCRIPTION
**Pull request by pastelka**
## Proposed change

I created own integration for my Arduino module with a lot of sensors.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is the ESPHome logo that has been modified; we can't accept that as this logo is property of the ESPHome project.

Also, I could not find a public repository providing this integration. Could you please point me to it?

Thanks! 👍 

../Frenck

**Comment by pastelka** [comment]
If the problem is that I used an existing logo, I'll create one of my own. That's not a problem.

The integration is related to my own solution with Arduino, which I have had for several years and now I have connected it to HA. It is not usable for anyone else. I didn't even put it on GitHub, but directly created it on I have HA in custom-components. Is this a problem?

**Comment by frenck** [comment]
> I didn't even put it on GitHub, but directly created it on I have HA in custom-components. Is this a problem?

Unfortunately, there is no good reason for add and host assets if there isn't a wide public use for them.

Therefore, I'm going to friendly decline this PR.

../Frenck

**Comment by pastelka** [comment]
Okay, I understand. How else to solve the logo in the custom integration so that the 404 error is not displayed?

**Pull request closed without merging**
