### PR TITLE
Adding icons for Eight Sleep custom integration.

### PR DESCRIPTION
**Pull request by lukas-clarke**
Adding icons for Eight Sleep custom integration. Have made new custom integration with OAuth2 compatibility/workaround, now that core integration no longer works.
UPDATE: Also removing Eight Sleep icons from eight_sleep core integration, since the integration was removed from core.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [x] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:
- Link to documentation pull request:
- Link to integration documentation on our website:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @lukas-clarke 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Oh! The CI is failing @lukas-clarke.

Could you take a look?

Thanks! 👍 

../Frenck

**Comment by lukas-clarke** [comment]
@frenck, it looks like the CI check failed since there were still the icons in the core integrations folder. I removed the icons from that folder since the integration was removed from core, and updated the PR comment.

**Review by frenck — APPROVED** [review]
Thanks, @lukas-clarke 👍 

../Frenck

**Pull request merged**
