### PR TITLE
Update Honeywell and Total Connect images

### PR DESCRIPTION
**Pull request by qwow5**
## Proposed change

Some branding changes have been made since Resideo acquired Honeywell's Home division. The Honeywell brand is now known as "Honeywell Home" (this includes Total Connect Comfort, both [US](https://mytotalconnectcomfort.com/portal) and [EU](https://international.mytotalconnectcomfort.com/Account/Login)), and Total Connect Alarm has a new logo as well (seen [here](https://totalconnect2.com/)).

This PR updates the logos and icons for the TC Comfort and TC Alarm integrations to the aforementioned ones. Also, because the "tc" icon is only used for Total Connect Alarm, it has been removed from the TCC directory and is replaced by the standard Honeywell "H" icon.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logo & logo@2x are not the same images:
CleanShot 2022-02-06 at 17 32 47@2x

The transparent space around them differ

**Comment by qwow5** [comment]
I did not create those images. Probably should've said this earlier, but those were pulled from the Honeywell Lyric integration: https://github.com/home-assistant/brands/tree/master/core_integrations/lyric.

**Comment by frenck** [comment]
That is fine, but the review comment remains the same 🤷

**Review by frenck — APPROVED** [review]
Thanks, @qwow5 👍

**Comment by qwow5** [comment]
Np. Will open new PR to fix Lyric logo.

**Pull request merged**
