### PR TITLE
Added brand images for fandffox custom integration.

### PR DESCRIPTION
**Pull request by tobiasz256**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @tobiasz256, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3170).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
The icons used, seem to be from one of their products, and not part of their brand icons.

**Comment by tobiasz256** [comment]
> The icons used, seem to be from one of their products, and not part of their brand icons.

Yes, Fox is one of products and integration is for this product ;) Logo is for whole brand.

**Comment by tobiasz256** [comment]
> 

To be clear, let me explain. 
F&F Filipowski is a brand for company. Their have also sub-brands such as Fox, F&Home etc, so Fox icons can be freely used like a brand in this repository. This is official information from their customer service ;)

**Comment by frenck** [comment]
Yes, but we collect manufacturer branding, not product branding. Please remove the product branding from this PR and, in case available, add icons that match the manufacturer branding.

Thanks 👍

**Comment by frenck** [comment]
Why did you remove the logo versions?

**Comment by tobiasz256** [comment]
> Why did you remove the logo versions?

Following the readme,
_,,If the brand uses the same image for the logo and icon (e.g., if the logo has a square aspect ratio), only add the icon images. The icon will be used as a fallback for the logo."_

Logo and icon are the same.

**Comment by frenck** [comment]
Sure, but you could create proper logos from those icons, by trimming the white border on the top and bottom of the icon.

**Comment by frenck** [comment]
The replaced logs removed some white background and replaced it with a transparent background, but they were not trimmed as suggested/requested in my previous post.

image


Could you look again?

**Comment by frenck** [comment]
Sorry, yeah, in that case, omitting seems the only option.

**Review by frenck — APPROVED** [review]
Thanks, @tobiasz256 👍

**Comment by tobiasz256** [comment]
Thank you too ;)

**Pull request merged**
