### PR TITLE
Add icons for gotify custom integration

### PR DESCRIPTION
**Pull request by 1RandomDev**
## Proposed change

Add icons for my custom [gotify integration](https://github.com/1RandomDev/homeassistant-gotify).

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: N/A
- Link to code base pull request: N/A
- Link to documentation pull request: N/A
- Link to integration documentation on our website: N/A

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This domain conflicts with a pull request open to adding the `gotify` integration domain to Home Assistant Core; and thus conflicts with PR #2694

**Comment by 1RandomDev** [comment]
Ok but then why can't the other PR be merged nowI can pulish soy custom integration?

**Comment by 1RandomDev** [comment]
Ok but then why can't the other PR be merged nowI can pulish soy custom integration?

**Comment by 1RandomDev** [comment]
Ok but then why can't the other PR be merged nowI can pulish soy custom integration?

**Comment by frenck** [comment]
I would not recommend using that domain for your custom integration, as that might result in a conflict in the future.

**Comment by frenck** [comment]
As there has not been further activity on this PR, I'll go ahead and close this for now. Feel free to re-open when ready to work on it again.

../Frenck

**Comment by 1RandomDev** [comment]
@frenck don't have the right to reopen. Why would it be a problem adding the gotify icons now instead of waiting for the (aperently discontinued in 2003) official gotify integration? I continued distributing my custom one with the `gotify` domain and there are already people using it, therefor it would make sense to have a proper icon for it and be able to publish it in HACS. If the official gotify integration will ever get continued people could just switch over to the new one and the current icons can be reused.

**Pull request closed without merging**
