### PR TITLE
Add icons for random entity integration

### PR DESCRIPTION
**Pull request by gickowtf**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by gickowtf** [comment]
@jpbede  moin ;) Feel free to approve

**Review by frenck — CHANGES_REQUESTED** [review]
The icons and logos are the same. In that case the logos can just be omitted.

../Frenck

**Comment by gickowtf** [comment]
@frenck ok i have deleted the logos i must have misunderstood something and thought it was logos and icons that were important. i am sorry

**Review by frenck — APPROVED** [review]
Thanks, @gickowtf 👍 

We automatically fallback to the icons when the logo is missing.

../Frenck

**Comment by gickowtf** [comment]
@frenck  thank you... next step https://github.com/hacs/default/pull/2147

**Pull request merged**
