### PR TITLE
Add Icon and Logo for Rinnai Integration

### PR DESCRIPTION
**Pull request by explosivo22**
## Proposed change

Add icon and logo for [Rinnai Control-R Integration](https://github.com/explosivo22/rinnaicontrolr-ha)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @explosivo22, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2664).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
image


Something went wrong with the normal logo version, it looks stretched.
Could you please take a look?


Also, could you please update the title of this PR to be descriptive and provide some content in the PR description (e.g., a link to the custom integration that the logo is being added for).

Thanks!

../Frenck

**Comment by explosivo22** [comment]
I have replaced the logo, but it seems github may be resizing it when I upload it.  I do not see this on the original image when uploading.  

Properties on my file show: `Dimensions: 557x128`

**Review by frenck — APPROVED** [review]
Thanks, @explosivo22 👍

**Pull request merged**
