### PR TITLE
Icon and logo for upcoming Alphatronics UNii integration

### PR DESCRIPTION
**Pull request by rrooggiieerr**
## Proposed change

I added icons and logos for our soon to be release HA integration for Alphatronics UNii security system.

https://github.com/unii-security/homeassistant-unii

The plan is to set our repository to public in the next one or two weeks.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by rrooggiieerr** [comment]
Updated @2x images

**Comment by frenck** [comment]
As per PR description, the custom integration isn't public, so there is nothing for us to review/merge.

Closing this PR for now. Feel free to re-open when the upstream repository is publicly available. I'm happy to review at that point in time.

Thanks! 👍 

../Frenck

**Comment by rrooggiieerr** [comment]
Would adding you to the private repository help? We really would like to have the company icon and logo available when we release our integration to the public

**Comment by frenck** [comment]
> Would adding you to the private repository help? 

No, that will not help. We won't be adding private repos, as there is no point for us to add files for integration that are not available for users.

> We really would like to have the company icon and logo available when we release our integration to the public

That isn't needed for the integration to function.

../Frenck

**Pull request closed without merging**
