### PR TITLE
Add new custom integration hiq

### PR DESCRIPTION
**Pull request by killer0071234**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by kvanzuijlen — APPROVED** [review]

**Review by frenck — CHANGES_REQUESTED** [review]
It seems their branding looks different from what is provided in this PR.

image

Could you point me to a location where the manufacturer uses this as their branding?

../Frenck

**Review by kvanzuijlen — COMMENTED** [review]
Looks like variants of this came from https://www.cybrotech.com/software-category/tools/

**Comment by frenck** [comment]
Right, but those are application icons, not brand assets :)

**Comment by killer0071234** [comment]
Hi,
I think i messed here something up. ;-(
cybro(tech) is a brand for industrial plc controller.
The plc base is nearly the same as the controllers for home application
The main difference is in the running software and expansion units.
The home application is called HIQ which can be found here: [hiq-home](http://hiq-home.com/)
I started with my integration with the name `cybro`, but the better name would be `hiq`.
In that case it will be the best if i change cybro to hiq and add the logo files.
\Daniel

**Review by frenck — CHANGES_REQUESTED** [review]
Both the icon and logos are icons.
I expected the logo not to be square in this case?

**Comment by killer0071234** [comment]
Yes you are right,
logo updated.
\Daniel

**Review by frenck — APPROVED** [review]
Thanks, @killer0071234 👍

**Pull request merged**
