### PR TITLE
Add icons for custom_components divoom_pixoo

### PR DESCRIPTION
**Pull request by gickowtf**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: https://github.com/gickowtf/pixoo-homeassistant

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This seems like a combined logo with a product and branding, however, looking at the upstream resources, this it not what the manufacturer uses for their normal branding.

Please use the branding of the manufacturer (not product).

../Frenck

**Comment by gickowtf** [comment]
ok sorry i changed the icon files and left out the logo files because they are identical. is it correct that the custom component is automatically listed in https://analytics.home-assistant.io/custom_integrations.json as soon as the icons for it are available? in the end i only see statistics in GitHub.

**Review by frenck — APPROVED** [review]
Thanks, @gickowtf 👍 

../Frenck

**Comment by frenck** [comment]
> ok sorry i changed the icon files and left out the logo files because they are identical. is it correct that the custom component is automatically listed in [analytics.home-assistant.io/custom_integrations.json](https://analytics.home-assistant.io/custom_integrations.json) as soon as the icons for it are available? in the end i only see statistics in GitHub.

Yes

**Pull request merged**
