### PR TITLE
Telenet custom integration icons

### PR DESCRIPTION
**Pull request by geertmeersman**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: <https://github.com/geertmeersman/telenet>

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I can't find a custom integration with only the `telenet` domain, only with [`telenet_telemeter`](https://github.com/myTselection/telenet_telemeter/blob/main/custom_components/telenet_telemeter/manifest.json#L2)

**Comment by geertmeersman** [comment]
Integration just waits now for the brand
https://github.com/geertmeersman/telenet/actions/runs/4512996142

**Review by frenck — APPROVED** [review]
Thanks, @geertmeersman 👍 

../Frenck

**Comment by geertmeersman** [comment]
@frenck , small question: when are the brand images  pushed to the https://brands.home-assistant.io/ ?

Thanks for all your work!

**Comment by frenck** [comment]
> @frenck , small question: when are the brand images pushed to the [brands.home-assistant.io](https://brands.home-assistant.io/) ?

Instantly, but they are heavily cached. They might appear sooner (depending on your region), but we do flush the cache on each major HA release (the first Wednesday of each month).

**Comment by geertmeersman** [comment]
Super, thanks for the info!!! Learning about the integrations and very eager  & happy to  contribute :-)
Lots of love for HA!

**Pull request merged**
