### PR TITLE
add w1000-energy-monitor icons

### PR DESCRIPTION
**Pull request by ZsBT**
## Proposed change

w1000-energy-monitor

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by ZsBT** [comment]
fix sizes

**Comment by ZsBT** [comment]
fix icon.png

**Review by frenck — CHANGES_REQUESTED** [review]
Could you point me to resources where this branding is used? The only brand I could find related to this integration is the E-on branding.

../Frenck

**Comment by ZsBT** [comment]
The product itself is made by https://www.meteringservicesgroup.com/ .
E.On is just using it, e.g. at https://energia.eon-hungaria.hu/W1000 .

**Review by frenck — APPROVED** [review]
Thanks, @ZsBT 👍

**Pull request merged**
