### PR TITLE
Add brink-home icons

### PR DESCRIPTION
**Pull request by samuolis**
## Proposed change

Adds new icons for Brink-Home custom component.
Link to integration: https://github.com/samuolis/brink
Link to vendor website: https://www.brink-home.com/

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/samuolis/brink
- Link to documentation pull request: https://github.com/samuolis/brink/blob/master/README.md
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The added icons are application icons (from their Apps in appstores), but not their main manufacturer branding. Please adjust them to use the main branding instead.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
You've set an icons using the white color for the normal logo. This one will be used on "light" themes (and thus not visible). (please note, we have the ability to set dark and light variants, see the repository readme for more information).

CleanShot 2023-05-09 at 20 10 27

../Frenck

**Comment by samuolis** [comment]
Something is still wrong @frenck ?

**Comment by frenck** [comment]
> Something is still wrong @frenck ?

Not sure why you ask that? Was there an indication something was wrong?

**Review by frenck — APPROVED** [review]
LGTM, thanks, @samuolis 👍 

../Frenck

**Pull request merged**
