### PR TITLE
Added icons for SAJ eSolar Air based on saj_esolar

### PR DESCRIPTION
**Pull request by faanskit**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes 
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: https://github.com/faanskit/ha-esolar#readme

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
These brand images provided seem to be customized. I could not find an official use of the assets provided by SAJ. 

Could you point me to it?

Thanks! 👍 

../Frenck

**Comment by faanskit** [comment]
> These brand images provided seem to be customized

I agree, the images appear customized. These icons are exactly the same as (copy of):
```
.../brands/tree/master/custom_integrations/saj_esolar
```

A symlink to any of these would suffice, but instruction does not allow the use of symlinks with custom_integrations:
> Symlinks are currently not allowed in the custom integrations folder.

Official unedited logos and icons are found here:

**Logo:**
https://www.saj-electric.com/images/footer/logo_footer.png
https://www.saj-electric.com/images/header/logo22.png

**Icon:**
https://fop.saj-electric.com/public/img/YW/new/logo.png

I can update the PR with new logos should the copy from `custom_integrations/saj_esolar` not be enough.
Please advice.

/Marcus

**Comment by frenck** [comment]
> A symlink to any of these would suffice, 

We don't allow symlinks for custom integrations, see also the documentation of this repository.

Please use the branding the manufacturer created/uses.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Based on their social media accounts, they seem to use the SAJ main logo as an icon as well.

image


I could not find a reference for their main branding in the provided assets in this PR. Could you point me to where they are using it?

../Frenck

**Comment by faanskit** [comment]
Update with latest changes

**Comment by faanskit** [comment]
> I could not find a reference for their main branding in the provided assets in this PR. Could you point me to where they are using it?

The SAJ Solar Panel cloud service is provided by SAJ's eSolar brand.

References to branding of Solar Panel (Cloud) services;
**Solar Panel Portal (eSolar Portal)**
https://fop.saj-electric.com/saj/login

**Solar Panel App (eSolar Air)**
https://apps.apple.com/se/app/esolar-air/id1441935310

Other sub-brands, such as **eSolar Pump** or **IE Control** have a different iconography:
https://apps.apple.com/se/app/esolar-pump/id1462600144
https://apps.apple.com/se/app/i-e-control/id1277582239


I may have misunderstood the instructions, being mislead by the existing `saj_esolar` integration.

> icon.png: 
> A square avatar-like icon, representing the brand or product for that domain.
> 

The icon I have provided represents the **product** (eSolar Portal/Air) for the domain (=Solar Cloud Services)
The custom_integration I made is a cloud polling integration providing the same information as the app/portal.


> logo.png: 
> The logo of the brand or product for that domain.
> 
The icon I have provided represents the **brand** (SAJ Electric) for the domain (=Solar Cloud Services).

HTH, and please advice if additional changes shall be made.

/Marcus
ps. Thanks for all your efforts. Love your work

**Comment by frenck** [comment]
> The SAJ Solar Panel cloud service is provided by SAJ's eSolar brand.

I could not find the Homepage of SAJ eSolar as an entity? It seems to be a product of SAJ Electric (saj-electric.com).

Please note, we collect branding of manufacturers here, and not product or service branding.

> The logo I have provided represents the brand (SAJ Electric) 

The logo does, but the icon doesn't.

../Frenck

**Comment by faanskit** [comment]
> I could not find the Homepage of SAJ eSolar as an entity? It seems to be a product of SAJ Electric (saj-electric.com).

You are likely right. I want to point out that the icon provided is visible on the homepage, see (A) in the attached picture when you hover the mouse over it.

Capture

As an option to use the (A) icon, would it be better to use (a scaled up) favicon.ico as icon. See (B) in the attached picture.

The third option is to replicate what `saj_modbus` integration did; which is to add white borders around the logo.png to match the size requirements.

That is, these are the options:
**(1) eSolar Portal logo**
icon_1

**(2) The favicon**
favicon

**(3) The logo with white borders**
icon

Please let me know your preference and I'll update the icon accordingly.

BR/Marcus

**Comment by frenck** [comment]
The esolar portal is a product image and should not be used, as I stated above, however, you said it was a brand. I'm confused now.

Please use the branding the manufacturer uses (and not product branding).

Thanks 👍 

../Frenck

**Comment by faanskit** [comment]
> The esolar portal is a product image and should not be used, as I stated above, however, you said it was a brand. I'm confused now.
> 
> Please use the branding the manufacturer uses (and not product branding).
> 

Product icon is now removed and replaced with a scaled up version of favicon.ico.
Sorry for the confusion and any mess created. New to this and the process, just want to make right.

Thanks for your continuous support, and I hope this is now agreable.

/Marcus

**Comment by faanskit** [comment]
@frenck , did you have any other comments or issues with the last update?

**Pull request merged**
