### PR TITLE
Add nest protect logos

### PR DESCRIPTION
**Pull request by iMicknl**
## Proposed change

Adds brand images for Nest Protect, custom integration. https://github.com/iMicknl/ha-nest-protect

Have thought about symlinking the Nest (core) directory, however it would be good to have a different (square) icon.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons are product images and or logos, however, the goal of our brands repository is to collect manufacturer brand images. Please adjust this PR to match that.

Thanks! 

../Frenck

**Comment by iMicknl** [comment]
> The icons are product images and or logos, however, the goal of our brands repository is to collect manufacturer brand images. Please adjust this PR to match that.

Thanks, I was not aware of this policy, but it makes sense. In that case it would be best to have a symlink to the nest integration in core. (if that is allowed)

**Comment by frenck** [comment]
image

**Comment by iMicknl** [comment]
Apologies... I fully missed this, my bad.

I have changed the images to duplicate the Nest logo / icons.

**Pull request merged**
