### PR TITLE
formulaone_api icons

### PR DESCRIPTION
**Pull request by marcokreeft87**
## Proposed change

I want to add my integration to HACS default and for that my integration images must be in the brands repo

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
- [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by delzear — APPROVED** [review]

**Review by delzear — APPROVED** [review]

**Review by frenck — CHANGES_REQUESTED** [review]
These brand images have been modified. Therefore we cannot accept those. The reason is that these kinds of modifications generally violate branding guidelines.

We like to respect the branding of the respective owners and have authentic branding for identification purposes for our users.

../Frenck

**Comment by marcokreeft87** [comment]
@frenck  Gotcha, I thought it was better to modify them

**Review by frenck — APPROVED** [review]
Can we add the logo versions too? That would look better on things like device pages

**Comment by marcokreeft87** [comment]
It was hard to find a good logo of the F1 brand but I think I found one. It isnt that big, thats why there is no 2x version

**Review by frenck — APPROVED** [review]
Thanks, @marcokreeft87 👍

**Pull request merged**
