### PR TITLE
Add icons for Omnilogic integration

### PR DESCRIPTION
**Pull request by chadlyy**
## Proposed change

Add icon/logo for the Hayward Omnilogic integration. 

## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: [PR 38911](https://github.com/home-assistant/core/pull/38911#partial-pull-merging)
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I'm a bit confused. Both images have a square aspect ratio (the same image size even). Why are they different?

**Comment by chadlyy** [comment]
The logo has more color but there really isn't much difference.  Do you prefer I just remove the logo.png?

**Comment by frenck** [comment]
We prefer icons/logo with transparency (as per the documentation of this repository), so I would indeed recommend removing the logo.png file in that case.

**Comment by chadlyy** [comment]
Removed logo.png... can we proceed?

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
