### PR TITLE
Add images for garmin_connect

### PR DESCRIPTION
**Pull request by cyberjunky**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
These are product icons/images, I would have expected the Garmin brand images to be used instead.

**Comment by cyberjunky** [comment]
They are the same as the core_integration ones which were there for years ;-)

They should match the integrations I guess, a quick look turns out that BMW connected drive is also not the BMW logo. And Garmin makes ship navigation which has nothing to do with Garmin Connect. The repo name is just wrong ;-)

**Comment by cyberjunky** [comment]
But I will see what i can do. Thinking rules where less strict with HACS, but they are not.

**Comment by cyberjunky** [comment]
I created new images as requested.
Following this guide https://creative.garmin.com/styleguide/logo/ I picked the without the the delta (triangle) since these are for navigation type products, hence there is no separate square icon available.

**Review by frenck — CHANGES_REQUESTED** [review]
The logo & logo@2x should be the same images (only a bigger version of it, retaining aspect ratio).

Unfortunately, that is not the case:

image

**Review by frenck — APPROVED** [review]
Thanks, @cyberjunky 👍

**Pull request merged**
