### PR TITLE
Add VSN Logos

### PR DESCRIPTION
**Pull request by kilimnik**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/78839
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/24193
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The linked PR is for adding the `hafas` integration, which is no using this brand icon? Nor does the domain match an core integration. I cannot place these images anywhere?

Could you clarify?

../Frenck

**Comment by kilimnik** [comment]
The linked hafas integration uses implenets an - virtual vsn integration

**Comment by frenck** [comment]
> The linked hafas integration uses implenets a virtual vsn integration

An PR against core can only implement a single integration as a time. So, that would be incorrect/impossible.

../Frenck

**Comment by kilimnik** [comment]
Just to clarify, if I understood that correctly. I am not allowed to add a virtual integration in the same pr as the integration is added in.
So I have to wait until the base integration is merged and after that, I can make a new PR with the virtual integration added?

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
