### PR TITLE
Added logos for JustNimbus integration

### PR DESCRIPTION
**Pull request by kvanzuijlen**
## Proposed change

Added logos for the new JustNimbus integration.

NOTE: I'm not, in any way, affiliated with JustNimbus.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to code base pull request: https://github.com/home-assistant/core/pull/75718
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/23702

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
The PR now conflicts with the icons of the custom integration. Maybe remove the custom integration version?

**Review by frenck — CHANGES_REQUESTED** [review]
Comment above :)

**Comment by kvanzuijlen** [comment]
> The PR now conflicts with the icons of the custom integration. Maybe remove the custom integration version?

Hi @frenck,

The weird thing is that the core/custom integration the check is failing on is not an integration that I made any changes to. Should I still remove these? If so, no problem, but I wanted to be sure.

**Comment by kvanzuijlen** [comment]
Should be fixed by #3574

**Comment by frenck** [comment]
Oh 🤦 It wasn't related to this PR. Missed that, sorry about that 🙈

**Comment by kvanzuijlen** [comment]
No problem, happy to help out :D. Thx for your great work on HomeAssistant!

**Review by frenck — APPROVED** [review]

**Pull request merged**
