### PR TITLE
Added MyEnergi logo and icon

### PR DESCRIPTION
**Pull request by CJNE**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x ] Add a new logo or icon for a custom integration (custom component)
  - [ x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to custom integration: https://github.com/CJNE/ha-myenergi
- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
Please add a public link to the repository of this custom integration to the description of this PR

**Comment by CJNE** [comment]
Sorry, i have added the link under additional information now.

**Review by ludeeus — CHANGES_REQUESTED** [review]
The logos provided here can not be with the default color scheme of homeassistant, white on white will be invisible.

**Comment by CJNE** [comment]
Ah, i'm so used to only seeing the dark theme so i didn't think of that. I've made the text black and added a white glow around it so it's visible in dark mode as well

**Comment by ludeeus** [comment]
When logos that work on white background exist in the PR you can also add `dark_*` variants that would be used if you use a dark theme in HA (see README.md for more info)

**Comment by CJNE** [comment]
> When logos that work on white background exist in the PR you can also add `dark_*` variants that would be used if you use a dark theme in HA (see README.md for more info)

Thanks for that, i didn't read it careful enough it seems. I'll quickly add dark mode variants then, will look better than the glow!

**Review by ludeeus — APPROVED** [review]
Looks good :+1:

**Pull request merged**
