### PR TITLE
Icons for custom integration meteoswiss

### PR DESCRIPTION
**Pull request by braetkuegeli**
Add missing icons for custom integration _meteoswiss_ (https://github.com/Rudd-O/homeassistant-meteoswiss)

## Type of change
- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information
https://github.com/Rudd-O/homeassistant-meteoswiss is a fork of websylv/homeassistant-meteoswiss:master which is unsupported.

- This PR fixes or closes issue: fixes https://github.com/Rudd-O/homeassistant-meteoswiss/issues/25
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/Rudd-O/homeassistant-meteoswiss

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by braetkuegeli** [comment]
MeteoSwiss is the service and app provider. 
- https://www.meteoswiss.admin.ch/services-and-publications/service.html 
- Also their [X](https://x.com/meteoschweiz) and [Instagram](https://www.instagram.com/meteoschweiz/) account uses this logo

**Comment by Rudd-O** [comment]
Upstream logo is this:

image

because upstream is the Confederatio Helvetica itself — the weather service is part of the federal confederation.

image

It would be confusing to use the general Confederatio shield as the branding for this integration.

BTW, if this goes through, I will try to upstream my integration work into HA.

**Review by frenck — APPROVED** [review]
Thanks, @braetkuegeli 👍 

../Frenck

**Comment by Rudd-O** [comment]
Thank you @frenck .

**Pull request merged**
