### PR TITLE
Adding zcs_azzurro_inverter logos

### PR DESCRIPTION
**Pull request by AlePerla**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/87807
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/26298

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The provided assets do not seem to match the branding the manufacturer uses:

image

Please update the branding to respect the manufacturer's branding.

../Frenck

**Comment by AlePerla** [comment]
> The provided assets do not seem to match the branding the manufacturer uses:
> 
> image
> 
> Please update the branding to respect the manufacturer's branding.
> 
> ../Frenck

Hi @frenck 
It is not possible. The manufacturer allowed me to use the APIs but not the logos

**Comment by frenck** [comment]
If that is the case, this PR won't be accepted.

../Frenck

**Comment by AlePerla** [comment]
Sorry but I'm not gonna go against a trademark issue. The integration will remain without a logo if so 🙂

**Comment by frenck** [comment]
As said, this PR won't be accepted in its current form. If you don't want to add the actual logos, the only option is to close the PR.

../Frenck

**Comment by AlePerla** [comment]
It's not about what I want, more about law🙂

**Comment by frenck** [comment]
That is up to you.

../Frenck

**Pull request closed without merging**
