### PR TITLE
Create icon.png

### PR DESCRIPTION
**Pull request by amaximus**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by amaximus** [comment]
update

**Review by frenck — CHANGES_REQUESTED** [review]
I would have expected icons & logos from these:

image


I'm not sure what the current icon represents.

**Comment by amaximus** [comment]
That's the logo of the data provider (Hungarian Meteorological Institute).
I guess that's not what should be uploaded.

**Comment by frenck** [comment]
> I guess that's not what it should be uploaded.

Please elaborate on why not?

**Comment by amaximus** [comment]
I thought it should be something that reflects my brand (that I don't have :) ), not the logo/icon of the data provider.

It seems I misunderstood the whole thing.
I will update it soon.

**Comment by amaximus** [comment]
Are there any further actions needed from my side?

**Review by frenck — APPROVED** [review]
Thanks, @amaximus 👍

**Pull request merged**
