### PR TITLE
Add wibeee icons for new integration

### PR DESCRIPTION
**Pull request by abacao**
## Type of change

- [] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Adds new integration [abacao/hass_wibeee]](https://github.com/hacs/default/pull/627)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes https://github.com/hacs/default/pull/627
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon looks like a weird cutout from the logo.
Please note, we don't allow messing with brand images from third-parties. We should respect the design/brand image by the third-party.

Please adjust the icons.

**Comment by abacao** [comment]
@frenck It's true. I wasn't able to find icons for this, Only the logo.
Can this be integrated without the "icons*"?

**Comment by frenck** [comment]
Icons are not mandatory, so it is probably best to remove those in this case.

**Comment by abacao** [comment]
@frenck can you please recheck? :pray:

**Review by frenck — APPROVED** [review]
Thanks, @abacao 👍

**Pull request merged**
