### PR TITLE
New custom_integration "patch" icons

### PR DESCRIPTION
**Pull request by amitfin**
## Proposed change

Adding icons for a new custom integration: https://github.com/amitfin/patch

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @amitfin 👍 

../Frenck

PS: Odd to see an integration for something, that is just native build-in functionality 🤷 

../Frenck

**Comment by frenck** [comment]
>  Can you point me to it?

`custom_components`. You can override any integration at full in any way you like with that folder (it is not just for adding new custom integrations). As a matter of fact, that is what that folder was originally designed for.

As everything in Home Assistant is an integration, you can override anything just by placing it into that folder.

../Frenck

**Comment by amitfin** [comment]
Correct. Overriding integration exists (and I'm indeed using it). The problem is overriding a dependency library. I was unable to find an easy way to do it. It's possible to copy the files of the library to the same folder as the integration and to do a global replace in the code, but it's not trivial. 
Is there an easier way to override a Python library?

**Comment by frenck** [comment]
The Python library is part of the ingestion manifest, but also of generated files. Copy the full integration, adjust what you like (including the used library). That is the correct way to go.

Modifying sources in the container itself, will lead to issues (as a matter of fact, we may mark you system as unsupported).

**Comment by amitfin** [comment]
But regardless, I'll add the information above overriding an integration into the documentation, so people know to use the simpler method of patching when the change is in integration code. Thanks!

**Pull request merged**
