### PR TITLE
Add DirecTV logos.

### PR DESCRIPTION
**Pull request by ctalkington**
## Proposed change

Add logos for DirecTV.

## Type of change

- [ ] Add a new logo or icon for a new integration
- [x] Add a missing icon or logo for an existing integration
- [ ] Replace an exiting icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by ctalkington** [comment]
seems the compression action is failing. 
```(node:1) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration```

**Comment by frenck** [comment]
Yes, I'm aware of the failing compression, this is due to an upstream bug:

<https://github.com/calibreapp/image-actions/issues/19>

**Comment by frenck** [comment]
Looks good! Can we add the icon as well?

**Comment by ctalkington** [comment]
let me look for a good source

**Comment by ctalkington** [comment]
@frenck should be good, still having issue with compress action it seems.

**Comment by frenck** [comment]
Meh weird, is should be fixed. Nevertheless, your PR looks good 👍

**Comment by ctalkington** [comment]
@frenck oh I guess rebasing might have fixed?  was thinking workflows were global ish but I bet it was using my base.

**Comment by frenck** [comment]
Probably, I made a note, will make sure in a later PR. 👍

**Pull request merged**
