### PR TITLE
Add XY Screens icons

### PR DESCRIPTION
**Pull request by rrooggiieerr**
## Proposed change

New icons for XY Screens

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

XY Screens is an OEM manufacturer of projector screen and projector lifts. I've created a custom integration to controll these devices

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by rrooggiieerr** [comment]
I wanted to create a second pull request for the BenQ logo and icon, but somehow it ended up in this pull request. Not really clear what happened especially since I created this pull request before I comitted my BenQ changes.

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is adding multiple integrations. Please create a separate and dedicated PR for each integration.

> I wanted to create a second pull request for the BenQ logo and icon, but somehow it ended up in this pull request. Not really clear what happened

Looks like you didn't create branches.

../Frenck

**Comment by rrooggiieerr** [comment]
@frenck Yes, I tried, but when I did more commits to my own fork of the brands repository they were automagically added to this pull request, don't know why

**Comment by frenck** [comment]
As mentioned in my previous comment, you didn't create branches.

**Pull request closed without merging**
