### PR TITLE
OralB_hacs custom integration

### PR DESCRIPTION
**Pull request by bkbilly**
## Proposed change

Added images for OralB_hacs custom integration.
https://github.com/bkbilly/oralb_hacs

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The provided domain name is invalid, it contains as `-`, which is not valid in a integration domain.

../Frenck

**Comment by bkbilly** [comment]
Fixed it with the proper name `oralb_hacs`.

**Review by frenck — CHANGES_REQUESTED** [review]
The domain in this PR doesn't match the domain in the custom integration. Additionally, there is a mismatch in the custom integration itself as well:

CleanShot 2023-01-04 at 12 04 30

**Comment by bkbilly** [comment]
Just fixed these too.
Thanks for noticing!

**Comment by bkbilly** [comment]
Fixed the domain.
Thanks!

**Review by frenck — APPROVED** [review]
Thanks, @bkbilly 👍 

Happy New Year 🥂 

../Frenck

**Pull request merged**
