### PR TITLE
Fix brand images for Aurora ABB Powerone int.

### PR DESCRIPTION
**Pull request by adrianmihalko**
## Proposed change

Fix Aurora ABB Solar PV brand images as requested by @davet2001 in #1354. Thanks!

## Type of change

- [ ] Add a new logo or icon for a new integration
- [ ] Add a missing icon or logo for an existing integration
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #1354 
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
@adrianmihalko A wild merge conflict appeared... could you take a look?

Thanks 👍

**Comment by adrianmihalko** [comment]
> @adrianmihalko A wild merge conflict appeared... could you take a look?
> 
> Thanks 👍

Yea, I removed symlinked directory, after merge I will post new images.

**Comment by frenck** [comment]
Thanks for updating by now I have:

image


So this PR is empty?

**Comment by adrianmihalko** [comment]
> Thanks for updating by now I have:
> 
> image
> 
> So this PR is empty?

Hmm, let's try. As you can see in dcd8d33 I removed just symlink, otherwise if I remove and post new files it shows as conflict.

**Comment by adrianmihalko** [comment]
Yeah, I have no ide why it shows up as conflicting file:

```
Conflicting files
src/aurora_abb_powerone

```

**Pull request closed without merging**
