### PR TITLE
add nicehash excavator integration icon

### PR DESCRIPTION
**Pull request by MesserschmittX**
## Proposed change

Add icon for custom [Nicehash Excavator Integration](https://github.com/MesserschmittX/hacs-nicehash-excavator)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I would have expected the NiceHash branding to be used here?

**Comment by MesserschmittX** [comment]
> I would have expected the NiceHash branding to be used here?

The Excavator miner has its own Application icon, and as this integration has nothing directly to do with NiceHash I thought it would fit better. Besides that, there already is a custom integration that accesses the NiceHash API so I thought it could be confusing to use the same icon here as well.

**Comment by frenck** [comment]
The Excavator API is part of the NiceHash organization on GitHub? So, but it isn't NiceHash?
I'm confused. Please note, we collect branding here, not product or application icons.

**Comment by MesserschmittX** [comment]
> The Excavator API is part of the NiceHash organization on GitHub? So, but it isn't NiceHash? I'm confused. Please note, we collect branding here, not product or application icons.

You are right about NiceHash being the brand, I updated the icon accordingly.

**Comment by frenck** [comment]
You might want to use these: <https://github.com/home-assistant/brands/tree/master/custom_integrations/nicehash>

As in, it would provide logos as well.

**Comment by MesserschmittX** [comment]
> You might want to use these: https://github.com/home-assistant/brands/tree/master/custom_integrations/nicehash
> 
> As in, it would provide logos as well.

I have added the logo and additional sizes

**Review by frenck — APPROVED** [review]
Thanks, @MesserschmittX 👍

**Pull request merged**
