### PR TITLE
Add icons for custom integration PiotrMachowski/burze_dzis_net

### PR DESCRIPTION
**Pull request by PiotrMachowski**
## Proposed change

Add icons for a custom integration [PiotrMachowski/burze_dzis_net](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @PiotrMachowski 👍 

../Frenck

**Comment by PiotrMachowski** [comment]
Thank you, @frenck!

**Comment by PiotrMachowski** [comment]
I have some issues with `icon.png`:
https://brands.home-assistant.io/burze_dzis_net/icon.png - doesn't work (404)
https://brands.home-assistant.io/burze_dzis_net/icon@2x.png - works
https://brands.home-assistant.io/_/burze_dzis_net/icon.png - works
https://brands.home-assistant.io/_/burze_dzis_net/icon@2x.png - works
https://brands.home-assistant.io/burze_dzis_net/darkicon.png - doesn't work (404)
https://brands.home-assistant.io/burze_dzis_net/darkicon@2x.png - works
https://brands.home-assistant.io/_/burze_dzis_net/darkicon.png - works
https://brands.home-assistant.io/_/burze_dzis_net/darkicon@2x.png - works

Do you have any suggestions on this issue?

**Comment by frenck** [comment]
Cache, will resolve automatically when HA Core releases.

**Pull request merged**
