### PR TITLE
Add broadlink manager logos/icons

### PR DESCRIPTION
**Pull request by xtraorange**
## Proposed change

Introduce logos and icons for the broadlink manager custom component I've been working on.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/xtraorange/hass-broadlink-manager

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by xtraorange** [comment]
First time I've made a pull request - huge apologies on anything I missed or have done incorrectly.

**Comment by xtraorange** [comment]
Just checking - is there anything more I need to do here?

**Review by frenck — CHANGES_REQUESTED** [review]
The brand assets provided are modified assets of the manufacturer. We cannot accept those, as there are almost always conflicting with branding guidelines.

Please use the plain branding of BroadLink instead.

Thanks! 👍

**Comment by xtraorange** [comment]
> The brand assets provided are modified assets of the manufacturer. We cannot accept those, as there are almost always conflicting with branding guidelines.
> 
> Please use the plain branding of BroadLink instead.
> 
> Thanks! 👍

Oh, I thought I had read I wasn't allowed to use the official branding for a custom integration - that would actually have been my preference.  If it's okay to do that, I will use that instead.  Thanks for the feedback!

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Pull request closed without merging**
