### PR TITLE
Add Dark Icons for Composite

### PR DESCRIPTION
**Pull request by alvinchen1**
## Proposed change

Add dark icons for Composite custom component

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Seems like something went wrong making these icons transparent:

CleanShot 2024-02-19 at 13 01 10@2x

There are quite a lot of artifacts around the images.

Could you take a look?

Thanks! 👍 

../Frenck

**Comment by alvinchen1** [comment]
Yeah, I agree.  I don't have the original icons, which I didn't create, but I do use the custom_integration.  To be honest, I used an image negative to flip the original icons. The current ones look pretty terrible in dark mode and indeed show the artifacts in dark mode.  So artifacts in + negative flip = artifacts out. :)

image
Current Icon in Dark Mode

image
The artifacts don't really show in non-dark mode

The new dark mode ones don't really show any of the artifacts and are a significant improvement

image
Proposed New Icon in Dark Mode

**Comment by pnbruckner** [comment]
I've submitted new icons in https://github.com/home-assistant/brands/pull/5235

**Comment by alvinchen1** [comment]
New icons looks great!  Updated PR with new dark mode icons and less artifacts around the images.

**Comment by pnbruckner** [comment]
I guess both PRs make sense. I'm good with both.

**Comment by frenck** [comment]
Closing this one in favor of https://github.com/home-assistant/brands/pull/5235

**Pull request closed without merging**
