### PR TITLE
new brand for vc2 trydan charger integration

### PR DESCRIPTION
**Pull request by Rain1971**
## Proposed change

This PR adds a new logo and icon for the custom integration V2C_trydan.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logos provided do not seem to match the manufacturer's branding:

From their website:

image

**Comment by Rain1971** [comment]
Sorry for inconvinient, I thought was an icon regarding to the device. New commit with brand icons

**Review by frenck — CHANGES_REQUESTED** [review]
The icons and logos are the same in this PR, that seems incorrect.

**Comment by Rain1971** [comment]
opened again. sorry for the missunderstanding

**Comment by Rain1971** [comment]
Logo and Icons are not the same now

**Pull request merged**
