### PR TITLE
Add Anglian Water Logo and Icon

### PR DESCRIPTION
**Pull request by thewillwilson**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/pantherale0/haanglianwater

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by thewillwilson** [comment]
PR updated to include hDPI images

**Comment by thewillwilson** [comment]
Fixed filename of hDPI png

**Comment by pantherale0** [comment]
Just a note for the HA team - this integration is currently set to private as reverse engineering the API from the mobile app has also uncovered serious security flaws and I don't want to be the person who provided code that allows a bad actor to expose thousands of PII details for AW's customers.

I have disclosed to AW and will await to hear back before thinking about making this integration public again.

**Comment by frenck** [comment]
Thanks for that message @pantherale0 👍 

@thewillwilson Thanks for the PR, but we won't be adding these brand images at this point, as the repo is private. Once the above is resolve and the integration is available again, please feel free to re-open the PR. I'm happy to review it at that point in time.

For now, I'm closing this PR.

../Frenck

**Comment by pantherale0** [comment]
@thewillwilson integration is public again, could you re-open PR?

Thanks

**Comment by thewillwilson** [comment]
> @thewillwilson integration is public again, could you re-open PR?
> 
> Thanks

Thanks for sorting that, I've raised a new PR for the logo/icons (#5417) since this one was closed.

**Pull request closed without merging**
