### PR TITLE
Powerbrain

### PR DESCRIPTION
**Pull request by mb-software**
## Proposed change

This PR adds icons and logos for the cFos Powerbrain custom component integration which will soon be published in HACS

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by mb-software** [comment]
the custom is now published here:
https://github.com/mb-software/homeassistant-powerbrain

**Comment by KevinCathcart** [comment]
The icons still have a bit of "S" visible on the left hand edge. It would be better to clear that out with an imaging editing tool, leaving just the icon portion of the logo.

**Comment by mb-software** [comment]
> The icons still have a bit of "S" visible on the left hand edge. It would be better to clear that out with an imaging editing tool, leaving just the icon portion of the logo.

yea, I missed that. It's fixed now. Thanks

**Review by frenck — APPROVED** [review]
Thanks, @mb-software 👍

**Pull request merged**
