### PR TITLE
Logo and icon for Repsol

### PR DESCRIPTION
**Pull request by tslpre**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/bzzoiro/repsolluzygas
- Link to documentation pull request: https://github.com/bzzoiro/repsolluzygas/blob/main/README.md
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
Please add a public link to the repository of this integration.

**Comment by tslpre** [comment]
Oops my bad... Template updated as requested.

**Review by ludeeus — COMMENTED** [review]
https://www.hdicon.com/wp-content/uploads/2013/09/repsol_2012.png
Here is a better version for the icon, just need a resize

**Comment by tslpre** [comment]
Thank you - I did resize it to 256x256 and uploaded the newer version. please let me know if there is anything else to tweak :)

**Review by ludeeus — APPROVED** [review]
Thanks :+1:

**Pull request merged**
