### PR TITLE
Icon and Logo for Sinapsi Alfa custom integration

### PR DESCRIPTION
**Pull request by alexdelprete**
## Proposed change

Icon+Logo for my custom integration: https://github.com/alexdelprete/ha-sinapsi-alfa

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @alexdelprete 👍 

../Frenck

**Comment by alexdelprete** [comment]
Thanks to you. :)

**Comment by alexdelprete** [comment]
@frenck I forgt to ask you: do I still need to do the PR in wheels? Can't remember what's there to do frankly speaking. :)

**Comment by frenck** [comment]
@alexdelprete only if you need specific binary wheels, that aren't provided by any of your dependencies.

**Comment by alexdelprete** [comment]
> @alexdelprete only if you need specific binary wheels, that aren't provided by any of your dependencies.

it's another modbus tcp integration, so I only need pymodbus that is provided by HA.

**Comment by frenck** [comment]
Those dependencies already exists, so nothing for you to do :)

**Comment by alexdelprete** [comment]
Great. So if it's in HA requirements.txt I don't need to PR wheels, correct? I think I got it now. :)

**Comment by frenck** [comment]
@alexdelprete No problem. You can always check @ <https://wheels.home-assistant.io/musllinux-index/> to check if we have pre-build wheels for it available already 👍 

../Frenck

**Pull request merged**
