### PR TITLE
Add Czech Energy Spot Prices icon

### PR DESCRIPTION
**Pull request by rnovacek**
## Proposed change

Add icons for [Czech Energy Spot Prices](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices) custom integration based on ote-cr.cz logo.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @rnovacek 👍 

../Frenck

**Comment by rnovacek** [comment]
Pardon my ignorance, but there seems to be some problem or I don't understand how it works:

1. https://brands.home-assistant.io/cz_energy_spot_prices/icon.png returns 404
2. https://brands.home-assistant.io/_/cz_energy_spot_prices/icon.png works fine
3. https://brands.home-assistant.io/cz_energy_spot_prices/logo.png works fine

Any idea why the default icon.png (without underscore) doesn't work while the rest of them works fine?

**Comment by Robbe-B** [comment]
Did you read the part about the caching of icons and the placeholder fallback ?
image 
image

**Comment by rnovacek** [comment]
I assumed that images are cached, but non-existing image is not cached. If that's expected then no worries, I'll wait that 7 days.

**Comment by frenck** [comment]
Wait at least util the next major release, which is each first Wednesday of the month.

**Comment by Robbe-B** [comment]
I'm in the same situation as you for https://github.com/home-assistant/brands/pull/4095
I guess it works for people who are installing this intgeration for the first time (the url was never requested before)
Just like I can see => https://brands.home-assistant.io/cz_energy_spot_prices/icon.png
You probably can see this one ? (I have 404)=> https://brands.home-assistant.io/maestro_mcz/icon.png

**Comment by rnovacek** [comment]
Yeah, I can see https://brands.home-assistant.io/maestro_mcz/icon.png 

It's weird, even if I disable browser caching, it's still the same. The server-side cache (cloudflare) shouldn't be user-specific, right?

**Comment by frenck** [comment]
> It's weird, even if I disable browser caching, it's still the same

It is not your caching, it is our caching @ CloudFlare.

**Comment by rnovacek** [comment]
> It is not your caching, it is our caching @ CloudFlare.

I get that, but why people get different results depending if they tried accessing the icon before it was deployed?

**Comment by Robbe-B** [comment]
Because, I assume, first time when your custom integration in HA access the link (when it wasn't deployed yet) => this 404 result was stored in the caching mechanism for your IP-adress.

**Comment by rnovacek** [comment]
Per IP cache sounds like unnecessary complexity over just one global cache for this usecase, but I'm fine with this explanation. Thanks everyone.

**Comment by frenck** [comment]
> I get that, but why people get different results depending if they tried accessing the icon before it was deployed?

Because cloudflare is huge and has many endpoints around the world. Some may have cached a different version, depending on when it was requested.

As said and documented, all will be flushed on the next major HA release.

**Comment by Robbe-B** [comment]
Thanks for the clarification, @frenck !

**Pull request merged**
