### PR TITLE
alsavopro

### PR DESCRIPTION
**Pull request by gllmlbrt**
## Proposed change

Introduction of logo for custom integration related to Alsavo Heat Pump currently under development.
https://github.com/goev/AlsavoProHomeAssistantIntegration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The branding provided in this PR, does not seem to match the branding used by the manufacturer:

CleanShot 2024-01-04 at 10 55 54@2x

CleanShot 2024-01-04 at 10 56 32@2x

../Frenck

**Comment by gllmlbrt** [comment]
This is a fair point, and I was considering the same issue. However, the real (behind it all) manufacturer is I think "Zealux" of China.
So I elected to use the logo relevant to the point of the planned custom integration, which is to replace the actual app used to control all those heatpumps, irrespective of the brainding and manufactuer.

So the app is called "AlsavoPro" hence the domain name rather than this particular brand "Alsavo" which is one of many of the resellers of heatpumps using the app AlsavoPro.

This app is available on both play store and app store, with the logo I propose in this PR.

**Comment by frenck** [comment]
Right, but app icons is not something we collect in this repository.

**Comment by gllmlbrt** [comment]
Ok I will adopt the Alsavo Reseller branding then and come with an update.

Side note though, isn't it the same with Ewelink ? it is only an app, which is in this repo, while the manufacturer is effectively iTead/SonOff ?

**Comment by frenck** [comment]
Ewelink and Sonoff are two different companies (Sonoff uses technology from Ewelink).

**Review by gllmlbrt — COMMENTED** [review]
Logos updated as requested.

**Review by frenck — APPROVED** [review]
Thanks, @gllmlbrt 👍 

../Frenck

**Pull request merged**
