### PR TITLE
Initial implementation of EnaSolar Integration

### PR DESCRIPTION
**Pull request by geustace**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:
- Link to documentation pull request:
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The builds fail at this point, because of:

```
Error: Invalid icon size! Size is 100x100px, must be 256x256px: core_integrations/enasolar/icon.png
```

Could you take a look?

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by geustace** [comment]
Can we remove the 'awaits-parent' please as it is now needed by my custom_component.

**Review by frenck — APPROVED** [review]
Yeah! Sure!

Thanks, @geustace 👍

**Pull request merged**
