### PR TITLE
logo for sunsynk

### PR DESCRIPTION
**Pull request by francoisverbeek**
## Proposed change

Adding the logo for Sunsynk

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/118111
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/32941
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [X ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is linked to a PR in the core repository, meaning this will be added as a core integration. However, in this PR brand assets for a custom integration is added.

Is this a mistake or am I missing something?

../Frenck

**Comment by francoisverbeek** [comment]
Sorry didn't realise the difference between core and custom, let me review the doc and adjust. Thank you

**Comment by francoisverbeek** [comment]
I don't think I will be able to get the core integration merged in reasonable time (I have issues with the build process and the dev containers, in addition to a relatively long review process) - I'll be using this for personal use only vi HACS for now. Should I keep this review open or close it?

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed as well 👍 

../Frenck

**Pull request closed without merging**
