### PR TITLE
Add new Apple AirPlay Integration

### PR DESCRIPTION
**Pull request by georgezhao2010**
## Type of change
* [ ]  Add a new logo or icon for a new core integration
* [ ]  Add a missing icon or logo for an existing core integration
* [x]  Add a new logo or icon for a custom integration (custom component)
* [ ]  I've opened up a PR for my custom integration on the [Home Assistant Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
* [ ]  Replace an existing icon or logo with a higher quality version
* [ ]  Removing an icon or logo

## Additional information
* This PR fixes or closes issue: fixes #
* Link to code base pull request:
* Link to documentation pull request:
* Link to integration documentation on our website:

## Checklist
* [x]  The added/replaced image(s) are **PNG**
* [x]  Icon image size is 256x256px (`icon.png`)
* [x]  hDPI icon image size is 512x512px for  (`icon@2x.png`)
* [x]  Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
* [x]  hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I'm pretty sure we are not allowed to use this image:

image


Additionally, this repository collects brand images, the above-listed image is not a brand.

**Comment by georgezhao2010** [comment]
> I'm pretty sure we are not allowed to use this image:
> 
> image
> 
> Additionally, this repository collects brand images, the above-listed image is not a brand.


Is this one OK？
logo

**Comment by frenck** [comment]
The brand image would be the apple logo in this case

**Comment by georgezhao2010** [comment]
> The brand image would be the apple logo in this case

I'd like to confirm if this apple logo could be used in this case. If no, what kind of image could be used?

**Comment by frenck** [comment]
I'm sorry, I've responded 2 times before now. I'm not sure how much clearer I can be.
This is a brands repository, we collect brand images. This is from the Apple brand, I would expect brand images from Apple, with the Apple branding/logo.

You are submitting some kind of logo from their products, this is not what we are trying to capture in this repository.

**Review by frenck — APPROVED** [review]

**Pull request merged**
