### PR TITLE
Add images for Sanix integration

### PR DESCRIPTION
**Pull request by tomaszsluszniak**
## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/106785
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/30587
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons provided are not used as brand icons by BIT Complex as it seems. 

../Frenck

**Comment by tomaszsluszniak** [comment]
I thought that the brand and product icons can be mixed here. I updated the logos to be the product logos.

**Review by frenck — CHANGES_REQUESTED** [review]
>  I updated the logos to be the product logos.

That would be incorrect, we collect brands not product assets (hence the repository name).

../Frenck

**Comment by tomaszsluszniak** [comment]
I focused on that:
https://github.com/home-assistant/brands/blob/c0a3e469c1138f9157db68948c287edbfff1d1b7/README.md?plain=1#L27

But, okay I will fix that.

**Review by frenck — APPROVED** [review]
Thanks, @tomaszsluszniak 👍 

../Frenck

**Pull request merged**
