### PR TITLE
Search brand files for unknown integrations

### PR DESCRIPTION
**Pull request by b-uwe**
## Proposed change

With the example of HELTUN and https://www.home-assistant.io/integrations/#version/2023.3 I propose that when integration icons cannot be found we search amongst the brand icon first before we show a placeholder

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo
- [x] None of the above 😬

## Additional information

- I never used netlify!
- I quickly googled the syntax but there is a chance I have made beginners mistakes
- I **did** some testing and it looks good to me, but I might have missed (even not so edgy) edge cases.
- In the worst case, it serves the purpose of showing my intent which I hope makes sense 😁 

## Checklist

All irrelevant in this case!

### CODE REVIEW

**Comment by ludeeus** [comment]
IMO we should fix the documentation site, not adjust this here.

**Comment by frenck** [comment]
Agree, this change is not right an breaks integration assets fallback completely

**Comment by b-uwe** [comment]
I'm tempted to disagree with
> breaks integration assets fallback completely

as it's just an additional 302, but fair enough to fix it where the origin of the problem is. Can one of you link me to where the magic happens? I wouldn't find it myself - or not in a reasonable amount of time

**Comment by b-uwe** [comment]
It would have removed all existing integration placeholder images and replaced them with the placeholder fallback image of the brands 🤷. The result would have been the same, just an additional 302. I did ofc. test with valid and invalid integration  names

**Comment by b-uwe** [comment]
Thx for https://github.com/home-assistant/home-assistant.io/pull/26427 🙏 

It's the better way to do it!

**Pull request closed without merging**
