### PR TITLE
add logos and icons for tuya v2 integration

### PR DESCRIPTION
**Pull request by zlinoliver**
## Proposed change

Tuya Smart always strive to provide the best development experience possible and keep updating our Home Assistant integration capabilities. Since the old version of Tuya Home Assistant integration supports limited categories and control commands, now we bring you our new integration with extended support for more categories and commands.

Our new integration is built on Tuya’s standard [Open APIs](https://developer.tuya.com/en/docs/cloud) and tackles the limits of categories and accessible control commands. We deliver more development-friendly features including virtual device debugging, official authorization, and technical supports, which will help you efficiently work on development with the Tuya ecosystem.

The existing [Tuya Integration](https://www.home-assistant.io/integrations/tuya/) is no longer maintained by Tuya officially,  and will be deprecated. The estimated deprecation date is 2021.12.31. The new integration will be officially maintained by the Tuya Developer Team, for more information of the migration, please check this documentation [How to Migrate the Tuya Home Assistant Integration from the Old Version](https://developer.tuya.com/en/docs/iot/migrate-from-an-older-version?id=Kamee9wtbd00b)

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
- [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @zlinoliver, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2619).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Why not replace the exiting integration in our core, so it is instantly available for all Home Assistant users?

**Comment by zlinoliver** [comment]
Hi @frenck , 

1. The new and existing Tuya integration are incompatible with each other, we will add more features to the new integration and provide technical support. The existing Tuya integration cannot be replaced by the new one directly, they are developed on different Tuya cloud APIs.
2. The existing Tuya integration will be deprecated by the end of this year, the estimated deprecation date is 2021.12.31. We will provide at least 6 months for our Home Assistant users to migrate to the new integration. Before that, these two integrations will exist at the same time.
3. The existing Tuya integration has around 6435 installations, if we replace it with the new integration directly, our Home Assistant users will be affected seriously. It's not user friendly.
4. The funtionalities of the new Tuya integration still need to be updated iteratively based on our users' feedbacks. More drivers for Tuya Smart's supported products are also required to be developed.

**Review by tsutsuku — COMMENTED** [review]
Done

**Comment by zlinoliver** [comment]
Hi @frenck any update on this PR?

**Review by zlinoliver — COMMENTED** [review]
uploaded icons are reviewed.

**Comment by frenck** [comment]
> Hi @frenck any update on this PR?

I'll get to it soon. In the meantime, we are going to try to reach out to you guys. We really would like to help out and talk about improving the user experience for our and your users.

../Frenck

**Comment by zlinoliver** [comment]
> > Hi @frenck any update on this PR?
> 
> I'll get to it soon. In the meantime, we are going to try to reach out to you guys. We really would like to help out and talk about improving the user experience for our and your users.
> 
> ../Frenck

Hi @frenck , thanks for the reply. Could you help to send me your email address? We can have further conversation through emails. Or you can send us an email using developer@tuya.com. Looking forward to talking with you guys!

**Comment by frenck** [comment]
Somehow not the full CI is triggered, I'm closing and re-opening to see if the CI picks up.

**Review by frenck — CHANGES_REQUESTED** [review]
@zlinoliver Could you remove the images for the `core_integrations` PR from this PR?

Thanks! 👍

**Comment by zlinoliver** [comment]
> @zlinoliver Could you remove the images for the `core_integrations` PR from this PR?
> 
> Thanks! 👍

Hi @frenck , sorry for the late reply! The images for the core_integrations is removed in the PR. Please help to merge it, thanks a lot!

**Review by balloob — APPROVED** [review]

**Pull request merged**
