### PR TITLE
Add dreo integration icons and logos

### PR DESCRIPTION
**Pull request by dreo-team**
## Proposed change

Add dreo integration icons and logos

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/119075
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/32869
- Link to integration documentation on our website: 
- Link to custom integration repository:https://github.com/dreo-team/home-assistant-custom

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by dreo-team** [comment]
Hey home-assistant!
Is it convenient to speed up the review process?
Thanks,
The Dreo Team

**Review by frenck — CHANGES_REQUESTED** [review]
This PR has some conflicting things.

1. The PR description links a PR to add this integration to the core repository, however, this PR is trying to add it as a custom integration?
2. There is a link to a custom integration, which has a conflicting integration domain with the PR in the core repository, both use the `dreo` domain, which will cause conflicts for users.

Can you take a look?

../Frenck

**Comment by dreo-team** [comment]
> 这份 PR 有一些互相矛盾的内容。
> 
> 1. PR 描述链接一个 PR 以将此集成添加到核心存储库，但是，此 PR 试图将其添加为自定义集成？
> 2. 有一个指向自定义集成的链接，该集成域与核心存储库中的 PR 存在冲突，两者都使用该`dreo`域，这会给用户带来冲突。
> 
> 你能看一下吗？
> 
> ../弗伦克

dreo 

> 这份 PR 有一些互相矛盾的内容。
> 
> 1. PR 描述链接一个 PR 以将此集成添加到核心存储库，但是，此 PR 试图将其添加为自定义集成？
> 2. 有一个指向自定义集成的链接，该集成域与核心存储库中的 PR 存在冲突，两者都使用该`dreo`域，这会给用户带来冲突。
> 
> 你能看一下吗？
> 
> ../弗伦克

custom integration dreo and integration domain dreo PR All submitted by us，What to do next?

> This PR has some conflicting things.
> 
> 1. The PR description links a PR to add this integration to the core repository, however, this PR is trying to add it as a custom integration?
> 2. There is a link to a custom integration, which has a conflicting integration domain with the PR in the core repository, both use the `dreo` domain, which will cause conflicts for users.
> 
> Can you take a look?
> 
> ../Frenck

custom integration dreo and integration domain dreo PR All submitted by us，What to do next?

**Comment by frenck** [comment]
> What to do next?

Resolve the conflict as pointed out in the review comment above.

../Frenck

**Comment by dreo-team** [comment]
> > 接下来做什么？
> 
> 解决上述评审意见中指出的冲突。
> 
> ../弗伦克



> > What to do next?
> 
> Resolve the conflict as pointed out in the review comment above.
> 
> ../Frenck

Can you tell me which PR conflicts? It is best to have a PR address.  Thanks!

**Comment by frenck** [comment]
> Can you tell me which PR conflicts? It is best to have a PR address. Thanks!

https://github.com/home-assistant/brands/pull/5487#pullrequestreview-2077019249

**Comment by frenck** [comment]
There is not `git` conflict, my comment doesn't write or say that.

> There is a link to a custom integration, which has a conflicting integration domain with the PR in the core repository, both use the dreo domain, which will cause conflicts for users.

☝️  There is a domain conflict.

Additionally, this PR links to a custom integration and a core integration. Which is odd, as brands are either for a core domain or a custom domain, not both.

../Frenck

**Comment by dreo-team** [comment]
> There is not `git` conflict, my comment doesn't write or say that.
> 
> > There is a link to a custom integration, which has a conflicting integration domain with the PR in the core repository, both use the dreo domain, which will cause conflicts for users.
> 
> ☝️ There is a domain conflict.
> 
> Additionally, this PR links to a custom integration and a core integration. Which is odd, as brands are either for a core domain or a custom domain, not both.
> 
> ../Frenck

Excuse me! First PR, trouble!


Is there something wrong here?

**Comment by frenck** [comment]
I'm sorry, I'm not sure how to make this more clear. 

We are dealing with a language gap (considering you seem to be using a translation tool for this). I would advise you to see if you can find someone who can help with the translating so you can understand the issue and review comments better.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
The CI is not passing, can you please take a look?

../Frenck

**Comment by dreo-team** [comment]
Hello! How is the PR review going?

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
