### PR TITLE
Logo and icon for xComfort Bridge

### PR DESCRIPTION
**Pull request by jankrib**
## Proposed change

Logo and icon for xComfort Bridge

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons look like a combination of the logo and a product. Please only use the manufacturer's branding and not product images or logos.

Thanks! 👍 

../Frenck

**Comment by jankrib** [comment]
I agree that the icon is terrible. It is the official icon for the app, though.
This is how it looks on the google store:
https://play.google.com/store/apps/details?id=com.eaton.corp.xComfortBridge

Do you still want me to change it?

**Comment by frenck** [comment]
We are not collecting app icons in this repository, but the manufacturer's branding, so yes, please change it to the manufacturer's branding.

**Comment by jankrib** [comment]
Thanks for the clarification. Updated the files now

**Review by frenck — APPROVED** [review]
Thanks, @jankrib 👍 

../Frenck

**Pull request merged**
