### PR TITLE
Add dobiss brand

### PR DESCRIPTION
**Pull request by kesteraernoudt**
## Proposed change

Add the dobiss brand

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/wheels-custom-integrations/pull/222
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @kesteraernoudt 👍 

Happy New Year 🥂

**Comment by kesteraernoudt** [comment]
thanks @frenck 
Happy New Year to you to!

**Comment by kesteraernoudt** [comment]
Is it expected that https://brands.home-assistant.io/dobiss/logo.png is not accessible, but https://brands.home-assistant.io/dobiss/icon.png, https://brands.home-assistant.io/dobiss/icon@2x.png and https://brands.home-assistant.io/dobiss/logo@2x.png are? All 4 files are in uploaded and visible in the repository...

**Comment by frenck** [comment]
This is caused by cache, which will be flushed each Home Assistant Core release.

**Comment by kesteraernoudt** [comment]
ah ok, good to know, thanks!

**Pull request merged**
