### PR TITLE
Add brand icons for NIBE

### PR DESCRIPTION
**Pull request by priiduonu**
## Proposed change

Add brand icons for NIBE integration (custom component)
https://github.com/elupus/hass_nibe

## Type of change

- [ ] Add a new logo or icon for a new integration
- [x] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by cogneato** [comment]
Icon is fine but NIBE? Can you fill out the template?

**Comment by priiduonu** [comment]
Anything else I should do? As this is an existing custom component, it is impossible to fill in the links in the template.

**Comment by frenck** [comment]
This repository is not for custom components/integrations.

**Comment by priiduonu** [comment]
Well, it would be nice to mention somewhere in the README, to save time for both of us.

**Comment by frenck** [comment]
It does: `The ./src folder contains a folder for each domain Home Assistant provides an integration for. `

This integration is not provided by Home Assistant.

**Pull request closed without merging**
