### PR TITLE
Added logo for pse_grid_stat custom component

### PR DESCRIPTION
**Pull request by mobrembski**
## Proposed change

Just added a logo for pse_grid_stat - my custom component to show current Poland energy grid statistics

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
    https://github.com/home-assistant/wheels-custom-integrations/pull/561
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @mobrembski, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3023).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
On social media, PSE seems to be using a different icon:

image

And their logo also looks different:

image

Could you please use the actual brand assets?

Thanks 👍

**Comment by mobrembski** [comment]
@frenck Sorry, but i cant understood what is the difference between my logos and those from Social Media?
I've removed text "Polskie Sieci Energetyczne" because it was too wide to use it as a logo

**Comment by frenck** [comment]
> I've removed text "Polskie Sieci Energetyczne" because it was too wide to use it as a logo

That is exactly the issue. We should not mess with the branding of a company.

**Comment by mobrembski** [comment]
> > I've removed text "Polskie Sieci Energetyczne" because it was too wide to use it as a logo
> 
> That is exactly the issue. We should not mess with the branding of a company.

Ok but any idea how to deal with it?
Current logo has about 628 px wide, it cant fit into icon (256px x 256px)

**Comment by mobrembski** [comment]
> > I've removed text "Polskie Sieci Energetyczne" because it was too wide to use it as a logo
> 
> That is exactly the issue. We should not mess with the branding of a company.

Maybe this way?
Icon stays as it was, logo is just same as in social media

**Comment by frenck** [comment]
That icon is out of perspective. As I stated above, we should not mess/edit branding. Please use their original brand assets. We might have opinions on how their branding looks, but that is not our call or decision to make.

**Comment by mobrembski** [comment]
> 

I don't really understand :)
So we should deal with original brand but we cannot crip the icon to be in perspective?
So how i would do that?

**Comment by frenck** [comment]
By adding whitespace to ensure the logo isn't stretched.

**Comment by mobrembski** [comment]
> By adding whitespace to ensure the logo isn't stretched.

Hmm ok is there a way to test it locally?

**Comment by frenck** [comment]
> Hmm ok is there a way to test it locally?

It is a regular image? What do you mean by locally testing it?
Any computer nowadays can view an image...?

**Comment by mobrembski** [comment]
> > Hmm ok is there a way to test it locally?
> 
> It is a regular image? What do you mean by locally testing it? Any computer nowadays can view an image...?

:)

I wish to see icon and logo inside my local home assistant settings->integrations to see how it looks in real

**Comment by frenck** [comment]
> I wish to see icon and logo inside my local home assistant settings->integrations to see how it looks in real

The same as it looks on GitHub or your image viewer... 🤷

**Comment by mobrembski** [comment]
> > I wish to see icon and logo inside my local home assistant settings->integrations to see how it looks in real
> 
> The same as it looks on GitHub or your image viewer... shrug

HA doesn't scale images at all while rendering list?
If so, then right :D

**Comment by frenck** [comment]
> HA doesn't scale images at all while rendering list?

We scale, depending on the place used, but don't change the aspect ratio of the image

**Comment by apichlinski** [comment]
@frenck I'm also interested in this brand logo in custom integration.
What about official Twitter account of PSE? They used square logo maybe we could use one of them?
For example: [twitter](https://twitter.com/pse_pl), [spotify](https://open.spotify.com/show/2xbqSk3Q1nmNStqm6N4DRm), [facebook[(https://www.facebook.com/Polskie-Sieci-Elektroenergetyczne-SA-120969081353989/)

**Comment by frenck** [comment]
@apichlinski I'm not sure about your question. The requirements for this repository are described in the repository readme.

**Pull request closed without merging**
