### PR TITLE
Added Wolf SmartSet logos

### PR DESCRIPTION
**Pull request by adamkrol93**
## Proposed change

Added logo and icon for new WolfLink integration.

## Type of change

- [x] Add a new logo or icon for a new integration
- [ ] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/34104
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/12917
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by adamkrol93** [comment]
@frenck parent merged.

**Comment by adamkrol93** [comment]
@frenck Main PR merged.

**Comment by frenck** [comment]
@adamkrol93 No need to ping for those things. Please have patience. Thanks.

**Comment by adamkrol93** [comment]
I though so. But I see that there is no link with main PR here, this is why I wrote here. I though that I did sth wrong while creating PR. It took almost 3,5 month to merge main PR do I am patient :)

**Pull request merged**
