### PR TITLE
Add logos for Moebot custom integration

### PR DESCRIPTION
**Pull request by Whytey**
## Proposed change

Minimum icon set for the [MoeBot custom integration](https://github.com/Whytey/moebot-hass-integration).  MoeBot is a robot lawn mower in Australia.  The custom integration is installed via HACS.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- Link to custom integration repository: https://github.com/Whytey/moebot-hass-integration

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @Whytey 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Oh, the CI seems to be failing @Whytey...

Can you take a look? 👍 

../Frenck

**Comment by Whytey** [comment]
All fixed - thanks @frenck

**Review by frenck — APPROVED** [review]
Thanks, @Whytey 👍 

../Frenck

**Pull request merged**
