### PR TITLE
Add kostal_piko branding

### PR DESCRIPTION
**Pull request by scheidtdav**
## Proposed change

Adds symlinks from the already existing kostal_plenticore images to a new kostal_piko integration I have been working on.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/82391
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/25002
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/kostal_piko

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
- If you symlink all assets from a folder, please symlink the folder instead of the individual assets.
- Instead of symlinking with `kostal_plenticore`, please create the `kostal` brand in the core repository and in the brand's repository and link both `kostal_piko` and `kostal_plenticore` against that brand.

../Frenck

**Comment by scheidtdav** [comment]
Sorry for the additional commits, I just realized those textfiles for linking aren't actually textfiles.
Added proper symlinks now to the core_brands/kostal folder now. Hope the workflow is fine with that.

**Comment by frenck** [comment]
The parent PR (in the Core repository) needs a brand file/definition too. This is currently missing (and thus doesn't match this brands PR).

Please adjust the parent PR in Core.

../Frenck

**Comment by scheidtdav** [comment]
Thanks @frenck, added the missing brand file in [this commit](https://github.com/home-assistant/core/pull/82391/commits/224f9eaf4a2c7787f0b7b5b44ce87cbc19b941d7).

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
