### PR TITLE
Add icons & logos for iCloud3 custom component

### PR DESCRIPTION
**Pull request by gcobb321**
## Proposed change

Add icons and logos for the iCloud3 Custom Component

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @gcobb321, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2965).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
This custom integration integrates Apple devices. I would have excepted it to use the Apple branding for that matter.

**Comment by gcobb321** [comment]
"This custom integration integrates Apple devices. I would have excepted it to use the Apple branding for that matter."

I'm not sure what you mean and would appreciate some clarification. The Apple iCloud icon is use by the HA iCloud core integration and I did not want to lead to confusion by also using it.

Would you like me to change it to the Apple iCloud icons but say iCloud3 in the logo? (No problem)
Would you like me to change it but be a little different (maybe 3 Apple iClouds with different colors)? (No problem)

**Comment by frenck** [comment]
The brands repository represents the branding of the devices integrated into Home Assistant, not the branding of the integration itself. Thus I expected Apple branding to be used.

**Comment by gcobb321** [comment]
Understood. I will change icons to use the same icons as iCloud core integration. The iCloud core integration logo has ‘iCloud’ on it. I will use that also rather than ‘iCloud3’

————————
Gary Cobb

**Comment by frenck** [comment]
3rd time I'm going to respond with the same answer now, so: The brands repository represents the branding of the devices integrated into Home Assistant, not the branding of the integration itself. Thus I expected Apple branding to be used.

**Comment by gcobb321** [comment]
The icons have been updated. Thank you.

**Review by frenck — APPROVED** [review]
Thanks, @gcobb321 👍

**Pull request merged**
