### PR TITLE
Add Logo for Mawaqit

### PR DESCRIPTION
**Pull request by mohaThr**
Domain : mawaqit

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I could not find the public git repository providing this integration. Could you please point me to it? 

Thanks! 👍 

../Frenck

**Comment by mohaThr** [comment]
Here's the public repository : https://github.com/mawaqit/home-assistant

**Review by frenck — APPROVED** [review]
Thanks, @mohaThr 👍 

../Frenck

**Comment by mohaThr** [comment]
Thanks for the merge ! I have a little problem though. 

The logo is shown here in the details of the integration :
Screenshot

But here in the integration dashboard, the logo doesn't seem to be displayed :
Capture d’écran 2023-09-20 à 19 59 19

Can you help me on what should I do to fix that please ?

**Comment by frenck** [comment]
@mohaThr That is caching. Our cache is flushed with every major release of Home Assistant.

.>?Frenck

**Comment by mohaThr** [comment]
Thank you ! Have a great day !

**Pull request merged**
