### PR TITLE
Add new custom component adax

### PR DESCRIPTION
**Pull request by Danielhiversen**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component): https://github.com/Danielhiversen/home_assistant_adax
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by Danielhiversen** [comment]
Not an integration yet, so closing this for now

**Review by frenck — CHANGES_REQUESTED** [review]
Their logo is available on their website as SVG.

Can we use that SVG to generate the logos images as well, to make the brand images complete?

<https://adax.no/content/themes/simpleCom/assets/images/logo.svg>

**Review by frenck — CHANGES_REQUESTED** [review]
Not sure what happened to the logo? They look blown up. Did you use the SVG?

Here are 2 alternatives for the logo that are resized, ready and have the max possible resolution.

adax_logo@2x
adax_logo

**Comment by Danielhiversen** [comment]
Hmm, I tried to use the svg, but I probably did something wrong.
I have now added your files.
Thank you so much.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @Danielhiversen 👍

**Pull request merged**
