### PR TITLE
Added icon for custom integration fronius_inverter

### PR DESCRIPTION
**Pull request by safepay**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please use (copy) the images from here: <https://github.com/home-assistant/brands/tree/master/core_integrations/fronius>

They seem to be a better fit (and a more complete set).

**Comment by safepay** [comment]
The new icons are for a HACS integration that is used by a lot of people.

It is for the same Fronius inverter, but has a lot more flexibility and a lot of people are using it.

**Comment by frenck** [comment]
@safepay Go to hear! But that is not related to my change request in any way.

**Comment by safepay** [comment]
I don't know how to do that.

**Pull request closed without merging**
