### PR TITLE
Add icons for my custom integration oekofen_pellematic_compact 

### PR DESCRIPTION
**Pull request by dominikamann**
## Proposed change
Add icons for custom integration https://github.com/dominikamann/oekofen-pellematic-compact. I want to make my integration easier to use by the HomeAssistant-Community. Thanks to HACS this is possible :)

## Type of change
- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information
- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist
- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The provided icons are product images, not branding.

Please use the branding of the manufacturer instead

CleanShot 2023-01-20 at 22 05 25


../Frenck

**Comment by dominikamann** [comment]
@frenck i used the product logo because the integration wors curently only for the "Pellematic" product series. I updated the logos to the brand logo. Thank you for the hint.

**Review by frenck — APPROVED** [review]
Thanks, @dominikamann 👍 

The product type can still be reflected in the integration name/title :) 

../Frenck

**Comment by dominikamann** [comment]
@frenck Are there any further action required from my side or will the pull request be merged automatically? Thanks a lot!

**Comment by frenck** [comment]
You have to wait patiently.

**Comment by dominikamann** [comment]
Ok I will try 👍

**Pull request merged**
