### PR TITLE
Fix Android TV domain + transparent logo

### PR DESCRIPTION
**Pull request by Quentame**
## Proposed change

Fix Android TV domain

## Type of change

- [ ] Add a new logo or icon for a new integration
- [ ] Add a missing icon or logo for an existing integration
- [x] Replace an exiting icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by Quentame** [comment]
@frenck Can the CI check domains ?

**Comment by frenck** [comment]
No, we can't, problem is that ideally, one opens a PR when opening a PR on the code base and documentation repo. At that point, it simply doesn't exist yet.

**Comment by Quentame** [comment]
@frenck https://brands.home-assistant.io/androidtv/logo@2x.png

Leads to the placeholder and https://brands.home-assistant.io/android_tv/logo@2x.png is still working ...

How the brands website is updated ?
At `master` commit/merge ?

**Comment by frenck** [comment]
@Quentame At merge to master, the Netlify builds trigger and a new version gets published on Netlify. However, we use Cloudflare in front of everything we have.

Considering the amount of traffic we have across the platform, it saves us terabytes of data traffic. The downside, is that changes are not visible instantly.

<https://github.com/home-assistant/brands#caching>

So for these images, once in the Cloudflare cache, they will stay in there for a long long time, unless we flush the cache. In general, we flush the cache on each release of Home Assistant Core.

**Pull request merged**
