### PR TITLE
added images for custom componente vartastorage

### PR DESCRIPTION
**Pull request by Vip0r**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- https://github.com/Vip0r/brands/tree/master/custom_integrations/vartastorage
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ X ] The added/replaced image(s) are **PNG**
- [ X ] Icon image size is 256x256px (`icon.png`)
- [ X ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ X ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ X ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by frenck** [comment]
I cannot find the public repository providing this custom integration, could you point me to it?

**Comment by Vip0r** [comment]
> I cannot find the public repository providing this custom integration, could you point me to it?

The integration is not yet published. I plan for an pull request in the next days (currently i am testing on my own dev-environment). Is it a requirement that the integration already is published before adding the images?

**Comment by frenck** [comment]
> The integration is not yet published.

I cannot review or approve this PR without a actual integration 🤷

**Comment by Vip0r** [comment]
> > The integration is not yet published.
> 
> I cannot review or approve this PR without a actual integration 🤷

Okay, got it. Can we let this change in the current state ? I plan to publish the integration within next days and would post this link afterwards here

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is targeting the `custom_integrations` folder, while the linked PR is a PR against our core repository. Therefore, the folder targeted should be the `core_integrations` folder.

**Comment by Vip0r** [comment]
Updated target folder.
Sorry for the inconvenience - its my first PR :/

**Comment by Vip0r** [comment]
as the folder for the integration itself need to be changed to varta_storage i assume i need to change this for the brand images as well.

**Comment by Vip0r** [comment]
Hey frenck,
updated now the folder name according to the new domain name you recommended within the PR for the new integration

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by Vip0r** [comment]
Hi there,
i plan to publish an [integration in the HACS ](https://github.com/Vip0r/vartastorage-hacs)until my [PR to the core repo](https://github.com/home-assistant/core/pull/63736) will be approved 

Can you please merge this to provide the commuity the VARTA Brand?

**Comment by tjorim** [comment]
Please adjust your PR in that case, it should not go into core_integrations but custom_integrations: Contains images for custom integrations (custom components).

**Comment by Vip0r** [comment]
done @tjorim : moved files from core_integrations to custom_integrations

**Comment by frenck** [comment]
Closing PR as the linked parent PR has been closed.

**Pull request closed without merging**
