### PR TITLE
Added Roth icons for a new integration

### PR DESCRIPTION
**Pull request by kasperbirk**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by kasperbirk** [comment]
Sorry.. Didn't see the requirement about the size

**Review by frenck — CHANGES_REQUESTED** [review]
This PR adds a new brand for core, but I don't see a PR that actually adds the brand to it? Could you point me to the Core PR that adds this brand?

Thanks! 👍 

../Frenck

**Comment by kasperbirk** [comment]
Hi frenck

I am still working on the integration and not ready for PR. But need the logo is live to see it work in my dev environment

**Comment by frenck** [comment]
We won't handle PRs that don't have a matching upstream PR.

../Frenck

**Comment by kasperbirk** [comment]
Sorry. Its new for me to use Git in so large project. Will try again...

**Comment by frenck** [comment]
A little while later, there is no PR that links to this one. So, for now, I'll go ahead and close this one. Feel free to re-open it when the Core PR is available.

../Frenck

**Pull request closed without merging**
