### PR TITLE
Add logo for deva4004 custom integration

### PR DESCRIPTION
**Pull request by s1lvi0**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @s1lvi0 👋 

Thanks for the PR! I tried to find the public repository that provides the `deva4004` integration (domain), but I could not find it. Would you be so kind as to give me an URL for it?

Thanks already!

../Frenck

**Comment by s1lvi0** [comment]
I'm starting to write integration these days. I don't have the repository yet.

**Comment by frenck** [comment]
Hi @s1lvi0 ok, thanks for letting me know.

Going to close this PR for now, as there is no path forward at this point. Feel free to re-open when the integration is publicly available.

Thanks! 👍 

../Frenck

**Comment by s1lvi0** [comment]
this is the repository of the custom integration: [https://github.com/s1lvi0/deva4004](https://github.com/s1lvi0/deva4004)

**Pull request closed without merging**
