### PR TITLE
Added icons for teamtracker custom configuration.

### PR DESCRIPTION
**Pull request by vasqued2**
## Proposed change

Add icons for [ha-teamtracker](https://github.com/vasqued2/ha-teamtracker) custom component.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/vasqued2/ha-teamtracker
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I would expect just the ESPN branding here, the provided branding is not directly used by ESPN as it seems.

../Frenck

**Comment by vasqued2** [comment]
Here (https://www.espn.com/apis/devcenter/branding.html) is the source of the ESPN branding.  I'll be glad to replace entirely w/ the ESPN logo if that's what you recommend.  Just let me know.

**Comment by vasqued2** [comment]
Updated w/ ESPN branding per request.

**Review by frenck — APPROVED** [review]
Thanks, @vasqued2 👍

**Pull request merged**
