### PR TITLE
Add logos for wyzeapi

### PR DESCRIPTION
**Pull request by JoshuaMulliken**
## Proposed change

Adding logos and icons for the [wyzeapi](https://github.com/JoshuaMulliken/ha-wyzeapi) integration

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The logos added are white on a transparent background. We aim to use our images (at this point) to be visible on our default light theme. Unfortunately, these aren't visible.

**Comment by JoshuaMulliken** [comment]
@frenck I have updated the logos to be visible on light themes. Please let me know if this is acceptable.

Thank you (and the rest of the HA crew) for all your amazing work on this. Truly one of the most dynamic open-source communities!

**Review by frenck — CHANGES_REQUESTED** [review]
The logo & icons are now the same, in those cases, the logo should not be added (duplicate).

However, the Wyze logo is available as SVG right here:
<https://commons.wikimedia.org/wiki/File:Wyze_Labs_Logo.svg>

This means it should be fairly easy to add (see readme in this repository for some online tool suggestions).

**Comment by JoshuaMulliken** [comment]
@frenck I transformed and uploaded the linked logo. The two are now not the same. Thank you for your help!

**Review by frenck — APPROVED** [review]
Thanks, @JoshuaMulliken 👍

**Pull request merged**
