### PR TITLE
Add Napoleon brand for Napoleon eFIRE custom integration

### PR DESCRIPTION
**Pull request by kaechele**
## Proposed change
Add Napoleon brands used in this custom_component: https://github.com/kaechele/napoleon-efire/

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
Thanks @kaechele 

It might make sense to add some additional ones for dark mode in a followup

**Comment by kaechele** [comment]
Thanks for merging!
I somehow was under the impression the frontend would use the regular logos/icons when there are no dark variants available but it doesn't, so there currently is a blank space.
The logo as submitted should work well for dark mode, so a simple copy or symlink may be sufficient.

**Comment by bdraco** [comment]
It should work in dark mode as well (it might take a while for the cache to clear), I just wasn't sure it would look good given its mostly black (but if you tested it, I'm sure its fine)

cheers

**Comment by kaechele** [comment]
This is what it would look like:
image

image

image

**Pull request merged**
