### PR TITLE
Add custom integration neta_vehicle logo.png

### PR DESCRIPTION
**Pull request by netcookies**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
The logo is the same as the icon already provided.

In those cases, we can omit the logo, as we will automatically use the icon as the fallback.

Since that is the only asset in this PR, I'll go ahead and close this one up.

../Frenck

**Comment by netcookies** [comment]
For unknown reason, the image url `https://brands.home-assistant.io/neta_vehicle/icon.png` not reachable.

**Comment by frenck** [comment]
That is caused by caching. Our caches will be flushed on each main release.

**Comment by netcookies** [comment]
Thk for your reply. It's weird the url `
***@***.***` working
correctly

**Pull request closed without merging**
