### PR TITLE
Add solax_modbus icons

### PR DESCRIPTION
**Pull request by wills106**
## Proposed change

Add icons for custom_component solax_modbus

[solax_modbus](https://github.com/wills106/homsassistant-solax-modbus)

 PR for my custom integration on the Home Assistant Python wheels repository, has been submitted and [merged](https://github.com/home-assistant/wheels-custom-integrations/pull/588)

Edit: Added tick for hDPI logo image as this wasn't originally uploaded on the first commit.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR morphs/combines brand images of different branch and mixes them together into a new branding.

This is not something we can accept.

This custom integration integrates Home Assistant with Solax inverters, I would have expected the Solax branding to be used.

**Comment by frenck** [comment]
> Do I essentially just copy the existing SolaX logo into a new folder solax_modbus without any symlink's?

Yes

**Review by frenck — APPROVED** [review]
Thanks, @wills106 👍

**Comment by wills106** [comment]
This might be a simple / basic question...

But I have noticed this is still showing as "in-progress"

Am I meant to click on "Still in progress? Convert to draft"

I don't want to go and break stuff by randomly clicking things, thinking it's helping when potentially it isn't.

**Comment by frenck** [comment]
@wills106 No I simply forgot to hit the merge button (which would I've picked up on a general round of checks). Anyways, your comment also worked 😄 👍 

Thanks again!

**Comment by wills106** [comment]
> @wills106 No I simply forgot to hit the merge button (which would I've picked up on a general round of checks). Anyways, your comment also worked 😄 👍
> 
> Thanks again!

Was just worried I had messed something up 😅
I don't mean to mither, it's all very new to me.

**Comment by frenck** [comment]
Don't worry, you did well!

**Pull request merged**
