### PR TITLE
myuplinkv3

### PR DESCRIPTION
**Pull request by a-mavrides**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X ] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Hi there @a-mavrides 👋 

Two issues with this PR:

- I could not find the public repository providing this custom integration with the `myuplinkV3` integration domain. Could you please point me to it?
- The integration domain `myuplinkV3` is not a valid integration domain; integration domains cannot contain capital letters.

Could you please take a look?

Thanks! 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Use the wrong review button, meant to ask for changes of course (considering the above message).

Trying again...

**Comment by a-mavrides** [comment]
https://github.com/a-mavrides/myuplinkv3

**Review by frenck — CHANGES_REQUESTED** [review]
The domain name, as pointed out in my previous review, cannot contain capital letters.

CleanShot 2024-06-24 at 20 49 59@2x

Could you look into this?

Thanks 👍 

../Frenck

**Comment by a-mavrides** [comment]
changes done please review

**Review by frenck — APPROVED** [review]
Thanks, @a-mavrides 👍 

../Frenck

**Pull request merged**
