### PR TITLE
Add myq custom component

### PR DESCRIPTION
**Pull request by ehendrix23**
## Proposed change

New authentication API for MyQ requires web scraping which is not supported within the core.
In discussion with the owner @bdraco decision was made to remove MyQ component from core and make it available through HACS instead. See home-assistant/core#46079

This change is to add the icons for myq under custom_components allowing them to be removed from core in the future

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by ehendrix23** [comment]
Validation failed because currently it can still find myq in core. I did not remove them as not to break existing integration in the core until component is fully available within the HACS store.

**Comment by bdraco** [comment]
@ehendrix23 

Its looking more like the amendment to ADR0004 (https://github.com/home-assistant/architecture/pull/512) is going to happen which would open the way forward to updating the core integration.

We usually stay far away from recommending HACS since its not something that the Home Assistant org supports or can make representations for. However, in this case I think we should still proceed with publication to HACS since it will provide an avenue for users to recover when it does break who are comfortable running a non-core integrations.

**Review by frenck — CHANGES_REQUESTED** [review]
This domain collides with a domain of a core integration, thus this PR cannot be merged.

**Comment by ehendrix23** [comment]
> @ehendrix23
> 
> Its looking more like the amendment to ADR0004 ([home-assistant/architecture#512](https://github.com/home-assistant/architecture/pull/512)) is going to happen which would open the way forward to updating the core integration.
> 
> We usually stay far away from recommending HACS since its not something that the Home Assistant org supports or can make representations for. However, in this case I think we should still proceed with publication to HACS since it will provide an avenue for users to recover when it does break who are comfortable running a non-core integrations.
> 
> Apologizes for the confusion and uncertainty the changes in posture have caused. Thanks for being patient and hanging in there on this one.

So core component will most likely stay, hence I should rename mine to like hacs_myq for the HACS version and maybe use that as domain?

**Comment by ehendrix23** [comment]
> This domain collides with a domain of a core integration, thus this PR cannot be merged.

As mentioned, core integration was being scheduled to be removed due to violation of ADR0004 (home-assistant/architecture#512) for authentication.
But, it seems that might now be amended and thus the core integration staying which thus changes all this.

If the core integration is going to be removed, would this PR then be able to move forward as myq domain would become available?
Clearly, if core integration is not going to be remove anymore then I will just close this PR as it won't be needed then. :-)

**Comment by bdraco** [comment]
> 
> So core component will most likely stay, hence I should rename mine to like hacs_myq for the HACS version and maybe use that as domain?

There is precedent for core integrations being overridden by a HACS install with the same namespace so I'm not sure it needs to be renamed. There are a few that use this model to test new features before merging into core so its probably ok to keep the name.

**Comment by ehendrix23** [comment]
> There is precedent for core integrations being overridden by a HACS install with the same namespace so I'm not sure it needs to be renamed (it may even be desirable since it would be easy for someone to add/remove it when/if the core breaks) . There are a few that use this model to test new features before merging into core so its probably ok to keep the name.

Yeah, ended up thinking the same. :-)

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/46079 has merged. We can close this now

**Pull request closed without merging**
