### PR TITLE
Add check_weather integration

### PR DESCRIPTION
**Pull request by denysdovhan**
## Proposed change

I am publishing a new custom integration for checking weather in advance `check_weather`: https://github.com/denysdovhan/ha-check-weather

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by denysdovhan** [comment]
Seems like validate script fails because of other images. Not related to this PR. Am I wrong?

**Comment by frenck** [comment]
> Seems like validate script fails because of other images. Not related to this PR. Am I wrong?

Not really:

```
Error: Invalid logo size! Size is 2304x768px, shortest side must not exceed 256px: custom_integrations/check_weather/logo.png
Error: Invalid icon size! Size is 768x768px, must be 256x256px: custom_integrations/check_weather/icon.png
```

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @denysdovhan 👋 

The CI/tests for this PR are failing. Could you please take a look? I've pasted the specific errors in my comment above, that should help you to address the issue.

Additionally, could you consider changing the color of the icons? In general, the Home Assistant blue color is used on internal integration/helpers/entity components. We want to avoid an end-user to become confused with something official/supported.

Thanks already! 👍 

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @denysdovhan 👍 

../Frenck

**Pull request merged**
