### PR TITLE
Add icon and logo to a new custom integration: Librelink

### PR DESCRIPTION
**Pull request by gillesvs**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This seems to provide a logo for an app instead of the manufacturer branding.

CleanShot 2023-12-11 at 08 56 02@2x

Please use the manufacturer's branding instead.

Thanks! 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Seems like something went wrong here?

CleanShot 2023-12-11 at 15 42 14@2x

**Comment by gillesvs** [comment]
Hello Frenck,

Sorry for errors, this is my first integration from a non professional developper.
the new one is the logo.png
I didn't notice that the old one was named .png.png
Shoud I do a new PR or this is ok to proceed with the new one?

Gilles

**Review by frenck — APPROVED** [review]
Thanks, @gillesvs 👍 

Now it is correct 👍 

../Frenck

**Pull request merged**
