### PR TITLE
Added Daikin Madoka integration

### PR DESCRIPTION
**Pull request by mduran80**
## Proposed change

Added symlink to core integration Daikin to support core integration Daikin Madoka

https://github.com/mduran80/daikin_madoka

## Type of change

- [X] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:  https://github.com/home-assistant/core/pull/45314
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/16228
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @mduran80, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2185).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by mduran80** [comment]
This was a custom component but I have integrated it into Core

**Review by frenck — CHANGES_REQUESTED** [review]
This PR adds 2 integrations. A core and custom one. Please split those into separate PRs.

For the custom version, please don't link to core brand assets.

Thanks 👍

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
