### PR TITLE
Add icon for my integration domain

### PR DESCRIPTION
**Pull request by SCratORS**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @SCratORS, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2389).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by SCratORS** [comment]
Add smart_custom_miio integration

**Comment by SCratORS** [comment]
Add integration icon

**Review by frenck — CHANGES_REQUESTED** [review]
I could not find a reference to `smart_custom_miio`. Could you point me to the repository that provides this custom integration? 

Thanks! 👍

**Comment by SCratORS** [comment]
This integration is currently under development.
https://github.com/SCratORS/smart_custom_miio

**Review by frenck — CHANGES_REQUESTED** [review]
It seems like this is adding your own brand images? I would expect the Xiaomi brand images for this integration?

**Comment by SCratORS** [comment]
Yes, I'm going to use devices of my own design, they have the same exchange protocol as xiaomi.
And you can partially use this integration for xiaomi if you know all the parameters. In order not to confuse users, I have prepared another icon.

**Comment by frenck** [comment]
I can't tell that based on the current state of the custom integration.

Can you point me to the website of the manufacturer?

**Comment by SCratORS** [comment]
I design my own devices for my own purposes. Not for commercial purposes. For myself. It will not be possible to use xiaomi integrations, as they are tied to specific models, so I am developing my own integration, where all the parameters will need to be described manually.

**Comment by frenck** [comment]
In that case, I cannot add these images, as they do not serve a public goal.

**Comment by SCratORS** [comment]
How else can I upload images for my home assistant?

**Comment by SCratORS** [comment]
This does not prevent users from using this integration to communicate with devices that are not supported by Xiaomi

**Comment by frenck** [comment]
> How else can I upload images for my home assistant?

You can't at this point.

> This does not prevent users from using this integration to communicate with devices that are not supported by Xiaomi

No? This is an image, not code.

**Comment by frenck** [comment]
Closing this PR because of the above reasoning.

**Pull request closed without merging**
