### PR TITLE
Add motionEye icon

### PR DESCRIPTION
**Pull request by dermotduffy**
## Proposed change

Adds a motionEye icon for a new custom integration. See related [wheels PR](https://github.com/home-assistant/wheels-custom-integrations/pull/353).

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by dermotduffy** [comment]
Thanks @frenck .

I've decided to go the HACS route, at least for now --  so changed this over to a custom component icon  and add a [wheel  entry](https://github.com/home-assistant/wheels-custom-integrations/pull/353) .

**Comment by dermotduffy** [comment]
@frenck Would you mind stripping `has-parent`/`awaits-parent` on this? (So I can get it in and used for the custom component to start with?). Thanks.

**Review by frenck — CHANGES_REQUESTED** [review]
If this is added as a custom integration, the its must be moved to the `custom_integrations` folder.

**Comment by dermotduffy** [comment]
@frenck Apologies, my mistake. Fixed.

**Review by frenck — APPROVED** [review]
Thanks, @dermotduffy 👍

**Pull request merged**
