### PR TITLE
Added icon for SEMS portal

### PR DESCRIPTION
**Pull request by darek-margas**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/darek-margas/goodwe-sems-home-assistant
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon provided is from a product branding, not the manufacturer branding.
Please use the GoodWe branding instead.

../Frenck

**Comment by darek-margas** [comment]
> The icon provided is from a product branding, not the manufacturer branding. Please use the GoodWe branding instead.
> 
> ../Frenck

SEMS portal is used by Goodwe but portal itself has logo which is portal logo. There is another Goodwe integration which uses direct connection but this one uses strictly portal data. To me it does make sense to use portal logo as the integration integrates portal data only, while portal is used by Goodwe. https://semsportal.com

**Review by frenck — CHANGES_REQUESTED** [review]
>  To me it does make sense to use portal logo as the integration integrates portal data only, while portal is used by Goodwe

We don't collect product images. Please use the manufacturer branding as requested.

../Frenck

**Comment by darek-margas** [comment]
> > To me it does make sense to use portal logo as the integration integrates portal data only, while portal is used by Goodwe
> 
> We don't collect product images. Please use the manufacturer branding as requested.
> 
> ../Frenck

Replaced

**Review by frenck — COMMENTED** [review]
You might want to consider copying the contents of this folder:

<https://github.com/home-assistant/brands/tree/master/core_integrations/goodwe>

As it will provide you, not just an icon, but all assets.

**Comment by darek-margas** [comment]
> You might want to consider copying the contents of this folder:
> 
> https://github.com/home-assistant/brands/tree/master/core_integrations/goodwe
> 
> As it will provide you, not just an icon, but all assets.

This is where I found replacement for SEMS. I believe one will suffice but ok, copied others.

**Review by frenck — APPROVED** [review]
Thanks!

It is just nicer to have a full set, it will look better on e.g., device pages.

../Frenck

**Pull request merged**
