### PR TITLE
Integration for EPS alarms

### PR DESCRIPTION
**Pull request by parvarm**
## Proposed change

Added support for alarm systems powered by EPS (https://www.eps.fr/).
EPS is the telemonitoring leader in France (650k+ subscribers).

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: N/A
- Link to code base pull request: https://github.com/home-assistant/core/pull/103620
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/29745
- Link to integration documentation on our website: new integration

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by parvarm** [comment]
Hi @frenck,
I performed the requested changes - not sure if there is anything blocking anymore. 
Thanks in advance,
Cheers

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by parvarm** [comment]
Thanks @frenck, I don't really know how to get approval for the parent PR though... it has been opened for a couple of days without feedback :(

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
