### PR TITLE
Add Beckettlink Logos

### PR DESCRIPTION
**Pull request by dcmeglio**
## Proposed change

Add R. W. Beckett logos for the Beckettlink Oil Tank Monitor integration https://github.com/dcmeglio/homeassistant-beckettlink

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are two integration in this PR. Please split those out into multiple PRs.

../Frenck

**Comment by dcmeglio** [comment]
Hmm just a rebase issue. I’ll correct. Those other images are already merged

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR:

image

Please git rebase your changes on the latest upstream master branch to clean it up.

../Frenck

**Comment by dcmeglio** [comment]
Clearly I'm doing something wrong with my rebase :(

**Review by frenck — APPROVED** [review]
Thanks, @dcmeglio 👍 

Not fully cleaned, but much cleaner and acceptable 👍 

../Frenck

**Pull request merged**
