### PR TITLE
Add Jellyfin logo and icon

### PR DESCRIPTION
**Pull request by j-stienstra**
## Proposed change

Add logo and icon for the newly proposed [Jellyfin](https://jellyfin.org/) media system integration.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to code base pull request: https://github.com/home-assistant/core/pull/44401
- Link to documentation pull request: TBD
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/jellyfin/

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
@j-stienstra The parent has been merged, could you resolve the merge conflict here?

**Comment by frenck** [comment]
@j-stienstra The custom_icons needs to be removed, the domains collide

**Comment by j-stienstra** [comment]
Yeah, needed to figure that one out. Should be good now.

**Review by frenck — APPROVED** [review]
Thanks, @j-stienstra 👍

**Pull request merged**
