### PR TITLE
telenet_telemeter custom HACS integration

### PR DESCRIPTION
**Pull request by myTselection**
https://github.com/myTselection/telenet_telemeter

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/myTselection/telenet_telemeter
- Link to documentation pull request: https://github.com/myTselection/telenet_telemeter/readme.md
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This seems to be an application icon? And not the Telenet branding? It seems that Telenet isn't using this in their branding.

Please replace the currently provided branding with the ones used by Telenet.

../Frenck

**Comment by myTselection** [comment]
This is the icon used by Telenet in the official Telenet app to refer to the Telenet usage.
It(s somehow visible on this Telenet app screenshot: https://play-lh.googleusercontent.com/AQJCRD0MyKrResjJ7N3ac7Qz15Zx-Sz7GL2pLOGmcLXDTPrOnHIxz04ivc6uLToAWGU=w2560-h1440-rw

**Comment by frenck** [comment]
> This is the icon used by Telenet in the official Telenet app to refer to the Telenet usage.

Sure, but we are not collecting app icons in this repository, we collect branding. So, please use the Telenet branding instead.

**Review by frenck — CHANGES_REQUESTED** [review]
Can we also add the logo?

That will look much better on the device pages:

<https://nl.wikipedia.org/wiki/Bestand:Telenet_Logo.svg>

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @myTselection 👍 

../Frenck

**Pull request merged**
