### PR TITLE
logo for custom integration waterinfo

### PR DESCRIPTION
**Pull request by physje**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @physje 👋 

I could not find the public repository providing this custom integration. Could you please point me to it?

Thanks! 👍 

../Frenck

**Comment by physje** [comment]
repository can be found here : [https://github.com/physje/waterinfo](https://github.com/physje/waterinfo)

**Review by frenck — CHANGES_REQUESTED** [review]
This integration stricly pins a core dependency:

<https://github.com/physje/waterinfo/blob/2e721a3f63bf602cd5dcdd611b953733673a751e/custom_components/waterinfo/manifest.json#L10>

Any change on our end will break this integration. Please loosely pin it instead.

../Frenck

**Comment by physje** [comment]
I removed the requirement because the version of numpy is not important (the core-version will do).
btw, requirements needs to be pinned strictly otherwise you get `[ERROR] [REQUIREMENTS] Requirement numpy>=1.26.0 need to be pinned "<pkg name>==<version>`, so don't know how to loosely pin it.

**Review by frenck — APPROVED** [review]
Thanks, @physje 👍 

../Frenck

**Pull request merged**
