### PR TITLE
Add brand elro

### PR DESCRIPTION
**Pull request by jbouwh**
## Proposed change

Add icons and logo's for brand `elro`

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/hacs/default/pull/1560
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Elro connects is a product of Elro. I would have expected to see the regular branding of Elro in this case (as we collect brand images, not product images or branding).

**Comment by jbouwh** [comment]
> Elro connects is a product of Elro. I would have expected to see the regular branding of Elro in this case (as we collect brand images, not product images or branding).

Images were updated.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by jbouwh** [comment]
@frenck I retargeted this PR to add the brand as custom integration, can this PR be approved, or do we need a new PR?

**Comment by frenck** [comment]
Sorry, I missed that @jbouwh 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
