### PR TITLE
Add Seitron images

### PR DESCRIPTION
**Pull request by seitronspa**
## Proposed change

Added Seitron logos

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/84443
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/25386
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is adding brand assets for a core integration. However, it doesn't seem to be linked? Please make sure to fill out the PR template.

Thanks 👍 

../Frenck

**Comment by seitronspa** [comment]
> This PR is adding brand assets for a core integration. However, it doesn't seem to be linked? Please make sure to fill out the PR template.
> 
> Thanks 👍
> 
> ../Frenck

Uhh, thanks for the point! I was wondering how to link the pull requests together!! I also fixed the link in the core PR.
I don't understand the third link: `Link to integration documentation on our website`. Is it not the same of the second link ?🫤

**Comment by frenck** [comment]
`Link to integration documentation on our website` doesn't apply in this case, as it is a new integration that isn't on our website as of yet.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by seitronspa** [comment]
> ✅ Approved. Can be merged as soon as the parent PR gets merged.

Thanks @frenck. Do I need to do something now, or just wait? Thanks.

**Comment by frenck** [comment]
This PR now await the merge of the upstream code PR.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
