### PR TITLE
Added connectedcars_io icon

### PR DESCRIPTION
**Pull request by jnxxx**
## Proposed change

Adding icon for a custom integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The provided icons do not seem the match the branding of `connectedcars.io`

image

**Comment by jnxxx** [comment]
I have not created that logo or have the rights/license to submit it in any way.
I have just made an integration that utilized their public API. Does that mean one cannot get it published in HACS?

**Comment by frenck** [comment]
> I have not created that logo or have the rights/license to submit it in any way.

We do not add brand images that do not represent the original brand in this repository. We respect the branding made by organizations.

> Does that mean one cannot get it published in HACS?

I think that is a requirement of HACS indeed. But that is not related to this repository in any way.

**Comment by jnxxx** [comment]
1. HACS only accepts integrations with icons.
2. This repo only accepts the original logo with rights and license granted; which I assume can only be done by the brand rights owner.
That ought to mean all integrations are submitted by the companies behind brands themselves... I doubt that is the case.

So, as an enthusiast that wants to contribute with a third-party integration that is not possible?
I thought that was the case with almost all integrations in HACS.

Anyways, I am dropping the request.

**Comment by frenck** [comment]
HACS is not a concern for this repository. We are happy to accept any branding to represent a brand properly on our end. We are fine with not having any branding for integration as well.

> Anyways, I am dropping the request.

Do you mean this pull request? If so, please close it.

**Comment by jnxxx** [comment]
So you say, but the tests you have to run to get the integration included in HACS fails if there is no logo.

[https://hacs.xyz/docs/publish/include#check-brands](https://hacs.xyz/docs/publish/include#check-brands)

[https://github.com/jnxxx/homeassistant-connectedcars_io/runs/4306331758?check_suite_focus=true](https://github.com/jnxxx/homeassistant-connectedcars_io/runs/4306331758?check_suite_focus=true)

**Comment by frenck** [comment]
> So you say, but the tests you have to run to get the integration included in HACS fails if there is no logo.

That is a HACS requirement, not from Home Assistant perspective. This PR is @ the Home Assistant project.

**Pull request closed without merging**
