### PR TITLE
Logo and Icon for netro_watering integration

### PR DESCRIPTION
**Pull request by kcofoni**
## Proposed change

Add icon and logo for custom component: https://github.com/kcofoni/ha-netro-watering

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks for the PR @kcofoni 👍 

Hope you have a good weekend!

../Frenck

**Comment by kcofoni** [comment]
Hi Frenck,

Great thanks for merging my new integration icon !
Nevertheless it seems that the "icon" image is not "always" accessible.

Right now, the status is (at  the time I am writing this post) :

https://brands.home-assistant.io/netro_watering/icon.png -------------> NOT OK (404)
https://brands.home-assistant.io/netro_watering/icon@2x.png ---------> OK
https://brands.home-assistant.io/netro_watering/logo.png -------------> OK
https://brands.home-assistant.io/netro_watering/logo@2x.png )--------> OK

Do you have an idea about this random malfunction ?

Have a nice day !

**Comment by frenck** [comment]
We cache heavily, it takes a bit for the caches to expire. We flush all caches each major release (first Wednesday of the month during the release).

../Frenck

**Comment by kcofoni** [comment]
OK Frenck. Thanks for the answer. Considering your explanation I am just wondering why the problem did not occur for icon@2x and both version of logo...but OK :-)

**Comment by frenck** [comment]
> Considering your explanation I am just wondering why the problem did not occur for icon@2x and both version of logo...but OK :-)

It depends on who requested which icon where. CloudFlare caches them on their edge endpoints on the first request.

**Pull request merged**
