### PR TITLE
adding froeling connect

### PR DESCRIPTION
**Pull request by d3nergy**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Oh hi there @d3nergy 👋 

I seems like something went with the icon version of the provided branding:

CleanShot 2024-06-22 at 09 02 24@2x

Could you please take a look?

Thanks 👍 

../Frenck

**Comment by d3nergy** [comment]
hi @frenck 

thanks for recognising.
Something must have been wrong when I added the icons.
I corrected it.

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks for the correction 👍 

Can you please point me to the public repository providing this custom integration? It wasn't listed in the PR description, and also searching for it didn't reveal anything.

Thanks already 👍 

../Frenck

**Comment by d3nergy** [comment]
> Thanks for the correction 👍
> 
> Can you please point me to the public repository providing this custom integration? It wasn't listed in the PR description, and also searching for it didn't reveal anything.
> 
> Thanks already 👍
> 
> ../Frenck

I did not yet upload any code into a repository.
I manually added my custom-component to my HA instance.

**Comment by frenck** [comment]
> I did not yet upload any code into a repository.

Ok, in that case, I'll go ahead and close this PR up. There is no good reason for us to add brand assets for an integration that isn't available for the community.

Feel free to re-open this PR once the integration is publicly available.

Nevertheless; thanks for being willing to contribute 👍 

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @d3nergy 👍 

../Frenck

**Pull request merged**
