### PR TITLE
add icons for linkytic custom integration

### PR DESCRIPTION
**Pull request by hekmon**
## Proposed change

Add icon and brand logo for the [linkytic](https://github.com/hekmon/lixeeticdin) custom integration. This is a serial local polling integration allowing to get information from Linky, the french main electric meter, in order to integrate it to the energy module of Home Assistant (and more).

Note: do not mind the current name of the repository: the v2 (currently in [beta](https://github.com/hekmon/lixeeticdin/releases)) has a new and more universal name as it is compatible with a lot a serial2usb modules. The [v2 manifest](https://github.com/hekmon/lixeeticdin/blob/v2/manifest.json#L2) can confirm the new name of the integration.  v1 was configured thru YAML and v2 will offer config flow and this PR is here to prepare that. Repository will be renamed when v2 will be out of beta.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons provided don't seem like a branding used by Enedis, for example, on their socials they use:

image

Can you point me to a resource they use the provided icons as their branding?

../Frenck

**Comment by hekmon** [comment]
Enedis is the French power grid operator, they have a lot of services and products (a lot of open data too for nation wide electricity data). Linky is the smart meter they have deployed into people houses to start transitioning to a nation wide smart grid.

This extension does not connect to Enedis services or open data API but specificaly to the serial connection of the Linky device to poll localy customer informations. Linky meter is owned and managed by Enedis.

So the icon reflects this extension is only about the Linky smart meter and nothing else but the brand behind the Linky is Enedis.

You can find more information and relationship between the two in English [here](https://particulier.edf.fr/en/home/contract-and-consumption/meter/linky-meter.html) and [here](https://en.selectra.info/energy-france/guides/electricity/linky) or directly on the Enedis [website](https://www.enedis.fr/le-compteur-linky-bientot-chez-vous) (but only in French sorry).

**Comment by frenck** [comment]
> So the icon reflects this extension is only about the Linky smart meter and nothing else but the brand behind the Linky is Enedis.

Sure, but still, I would expect the Enedis branding in that case. I could not find any of the icons used in the branding upstream. Hence my question: Please point me to an official resource using the icons provided in their branding.

**Comment by hekmon** [comment]
On this [pdf](https://www.enedis.fr/sites/default/files/documents/pdf/2021-01/smart-grids-innovation-au-service-des-clients-et-enjeux-energetiques-des-territoires.pdf) about smart grid directly from the Enedis website you can see:
- In the front page, the Enedis logo
- On page 10 the Linky meter

About the Enedis logo, it has been picked up from the Enedis [wikipedia page](https://fr.wikipedia.org/wiki/Enedis).
Icon has been redrawn to better show in home assistant (less details) as integration page shows icons in 40x40.

If issue is that the icon (the Linky meter) has been redrawn to better integrate into Home Assistant and is not "official" I would say that it would be best to totally remove the enedis logo and keep the linky icon: users will instantly recognize the Linky icon as this is what they are looking for but are not too familiar with Enedis icon/logo itself. Integration is connecting to the Linky directly and not Enedis services (open data for example).

**Comment by hekmon** [comment]
In this english [PDF](https://particulier.edf.fr/content/dam/2-Actifs/Documents/Documents-Site-Anglais/Notice_compteur_Linky_Monophase_anglais.pdf) (from EDF website, which is the [company owning Enedis](https://www.enedis.fr/faq/enedis/quelle-est-la-difference-entre-edf-et-enedis)) you can see both the icon and the logo.

**Comment by frenck** [comment]
Right, but those you pointed out, are product images, not brand assets.

**Comment by hekmon** [comment]
I am a bit confused.
- icon is not a brand asset per se, this is true
- logo is litteraly the official Enedis logo as show on the [enedis website](https://www.enedis.fr/) (check the header and the footer for the correct color)

It seems that what is bothering you is to tied a "non official" icon of the product the integration is interfacing with and the official company logo. So from here I understand that you are expecting an official Enedis icon.

This is where it might be counterproductive: people do not interface often with Enedis and won't necessarily recognize their icon while researching (in hacs for example) an integration for their Linky meter.

So, would it be acceptable to remove the Enedis logo and only keep the Linky icon as the integration implements their [TIC standard](https://www.enedis.fr/media/2035/download) and do not connect to them directly ?

**Comment by frenck** [comment]
> I am a bit confused.

I'm not sure how, this is a "brands" repository, not a product icons repository.
I could not find any reference of Enedis using the icons provided in their branding. Please point to such a resource, or, in case these are product images, replace them with branding icons.

../Frenck

**Comment by hekmon** [comment]
> This is where it might be counterproductive: people do not interface often with Enedis and won't necessarily recognize their icon while researching (in hacs for example) an integration for their Linky meter.

As I said.

> So, would it be acceptable to remove the Enedis logo and only keep the Linky icon as the integration implements their [TIC standard](https://www.enedis.fr/media/2035/download) and do not connect to them directly ?

I am guessing this is a no, would have been nice to answer it directly.

>I'm not sure how, this is a "brands" repository, not a product icons repository.

That's a bummer. So I guess I will wait HA to support local icon and logo from custom integrations as for now I prefer my integration to have no icon that having one confusing my users.

Thank you for your time.

**Comment by frenck** [comment]
> So, would it be acceptable to remove the Enedis logo and only keep the Linky icon as the integration implements their [TIC standard](https://www.enedis.fr/media/2035/download) and do not connect to them directly ?

No.

>  So I guess I will wait HA to support local icon and logo from custom integrations as for now 

We have no plans to do so.

> I prefer my integration to have no icon that having one confusing my users.

That is fine as well, feel free to close the PR in that case.

**Comment by hekmon** [comment]
> We have no plans to do so.

Well, you should. It will not make sense for all HA integrations to be linked to a brand. Forcing integration to be linked to a brand to have an icon is unfortunate at best.

It was a pleasure getting answers and explanations out of you.

Have a positive day.

**Comment by frenck** [comment]
You too 👍 

If you change your mind, feel free to re-open the PR.

Anyways, still a Happy New Year 🥂 

../Frenck

**Comment by hekmon** [comment]
Feel free to notify me here when HA will have better rules/possibilities for custom integrations to have icons/logos !

Happy new year to you too 😏

**Comment by hekmon** [comment]
Hello again,

#4097 taught me:

- You need a brand icon if you want your custom extension [statistics](https://analytics.home-assistant.io/custom_integrations.json) 
- You need a brand icon if you want to be included in [HACS](https://hacs.xyz/docs/publish/include/#check-brands)

So I guess... I will have to comply 🥲 

proper commit with enedis logo incoming...

**Review by frenck — APPROVED** [review]
Thanks, @hekmon 👍 

../Frenck

**Pull request merged**
