### PR TITLE
Add icon and logo for HyperHDR MQTT 

### PR DESCRIPTION
**Pull request by xZetsubou**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/xZetsubou/hass-HyperHDR-MQTT

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This seems to be a customized version of the HyperHDR logo.

We don't allow the use of customized branding, as this often conflicts with upstream branding guidelines.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Maybe I'm wrong, but the logo is still customized?
I could not find a variant with the MQTT in it in their resources. Could you please point me to it?

Thanks! 👍 

../Frenck

**Comment by xZetsubou** [comment]
I may be wrong as well :), but I can't find any relation between the new logo and the HyperHDR one. I only used their "H" font before, but not anymore. 

> I could not find a variant with the MQTT in it in their resources. Could you please point me to it?

If I understood what you are looking for then It can be found in sources [HyperHDR](https://github.com/awawa-dev/HyperHDR)

**Comment by xZetsubou** [comment]
Correct me I may misunderstood the situation, Do I need to use the original HyperHDR logo? and not actually something un-related to the original logo of HyperHDR?

**Comment by frenck** [comment]
The MQTT part here, seems to be an non-existing addition upstream.

CleanShot 2024-07-07 at 23 23 25@2x


If I missed that, I'm sorry; in that case, please point me to an upstream resource where they are using this for their branding.

Thanks 👍 

../Frenck

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Comment by xZetsubou** [comment]
They don't use MQTT in the logo brand, Would removing MQTT text would resolve this?

**Pull request closed without merging**
