### PR TITLE
Added Icons for miwifi-cb0401v2 Integration

### PR DESCRIPTION
**Pull request by MKsys1337**
## Proposed change
Added logo and icons for MiWiFi Integration, specialized for CB0401V2 5G/LTE Router.
Integration-Link: https://github.com/MKsys1337/MiWiFi-CB0401V2

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This integration is with a device manufactured by Xiaomi; therefore, I expected the Xiaomi branding to be added here.

If I'm not correct, can you please point me to a web location showing this branding?

Thanks! 👍 

../Frenck

**Comment by MKsys1337** [comment]
Hi @frenck,

there is no Xiaomi Logo in its own Webinterface, it uses only the MiWiFi Logo.
Thanks for reviewing!

image

**Review by frenck — CHANGES_REQUESTED** [review]
This repository is not about product branding, but manufacturer branding. I'm not aware of a manufacturer called "mywifi", I might be wrong. If that is the case, can you point me to some resources of this manufacturer?

**Comment by MKsys1337** [comment]
I've replaced the product icons/logos with the manufacturer ones.
If this isn't correct, please give me a hint what to do.

**Review by frenck — CHANGES_REQUESTED** [review]
The folder used in this PR doesn't match the domain of the integration.

CleanShot 2024-11-09 at 16 19 23@2x

Please rename the directory to lower the dash to an underscore.

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @MKsys1337 👍 

../Frenck

**Pull request merged**
