### PR TITLE
Add Icon and Logo for Custom Integration - SAAS - Sleep As Android Status

### PR DESCRIPTION
**Pull request by sudoxnym**
Adding the icon for my custom integration that allows for different status's to be tracked via Sleep As Android App.

## Proposed change

adding icon for custom repo saas

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- https://www.github.com/sudoxnym/saas
- Link to documentation pull request: 
- https://github.com/sudoxnym/saas/blob/main/README.md
- Link to integration documentation on our website: 
- https://github.com/sudoxnym/brands/tree/master/custom_integrations/saas
- Link to custom integration repository:
   https://www.github.com/sudoxnym/saas

## Checklist

- [x ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @sudoxnym 👋 

The PR template isn't filled out, and is thus missing links to where I can find this custom integration.

Can you please properly fill out the template, provide a description and a proper PR title that is descriptive?

Thanks 👍 

../Frenck

**Comment by sudoxnym** [comment]
My apologies. Somehow didn't see the middle, filled out everything that applies hitting button next

**Comment by sudoxnym** [comment]
My apologies, I'm super new to the world of developing. If you're referring to the app as saas, then I made saas, ground up, if you're referring to the original app, that is Sleep As Android, they have different branding. My integration doesn't connect directly to their app, it just listens for the MQTT topic it puts out. I'm willing to add anything necessary though if pointed in the right direction.

**Comment by frenck** [comment]
> My apologies, I'm super new to the world of developing.

No worries, I'll try to explain.

We collect the branding of manufacturers of devices or providers of services that an integration connects/integrates into this repository (regardless of transport).

I'm trying to figure out which service this integration integrates with and the branding that goes with it so I can validate that the provided branding in this PR matches the upstream branding.

../Frenck

**Comment by sudoxnym** [comment]
I'm slightly embarrassed for not knowing this stuff, you're one of my heroes lol. I'm hoping this is what you were asking for.
https://sleep.urbandroid.org/

**Comment by frenck** [comment]
Right, which brings me to the points of:

CleanShot 2024-05-13 at 21 15 41@2x

Doesn't match with what has been provided in this PR.

../Frenck

**Comment by sudoxnym** [comment]
So I'd have to use their logo? Does that mean I'd need to get in contact with them and permission? The logo provided was made by me and designed for saas specifically. Sorry for confusion.

**Comment by sudoxnym** [comment]
Sorry for the lack of knowledge, but if you could direct me in my next steps I'd be happy to follow them.

**Comment by sudoxnym** [comment]
Hey bud, not trying to bother you, just trying to figure out what I need to do to get a logo on my integration. If I need to use the original app logo instead of my own I can, just need to know what to do.

**Comment by frenck** [comment]
Hey m8,

It indeed means we need to add their logo here; we won't be accepting anything else, as we don't want to brand to be misrepresented.

../Frenck

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Pull request closed without merging**
