### PR TITLE
Add dark logos for Frigate

### PR DESCRIPTION
**Pull request by dan-r**
## Proposed change

Added inverted icon and logo for Frigate custom integration. Using Home Assistant in dark mode, icon contrast is too low and on the Frigate app the logo inverts with dark mode.

CC @blakeblackshear incase it goes against any branding guidelines you have.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [x] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Review by frenck — APPROVED** [review]
Thanks, @dan-r 👍 

../Frenck

**Comment by frenck** [comment]
Why did you merge again? Was there a conflict? Did you change anything?

**Comment by dan-r** [comment]
I've not changed anything - I thought it blocked merging if it wasn't up to date with the target branch?

**Comment by frenck** [comment]
>I've not changed anything - I thought it blocked merging if it wasn't up to date with the target branch?

Nope, that is now how git works 😄 
The only thing it causes is that you triggers the CI again, which is mostly a waste of resources... also, we have to wait :)

**Comment by dan-r** [comment]
My bad, apologies, I'll stop hitting the big 'Update branch' button!

**Pull request merged**
