### PR TITLE
Add MCZ Maestro icon

### PR DESCRIPTION
**Pull request by Robbe-B**
## Proposed change

Add icons for the custom_component maestro_mcz: https://github.com/Crisicus/maestro_mcz
Got confirmation for this PR from @Crisicus
No hDPI available due to the fact this correct icon is only found in 1 format and upscaling would make it blurry.
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by Crisicus — COMMENTED** [review]
I agree on the icon, as it's the one used for the iOS/Android app this integration aims to mimick.
Thanks for the PR @Robbe-B !

**Review by frenck — CHANGES_REQUESTED** [review]
This PR uses an application/product images, which is not what we collect in this repository. Please the manufacturer branding instead.

../Frenck

**Comment by Robbe-B** [comment]
Hi @frenck , thanks for reviewing this PR ! This is indeed a product line of the Brand 'MCZ', this is a brand which makes pellet stoves. This brand makes stoves which are not smart connected, but others which are smart conneced. The connected models are branded as MAESTRO MCZ. It's like you would say LG devices or the SmartThinq LGE device line (the connected once).

See a screenshot of the android app icon


There are simply no other designs for this device line.

Kind regards,
Robbe

**Comment by Crisicus** [comment]
> Thanks for your response, but we don't collect product branding here. Please use the manufacturer branding as requested. Thanks 👍 
> 
> 
> 
> ../Frenck

While I agree with what you're saying, what @Robbe-B is saying is that what you're proposing is conflicting with the "SmartThinQ LGE Sensors" integration icons currently accepted.

**Comment by frenck** [comment]
Decisions or things in the past don't set current procedures or rules. Please adjust accordingly.

Thanks 👍 

../Frenck

**Comment by Robbe-B** [comment]
@frenck , thanks for helping us in doing the right things here ! 
I've adjusted the images to the MZC branding instead of the Maestro device icons (as requested).

**Review by frenck — APPROVED** [review]
Thanks, @Robbe-B 👍 

../Frenck

**Pull request merged**
