### PR TITLE
Add icons for tk_husteblume integration

### PR DESCRIPTION
**Pull request by artspb**
## Proposed change

Add icons for [tk_husteblume](https://github.com/artspb/homeassistant-tk-husteblume) custom integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/artspb/homeassistant-tk-husteblume

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
These are app/product icons, not manufacturer/provider branding icons. Please release these assets with the brand assets from TK.

../Frenck

**Comment by artspb** [comment]
@frenck Thank you for your response. I'm afraid I need a clarification. Do you propose to add the TK brand assets to `tk_husteblume` or create a new folder for TK and add the app logo there? I tried reading the documentation but probably missed the part that describes this scenario. Perhaps, you can share an example of how it should be done. I wasn't able to find a similar brand by quickly scanning the repo. Thanks.

**Comment by frenck** [comment]
We don't need to app icons at all. We collect manufacturer branding in this repository, not product or app branding. The assets used in this PR need to be replaced by the manufacturer branding.

**Comment by artspb** [comment]
Fair enough. I have two follow-up questions, though.

1. Is it OK that broader TK brand assets are placed in a narrower TK Husteblume directory? If not, and they should be placed in `tk`, will they be picked up by the `tk_husteblume` integration?
2. Is there a way for a custom integration to use an app, not a brand icon? I'm a bit afraid that users might be confused as there's, in fact, no integration with the main TK services per se.

Thank you for your time answering.

**Comment by frenck** [comment]
> Is it OK that broader TK brand assets are placed in a narrower TK Husteblume directory? If not, and they should be placed in tk, will they be picked up by the tk_husteblume integration?

I'm not following that logic at all. This is an directory names after the integration domain that contains matching brand assets for that integration. Nothing more or less.

> Is there a way for a custom integration to use an app, not a brand icon?

No, as said before, we don't collect app assets in this repo.

../Frenck

**Comment by artspb** [comment]
>I'm not following that logic at all. This is an directory names after the integration domain that contains matching brand assets for that integration. Nothing more or less.

The logic is in reusability. As far as I understand, there's some for core integrations. I though that, perhaps, something can (should?) be done for custom integrations as well. Anyway, it doesn't seem to be a problem right now, as I didn't find any other integrations that might benefit from this branding.

>No, as said before, we don't collect app assets in this repo.

I see. My idea was that there's, perhaps, a way for custom integration to ship its own branding that I missed.

**Comment by frenck** [comment]
> The logic is in reusability. As far as I understand, there's some for core integrations. 

This isn't a core integration, so that doesn't apply.

**Review by frenck — APPROVED** [review]
Thanks, @artspb 👍 

../Frenck

**Comment by artspb** [comment]
Thank you!

**Pull request merged**
