### PR TITLE
Added dark_icon

### PR DESCRIPTION
**Pull request by HAEdwin**
## Proposed change
This is the transparent version (dark_icon) optimized for a dark background 

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information
None

## Checklist
- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Why not replace the `icon.png` instead? This icon would work on both dark and non-dark mode versions.

**Comment by HAEdwin** [comment]
I wasn't aware of the fact that is is allowed. I'd aprove your suggestion but am not certain what to do next in GitHub. Are you able to replace icon.png with dark_icon (renaming it to icon)?

**Comment by frenck** [comment]
I would copy the `dark_icon.png` to `icon.png`, delete `dark_icon.png`; git commit and push up those changes.

**Comment by HAEdwin** [comment]
Deleted the previous dark_icon and non-transparent icon and replaced them for this transparent icon.png

**Review by frenck — APPROVED** [review]
Thanks, @HAEdwin 👍

**Pull request merged**
