### PR TITLE
Copy ElevenLabs to core

### PR DESCRIPTION
**Pull request by sorgfresser**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [x] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

Copying the elevenlabs icons for the newly added core integration
- Link to code base pull request: https://github.com/home-assistant/core/pull/115645
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/32322

## Checklist
I just used `cp`, so these checks shouldn't have changed.

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by sorgfresser** [comment]
@joostlek I copied the files for now as there are existing hacs integrations

**Comment by joostlek** [comment]
Please remove from custom

**Comment by sorgfresser** [comment]
Done @joostlek! Should I squash the two commits?

**Comment by joostlek** [comment]
We squash them with merging

**Comment by joostlek** [comment]
By the way, did you send your discord username?

**Review by c0ffeeca7 — APPROVED** [review]
LGTM, @sorgfresser :+1:

**Comment by sorgfresser** [comment]
> By the way, did you send your discord username?

`sorgfresser`, same as Github. Thanks!!
https://github.com/home-assistant/core/pull/115645#issuecomment-2261279979

**Pull request merged**
