### PR TITLE
Add custom logo and icon for EffortlessHome

### PR DESCRIPTION
**Pull request by newmie10**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by newmie10** [comment]
Not sure where my description went, but the link to the custom integration repository is here -> https://github.com/EffortlessHome/HA_Integration

**Review by frenck — CHANGES_REQUESTED** [review]
> Not sure where my description went, but the link to the custom integration repository is here -> [EffortlessHome/HA_Integration](https://github.com/EffortlessHome/HA_Integration)

That link gives me a 404. Could you please provide a link to the publicly available custom integration?

Thanks! 👍 

../Frenck

**Comment by newmie10** [comment]
Anything else I need to do to get this merged?
Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @newmie10 👋 

I've looked at the provided link (which is now indeed accessible), but it seems to be our example repository and not the custom integration?

Can you please point me to the location of the repository where this integration is offered?

Thanks! 👍 

../Frenck

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Pull request closed without merging**
