### PR TITLE
Add icon and logo for medcom_ble integration

### PR DESCRIPTION
**Pull request by elafargue**
## Proposed change

This is a set of icon/logo for [International Medcom](https://medcom.com), used for the medcom_ble integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/100289
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/28956
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I could not find the public repository providing this custom integration. Could you point me to it?

Thanks already! 👍 

../Frenck

**Comment by elafargue** [comment]
- The integration PR is at: https://github.com/home-assistant/core/pull/100289
- The documentation PR is at: https://github.com/home-assistant/home-assistant.io/pull/28956
- The public repository for the Medcom Python library is at: https://github.com/elafargue/medcom-ble/

**Review by frenck — CHANGES_REQUESTED** [review]
Ok, so that means this integration is pending to be added to Home Assistant Core itself. In that case, this PR should be going into the `core_integrations` folder as it is not a custom integration.

../Frenck

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by bdraco — APPROVED** [review]

**Pull request merged**
