### PR TITLE
Add Purrsong icon and logo

### PR DESCRIPTION
**Pull request by RobertD502**
## Proposed change

Add icon and logo for purrsong which is used by the custom_integration [home-assistant-lavviebot](https://github.com/RobertD502/home-assistant-lavviebot)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The brand, in this case, is LavvieBot S, I would have expected their brand images, not images for one of their products.

**Comment by RobertD502** [comment]
I wasn't 100% sure, but the LavvieBot website lists the company as PurrSong in the [about Lavviebot section.](https://www.lavviebot.com/en/about.html)

**Review by frenck — APPROVED** [review]
Ok, indeed, it seems like they haven't figured it out themselves either yet, as they copyright everything as LavvieBot S as well 🤷 . They are from South Korea actually.

Alright, lets merge it in, thanks @RobertD502 👍

**Comment by RobertD502** [comment]
Thanks Franck!

**Pull request merged**
