### PR TITLE
Update of Ubiquiti and Unifi logos

### PR DESCRIPTION
**Pull request by kongo09**
## Proposed change

Ubiquiti is no longer called Ubiquiti Networks, so the logo is outdated and doesn't exist anymore. Ubiquiti is now using the icon also as a logo on their website and official communication.

Unifi has been developed as an independent brand. While it is still using the same icon as Ubiquiti, it uses its own logo.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [x] Replace an existing icon or logo after a branding change
- [x] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR removes the full ubiquiti from the brands folder, but that is not correct, as core hold a ubiquiti brand...

Removing this, will cause dead images in the Home Assistant UI.

Please re-add a ubiquiti branding. Thanks! 👍 

../Frenck

**Comment by kongo09** [comment]
Ubiquiti changed its branding, as evidenced here: https://ir.ui.com/ It is now also just using the U for both, logo and icon.

**Comment by frenck** [comment]
I understood. The problem is that PR removes the occurrences from `core_brands`, however, core relies on it.

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Comment by kongo09** [comment]
Just to clarify, if logos are missing, then the icons are used. Correct? That's how I understood the documentation here: https://github.com/home-assistant/brands which is why I removed the wrong logos and only left the icons.

**Pull request closed without merging**
