### PR TITLE
Ambihue

### PR DESCRIPTION
**Pull request by Mr-Groch**
## Proposed change

Add icon for custom integration https://github.com/Mr-Groch/ambihue

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is a product image of the ambilight + hue app, however, we track brand images in this repository, not product images.

Please use the assets for the brand instead.

**Comment by Mr-Groch** [comment]
I've updated logo to custom made with philips, ambilight and hue brands

**Review by frenck — CHANGES_REQUESTED** [review]
This is not the logo philips uses as a brand, but contains product brands images. Please simply use the Philips brand images.

**Comment by Mr-Groch** [comment]
@frenck There's no ambilight+hue official brand logo. Should I use just ambilight image? That will not correctly describe my custom component to control Ambilight+Hue TV function...

**Comment by frenck** [comment]
No, this is a product of Philips? In that case Philips logos and brand images should be used.

**Comment by Mr-Groch** [comment]
OK, iv'e changed to Hue brand logo

**Comment by frenck** [comment]
Hue isn't a brand, but a product now owned by Signify, not Philips...
could you just use the Philips logos as I now have requested?

**Comment by Mr-Groch** [comment]
Philips logo this time ;)

**Comment by Mr-Groch** [comment]
@frenck done

**Comment by Mr-Groch** [comment]
@frenck Hey, is there something else must I do? I've changed to philips brand logo 2 days ago as you requested

**Review by frenck — CHANGES_REQUESTED** [review]
Philips has all branch images available, you can save yourself quite a bit of time by just grabbing them from the core integrations:

<https://github.com/home-assistant/brands/tree/master/core_integrations/philips_js>

**Pull request merged**
