### PR TITLE
Add Aldes integration

### PR DESCRIPTION
**Pull request by aalmazanarbs**
## Proposed change

This feature adds icons and logos for the Aldes custom integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @aalmazanarbs, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3280).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by aalmazanarbs** [comment]
Hi @frenck, could you review this PR? Let me know if there is any mistake. Regards.

**Comment by frenck** [comment]
Hi there @aalmazanarbs 👋 

I cannot find the custom integration for which these brand images are added. Could you point me to the repository providing this integration?

Thanks! 👍 

../Frenck

**Comment by aalmazanarbs** [comment]
> Hi there @aalmazanarbs 👋
> 
> I cannot find the custom integration for which these brand images are added. Could you point me to the repository providing this integration?
> 
> Thanks! 👍
> 
> ../Frenck

Hi @frenck thank you for your comment, the repository is here https://github.com/aalmazanarbs/hassio_aldes

For the moment it is empty since it is a local development but will be available soon. The integration is based on this tutorial https://github.com/boralyl/github-custom-component-tutorial.

Do I have to achieve other requirements?

Regards!

**Comment by frenck** [comment]
> For the moment it is empty

I cannot approve and merge brand assets for a non-existing integration.

**Comment by frenck** [comment]
Hi there @aalmazanarbs!

Any progress on the custom integration? If not, maybe we should consider closing this one in the meantime.

../Frenck

**Comment by aalmazanarbs** [comment]
Hi @frenck, the code of the Aldes cutom integration is now in the repository https://github.com/aalmazanarbs/hassio_aldes, could you please review? Thank!

**Review by frenck — APPROVED** [review]
Thanks, @aalmazanarbs 👍

**Pull request merged**
