### PR TITLE
Change System Health to mdi:heart-pulse

### PR DESCRIPTION
**Pull request by Mariusthvdb**
to go with https://github.com/home-assistant/frontend/pull/13275

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:  https://github.com/home-assistant/frontend/pull/13275
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by zsarnett** [comment]
The system health menu item is being removed

**Comment by zsarnett** [comment]
This can actually still be changed. My mistake. For integration icons in various places

**Comment by frenck** [comment]
Anyways, can't re-open, as the branch has been deleted by @Mariusthvdb

**Comment by Mariusthvdb** [comment]
Should I rewrite?

Just followed GitHub instructions....

**Comment by zsarnett** [comment]
yes pls. My bad

**Comment by Mariusthvdb** [comment]
sorry, but this one is only closed, not deleted? Zack could re-open this?

**Comment by Jc2k** [comment]
Screenshot 2022-07-26 at 22 34 12

And unfortunately there is no re-open button.

**Comment by Mariusthvdb** [comment]
check https://github.com/home-assistant/brands/pull/3559

**Pull request closed without merging**
