### PR TITLE
renamed valetudo_vacuum_camera to mqtt_vacuum_camera new icons and logos

### PR DESCRIPTION
**Pull request by sca075**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [x] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #5564 and #5533
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/sca075/mqtt_vacuum_camera

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @sca075 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Oh, the CI is failing, as the images are probably not according to specifications. Can you take a look @sca075?

Thanks! 👍 

../Frenck

**Comment by sca075** [comment]
> Oh, the CI is failing, as the images are probably not according to specifications. Can you take a look @sca075?
> 
> Thanks! 👍
> 
> ../Frenck

Sure just few minutes and will retry.

**Comment by sca075** [comment]
@frenck all tests passed thank once again 👍

**Review by frenck — APPROVED** [review]
Thanks, @sca075 👍 

../Frenck

**Comment by sca075** [comment]
My pleasure to contribute @frenck 👍

**Pull request merged**
