### PR TITLE
Added Yandex media player logo

### PR DESCRIPTION
**Pull request by itsib**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by itsib** [comment]
Hey @frenck. I understood you. I think I can use the Yandex logo if I write that this is the Yandex logo, not mine. Since my player works exclusively with Yandex stations.

**Review by frenck — CHANGES_REQUESTED** [review]
The provided images are not the Yandex branding, additionally, the logos are a duplicate of the icons (which is not needed).

../Frenck

**Comment by itsib** [comment]
@frenck I don't understand what I need to do to get my logo into this repository?

**Comment by itsib** [comment]
Do I need to portray the Yandex logo in my own style?

**Comment by itsib** [comment]
Closing it. I managed to insert my icon. Maybe then I will issue this solution as a package. 
I'm sorry to bother you.

**Pull request closed without merging**
