### PR TITLE
Add renault custom integration logo and icon

### PR DESCRIPTION
**Pull request by epenet**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by epenet** [comment]
Linked to #1825, but until the integration is fully merged into the core it would be nice to have inside the custom integrations

**Comment by epenet** [comment]
Linked PR on Home Assistant Python wheels repository: https://github.com/home-assistant/wheels-custom-integrations/pull/168

**Review by frenck — APPROVED** [review]
Thanks, @epenet 👍

**Comment by epenet** [comment]
Thanks @frenck 

Two quick questions:
- how long does it take to be available (https://brands.home-assistant.io/renault/logo.png is coming back with 404 error after 24hrs)
- should I rebase PR #1825 and add the removal of these files?

**Comment by frenck** [comment]
- Up until the next main Home Assistant release
- Yes

**Pull request merged**
