### PR TITLE
Samsung TV Tizen Integration Icon

### PR DESCRIPTION
**Pull request by jaruba**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
These images do not match Samsung or Tizen brand guidelines.

Looking here: <https://www.tizen.org/about/tizen-brand-guidelines>

So I'm kinda thinking these are maybe older images?

**Comment by jaruba** [comment]
No, this is the logo for Samsung Smart TVs. All 2017+ Samsung TVs use Tizen OS. Tizen is although used on other devices too by Samsung, including Smart Watches. The custom component's name is "samsungtv_tizen" as it supports only the Tizen family of Samsung TVs, for which Samsung has a "Samsung Smart TV" logo.

This was the most fitting logo I could find for this, because the Tizen logo wouldn't be correct as this is only for TVs.

**Review by frenck — CHANGES_REQUESTED** [review]
Ok, 👍 

Please remove the logos, as it is the same as the icons.

**Comment by jaruba** [comment]
I removed the logo images, thanks

**Review by frenck — APPROVED** [review]
Thanks, @jaruba 👍

**Pull request merged**
