### PR TITLE
Yieryi BLE_YC01

### PR DESCRIPTION
**Pull request by jdeath**
## Proposed change

Add icon and logo for ble_yc01

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @jdeath 👋 

This PR adds a core brand, but doesn't have a parent PR linked that adds this brand to our core repository. Could you please point me to it?

../Frenck

**Comment by jdeath** [comment]
@frenck I am so sorry. I should have uploaded to custom_components. PR has been updated.

**Review by frenck — CHANGES_REQUESTED** [review]
CleanShot 2023-12-27 at 22 14 39@2x

The integration domain (and thus also the folder these images are in), is invalid. Integration domains cannot contain capital letters.

../Frenck

**Comment by jdeath** [comment]
I am sorry. Fixed and changed my domain to be lowercase

**Review by frenck — APPROVED** [review]
Thanks, @jdeath 👍 

../Frenck

**Pull request merged**
