### PR TITLE
Strip transparency from Alexa logo

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

Strip transparency from Alexa logo.

## Type of change

- [ ] Add a new logo or icon for a new integration
- [ ] Add a missing icon or logo for an existing integration
- [x] Replace an exiting icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by balloob** [comment]
Oh I see now why it had some transparency 🤔

**Comment by balloob** [comment]
This is what I was trying to fix

image

**Comment by frenck** [comment]
Yeah we should use icons there...

**Comment by frenck** [comment]
Aah I see, yeah that is fixable. Will generate one.

**Comment by frenck** [comment]
While according to spec now, it makes the icon huge in size...

I wonder if the spec in this case, if working against us?

**Comment by frenck** [comment]
Furthermore, this is how it looks on my end:

image


Chrome vs Firefox issue in layout maybe?

**Comment by Quentame** [comment]
I have the same behaviour as @balloob 

@frenck I don't think it's a big deal to have extremely large width.

Depending on the max width we gonna set lots of `@2x` should not be added.
Exemple with `digital_ocean/logo@2x.png` :

- Actual : 2500 × 422
- 1500px max : 1500 × 253 (`@2x` already useless)
- 1024px max : 1024 × 173 (even more 😆)


But if you want a simpler way : 
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)
- [ ] Both logo longest side should not exceed [X]px

**Pull request merged**
