### PR TITLE
Files for bolletta

### PR DESCRIPTION
**Pull request by StefanoGiu**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/StefanoGiu/bolletta

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
If the dark & light versions are the same, and the logo and icon version the same, please than just leave the light icon version. Remove all the others.

../Frenck

**Comment by StefanoGiu** [comment]
How can I delete files from the pull request? I'm not an expert

**Comment by StefanoGiu** [comment]
How do I do it? May you guide me please?

**Comment by StefanoGiu** [comment]
I'm using the browser Chrome and I don't know how to do it...

**Comment by frenck** [comment]
> I'm using the browser Chrome and I don't know how to do it...

That will be hard. Please use a git client locally.

**Comment by StefanoGiu** [comment]
I don't know how to use the git client and what commands to issue... Can you help me? Would you be able to remove files on my behalf?

**Comment by frenck** [comment]
@StefanoGiu I'm sorry, but I currently lack the time to teach you how to use git.

And honestly, how would you manage maintaining a custom integration if you haven't got that skill? 🤷 

Everyone has to learn, that I get. There are tons of resources to be found online on this subject.

../Frenck

**Comment by StefanoGiu** [comment]
What about if I create a new pull request with only the 4 files of the light version?

**Comment by StefanoGiu** [comment]
Please let me know if this is ok

**Comment by frenck** [comment]
You should just adjust this PR 🤷

**Comment by StefanoGiu** [comment]
Is it ok now?

**Comment by frenck** [comment]
Nope, the logo version can be removed too. As they are the same as the icon version.

Additionally, there seems to be an artifact visible on the 2x versions; could you take a look at that?

**Comment by StefanoGiu** [comment]
Fixed

**Review by frenck — APPROVED** [review]

**Comment by StefanoGiu** [comment]
I'm moving the integration to my other account:
https://github.com/Sanji78/bolletta

**Pull request merged**
