### PR TITLE
Add plex_recently_added icon

### PR DESCRIPTION
**Pull request by NemesisRE**
## Proposed change

Adding brand images for a new `plex_upcoming_media` custom integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Supports the custom integration: https://github.com/NemesisRE/sensor.plex_recently_added
- Published via HACS
- No logo available

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @NemesisRE, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3429).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
The icons used in this PR are modified icons from a manufacturer. We don't accept those, as this generally conflicts with the brand guidelines of the respective owner of those images.

Please use the original branding.

**Comment by NemesisRE** [comment]
I made a custom design which should not conflict with the brand guidelines

**Comment by NemesisRE** [comment]
Oh I see so multiple integrations can use the same icon cause they are integrating with the same manufacturer, I thought I have to make my own image.
That makes it way easier ^^

**Pull request merged**
