### PR TITLE
Hifiberry integration

### PR DESCRIPTION
**Pull request by willholdoway**
## Type of change

- [x] Add a new logo or icon for a new integration
- [ ] Add a missing icon or logo for an existing integration
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/33741
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/12712
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by willholdoway** [comment]
> Let's make sure we add all images 👍
> 
> Here are some logo's:
> 
> berry2
> berry1

thanks for find these @frenck, I've added them now plus icon crops!

**Comment by frenck** [comment]
I don't see them? Have you pushed the commit?

**Comment by frenck** [comment]
This file: `src/logo.png` doesn't belong there. Please remove it.

**Comment by willholdoway** [comment]
> This file: `src/logo.png` doesn't belong there. Please remove it.

accident, deleted now

**Comment by frenck** [comment]
Closing the PR as the parent PR has been closed.

**Comment by willholdoway** [comment]
@frenck could you reopen for new https://github.com/home-assistant/home-assistant.io/pull/17908 please?

**Comment by frenck** [comment]
I can't, as your fork doesn't exists anymore.

**Pull request closed without merging**
