### PR TITLE
Added Shopping list with grocy icons

### PR DESCRIPTION
**Pull request by Anrolosia**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
These are modified Grocy icons. We don't accept branding that has been modified.

../Frenck

**Comment by Anrolosia** [comment]
Sorry @frenck ! I forgot to update with the latest ones :(

**Review by frenck — CHANGES_REQUESTED** [review]
This PR does not provide the branding of the software or devices that it integrates with.

**Comment by frenck** [comment]
I mean that this custom integration integrates with Grocy; therefore the Grocy branding would be expected. The provided branding is not the branding Grocy uses.

../Frenck

**Comment by Anrolosia** [comment]
What about now @frenck ?

**Comment by frenck** [comment]
That doesn't look like a branding that is officially used by Grocy. Can you point me to such a resource? Please note, we don't accept custom branding, we require that upstream branding is respected.

../Frenck

**Comment by Anrolosia** [comment]
I looked at the branding in this got repository under custom_repository/grocy 
But to be honest, this custom module doesn't need the one from homeassistant. It works with self hosted grocy instance too.

**Comment by frenck** [comment]
I'm not sure why your last comments matters in this case?

**Comment by frenck** [comment]
> Ok, I think I understand now, I should use the EXACT branding icon and banner from grocy, right?

Yes! 

As I already said [here](https://github.com/home-assistant/brands/pull/3854#pullrequestreview-1181474471), [here](https://github.com/home-assistant/brands/pull/3854#issuecomment-1315806068)  and [here](https://github.com/home-assistant/brands/pull/3854#issuecomment-1315843402).

This repository provides brand images to manufacturers of devices (or providers of the services/data). Not custom-made-up images for integrations. Additionally, messing with/re-using brand assets to create new branding images is mostly not allowed by the original creator/copyright holder of the images and is generally a violation of branding guidelines.

**Comment by Anrolosia** [comment]
Alright, done :) Sorry for that misunderstanding :)

**Review by frenck — APPROVED** [review]
Thanks, @Anrolosia 👍

**Pull request merged**
