### PR TITLE
Add icons and logos for kub custom component

### PR DESCRIPTION
**Pull request by JackJPowell**
## Proposed change

This change adds icons and logos for the [Knoxville Utility Board - kub.org](https://kub.org) (KUB) custom integration. This integration consumes the KUB api to report the user's Electricity, Gas, and Water hourly consumption and associated cost. 

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: N/A
- Link to code base pull request: N/A
- Link to documentation pull request: N/A
- Link to integration documentation on our website: N/A
- Link to custom integration repository: [https://github.com/JackJPowell/hass-kub](https://github.com/JackJPowell/hass-kub)

## Checklist

- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The integration domain in the upstream manifest seems to be invalid:

CleanShot 2024-06-02 at 15 20 25@2x

Integration domain names must be lower case.

Could you take a look?

../Frenck

**Comment by JackJPowell** [comment]
Screenshot 2024-06-02 at 10 25 46 AM

Thanks for the quick review, frenck. I had that wrapped up on another branch and lost sight that it wasn't merged into main yet. Should be good now.

**Comment by JackJPowell** [comment]
Sorry about requesting. I saw the button to mark as ready immediately after I clicked 'request review'. I made a bad assumption about what the bot was asking me to do. 🤦‍♂️

**Review by frenck — APPROVED** [review]
Thanks, @JackJPowell 👍 

../Frenck

**Pull request merged**
