### PR TITLE
Add Panasonic Smart IoT logo and icon

### PR DESCRIPTION
**Pull request by tsunglung**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icons used to look like an icon from an app or something similar and not the icons Panasonic uses for its branding.

Please adjust the branding to match the manufacturer's branding instead.

Thanks! 👍 

../Frenck

**Comment by tsunglung** [comment]
Yes, the icon is from the app of Panasonic IoT app. The Panasonic IoT app is for Panasonic appliances that are using in Taiwan. Please check this url https://github.com/tsunglung/panasonic_ems2.
The logo is from the Panasonic logo of another integration for the Panasonic app.

**Comment by frenck** [comment]
Right, but we don't collect app icons. Please use the manufacturer branding instead.

Thanks 👍 

../Frenck

**Comment by tsunglung** [comment]
The app icon is from manufacturer branding (Panasonic Taiwan). I am not the manufacturer and I did not create manufacturer branding's icon.

**Comment by frenck** [comment]
🤷 Sorry, I think I was pretty clear in the review. We don't collect app icons. The icons provided are not the icons used by the manufacturer (as shown on, for example, all social media profiles from Panasonic).

You can at this point either choose to adjust the PR, or to close it. It won't be accepted in the current state.

../Frenck

**Comment by tsunglung** [comment]
Sucks, I saw other custom integrations use the same icon of App. What this icon is not approved  and ask to close PR.

**Review by frenck — CHANGES_REQUESTED** [review]
This is not the Panasonic branding.

Closing the PR. Feel free to open a new one that does use the Panasonic branding if you feel that that is right thing to do.

../Frenck

**Pull request closed without merging**
