### PR TITLE
Add logo and icon for the google_assistant_sdk integration

### PR DESCRIPTION
**Pull request by tronikos**
## Proposed change

Needed for https://github.com/home-assistant/core/pull/82328

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by tronikos** [comment]
Parent PR was merged a while ago. Should this automatically merge?

**Comment by tronikos** [comment]
Can this be merged? The logo is missing from the rc documentation:
https://rc.home-assistant.io/integrations/#search/Google%20assistant

**Comment by frenck** [comment]
@tronikos Have patience; merging this will not instantly fix RC docs. The PR is labeled correctly.

**Review by frenck — APPROVED** [review]

**Pull request merged**
