### PR TITLE
Added logos and icons for new Bitvavo integration

### PR DESCRIPTION
**Pull request by cyberjunky**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/48042
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks for the PR @cyberjunky!

Could you please make sure the build passes? 👍

**Review by frenck — CHANGES_REQUESTED** [review]
One small additional comment: 

Can we remove the empty space above/below the logo a bit? So the logo fills the image?

**Comment by cyberjunky** [comment]
> One small additional comment:
> 
> Can we remove the empty space above/below the logo a bit? So the logo fills the image?

Done, GIMP to the rescue... ;-)

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed and not revived

**Comment by cyberjunky** [comment]
Ah wait, i'm about to open new PR of Bitvavo integration

**Pull request closed without merging**
