### PR TITLE
Added symlink for sql_json integration logos

### PR DESCRIPTION
**Pull request by crowbarz**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

~~Note that this is just a symlink from custom_integrations/sql_json to core_integrations/sql as there isn't a need for a separate logo. I didn't see any other examples of this so was not sure that linking across the two directories is supported.~~ Updated PR to copy existing core_integrations/sql icons to custom_integrations/sql_json

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please do not symlink between core & custom integrations.

**Comment by crowbarz** [comment]
Updated PR to use a copy of the existing icons for core_integrations/sql instead of symlinking.

**Review by frenck — CHANGES_REQUESTED** [review]
This custom integration is using our logo template. We don't allow this, because it might confuse the end-user that this is an internal/official integration, which is not the case.

**Comment by crowbarz** [comment]
I've changed the icon to something completely disconnected with the HA brand.

Unless this should be handled in another manner (please advise) I'll also raise a PR for [README.md](https://github.com/home-assistant/brands/blob/master/README.md) shortly to document these two policies, which I did not see discussed there currently.

**Review by frenck — APPROVED** [review]
Thanks, @crowbarz 👍

**Pull request merged**
