### PR TITLE
Add fujitsu_hvac integration images

### PR DESCRIPTION
**Pull request by crevetor**
## Proposed change
Add the images for the new fujitsu_hvac integration. These are just copies of the ones in fujitsu_airstage since linking is not allowed between custom integrations.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/109335
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/31192
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
You write in the title/description that this is a custom integration, however, a Core parent PR is linked. So it is not an custom integration?

../Frenck

**Comment by crevetor** [comment]
Are custom integrations integrations that don't live in the HA repo ? If so, this isn't a custom integration.

**Comment by crevetor** [comment]
Fixed it.

**Review by joostlek — CHANGES_REQUESTED** [review]
Please move them to `core_brands` and then use a symlink to link the `core_integrations/fujitsu_fglair` files to the brand. Please check other integrations how that works (I think `switchbot` is one to look for)

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @crevetor :+1:

**Pull request merged**
