### PR TITLE
Tasmota IRHVAC logo initial commit

### PR DESCRIPTION
**Pull request by hristo-atanasov**
## Proposed change

I'm adding my custom integration brand/logo as I want to add it to HACS

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is a modified/custom logo based on the Tasmota logo. 

We don't accept custom creations, as they most often collide with branding guidelines.

Please use the normal Tasmota logo instead.

../Frenck

**Comment by hristo-atanasov** [comment]
I have a permission from Arends,  Tasmota creator to use his logo. If I could, I would use his original one even, but I don't know how. Also my custom component is just a bridge between Home Assistant and the "IRHVAC" command in Tasmota.

**Comment by hristo-atanasov** [comment]
> This is a modified/custom logo based on the Tasmota logo.
> 
> We don't accept custom creations, as they most often collide with branding guidelines.
> 
> Please use the normal Tasmota logo instead.
> 
> ../Frenck

Can you give me some directions how can I add my custom component to HACS and use the original one?

**Comment by frenck** [comment]
Just adjust this PR and by adding the right images?

../Frenck

**Comment by hristo-atanasov** [comment]
> Just adjust this PR and by adding the right images?
> 
> ../Frenck

You mean to add the same logos as Tasmota core integration?

**Comment by frenck** [comment]
> > Just adjust this PR and by adding the right images?
> > ../Frenck
> 
> You mean to add the same logos as Tasmota core integration?

Probably. I mean the upstream branding from Tasmota itself, yes.

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

../Frenck

**Pull request closed without merging**
