### PR TITLE
Adding icons for localtuya custom component

### PR DESCRIPTION
**Pull request by rospogrigio**
## Proposed change
Added localtuya integration, to communicate with Tuya devices locally.

## Type of change
- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [X] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information
- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: https://github.com/rospogrigio/localtuya-homeassistant

## Checklist
- [X] The added/replaced image(s) are **PNG**
- [X] Icon image size is 256x256px (`icon.png`)
- [X] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [X] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [X] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is a variant of the official tuya logo.

We do not allow changed/variants of a brand image. We should respect the brand images by the manufacturer.

**Comment by rospogrigio** [comment]
> This is a variant of the official tuya logo.
> 
> We do not allow changed/variants of a brand image. We should respect the brand images by the manufacturer.

Ooops, yes you are right. How about now?

**Review by frenck — APPROVED** [review]
Thanks, @rospogrigio

**Comment by rospogrigio** [comment]
Thank you! How am I supposed to see it in the Integrations? Should I clear the cache in some way?

**Comment by frenck** [comment]
The cache on our end is flushed when a Home Assistant Core version is released.

**Comment by rospogrigio** [comment]
OK didn't know that, thanks!

**Pull request merged**
