### PR TITLE
Add hOn custom integration Logo

### PR DESCRIPTION
**Pull request by gvigroux**
## Proposed change

Logos for hOn customer integration (Candy Hoover Group)

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by bkbilly — CHANGES_REQUESTED** [review]
On dark themes they don't look so good because there is some white left around.

**Comment by gvigroux** [comment]
I've updated them. Hope it will be better

**Review by bkbilly — APPROVED** [review]

**Review by bkbilly — APPROVED** [review]
They look much better!

**Comment by gvigroux** [comment]
> They look much better!

Thanks :) What's the next step ?

**Review by frenck — CHANGES_REQUESTED** [review]
I'm confused by this branding. Does this seem like product or app branding?

Please note, we collect manufacturer branding in this repository, not product/app branding.

../Frenck

**Comment by gvigroux** [comment]
> repository

In fact the hOn application: 
https://apps.apple.com/fr/app/hon/id1500597674

is for the entire "Candy Hoover Group" and can control multiple brands: Candy, Hoover, Haier....

**Review by frenck — CHANGES_REQUESTED** [review]
> In fact the hOn application:

As stated above, we don't collect product/application branding in this repository.

**Comment by gvigroux** [comment]
> > In fact the hOn application:
> 
> As stated above, we don't collect product/application branding in this repository.

Understood. Because it can covers multiple brands, what should I do for the logo of the custom integration? IT's not possible ?
And for each entity created by the integration, can I choose a different domain corresponding to the real brand ?

Any pointer will be good :)
Thanks for the help

**Comment by frenck** [comment]
superseded by #4196

**Pull request closed without merging**
