### PR TITLE
Icon for custom integration SWS12500 Weather station. 

### PR DESCRIPTION
**Pull request by schizza**
## Proposed change

Add icon for custom component SWS12500 weather station.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/schizza/SWS-12500-custom-component

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @schizza 👋 

We collect brands in this repository, I would have expected the branding of Sencor to be used here.

../Frenck

**Comment by schizza** [comment]
> Hi there @schizza 👋
> 
> We collect brands in this repository, I would have expected the branding of Sencor to be used here.
> 
> ../Frenck

Ok, I see.  I thought as this is custom component, that logo is for this custom component - I was wrong :) 
I have changed logo to `Sencor` brand and icon to integration icon? Is that right?

**Review by frenck — CHANGES_REQUESTED** [review]
The logos look like the icons in terms of size? The icons don't seem to match what the manufacturer is using for their branding?

../Frenck

**Comment by schizza** [comment]
> The logos look like the icons in terms of size? The icons don't seem to match what the manufacturer is using for their branding?
> 
> ../Frenck

The logo I have added is well know for years.

CleanShot 2024-05-24 at 16 18 05@2x

**Comment by frenck** [comment]
@schizza I meant these, are not matching:

CleanShot 2024-07-07 at 23 20 36@2x

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Pull request closed without merging**
