### PR TITLE
Add Legrand Home+ Control logos and icons.

### PR DESCRIPTION
**Pull request by chemaaa**
## Proposed change

This adds the logo and icons that go alongside the Legrand Home+ Control integration. This integration connects Home Assistant to the Legrand API ("Works with Legrand" platform) that can manage "Legrand/Bticino with Netatmo" products.

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/46783
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/16644
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @chemaaa, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2272).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by chemaaa** [comment]
Hi @frenck ,
In the codebase review I was asked to add underscores to the component name like so: `home_plus_control`, so I understand that this also has to change in the directory naming of the logos. 

Is it OK if I rebase and commit in this PR or should I proceed some other way to commit this change?

Thanks!

**Comment by frenck** [comment]
Fix the PR :)

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
