### PR TITLE
Renpho

### PR DESCRIPTION
**Pull request by antoinebou12**
## Proposed change
Renpho logo

## Type of chang
- [X] Add a new logo or icon for a custom integration (custom component)
  - [X] I've added a link to my custom integration repository in the PR description

## Additional information
https://github.com/antoinebou12/hass_renpho

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
The icons are different from each other 🤔 

./Klaas

**Comment by antoinebou12** [comment]
ok just changed it

**Comment by antoinebou12** [comment]
Where i can see my changes for my plugin

[antoinebou12/hass_renpho](https://github.com/antoinebou12/hass_renpho)

my manifest

{
  "domain": "renpho",
  "name": "Renpho",
  "documentation": "https://github.com/neilzilla/hass-renpho",
  "issue_tracker": "https://github.com/neilzilla/hass-renpho/issues",
  "dependencies": [],
  "codeowners": ["@neilzilla", "@antoinebou12"],
  "requirements": [
    "pycryptodome>=3.3.1",
    "requests>=2.25.0",
    "aiohttp>=3.6.1",
    "voluptuous>=0.11.7",
    "pydantic",
    "aiohttp_socks"
  ],
  "iot_class": "cloud_polling",
  "version": "3.0.1",
  "config_flow": true
}

**Comment by frenck** [comment]
I'm not understanding your question? Adding brand images to our repo will not change your repo?

../Frenck

**Comment by antoinebou12** [comment]
image

will i see a icon here ?

**Comment by frenck** [comment]
Once we flush our caches or do a major release: Yes.

../Frenck

**Pull request merged**
