### PR TITLE
Dell printer

### PR DESCRIPTION
**Pull request by kongo09**
## Proposed change

I'm working on a new custom integration to add sensors for Dell color laser printers.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I cannot find a dell reference where the manufacturer uses this icon. Could you point me to that?

Please note, this repository collects brands assets, not product images or modified brand images.

**Comment by kongo09** [comment]
Apologies, I wasn't aware that you need a source for the submission.

The icon is the official Dell printer software icon, not modified:
https://play.google.com/store/apps/details?id=com.dell.documenthub

Happy new year!

**Comment by frenck** [comment]
Right, but this is a brands repository, not an repository for product images or branding.
The linked icon is branding for an application of Dell, not the Dell branding.

**Comment by kongo09** [comment]
Oh, I see, so the idea is to use pure brand images? Sorry, I'll change to Dell icons, which are indeed also missing.

**Pull request closed without merging**
