### PR TITLE
add oilfox icon

### PR DESCRIPTION
**Pull request by chises**
## Proposed change

add oilfox icon and made old icon to logo

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
OilFox seems like the product, not brand. I kinda would expected to see the FoxInsights logo in this case?

**Comment by chises** [comment]
Thats correct, it is a product from foxinsights. If you want the manufacture logo I will change it, no problem :) I am new to PRs but I try my best to update this one! Give me some time.

**Comment by chises** [comment]
I hope everything is fine. I updated my repo branch and suddenly the changes showed up here :)
replace the product ogo with the brand (foxinsights) logo. Please let me know if something is wrong.

**Review by frenck — APPROVED** [review]
Thanks, @chises 👍

**Pull request merged**
