### PR TITLE
Add the stihl_imow brand logo

### PR DESCRIPTION
**Pull request by ChrisHaPunkt**
## Proposed change

Add the brand logo for STIHL iMow lawn mower integration ("stihl_imow")

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
Hmm, I would have expected the STIHL brand images in this case, not their product branding.

**Comment by ChrisHaPunkt** [comment]
Hi @frenck , thanks for your reply. The integration is intended to support the lawn mower series. That is why I thought the product brand would fit ( like the Google cast integration uses the cast logo not the Google logo).
But I could search and provide a STIHL logo if you think this would fit better.

**Comment by frenck** [comment]
We generally avoid product branding and prefer company branding. But do in some cases, for example, Microsoft and Google have huge catalogs of products.

**Comment by ChrisHaPunkt** [comment]
Okay, that's fine for me. I'm going to look for the corresponding images and will update the PR.

**Review by frenck — APPROVED** [review]

**Pull request merged**
