### PR TITLE
Add icons and logos for little_monkey

### PR DESCRIPTION
**Pull request by jmcruvellier**
## Proposed change

You can find the custom component code repository here: https://github.com/jmcruvellier/little_monkey

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This integration integrates ecojoko, however, the provided images do not seems to be used by them?

CleanShot 2023-11-09 at 17 19 43@2x

Can you please point me to a resource they use this for their branding? Otherwise, please update the providing branding to the manufacturers branding instead.

../Frenck

**Comment by jmcruvellier** [comment]
Hi frenck, I'm not using ecojoko branding because this custom integration is not official (I'm not part of their company). 
Each ecojoko client's are having access to their data by calling APIs with their ecojoko's credentials.
That's why this integration name does not contain "ecojoko" and that I'm not using their official logo.

**Review by frenck — CHANGES_REQUESTED** [review]
Right, however, that is not what we collect in this repository.

../Frenck

**Comment by jmcruvellier** [comment]
Ok understood. I've updated both icon and logo as requested. Is it ok now?

**Review by frenck — APPROVED** [review]
Thanks, @jmcruvellier 👍 

../Frenck

**Pull request merged**
