### PR TITLE
Added brand icons for custom integration lucide-icons

### PR DESCRIPTION
**Pull request by karlis-vagalis**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: -
- Link to code base pull request: -
- Link to documentation pull request: -
- Link to integration documentation on our website: -

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The domain name used for this integration isn't valid.

CleanShot 2024-01-16 at 19 09 33@2x

`-` are not allowed in integration domains, underscores (`_`) are allowed though.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
The upstream integration doesn't match the latest changes:

CleanShot 2024-01-16 at 20 51 03@2x

This PR will have no effect. Please make sure it matches

../Frenck

**Comment by karlis-vagalis** [comment]
I am aware of this. This mismatch will be solved tomorrow. I would really appreciate if this PR would still be merged, to not delay this integration being published on HACS any longer.

**Review by frenck — CHANGES_REQUESTED** [review]
Sorry, can't merge the PR if it ain't correct.

../Frenck

**Comment by karlis-vagalis** [comment]
What a joke. Here you go.

**Comment by frenck** [comment]
> What a joke.

I'm sorry? I don't think that is called for or a needed comment/attitude to put out.

../Frenck

**Comment by karlis-vagalis** [comment]
> I'm sorry? I don't think that is called for or a needed comment/attitude to put out.

Well, we disagree in that regard then 🤷🏻‍♂️

**Comment by frenck** [comment]
There is no good reason to mock a review with "What a joke".

There is a difference between not agreeing with the project's policies versus leaving a comment like that. It is just disrespectful.

I hope you understand I'm less motivated to complete this review.

../Frenck

**Comment by karlis-vagalis** [comment]
> There is no good reason to mock a review with "What a joke".
> 
> There is a difference between not agreeing with the project's policies versus leaving a comment like that. It is just disrespectful.
> 
> I hope you understand I'm less motivated to complete this review. I'll leave it for someone else to pick up instead.

Well, take all the time you need. Oh no, poor me, being held hostage.

Secondly, the requirements from HA Developer docs say, that the domain name can contain characters and underscores. It does not say only alphanumerical characters and underscores. In addition to the integration domain names in this repo: several with `-` in the `custom_components` folder. Just FYI

**Comment by frenck** [comment]
> Well, take all the time you need. Oh no, poor me, being held hostage.

Alright, that does it.

Going to close this PR for the above behavior. Please consider this a warning for violating our Code of Conduct.

../Frenck

**Comment by karlis-vagalis** [comment]
Yes, just ignore the brought up arguments. You know what is especially funny? You just make the life harder for people who want more convenient way to install and update this integration. I don't need it: I wrote this integration, I know how to install it and always have the latest version anyways.

**Pull request closed without merging**
