### PR TITLE
Add brand images for custom component Bureau of Meteorology

### PR DESCRIPTION
**Pull request by bremor**
## Proposed change

Branding for custom component
https://github.com/bremor/bureau_of_meteorology

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The icon has a mixed transparent and white background. Also, the icon looks like the normal logo version. Maybe just remove the icon in that case?

**Comment by frenck** [comment]
Why did you delete the logo?

**Comment by bremor** [comment]
> Why did you delete the logo?

Sorry if I've misunderstood. You suggested that I remove the icon, but my understanding was that an icon should not be missing, as per the main README.md:
If a domain is missing the icon.png file, 404 will be served
If a domain is missing the logo.png file, the icon.png is served instead (if available).

**Comment by frenck** [comment]
I'm still not sure what made you remove the logo? The logo was fine, right? why did it have to go? even with the rules from the repo, why not deliver a good as well?

**Comment by frenck** [comment]
image

Wut?

**Comment by bremor** [comment]
Really sorry Frenck, uploaded the wrong logo. Fixed now.

**Review by frenck — APPROVED** [review]
Haha Don't worry @bremor :D That stuff happens.

Thanks 👍

**Pull request merged**
