### PR TITLE
HASSMPRIS icons added.

### PR DESCRIPTION
**Pull request by Rudd-O**
This adds icons for the custom MPRIS integration.

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/23857/files

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR contains a modified Home Assistant logo. We cannot accept such brand images, as they might be confused as supported by the Home Assistant project.

PS: This PR links to a documentation PR in our official repos, but is adding a custom integration domain? Not entirely sure what you are adding now? Is this a custom integration, or are you adding this integration to core?

../Frenck

**Comment by Rudd-O** [comment]
Hi there, and thanks for your reply @frenck !

I can change the logo to contain no Home Assistant trademarked material, no problem.  I will do that right away.

In answer to your question, this is for HACS inclusion of a custom integration that I want to make available to others while the *actual* integration proposed to core (here: https://github.com/home-assistant/core/pull/77188 ) is under review.  Since the review got no comments in over 2 months, I decided to push the software via HACS instead.

**Comment by frenck** [comment]
Right, but right now, there is a domain collision in the custom integration and the core PR, additionally this PR links to a documentation page not related to custom integrations. So, at this point, this PR is not correct.

**Comment by Rudd-O** [comment]
OK.  Let's suppose I desist from adding this to HACS.

What is the process to get reviewers to be added to the official core addon PR, linked above?

**Comment by frenck** [comment]
> What is the process to get reviewers to be added to the official core addon PR, linked above?

Nothing, it is just patience. If you want review to be quicker, feel free to join the review process to help reviewing the large queue of PRs in our org.

**Comment by Rudd-O** [comment]
Moving this to draft in hopes that the PR in core is reviewed soon.  Thanks.

**Comment by Rudd-O** [comment]
Closing on account of https://github.com/hacs/default/pull/1563 .

**Pull request closed without merging**
