### PR TITLE
Add awattar icons and logos - https://www.awattar.at

### PR DESCRIPTION
**Pull request by mexx42**
## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/112511
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/31759
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by klaasnicolaas — CHANGES_REQUESTED** [review]
When I look at the awatter website, they have an icon without text and a logo with the text to the right next to it and not below it.

./Klaas

**Comment by mexx42** [comment]
i took the images from here (section logos) https://www.awattar.at/company/press

so basically there are no logos ... i thought of just using the rings as icon, but i am not sure if this is ok for them as its not in their ci ... ?

**Comment by klaasnicolaas** [comment]
On Twitter they also only use the rings as a profile image and an icon with only the rings will also look better visually later in the integration list.

./Klaas

**Comment by klaasnicolaas** [comment]
In terms of logo, I would prefer the wide variant with text on the right side. 

./Klaas

**Comment by mexx42** [comment]
Yes, /me too, but then you don't have the "energy in sync with nature" text below, but i can change it if you want.

**Comment by klaasnicolaas** [comment]
image

**Comment by mexx42** [comment]
Ok, sorry, i must have been blind ... one second, i will replace it

**Review by klaasnicolaas — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

**Comment by mexx42** [comment]
Thanks!

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
