### PR TITLE
Add icons for config_editor custom component

### PR DESCRIPTION
**Pull request by htmltiger**
## Proposed change
Add the icons for the custom integration config_editor to home-assistant/brands in order to facilitate submission as HACS default repository.

https://community.home-assistant.io/t/addon-lovelace-configuration-yaml-editor-for-core-install/362093

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @htmltiger, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#2985).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
This icon uses our template for Home Assistant icons for a custom integration. This may cause a user to think that this is an official integration; therefore we cannot accept this branding.

**Comment by htmltiger** [comment]
> This icon uses our template for Home Assistant icons for a custom integration. This may cause a user to think that this is an official integration; therefore we cannot accept this branding.

No problems, I have updated them and removed the Home altogether.
Thanks.

**Review by frenck — APPROVED** [review]
Thanks, @htmltiger 👍

**Pull request merged**
