### PR TITLE
Karcher Home Robots

### PR DESCRIPTION
**Pull request by lafriks**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

WIP integration: https://github.com/lafriks/homeassistant_karcher_home_robots

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @lafriks 👋 

Looked at the PR and noticed two things:

- The provided link to the repository providing the custom integration is empty (and thus does not contain an integration).
- The provided icons seem like application icons and not branding, please the manufacturer branding instead.

Thanks already! 👍 

../Frenck

**Comment by lafriks** [comment]
>     * The provided link to the repository providing the custom integration is empty (and thus does not contain an integration).

Yes, still working on it, will publish soon, that's why I noted it as WIP

>     * The provided icons seem like application icons and not branding, please the manufacturer branding instead.

Yes, because it's integration specific exactly for Kärcher Home Robots (cloud controllable robot vacuum cleaners). So shouldn't that be also an icon for this specific product integration?

**Comment by frenck** [comment]
> Yes, still working on it, will publish soon, that's why I noted it as WIP

Ok, in that case, I'll go ahead and close this PR for now. Feel free to re-open when it is ready.

> So shouldn't that be also an icon for this specific product integration?

We try to collect branding, not product brandings. There is an exception to this, but that is specifically for a feature for Core integrations that is not available for custom integrations.

Therefore, this PR should adjust its icon to match the manufacturer's branding.

Thanks 👍 

../Frenck

**Comment by lafriks** [comment]
Ok, will reopen when I have published code.

Is this ok for icon?
attels

**Comment by frenck** [comment]
@lafriks No, that is not OK. As that is not the branding they use. For reference, see for example:

image
image

../Frenck

**Comment by lafriks** [comment]
That icon I found they use for their home and garden products but updated PR as per your suggested icon, please confirm it's ok

**Comment by frenck** [comment]
@lafriks This PR is currently closed, there is nothing to review. Feel free to re-open when there is an integration to go with it.

../Frenck

**Comment by lafriks** [comment]
@frenck yes I know, just wanted to make sure I got it right for next PR: https://github.com/lafriks-fork/brands/blob/feat/karcher_home_robots/custom_integrations/karcher_home_robots/icon%402x.png

**Comment by frenck** [comment]
If there is a next PR is needs review, at that point, I'll look again (or someone else that is processing the PR).

../Frenck

**Pull request closed without merging**
