### PR TITLE
Add switchbot cloud integration

### PR DESCRIPTION
**Pull request by SeraphicRav**
## Proposed change

Adding switchbot via api

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/99607
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/28782
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by SeraphicRav** [comment]
What should I do? It seems there is a custom_componenr with the same name but it does not seem maintained, does not have the same purpose and do not use the recommended way to use the api.

**Comment by SeraphicRav** [comment]
Not needed as using SwitchBot brand

**Comment by joostlek** [comment]
When using switchbot brand, the integration still has its own brand logo. (Checkout adding an integration for google/youtube, youtube has a different logo than google).

Please create a new PR (or reopen this one) to add Switchbot to the core_brands folder and add the switchbot_cloud logo's

**Comment by joostlek** [comment]
You should now also add the icons and stuff to the core_brand folder

**Comment by SeraphicRav** [comment]
@joostlek Thanks, sorry, I did not understand there 2 folders to create after looking at the PR for Youtube.

**Comment by SeraphicRav** [comment]
@joostlek Is this PR not necessary ?

**Comment by joostlek** [comment]
Yes it is, but usually Frencks merges them (he knows what to look out for especially). But he's on holiday. I'll make sure he gets notified of it :)

**Review by frenck — CHANGES_REQUESTED** [review]
The icons provided in this PR, seem no to match the branding SwitchBot is using.

For example, this is from their X/Twitter:

CleanShot 2023-09-24 at 19 21 03

**Comment by SeraphicRav** [comment]
@frenck 
Oh, I just copy/pasted the images already used for  core_integrations/switchbot, I will see if I can find something.

**Comment by SeraphicRav** [comment]
I used the logo on Wikipedia and the icon in the Google Play Store

**Review by frenck — APPROVED** [review]
Thanks, @SeraphicRav 👍 

../Frenck

**Pull request merged**
