### PR TITLE
adding solcast_solar integration images

### PR DESCRIPTION
**Pull request by oziee**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The 2x versions of the images look really blown up / pixelated.

image


Either use higher quality images for those, or omit them.

**Comment by oziee** [comment]
done

**Review by frenck — CHANGES_REQUESTED** [review]
image


These images are optimized for a dark background, however, our default are based on a light/white background. Please use assets that work on light backgrounds. Additional dark mode images can be provided if wanted (see repository README for more information on that).


Lastly, the 2x version of the icon also has pixelation. Please adjust that or omit the 2x version.

**Comment by oziee** [comment]
done
I will add the others again when I get some time to vector them and make them better

**Comment by frenck** [comment]
I'm not sure why you have removed `logo.png`:

image


Could you explain why it was removed?

**Comment by oziee** [comment]
> Could you explain why it was removed?

thought they were all too low a resolution and your said if they are low to just remove them, so I did.. I can re-add it

**Comment by frenck** [comment]
> thought they were all too low a resolution and your said if they are low to just remove them

I wrote:

> The 2x versions of the images look really blown up / pixelated.

You've removed the 1x version.

**Comment by frenck** [comment]
`solcast_rooftop_solar` was now added as well? A PR should only cover a single integration.

**Comment by oziee** [comment]
> `solcast_rooftop_solar` was now added as well? A PR should only cover a single integration.

sorry Frenck... I not a GitHub expert as you can tell.. I clicked pr thinking it was creating a new one

**Comment by oziee** [comment]
ill start again

**Pull request closed without merging**
