### PR TITLE
add citymind_water_meter

### PR DESCRIPTION
**Pull request by elad-bar**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:
https://github.com/maorcc/citymind_water_meter

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @elad-bar 👋 

The icons added here are a bit unexpected. I would have expected the branding used by Arad Technologies?

../Frenck

**Comment by elad-bar** [comment]
> Hi there @elad-bar 👋
> 
> The icons added here are a bit unexpected. I would have expected the branding used by Arad Technologies?
> 
> ../Frenck

Arad is the meter provider, Read Your Meter Pro (Former name CityMind) is the name of the product of the console, according to their web console, that's the icon

Screenshot_20240705_102651_Google

**Comment by frenck** [comment]
Right, but our goal is not to collect icons from the app stores, we try to collect branding here :)

**Comment by elad-bar** [comment]
Make sense, will try to find

**Comment by elad-bar** [comment]
hi Frenck,

updated the icons, added also logo
hope it will be better this time :)

thanks

**Review by frenck — APPROVED** [review]
Thanks, @elad-bar 👍 

../Frenck

**Pull request merged**
