### PR TITLE
Adding PECO logo and icon

### PR DESCRIPTION
**Pull request by IceBotYT**
## Proposed change

Adding PECO logo and icon for new PECO Outage Counter integration

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- Link to code base pull request: https://github.com/home-assistant/core/pull/65194
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/21392
- Link to integration documentation on our website: soon here: [https://home-assistant.io/integrations/peco](https://home-assistant.io/integrations/peco)

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by IceBotYT** [comment]
Just a heads up, [PECO is going through a rebranding](https://www.pecoconnection.com/2022/02/02/new-look-same-dedication-and-commitment/). I cannot access the new logos in a high-quality format, but I will make another PR soon with the new logos and icons.

**Comment by IceBotYT** [comment]
Just uploaded the new icons as per the PECO rebranding. Should be good to go :)

**Comment by IceBotYT** [comment]
Hey @frenck I updated the icon and logo with the rebranded version.

**Review by frenck — APPROVED** [review]
Thanks, @IceBotYT 👍

**Pull request merged**
