### PR TITLE
Add logo for octopus_intelligent

### PR DESCRIPTION
**Pull request by guybw**
added logs for Intelligent Octopus

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/megakid/ha_octopus_intelligent
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x ] The added/replaced image(s) are **PNG**
- [x ] Icon image size is 256x256px (`icon.png`)
- [x ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The provided icon doesn't seem to match the icons Octopus Energy uses for its branding. For example:

image

../Frenck

**Comment by guybw** [comment]
@frenck Hi yes thats the same company but there is already an Octopus Icon / integration. This is slightly different as it's Intelligent https://octopus.energy/intelligent-octopus/
I'm happy to change it over to the company Icon I just thought it would be better to have a different icon but totally open to either.

**Comment by frenck** [comment]
> Hi yes thats the same company but there is already an Octopus Icon / integration. This is slightly different as it's Intelligent [octopus.energy/intelligent-octopus](https://octopus.energy/intelligent-octopus/)

The branding doesn't represent the integration, it represents the branding of the company/manufacturer that provided the device or service. Multiple integrations will thus have the same branding.

../Frenck

**Comment by guybw** [comment]
No problem, it's now updated.

**Review by frenck — APPROVED** [review]
Thanks, @guybw 👍

**Pull request merged**
