### PR TITLE
Add Swatch Logo

### PR DESCRIPTION
**Pull request by NickM-27**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
It looks like this icon has some issues in terms of quality. There some partial transparency and blurriness visible:

CleanShot 2022-04-08 at 21 21 46@2x

Could you take a look?

**Comment by NickM-27** [comment]
@frenck Thank you! New image should be higher quality and I made sure it has no transparency 👍

**Review by frenck — COMMENTED** [review]
The image is square, shouldn't this be `icon.png` instead of `logo.png`?

**Comment by NickM-27** [comment]
> The image is square, shouldn't this be `icon.png` instead of `logo.png`?

Ah I see, my bad! I have updated logo.png and added icon.png

**Comment by frenck** [comment]
The logo is 256x256? That is icon size.
You don't have to provide both. Just an icon it good to!

I suggest:

- Remove the non-transparent `icon.png`
- Rename `logo.png` -> `icon.png`

**Comment by NickM-27** [comment]
> The logo is 256x256? That is icon size. You don't have to provide both. Just an icon it good to!
> 
> I suggest:
> 
> * Remove the non-transparent `icon.png`
> * Rename `logo.png` -> `icon.png`

Makes sense, thanks for your patience. Adjusted per your suggestion.

**Review by frenck — APPROVED** [review]
Thanks, @NickM-27 👍

**Pull request merged**
