### PR TITLE
Added icons for Atrea custom integration

### PR DESCRIPTION
**Pull request by ain-ver**
## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ain-ver, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3633).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Two things:

- I cannot find the GitHub repository providing this custom integration. Could you point me to it?
- Looking at the icon, there could be a logo version created from it. Could you consider doing that? Adding a logo asset looks much nicer on e.g., device pages.

../Frenck

**Comment by ain-ver** [comment]
- Custom integration repo: https://github.com/JurajNyiri/HomeAssistant-Atrea
- Logo is the same as the icon (https://atrea.eu/en/), cutting it to the actual size of the content violates requirement for minumum height (67px vs 128px required). So I assumed that fallback to icons would work here. Or am I missing anything?

**Comment by frenck** [comment]
@ain-ver You can supply both icons and logos. Specs are in the README.
The brand has an SVG available: <https://atrea.eu/img/logo.svg>

SVGs can be sized and scaled to any size without quality loss.

**Review by frenck — CHANGES_REQUESTED** [review]
The logo & icons are now the same. Please remove the additional empty space top/bottom of the logo (crop the image).

**Comment by ain-ver** [comment]
Cropped to the minimal required height for the logo.

**Review by frenck — APPROVED** [review]
Thanks, @ain-ver 👍

**Pull request merged**
